# -*- coding: utf-8 -*-
"""Kitob Xotirasi (Book Memory) — muallif, asar, janr va qahramon juftliklarini xotirada tiklash."""

BOOKMEMORY_QUESTIONS = [
    {"q": "Qaysi juftlik TO'G'RI moslashtirilgan?", "options": ["Abdulla Qodiriy — «O'tkan kunlar»", "Cho'lpon — «Shum bola»", "Oybek — «Mehrobdan chayon»", "G'afur G'ulom — «Kecha va kunduz»"], "correct": 0},
    {"q": "Qaysi doston va uning bosh qahramoni TO'G'RI ko'rsatilgan?", "options": ["«Farhod va Shirin» — Shopur", "«Layli va Majnun» — Bahrom", "«Sab'ai sayyor» — Iskandar", "«Saddi Iskandariy» — Dilorom"], "correct": 0},
    {"q": "Qaysi alloma va uning asari TO'G'RI juftlangan?", "options": ["Abu Ali ibn Sino — «Tib qonunlari»", "Abu Rayhon Beruniy — «Ziji Ko'ragoniy»", "Mirzo Ulug'bek — «Qadimgi xalqlar»", "Muso Xorazmiy — «Ihyou ulumiddin»"], "correct": 0},
    {"q": "Qaysi jahon adibi va uning mashhur romani TO'G'RI mos keladi?", "options": ["Lev Tolstoy — «Urush va tinchlik»", "Fyodor Dostoyevskiy — «Anna Karenina»", "Viktor Gyugo — «Graf Monte-Kristo»", "Aleksandr Dyuma — «Xo'rlanganlar»"], "correct": 0},
    {"q": "Qaysi asar va uning bosh g'oyasi TO'G'RI berilgan?", "options": ["«Lison ut-tayr» — Komil inson va o'zlikni anglash", "«Hayrat ul-abror» — Faqat sevgi qissasi", "«Shum bola» — Boylik orttirish yo'li", "«Sariq devni minib» — Kosmik sayohat"], "correct": 0},
    {"q": "Qaysi jadid adibi va uning asari TO'G'RI ko'rsatilgan?", "options": ["Mahmudxo'ja Behbudiy — «Padarkush»", "Abdurauf Fitrat — «Turkiy Guliston»", "Abdulla Avloniy — «Munozara»", "Abdulhamid Cho'lpon — «O'tkan kunlar»"], "correct": 0},
    {"q": "Qaysi asar va uning bosh salbiy qahramoni TO'G'RI moslangan?", "options": ["«O'tkan kunlar» — Homid", "«Mehrobdan chayon» — Otabek", "«Kecha va kunduz» — Anvar", "«Shum bola» — Qoravoy"], "correct": 0},
    {"q": "Qaysi adib va uning tug'ilgan shahri TO'G'RI berilgan?", "options": ["Zahiriddin Muhammad Bobur — Andijon", "Alisher Navoiy — Samarqand", "Abdulla Qodiriy — Marg'ilon", "Ahmad Yassaviy — Buxoro"], "correct": 0},
    {"q": "Qaysi juftlik TO'G'RI?", "options": ["Alisher Navoiy — «Mahbub ul-qulub»", "Zahiriddin Bobur — «Xamsa»", "Lutfiy — «Boburnoma»", "Atoiy — «Devoni hikmat»"], "correct": 0},
    {"q": "Qaysi asar va janr TO'G'RI juftlangan?", "options": ["«O'tkan kunlar» — Roman", "«Shum bola» — She'riy doston", "«O'zbegim» — Tragediya drama", "«Padarkush» — Lirik g'azal"], "correct": 0},
    {"q": "Qaysi tasavvuf piri va uning asari TO'G'RI?", "options": ["Xoja Ahmad Yassaviy — «Devoni hikmat»", "Bahouddin Naqshband — «Masnaviy»", "Mavlono Rumiy — «Kimyoi saodat»", "Imom G'azzoliy — «Hibat ul-haqoyiq»"], "correct": 0},
    {"q": "Qaysi asar va bosh qahramon qiz TO'G'RI moslangan?", "options": ["«Mehrobdan chayon» — Ra'no", "«O'tkan kunlar» — Shirin", "«Farhod va Shirin» — Kumush", "«Kecha va kunduz» — Layli"], "correct": 0},
    {"q": "Qaysi asar va undagi ramziy narsa TO'G'RI juftlangan?", "options": ["«Sariq devni minib» — Sehrli qalpoqcha", "«Chol va dengiz» — Oltin buzoq", "«1984» — Sehrli tayoqcha", "«Kichkina Shahzoda» — Uchuvchi gilam"], "correct": 0},
    {"q": "Qaysi chet el adibi va uning personaji TO'G'RI moslangan?", "options": ["Artur Konan Doyl — Sherlok Xolms", "Agata Kristi — Jan Valjan", "Viktor Gyugo — Erkyul Puaro", "Migel de Servantes — Gamlet"], "correct": 0},
    {"q": "Qaysi asar va uning qishlog'i / shahri TO'G'RI?", "options": ["«Yuz yillik yolg'izlik» — Makondo", "«Don Kixot» — Verona", "«Romeo va Juletta» — Madrid", "«Gamlet» — Parij"], "correct": 0},
    {"q": "Qaysi alloma va uning fani TO'G'RI mos keladi?", "options": ["Muso Xorazmiy — Algebra va matematika", "Abu Ali ibn Sino — Faqat astronomiya", "Mirzo Ulug'bek — Faqat tibbiyot", "Ahmad Farg'oniy — Faqat tilshunoslik"], "correct": 0},
    {"q": "Qaysi shoir va uning mashhur qasidasi / dostoni TO'G'RI?", "options": ["Erkin Vohidov — «Ruhlar isyoni»", "Abdulla Oripov — «O'zbegim»", "Muhammad Yusuf — «Jannatga yo'l»", "Hamid Olimjon — «Surat va siyrat»"], "correct": 0},
    {"q": "Qaysi shoir va uning asari TO'G'RI?", "options": ["Abdulla Oripov — «Jannatga yo'l»", "Erkin Vohidov — «O'zbekiston»", "Zulfiya — «Ruhlar isyoni»", "G'afur G'ulom — «Lolaqizg'aldoq»"], "correct": 0},
    {"q": "Qaysi xalq dostoni va qahramonning oti TO'G'RI juftlangan?", "options": ["«Alpomish» — Boychibor", "«Go'ro'g'li» — Jironqashqa", "«Rustamxon» — G'irko'k", "«Kuntug'mish» — To'rtko'z"], "correct": 0},
    {"q": "Qaysi qahramon va uning quroli / xislati TO'G'RI?", "options": ["Farhod — Tosh kesuvchi cho'kich", "Majnun — Qilichbozlik", "Otabek — Sehrgarlik", "Hoshimjon — Kamon otish"], "correct": 0},
    {"q": "Qaysi asar va undagi tarixiy xonlik TO'G'RI?", "options": ["«O'tkan kunlar» — Qo'qon xonligi davri", "«Navoiy» — Buxoro amirligi", "«Shum bola» — Xiva xonligi", "«Yulduzli tunlar» — Xorazmshohlar davri"], "correct": 0},
    {"q": "Qaysi qissada onaga ehtirom bosh mavzu qilingan?", "options": ["«Dunyoning ishlari» — O'tkir Hoshimov", "«Shaytanat» — Tohir Malik", "«Lolazor» — Murod Muhammad Do'st", "«Chinor» — Asqad Muxtor"], "correct": 0},
    {"q": "Qaysi asar o'zbek paxtakori fojiasini ochib bergan?", "options": ["«Otamdan qolgan dalalar» — Tog'ay Murod", "«Yulduzlar mangu yonadi»", "«Ot kishnagan oqshom»", "«Bu dunyoda o'lib bo'lmaydi»"], "correct": 0},
    {"q": "Qaysi roman 1916-yilgi xalq qo'zg'olonini tasvirlaydi?", "options": ["«Qutlug' qon» — Oybek", "«Navoiy» — Oybek", "«O'tkan kunlar» — Qodiriy", "«Kecha va kunduz» — Cho'lpon"], "correct": 0},
    {"q": "Qaysi doston Boburning hayotiga bag'ishlangan?", "options": ["«Yulduzli tunlar» — Pirimqul Qodirov", "«Ulug'bek xazinasi» — Odil Yoqubov", "«Humoyun va Akbar»", "«Ko'hna dunyo»"], "correct": 0},
    {"q": "Qaysi drama jadid teatrining birinchi asari hisoblanadi?", "options": ["«Padarkush» — Mahmudxo'ja Behbudiy (1911)", "«Yorqinoy» — Cho'lpon", "«To'y» — Avloniy", "«Boy ila xizmatchi» — Hamza"], "correct": 0},
    {"q": "Qaysi kitob axloqiy tarbiya bo'yicha mashhur darslikdir?", "options": ["«Turkiy Guliston yoxud axloq» — Abdulla Avloniy", "«Munozara» — Fitrat", "«Padarkush» — Behbudiy", "«Qiyomat» — Fitrat"], "correct": 0},
    {"q": "Qaysi muallif qisqa hajviy hikoyalar ustasi deb tanilgan?", "options": ["Abdulla Qahhor", "Oybek", "Pirimqul Qodirov", "Odil Yoqubov"], "correct": 0},
    {"q": "Qaysi asar bolalar fantastikasi durdonasidir?", "options": ["«Sariq devni minib» — Xudoyberdi To'xtaboyev", "«Shum bola» — G'afur G'ulom", "«Bemor» — Abdulla Qahhor", "«O'g'ri» — Abdulla Qahhor"], "correct": 0},
    {"q": "Qaysi adib detektiv janrida o'zbek maktabini yaratgan?", "options": ["Tohir Malik", "O'tkir Hoshimov", "Said Ahmad", "Asqad Muxtor"], "correct": 0},
    {"q": "Qaysi asar ko'p qismli komediya pyesasidir?", "options": ["«Kelinlar qo'zg'oloni» — Said Ahmad", "«Ufq» — Said Ahmad", "«Chinor» — Asqad Muxtor", "«Sinchalak» — Abdulla Qahhor"], "correct": 0},
    {"q": "Qaysi shoira bahor va sadoqat kuychisi deb atalgan?", "options": ["Zulfiyaxonim", "Nodirabegim", "Uvaysiy", "Zebuniso"], "correct": 0},
    {"q": "Qaysi tarixiy shaxs «To'maris» asarining bosh qahramoni?", "options": ["Massagetlar malikasi To'maris", "Zarina", "Barchinoy", "Roxana"], "correct": 0},
    {"q": "Qaysi alloma o'zbek tilining boyligini isbotlab kitob yozgan?", "options": ["Alisher Navoiy — «Muhokamat ul-lug'atayn»", "Zahiriddin Bobur — «Mubayyin»", "Mahmud Qoshg'ariy — «Devon»", "Yusuf Xos Hojib — «Qutadg'u»"], "correct": 0},
    {"q": "Qaysi asar Navoiyning 4 turkiy devoni to'plamidir?", "options": ["«Xazoyin ul-maoniy»", "«Xamsa»", "«Lison ut-tayr»", "«Mahbub ul-qulub»"], "correct": 0},
    {"q": "Qaysi shoir «O'zbegim» qasidasini yozgan?", "options": ["Erkin Vohidov", "Abdulla Oripov", "Muhammad Yusuf", "Usmon Nosir"], "correct": 0},
    {"q": "Qaysi adib «Omonboy va Davronboy» ertak-qissasini yozgan?", "options": ["Xudoyberdi To'xtaboyev", "Anvar Obidjon", "G'afur G'ulom", "Quddus Muhammadiy"], "correct": 0},
    {"q": "Qaysi muallif «Meshpolvonning janglari» hajviy ertagini yaratgan?", "options": ["Anvar Obidjon", "Xudoyberdi To'xtaboyev", "Po'lat Mo'min", "Tursunboy Adashboyev"], "correct": 0},
    {"q": "Qaysi roman Ikkinchi jahon urushi yillari fojiasini ochib bergan?", "options": ["«Ufq» trilogiyasi — Said Ahmad", "«Kelinlar qo'zg'oloni»", "«Lolazor»", "«Yulduzlar mangu yonadi»"], "correct": 0},
    {"q": "Qaysi asarda dehqonning o'g'irlangan ho'kizi qidiriladi?", "options": ["«O'g'ri» — Abdulla Qahhor", "«Bemor» — Abdulla Qahhor", "«Anor» — Abdulla Qahhor", "«Dahshat» — Abdulla Qahhor"], "correct": 0},
    {"q": "Qaysi xorijiy adib «Chol va dengiz» qissasini yozgan?", "options": ["Ernest Xeminguey", "Jek London", "Uilyam Folkner", "Teodor Drayzer"], "correct": 0},
    {"q": "Qaysi roman Makondo qishlog'idagi yetti avlod haqida?", "options": ["«Yuz yillik yolg'izlik» — Gabriel Garsia Markes", "«Patriarxning kuzi»", "«Vabo davridagi muhabbat»", "«Alkimyogar»"], "correct": 0},
    {"q": "Qaysi asarda totalitar tuzum «1984» yilda fosh etiladi?", "options": ["«1984» — Jorj Oruell", "«Molxona» — Jorj Oruell", "«Farengeyt» — Rey Bredberi", "«Jarayon» — Frants Kafka"], "correct": 0},
    {"q": "Qaysi asar hayvonlar fermasi orqali jamiyatni satira qilgan?", "options": ["«Molxona» — Jorj Oruell", "«1984»", "«Kichkina Shahzoda»", "«Don Kixot»"], "correct": 0},
    {"q": "Qaysi asarda qahramon bir tongda ulkan hasharotga aylanib uyg'onadi?", "options": ["«Evrilish» — Frants Kafka", "«Jarayon» — Frants Kafka", "«Begona» — Alber Kamyu", "«Qasr» — Frants Kafka"], "correct": 0},
    {"q": "Qaysi faylasuf «Begona» va «Vabo» romanlarini yozgan?", "options": ["Alber Kamyu", "Jan-Pol Sartr", "Fridrix Nitsshe", "Artur Shopengauer"], "correct": 0},
    {"q": "Qaysi ertak-qissada sayyoralar kezgan bola tasvirlangan?", "options": ["«Kichkina Shahzoda» — Antuan de Sent-Ekzyuperi", "«Alisa mo''jizalar yurtida»", "«Piter Pen»", "«Tom Soyer»"], "correct": 0},
    {"q": "Qaysi roman Parij ibodatxonasidagi bukri qorovul haqida?", "options": ["«Parij Bibi Maryam ibodatxonasi» — Viktor Gyugo", "«Xo'rlanganlar»", "«Graf Monte-Kristo»", "«Mushketyorlar»"], "correct": 0},
    {"q": "Qaysi asarda Edmon Dantes If qal'asidan qochib qasos oladi?", "options": ["«Graf Monte-Kristo» — Aleksandr Dyuma", "«Uch mushketyor»", "«Temir niqob»", "«Qora lolalar»"], "correct": 0},
    {"q": "Qaysi asar ritsar Don Kixot va uning xizmatkori haqida?", "options": ["«Don Kixot» — Migel de Servantes", "«Gamlet»", "«Dekameron»", "«Faust»"], "correct": 0},
    {"q": "Qaysi tragediyada «Bo'lmoq yo bo'lmaslik» monologi yangraydi?", "options": ["«Gamlet» — Uilyam Shekspir", "«Otello»", "«Qirol Lir»", "«Makbet»"], "correct": 0},
    {"q": "Qaysi fojia rashkchi general va Dezdemona haqida?", "options": ["«Otello» — Uilyam Shekspir", "«Gamlet»", "«Romeo va Juletta»", "«Koriolan»"], "correct": 0},
    {"q": "Qaysi asarda olim o'z ruhini Mefistofelga sotadi?", "options": ["«Faust» — Iogann Volfgang Gyote", "«Verter»", "«Vilgelm Tell»", "«Qaroqchilar»"], "correct": 0},
    {"q": "Qaysi romanda talaba Raskolnikov kampirni o'ldirib pushaymon bo'ladi?", "options": ["«Jinoyat va jazo» — Fyodor Dostoyevskiy", "«Idiot»", "«Aka-uka Karamazovlar»", "«Yozuvlar»"], "correct": 0},
    {"q": "Qaysi roman Napoleonning 1812-yilgi urushiga bag'ishlangan?", "options": ["«Urush va tinchlik» — Lev Tolstoy", "«Anna Karenina»", "«Tirilish»", "«Kazaklar»"], "correct": 0},
    {"q": "Qaysi romanda qahramon ayol o'zini poyezd ostiga tashlaydi?", "options": ["«Anna Karenina» — Lev Tolstoy", "«Urush va tinchlik»", "«Madam Bovari»", "«Dorian Grey»"], "correct": 0},
    {"q": "Qaysi qissada kimsasiz orolda 28 yil yashagan dengizchi tasvirlanadi?", "options": ["«Robinzon Kruzo» — Daniel Defo", "«Gulliver»", "«Xazinalar oroli»", "«Dengiz bo'risi»"], "correct": 0},
    {"q": "Qaysi asarda liliputlar va gigantlar o'lkasi tasvirlanadi?", "options": ["«Gulliverning sayohatlari» — Jonatan Svift", "«Robinzon Kruzo»", "«Alisa»", "«Mo''jizalar oroli»"], "correct": 0},
    {"q": "Qaysi sarguzasht asarida Tom Soyer do'sti Gek bilan xazina qidiradi?", "options": ["«Tom Soyerning sarguzashtlari» — Mark Tven", "«Geklberri Finn»", "«Shahzoda va gado»", "«Oliver Tvist»"], "correct": 0},
    {"q": "Qaysi asarda Dorian Greyning o'zi emas, balki portreti qariydi?", "options": ["«Dorian Greyning portreti» — Oskar Uayld", "«Kenterberri sharpasi»", "«Baxtli shahzoda»", "«Salomeya»"], "correct": 0}
]
