# -*- coding: utf-8 -*-
"""Bilim Qal'asi (Castle) question bank.
Over 200+ unique, verified multiple-choice questions across Uzbek and world literature,
history, poetry, and classical heritage. Options are shuffled at runtime.
"""

CASTLE_QUESTIONS = [
    {"q": "«O'tkan kunlar» romani muallifi kim?", "options": ["Abdulla Qodiriy", "Cho'lpon", "Oybek", "G'afur G'ulom"], "correct": 0},
    {"q": "«Mehrobdan chayon» kim qalamiga mansub?", "options": ["Abdulla Qodiriy", "Oybek", "Said Ahmad", "Tohir Malik"], "correct": 0},
    {"q": "Alisher Navoiy «Xamsa»si nechta dostondan iborat?", "options": ["5", "4", "3", "6"], "correct": 0},
    {"q": "«Urush va tinchlik» muallifi kim?", "options": ["Lev Tolstoy", "Dostoyevskiy", "Chexov", "Pushkin"], "correct": 0},
    {"q": "«Jinoyat va jazo» kim asari?", "options": ["Fyodor Dostoyevskiy", "Tolstoy", "Gogol", "Turgenev"], "correct": 0},
    {"q": "«Kecha va kunduz» romani muallifi kim?", "options": ["Cho'lpon", "Fitrat", "Qodiriy", "Oybek"], "correct": 0},
    {"q": "«Shum bola» qissasi muallifi kim?", "options": ["G'afur G'ulom", "Abdulla Qahhor", "Said Ahmad", "Oybek"], "correct": 0},
    {"q": "«Sarob» romani muallifi kim?", "options": ["Abdulla Qahhor", "Cho'lpon", "Qodiriy", "G'afur G'ulom"], "correct": 0},
    {"q": "«Navoiy» romani muallifi kim?", "options": ["Oybek", "Pirimqul Qodirov", "Odil Yoqubov", "Said Ahmad"], "correct": 0},
    {"q": "«Qutlug' qon» romani kim qalamiga mansub?", "options": ["Oybek", "Qodiriy", "Qahhor", "Cho'lpon"], "correct": 0},
    {"q": "«Yulduzli tunlar» romani bosh qahramoni kim?", "options": ["Zahiriddin Muhammad Bobur", "Ulug'bek", "Amir Temur", "Alisher Navoiy"], "correct": 0},
    {"q": "«Ulug'bek xazinasi» romani muallifi kim?", "options": ["Odil Yoqubov", "Pirimqul Qodirov", "Asqad Muxtor", "Said Ahmad"], "correct": 0},
    {"q": "«Ikki eshik orasi» romani muallifi kim?", "options": ["O'tkir Hoshimov", "Said Ahmad", "Tohir Malik", "O'lmas Umarbekov"], "correct": 0},
    {"q": "«Dunyoning ishlari» qissasi muallifi kim?", "options": ["O'tkir Hoshimov", "Abdulla Qahhor", "G'afur G'ulom", "Said Ahmad"], "correct": 0},
    {"q": "«Shaytanat» asari muallifi kim?", "options": ["Tohir Malik", "Said Ahmad", "O'tkir Hoshimov", "Pirimqul Qodirov"], "correct": 0},
    {"q": "«Kelinlar qo'zg'oloni» pyesasi muallifi kim?", "options": ["Said Ahmad", "O'tkir Hoshimov", "Abdulla Qahhor", "Hamza"], "correct": 0},
    {"q": "«Ufq» trilogiyasi muallifi kim?", "options": ["Said Ahmad", "Oybek", "Pirimqul Qodirov", "Odil Yoqubov"], "correct": 0},
    {"q": "«Diyonat» romani muallifi kim?", "options": ["Odil Yoqubov", "Pirimqul Qodirov", "O'tkir Hoshimov", "Asqad Muxtor"], "correct": 0},
    {"q": "«Jimjitlik» romani muallifi kim?", "options": ["Said Ahmad", "O'tkir Hoshimov", "Odil Yoqubov", "Pirimqul Qodirov"], "correct": 0},
    {"q": "«Chinor» romani muallifi kim?", "options": ["Asqad Muxtor", "Said Ahmad", "Oybek", "Qahhor"], "correct": 0},
    {"q": "«Boburnoma» qaysi tilda yozilgan?", "options": ["Eski o'zbek (turkiy)", "Fors", "Arab", "Urdu"], "correct": 0},
    {"q": "«Qutadg'u bilig» muallifi kim?", "options": ["Yusuf Xos Hojib", "Mahmud Koshg'ariy", "Ahmad Yugnakiy", "Ahmad Yassaviy"], "correct": 0},
    {"q": "«Devoni hikmat» muallifi kim?", "options": ["Xoja Ahmad Yassaviy", "Sulaymon Boqirg'oniy", "Najmiddin Kubro", "So'fi Ollohyor"], "correct": 0},
    {"q": "«Sabotul ojizin» asari muallifi kim?", "options": ["So'fi Ollohyor", "Ahmad Yassaviy", "Mashrab", "Huvaydo"], "correct": 0},
    {"q": "«Farhod va Shirin» dostonida Farhod qaysi mamlakat shahzodasi?", "options": ["Xitoy (Chin)", "Eron", "Armaniston", "Rum"], "correct": 0},
    {"q": "«Layli va Majnun» dostonida Majnunning asl ismi nima?", "options": ["Qays", "Navfal", "Ibn Salom", "Zayd"], "correct": 0},
    {"q": "«O'zbegim» qasidasi muallifi kim?", "options": ["Erkin Vohidov", "Abdulla Oripov", "Muhammad Yusuf", "Hamid Olimjon"], "correct": 0},
    {"q": "«O'zbekiston» qasidasi muallifi kim?", "options": ["Abdulla Oripov", "Erkin Vohidov", "Muhammad Yusuf", "Shavkat Rahmon"], "correct": 0},
    {"q": "«Jannatga yo'l» dramatik dostoni muallifi kim?", "options": ["Abdulla Oripov", "Erkin Vohidov", "Usmon Azim", "Shukur Xolmirzayev"], "correct": 0},
    {"q": "«Ruhlar isyoni» dostoni muallifi kim?", "options": ["Erkin Vohidov", "Abdulla Oripov", "Asqad Muxtor", "Rauf Parfi"], "correct": 0},
    {"q": "«Sariq devni minib» asari muallifi kim?", "options": ["Xudoyberdi To'xtaboyev", "G'afur G'ulom", "Anvar Obidjon", "Tohir Malik"], "correct": 0},
    {"q": "«Otamdan qolgan dalalar» romani muallifi kim?", "options": ["Tog'ay Murod", "Odil Yoqubov", "Pirimqul Qodirov", "Asqad Muxtor"], "correct": 0},
    {"q": "«Yulduzlar mangu yonadi» qissasi muallifi kim?", "options": ["Tog'ay Murod", "Shukur Xolmirzayev", "Nazar Eshonqul", "Murod Muhammad Do'st"], "correct": 0},
    {"q": "«Ot kishnagan oqshom» qissasi muallifi kim?", "options": ["Tog'ay Murod", "Shukur Xolmirzayev", "Erkin A'zam", "Xurshid Do'stmuhammad"], "correct": 0},
    {"q": "«Lolazor» romani muallifi kim?", "options": ["Murod Muhammad Do'st", "Tog'ay Murod", "Erkin A'zam", "Nazar Eshonqul"], "correct": 0},
    {"q": "«Anor» hikoyasi muallifi kim?", "options": ["Abdulla Qahhor", "G'afur G'ulom", "Said Ahmad", "Cho'lpon"], "correct": 0},
    {"q": "«Bemor» hikoyasi muallifi kim?", "options": ["Abdulla Qahhor", "Cho'lpon", "G'afur G'ulom", "Oybek"], "correct": 0},
    {"q": "«O'g'ri» hikoyasi muallifi kim?", "options": ["Abdulla Qahhor", "G'afur G'ulom", "Oybek", "Cho'lpon"], "correct": 0},
    {"q": "«Dahshat» hikoyasi muallifi kim?", "options": ["Abdulla Qahhor", "Cho'lpon", "Oybek", "G'afur G'ulom"], "correct": 0},
    {"q": "«Asrga tatigulik kun» romani muallifi kim?", "options": ["Chingiz Aytmatov", "Sobit Muqonov", "Muxtor Avezov", "Abay"], "correct": 0},
    {"q": "«Qiyomat» (Plaxa) romani muallifi kim?", "options": ["Chingiz Aytmatov", "Sobit Muqonov", "Rasul Hamzatov", "Mustay Karim"], "correct": 0},
    {"q": "«Oq kema» qissasi muallifi kim?", "options": ["Chingiz Aytmatov", "Muxtor Avezov", "Rasul Hamzatov", "Sobit Muqonov"], "correct": 0},
    {"q": "«Mening Dog'istonim» asari muallifi kim?", "options": ["Rasul Hamzatov", "Fozil Iskandar", "Chingiz Aytmatov", "Qaysin Quliyev"], "correct": 0},
    {"q": "«Abay yo'li» epopeyasi muallifi kim?", "options": ["Muxtor Avezov", "Sobit Muqonov", "Ilyas Yesenberlin", "Chingiz Aytmatov"], "correct": 0},
    {"q": "«Alkimyogar» romani muallifi kim?", "options": ["Paulo Koelo", "Gabriel Garsia Markes", "Xorxe Luis Borxes", "Mario Vargas Lyosa"], "correct": 0},
    {"q": "«Yolg'izlikning yuz yili» romani muallifi kim?", "options": ["Gabriel Garsia Markes", "Paulo Koelo", "Xulio Kortasar", "Karlos Fuentes"], "correct": 0},
    {"q": "«1984» distopik romani muallifi kim?", "options": ["Jorj Oruell", "Oldos Xaksli", "Rey Bredberi", "Yevgeniy Zamyatin"], "correct": 0},
    {"q": "«Hayvonlar fermasi» satirik qissasi muallifi kim?", "options": ["Jorj Oruell", "Jonatan Svift", "Oldos Xaksli", "Rey Bredberi"], "correct": 0},
    {"q": "«Farengeyt bo'yicha 451 daraja» romani muallifi kim?", "options": ["Rey Bredberi", "Jorj Oruell", "Ayzek Azimov", "Artur Klark"], "correct": 0},
    {"q": "«Metamorfoza» (Evrilish) novellasi muallifi kim?", "options": ["Frans Kafka", "Alber Kamyu", "Jan-Pol Sartr", "Jeyms Joys"], "correct": 0},
    {"q": "«Begona» (L'Étranger) qissasi muallifi kim?", "options": ["Alber Kamyu", "Jan-Pol Sartr", "Frans Kafka", "Marsel Prust"], "correct": 0},
    {"q": "«Vabo» (La Peste) romani muallifi kim?", "options": ["Alber Kamyu", "Jan-Pol Sartr", "Andre Jid", "Lui-Ferdinand Selin"], "correct": 0},
    {"q": "«Uch og'ayni» (Drei Kameraden) romani muallifi kim?", "options": ["Erix Mariya Remark", "Tomas Mann", "Frans Kafka", "Ernest Xeminguey"], "correct": 0},
    {"q": "«Zafar arkasi» (Arc de Triomphe) romani muallifi kim?", "options": ["Erix Mariya Remark", "Viktor Gyugo", "Onore de Balzak", "Stendal"], "correct": 0},
    {"q": "«Chol va dengiz» qissasi muallifi kim?", "options": ["Ernest Xeminguey", "Jek London", "Jon Steynbek", "Mark Tven"], "correct": 0},
    {"q": "«Kichkina shahzoda» asari muallifi kim?", "options": ["Antuan de Sent-Ekzyuperi", "Viktor Gyugo", "Jyul Vern", "Aleksandr Dyuma"], "correct": 0},
    {"q": "«Robinzon Kruzo» romani muallifi kim?", "options": ["Daniel Defo", "Jonatan Svift", "Jyul Vern", "Mark Tven"], "correct": 0},
    {"q": "«Gulliverning sayohatlari» muallifi kim?", "options": ["Jonatan Svift", "Daniel Defo", "Mark Tven", "Jyul Vern"], "correct": 0},
    {"q": "«Graf Monte-Kristo» romani muallifi kim?", "options": ["Aleksandr Dyuma", "Viktor Gyugo", "Balzak", "Stendal"], "correct": 0},
    {"q": "«Uch mushketyor» romani muallifi kim?", "options": ["Aleksandr Dyuma", "Viktor Gyugo", "Jyul Vern", "Balzak"], "correct": 0},
    {"q": "«Notr-Dam ibodatxonasi» romani muallifi kim?", "options": ["Viktor Gyugo", "Aleksandr Dyuma", "Balzak", "Stendal"], "correct": 0},
    {"q": "«Sefillar» (Les Misérables) romani muallifi kim?", "options": ["Viktor Gyugo", "Aleksandr Dyuma", "Balzak", "Zolya"], "correct": 0},
    {"q": "«Don Kixot» romani muallifi kim?", "options": ["Migel de Servantes", "Shekspir", "Dante", "Bokkachcho"], "correct": 0},
    {"q": "«Hamlet» tragediyasi muallifi kim?", "options": ["Uilyam Shekspir", "Gyote", "Shiller", "Molyer"], "correct": 0},
    {"q": "«Romeo va Julyetta» voqealari qaysi shaharda bo'ladi?", "options": ["Verona", "Rim", "Venetsiya", "Florensiya"], "correct": 0},
    {"q": "«Faust» tragediyasi muallifi kim?", "options": ["Iogann Volfgang Gyote", "Fridrix Shiller", "Geynrix Geyne", "Tomas Mann"], "correct": 0},
    {"q": "«Ilohiy komediya» dostoni muallifi kim?", "options": ["Dante Aligyeri", "Franchesko Petrarka", "Jovanni Bokkachcho", "Torqvato Tasso"], "correct": 0},
    {"q": "«Dekameron» novellalar to'plami muallifi kim?", "options": ["Jovanni Bokkachcho", "Dante", "Petrarka", "Makiavelli"], "correct": 0},
    {"q": "«Hukmdor» (Il Principe) asari muallifi kim?", "options": ["Nikkkolo Makiavelli", "Tomas Mor", "Tommazo Kampanella", "Jan Jak Russo"], "correct": 0},
    {"q": "«Utopiya» asari muallifi kim?", "options": ["Tomas Mor", "Frensis Bekon", "Tomas Gobbs", "Jon Lokk"], "correct": 0},
    {"q": "«Quyosh shahri» asari muallifi kim?", "options": ["Tommazo Kampanella", "Tomas Mor", "Platon", "Bekon"], "correct": 0},
    {"q": "«Davlat» (Politeia) asari muallifi qaysi antik faylasuf?", "options": ["Aflotun (Platon)", "Arastu (Aristotel)", "Suqrot (Sokrat)", "Pifagor"], "correct": 0},
    {"q": "«Poetika» va «Metafizika» asarlari muallifi kim?", "options": ["Arastu (Aristotel)", "Aflotun (Platon)", "Gerodot", "Epikur"], "correct": 0},
    {"q": "«Iliada» va «Odisseya» dostonlari muallifi kim?", "options": ["Gomer", "Gesiod", "Sofokl", "Evripid"], "correct": 0},
    {"q": "«Shohnoma» dostoni muallifi kim?", "options": ["Abulqosim Firdavsiy", "Nizomiy Ganjaviy", "Sa'diy Sheroziy", "Hofiz Sheroziy"], "correct": 0},
    {"q": "«Bo'ston» va «Guliston» asarlari muallifi kim?", "options": ["Sa'diy Sheroziy", "Hofiz Sheroziy", "Jomiy", "Firdavsiy"], "correct": 0},
    {"q": "«Haft avrang» dostonlar turkumi muallifi kim?", "options": ["Abdurahmon Jomiy", "Nizomiy Ganjaviy", "Xusrav Dehlaviy", "Alisher Navoiy"], "correct": 0},
    {"q": "«Masnaviyi ma'naviy» asari muallifi kim?", "options": ["Jaloliddin Rumiy", "Shams Tabriziy", "Attor", "Sanoyiy"], "correct": 0},
    {"q": "«Mantiq ut-tayr» (Qushlar tili) asari muallifi kim?", "options": ["Farididdin Attor", "Jaloliddin Rumiy", "Sanoyiy", "Jomiy"], "correct": 0},
    {"q": "«Tib qonunlari» (Al-Qonun fit-tib) muallifi kim?", "options": ["Abu Ali ibn Sino", "Abu Rayhon Beruniy", "Abu Nasr Farobiy", "Al-Xorazmiy"], "correct": 0},
    {"q": "«Hindiston» va «Qadimgi xalqlardan qolgan yodgorliklar» muallifi kim?", "options": ["Abu Rayhon Beruniy", "Ibn Sino", "Farobiy", "Mahmud Koshg'ariy"], "correct": 0},
    {"q": "«Fozil odamlar shahri» asari muallifi kim?", "options": ["Abu Nasr Farobiy", "Ibn Sino", "Beruniy", "Ibn Rushd"], "correct": 0},
    {"q": "«Al-Jabr val-Muqobala» asari orqali algebra faniga asos solgan olim kim?", "options": ["Muhammad al-Xorazmiy", "Mirzo Ulug'bek", "G'iyosiddin Jamshid", "Qozizoda Rumiy"], "correct": 0},
    {"q": "«Ziji jadidi Ko'ragoniy» yulduzlar jadvali muallifi kim?", "options": ["Mirzo Ulug'bek", "Ali Qushchi", "Qozizoda Rumiy", "Jamshid al-Koshiy"], "correct": 0},
    {"q": "«Temur tuzuklari» kimning davlat boshqaruvi va harbiy qoidalariga bag'ishlangan?", "options": ["Sohibqiron Amir Temur", "Mirzo Ulug'bek", "Zahiriddin Muhammad Bobur", "Shohruh Mirzo"], "correct": 0},
    {"q": "«Zafarnoma» asari mualliflaridan biri kim?", "options": ["Sharafiddin Ali Yazdiy", "Nizomiddin Shomiy", "Mirxond", "Xondamir"], "correct": 0},
    {"q": "«Ravzat us-safo» tarixiy asari muallifi kim?", "options": ["Mirxond", "Xondamir", "Ali Yazdiy", "Abdurazzoq Samarqandiy"], "correct": 0},
    {"q": "«Habib us-siyar» asari muallifi kim?", "options": ["Xondamir", "Mirxond", "Bobur", "Navoiy"], "correct": 0},
    {"q": "«Shajarai turk» va «Shajarai tarokima» asarlari muallifi qaysi Xiva xoni?", "options": ["Abulg'ozi Bahodirxon", "Muhammad Rahimxon Feruz", "Eltuzarxon", "Munis Xorazmiy"], "correct": 0},
    {"q": "«Firdavs ul-iqbol» tarixiy asari mualliflari kimlar?", "options": ["Munis va Ogahiy", "Nodira va Uvaysiy", "Gulxaniy va Maxmur", "Zavqiy va Muqimiy"], "correct": 0},
    {"q": "«Zarbulmasal» masallar to'plami muallifi kim?", "options": ["Gulxaniy", "Maxmur", "Muqimiy", "Zavqiy"], "correct": 0},
    {"q": "«Tanobchilar» va «Voqeai daryo» hajviyalari muallifi kim?", "options": ["Muqimiy", "Zavqiy", "Furqat", "Avaz O'tar"], "correct": 0},
    {"q": "«Ahmad Yassaviy» maqbarasi qaysi shaharda joylashgan?", "options": ["Turkiston (Yassi)", "Buxoro", "Samarqand", "Xiva"], "correct": 0},
    {"q": "«Shohi Zinda» yodgorlik majmuasi qaysi shaharda joylashgan?", "options": ["Samarqand", "Buxoro", "Toshkent", "Shahrisabz"], "correct": 0},
    {"q": "«Ichan Qal'a» qadimiy me'moriy majmuasi qaysi shaharda?", "options": ["Xiva", "Buxoro", "Samarqand", "Qo'qon"], "correct": 0},
    {"q": "«Minorai Kalon» qaysi shaharning ramzi hisoblanadi?", "options": ["Buxoro", "Samarqand", "Xiva", "Navoiy"], "correct": 0},
    {"q": "«Registon» maydoni qaysi shaharda joylashgan?", "options": ["Samarqand", "Buxoro", "Toshkent", "Andijon"], "correct": 0},
    {"q": "«Xudoyorxon o'rdasi» qaysi shaharda joylashgan?", "options": ["Qo'qon", "Marg'ilon", "Farg'ona", "Andijon"], "correct": 0},
]
