# -*- coding: utf-8 -*-
"""Kitob Detektivi — mystery books with 3 progressive clues and normalized answer targets."""

DETECTIVE_BOOKS = [
    {"display": "O'tkan kunlar", "norms": ["otkan kunlar", "o'tkan kunlar", "abdulla qodiriy", "qodiriy"],
     "clues": ["Bu — birinchi o'zbek romani hisoblanadi.", "Bosh qahramonlari Otabek va Kumushbibi.", "Muallifi Abdulla Qodiriy, Toshkent va Marg'ilon voqealari tasvirlangan."]},
    {"display": "Mehrobdan chayon", "norms": ["mehrobdan chayon", "abdulla qodiriy"],
     "clues": ["Bu roman Qo'qon xonligi davri haqida.", "Bosh qahramon — munofiq domla Anvar va Ra'no sevgisi.", "Nomida ziyoratgoh joyi va zaharli jonivor nomi bor."]},
    {"display": "Sarob", "norms": ["sarob", "abdulla qahhor"],
     "clues": ["Bu roman ikkiyuzlamachilik va aldov mavzusiga bag'ishlangan.", "Bosh qahramoni Rahimjon ismli yosh yigit.", "Muallifi Abdulla Qahhor, nomi sahrodagi yolg'on suv tasvirini bildiradi."]},
    {"display": "Kecha va kunduz", "norms": ["kecha va kunduz", "cholpon", "abdulhamid sulaymon"],
     "clues": ["Muallifi — jadid shoiri va adibi, taxallusi yulduz nomi.", "Bosh qahramon qiz nomi Zebi.", "Muallifi Cho'lpon, roman nomi sutkaning ikki qismini ifodalaydi."]},
    {"display": "Shum bola", "norms": ["shum bola", "g'afur g'ulom", "gafur gulom"],
     "clues": ["Bu — sho'x va topqir yetim bola sarguzashtlari haqidagi qissa.", "Asarda Toshkent va uning atroflari hazil bilan tasvirlangan.", "Muallifi G'afur G'ulom, nomi bosh qahramon xarakterini ifodalaydi."]},
    {"display": "Boburnoma", "norms": ["boburnoma", "zahiriddin muhammad bobur", "bobur"],
     "clues": ["Bu — dunyo adabiyotidagi eng mashhur xotira-memuar asarlaridan biri.", "Muallifi Hindistonda buyuk davlat barpo etgan shoh va shoir.", "Asar Zahiriddin Muhammad Boburning o'z hayoti va yurishlari haqida."]},
    {"display": "Xamsa", "norms": ["xamsa", "alisher navoiy", "navoiy"],
     "clues": ["Bu — besh mustaqil dostondan iborat ulkan adabiy yodgorlik.", "Muallifi turkiy tilni jahon darajasiga ko'targan buyuk mutafakkir.", "Alisher Navoiy qalamiga mansub bo'lib, 'beshlik' degan ma'noni anglatadi."]},
    {"display": "Qutadg'u bilig", "norms": ["qutadgu bilig", "qutadg'u bilig", "yusuf xos hojib"],
     "clues": ["Bu — XI asrda yozilgan turkiy axloqiy-falsafiy doston.", "Asarda Kuntug'di, Oytoldi, O'gdulmish va O'zg'urmish obrazlari bor.", "Muallifi Yusuf Xos Hojib, nomi 'Baxt keltiruvchi bilim' degani."]},
    {"display": "Ulug'bek xazinasi", "norms": ["ulugbek xazinasi", "ulug'bek xazinasi", "odil yoqubov"],
     "clues": ["Bu tarixiy roman buyuk olim va hukmdor fojiasi haqida.", "Asarda Ali Qushchi, Salohiddin zargar va Abdullatif obrazlari bor.", "Muallifi Odil Yoqubov, Samarqand rasadxonasi va kutubxonasi taqdiri tasvirlanadi."]},
    {"display": "Yulduzli tunlar", "norms": ["yulduzli tunlar", "pirimqul qodirov"],
     "clues": ["Bu tarixiy roman Andijondan to Agragacha bo'lgan yo'lni qamrab oladi.", "Bosh qahramon — yosh Bobur Mirzo.", "Muallifi Pirimqul Qodirov, asar shoirning murakkab hayot yo'liga bag'ishlangan."]},
    {"display": "Ikki eshik orasi", "norms": ["ikki eshik orasi", "o'tkir hoshimov", "otkir hoshimov"],
     "clues": ["Bu roman inson umrini ikki eshik orasidagi yo'lga o'xshatadi.", "Asarda Robiya, Kimsan, Shomurod va boshqa qahramonlar taqdiri bor.", "Muallifi O'tkir Hoshimov, urush va urushdan keyingi yillar hayoti tasvirlangan."]},
    {"display": "Dunyoning ishlari", "norms": ["dunyoning ishlari", "o'tkir hoshimov", "otkir hoshimov"],
     "clues": ["Bu asar ona siymosiga bag'ishlangan ta'sirli novellalardan iborat.", "Asardagi hikoyalar 'Iltijo', 'Oq marmar', 'Qarz' kabi nomlar bilan ataladi.", "Muallifi O'tkir Hoshimov, har bir sahifasi mehr bilan yo'g'rilgan."]},
    {"display": "Shaytanat", "norms": ["shaytanat", "tohir malik"],
     "clues": ["Bu asar kriminal olam va inson nafsining buzulishi haqida.", "Bosh qahramon — Asadbek.", "Muallifi Tohir Malik, ko'p qismli mashhur o'zbek detektiv asari."]},
    {"display": "Kelinlar qo'zg'oloni", "norms": ["kelinlar qo'zg'oloni", "kelinlar qozgoloni", "said ahmad"],
     "clues": ["Bu — o'zbek teatrining eng mashhur komediyalaridan biri.", "Bosh qahramon — Farmonbibi va uning yetti kelini.", "Muallifi Said Ahmad, oiladagi yangilik va qat'iyat to'qnashuvi tasvirlanadi."]},
    {"display": "Urush va tinchlik", "norms": ["urush va tinchlik", "lev tolstoy", "tolstoy"],
     "clues": ["Bu — rus adabiyotining eng yirik epik romanlaridan biri.", "Voqealar Napoleonning Rossiyaga bostirib kirishi davrida kechadi.", "Bosh qahramonlari Andrey Bolkonskiy, Pyer Bezuxov va Natasha Rostova. Muallifi Lev Tolstoy."]},
    {"display": "Jinoyat va jazo", "norms": ["jinoyat va jazo", "fyodor dostoyevskiy", "dostoyevskiy"],
     "clues": ["Bosh qahramon o'zini 'favqulodda shaxs' deb hisoblab, qotillik sodir etadi.", "Asar qahramonning ruhiy kechinmalari va vijdon azobini ochib beradi.", "Bosh qahramon Rodion Raskolnikov. Muallifi Fyodor Dostoyevskiy."]},
    {"display": "Graf Monte-Kristo", "norms": ["graf monte kristo", "aleksandr dyuma", "dyuma"],
     "clues": ["Bu roman xiyonat qurboni bo'lib, if qal'asida yillab yotgan dengizchi haqida.", "Qahramon qamoqdan qochib, ulkan boylik topadi va qasos oladi.", "Bosh qahramon Edmond Dantes. Muallifi Aleksandr Dyuma."]},
    {"display": "Uch mushketyor", "norms": ["uch mushketyor", "aleksandr dyuma", "dyuma"],
     "clues": ["Bu roman 'Birimiz hammamiz uchun, hammamiz birimiz uchun' shiori bilan mashhur.", "Qahramonlar qirolicha marjonlarini qutqarish uchun Londonga boradilar.", "Bosh qahramonlari D'Artanyan, Atos, Portos va Aramis. Muallifi Aleksandr Dyuma."]},
    {"display": "Chol va dengiz", "norms": ["chol va dengiz", "ernest xeminguey", "xeminguey"],
     "clues": ["Bu qissa keksa kubalik baliqchining ulkan qilichbaliq bilan kurashi haqida.", "'Insonni yo'q qilish mumkin, lekin yengib bo'lmaydi' iqtibosi shu asardan.", "Bosh qahramon Santyago. Muallifi Ernest Xeminguey."]},
    {"display": "Kichkina shahzoda", "norms": ["kichkina shahzoda", "sent ekzyuperi", "sent-ekzyuperi"],
     "clues": ["Bosh qahramon o'zining kichik asteroid sayyorasidan Yerga uchib keladi.", "U atirgul, tulki va uchuvchi bilan do'stlashadi.", "'Yurak bilangina haqiqatni ko'rish mumkin' g'oyasi ilgari surilgan. Muallifi Sent-Ekzyuperi."]},
    {"display": "Alkimyogar", "norms": ["alkimyogar", "paulo koelo", "koelo"],
     "clues": ["Bu roman o'z shaxsiy afsonasini izlab Misr piramidalariga yo'l olgan yigit haqida.", "Bosh qahramon — andalusiyalik cho'pon Santyago.", "Muallifi braziliyalik adib Paulo Koelo."]},
    {"display": "1984", "norms": ["1984", "jorj oruell", "oruell"],
     "clues": ["Bu roman totalitar nazorat va 'Katta Birodar' tizimini fosh etadi.", "Asarda 'Haqiqat vazirligi' va 'Fikr politsiyasi' faoliyat yuritadi.", "Bosh qahramon Uinston Smit. Muallifi Jorj Oruell."]},
    {"display": "Hayvonlar fermasi", "norms": ["hayvonlar fermasi", "jorj oruell", "oruell"],
     "clues": ["Bu asar fermadagi inqilob va cho'chqalarning hokimiyatni egallashi haqidagi masal-allegoriya.", "'Barcha hayvonlar teng, ammo ba'zilari tengroq' shiori mashhur.", "Muallifi Jorj Oruell."]},
    {"display": "Don Kixot", "norms": ["don kixot", "servantes", "migel servantes"],
     "clues": ["Bosh qahramon ritsarlik kitoblarini ko'p o'qib, o'zini ritsar deb e'lon qiladi.", "U shamol tegirmonlarini maxluqlar deb o'ylab, ularga hujum qiladi.", "Bosh qahramonning xizmatkori Sancho Pansa. Muallifi Migel de Servantes."]},
    {"display": "Hamlet", "norms": ["hamlet", "shekspir", "uilyam shekspir"],
     "clues": ["Bu tragediya Daniya qirollik saroyidagi qotillik va qasos haqida.", "'Bo'lish yoki bo'lmaslik — mana masala' monologi shu asarda yangraydi.", "Bosh qahramon Daniya shahzodasi. Muallifi Uilyam Shekspir."]},
]
