# -*- coding: utf-8 -*-
"""Kitob Detektivi — mystery books with 3 progressive clues and normalized answer targets."""

DETECTIVE_BOOKS = [
    {"display": "O'tkan kunlar", "norms": ["otkan kunlar", "o'tkan kunlar", "abdulla qodiriy", "qodiriy"],
     "clues": ["Bu — birinchi o'zbek romani hisoblanadi.", "Bosh qahramonlari Otabek va Kumushbibi.", "Muallifi Abdulla Qodiriy, Toshkent va Marg'ilon voqealari tasvirlangan."]},
    {"display": "Mehrobdan chayon", "norms": ["mehrobdan chayon", "abdulla qodiriy"],
     "clues": ["Bu roman Qo'qon xonligi davri haqida.", "Bosh qahramon — munofiq domla Anvar va Ra'no sevgisi.", "Nomida ziyoratgoh joyi va zaharli jonivor nomi bor."]},
    {"display": "Sarob", "norms": ["sarob", "abdulla qahhor"],
     "clues": ["Bu roman ikkiyuzlamachilik va aldov mavzusiga bag'ishlangan.", "Bosh qahramoni Rahimjon ismli yosh yigit.", "Muallifi Abdulla Qahhor, nomi sahrodagi yolg'on suv tasvirini bildiradi."]},
    {"display": "Kecha va kunduz", "norms": ["kecha va kunduz", "cholpon", "abdulhamid sulaymon"],
     "clues": ["Muallifi — jadid shoiri va adibi, taxallusi yulduz nomi.", "Bosh qahramon qiz nomi Zebi.", "Muallifi Cho'lpon, roman nomi sutkaning ikki qismini ifodalaydi."]},
    {"display": "Shum bola", "norms": ["shum bola", "g'afur g'ulom", "gafur gulom"],
     "clues": ["Bu — sho'x va topqir yetim bola sarguzashtlari haqidagi qissa.", "Asarda Toshkent va uning atroflari hazil bilan tasvirlangan.", "Muallifi G'afur G'ulom, nomi bosh qahramon xarakterini ifodalaydi."]},
    {"display": "Boburnoma", "norms": ["boburnoma", "zahiriddin muhammad bobur", "bobur"],
     "clues": ["Bu — dunyo adabiyotidagi eng mashhur xotira-memuar asarlaridan biri.", "Muallifi Hindistonda buyuk davlat barpo etgan shoh va shoir.", "Asar Zahiriddin Muhammad Boburning o'z hayoti va yurishlari haqida."]},
    {"display": "Xamsa", "norms": ["xamsa", "alisher navoiy", "navoiy"],
     "clues": ["Bu — besh mustaqil dostondan iborat ulkan adabiy yodgorlik.", "Muallifi turkiy tilni jahon darajasiga ko'targan buyuk mutafakkir.", "Alisher Navoiy qalamiga mansub bo'lib, 'beshlik' degan ma'noni anglatadi."]},
    {"display": "Qutadg'u bilig", "norms": ["qutadgu bilig", "qutadg'u bilig", "yusuf xos hojib"],
     "clues": ["Bu — XI asrda yozilgan turkiy axloqiy-falsafiy doston.", "Asarda Kuntug'di, Oytoldi, O'gdulmish va O'zg'urmish obrazlari bor.", "Muallifi Yusuf Xos Hojib, nomi 'Baxt keltiruvchi bilim' degani."]},
    {"display": "Ulug'bek xazinasi", "norms": ["ulugbek xazinasi", "ulug'bek xazinasi", "odil yoqubov"],
     "clues": ["Bu tarixiy roman buyuk olim va hukmdor fojiasi haqida.", "Asarda Ali Qushchi, Salohiddin zargar va Abdullatif obrazlari bor.", "Muallifi Odil Yoqubov, Samarqand rasadxonasi va kutubxonasi taqdiri tasvirlanadi."]},
    {"display": "Yulduzli tunlar", "norms": ["yulduzli tunlar", "pirimqul qodirov"],
     "clues": ["Bu tarixiy roman Andijondan to Agragacha bo'lgan yo'lni qamrab oladi.", "Bosh qahramon — yosh Bobur Mirzo.", "Muallifi Pirimqul Qodirov, asar shoirning murakkab hayot yo'liga bag'ishlangan."]},
    {"display": "Ikki eshik orasi", "norms": ["ikki eshik orasi", "o'tkir hoshimov", "otkir hoshimov"],
     "clues": ["Bu roman inson umrini ikki eshik orasidagi yo'lga o'xshatadi.", "Asarda Robiya, Kimsan, Shomurod va boshqa qahramonlar taqdiri bor.", "Muallifi O'tkir Hoshimov, urush va urushdan keyingi yillar hayoti tasvirlangan."]},
    {"display": "Dunyoning ishlari", "norms": ["dunyoning ishlari", "o'tkir hoshimov", "otkir hoshimov"],
     "clues": ["Bu asar ona siymosiga bag'ishlangan ta'sirli novellalardan iborat.", "Asardagi hikoyalar 'Iltijo', 'Oq marmar', 'Qarz' kabi nomlar bilan ataladi.", "Muallifi O'tkir Hoshimov, har bir sahifasi mehr bilan yo'g'rilgan."]},
    {"display": "Shaytanat", "norms": ["shaytanat", "tohir malik"],
     "clues": ["Bu asar kriminal olam va inson nafsining buzulishi haqida.", "Bosh qahramon — Asadbek.", "Muallifi Tohir Malik, ko'p qismli mashhur o'zbek detektiv asari."]},
    {"display": "Kelinlar qo'zg'oloni", "norms": ["kelinlar qo'zg'oloni", "kelinlar qozgoloni", "said ahmad"],
     "clues": ["Bu — o'zbek teatrining eng mashhur komediyalaridan biri.", "Bosh qahramon — Farmonbibi va uning yetti kelini.", "Muallifi Said Ahmad, oiladagi yangilik va qat'iyat to'qnashuvi tasvirlanadi."]},
    {"display": "Urush va tinchlik", "norms": ["urush va tinchlik", "lev tolstoy", "tolstoy"],
     "clues": ["Bu — rus adabiyotining eng yirik epik romanlaridan biri.", "Voqealar Napoleonning Rossiyaga bostirib kirishi davrida kechadi.", "Bosh qahramonlari Andrey Bolkonskiy, Pyer Bezuxov va Natasha Rostova. Muallifi Lev Tolstoy."]},
    {"display": "Jinoyat va jazo", "norms": ["jinoyat va jazo", "fyodor dostoyevskiy", "dostoyevskiy"],
     "clues": ["Bosh qahramon o'zini 'favqulodda shaxs' deb hisoblab, qotillik sodir etadi.", "Asar qahramonning ruhiy kechinmalari va vijdon azobini ochib beradi.", "Bosh qahramon Rodion Raskolnikov. Muallifi Fyodor Dostoyevskiy."]},
    {"display": "Graf Monte-Kristo", "norms": ["graf monte kristo", "aleksandr dyuma", "dyuma"],
     "clues": ["Bu roman xiyonat qurboni bo'lib, if qal'asida yillab yotgan dengizchi haqida.", "Qahramon qamoqdan qochib, ulkan boylik topadi va qasos oladi.", "Bosh qahramon Edmond Dantes. Muallifi Aleksandr Dyuma."]},
    {"display": "Uch mushketyor", "norms": ["uch mushketyor", "aleksandr dyuma", "dyuma"],
     "clues": ["Bu roman 'Birimiz hammamiz uchun, hammamiz birimiz uchun' shiori bilan mashhur.", "Qahramonlar qirolicha marjonlarini qutqarish uchun Londonga boradilar.", "Bosh qahramonlari D'Artanyan, Atos, Portos va Aramis. Muallifi Aleksandr Dyuma."]},
    {"display": "Chol va dengiz", "norms": ["chol va dengiz", "ernest xeminguey", "xeminguey"],
     "clues": ["Bu qissa keksa kubalik baliqchining ulkan qilichbaliq bilan kurashi haqida.", "'Insonni yo'q qilish mumkin, lekin yengib bo'lmaydi' iqtibosi shu asardan.", "Bosh qahramon Santyago. Muallifi Ernest Xeminguey."]},
    {"display": "Kichkina shahzoda", "norms": ["kichkina shahzoda", "sent ekzyuperi", "sent-ekzyuperi"],
     "clues": ["Bosh qahramon o'zining kichik asteroid sayyorasidan Yerga uchib keladi.", "U atirgul, tulki va uchuvchi bilan do'stlashadi.", "'Yurak bilangina haqiqatni ko'rish mumkin' g'oyasi ilgari surilgan. Muallifi Sent-Ekzyuperi."]},
    {"display": "Alkimyogar", "norms": ["alkimyogar", "paulo koelo", "koelo"],
     "clues": ["Bu roman o'z shaxsiy afsonasini izlab Misr piramidalariga yo'l olgan yigit haqida.", "Bosh qahramon — andalusiyalik cho'pon Santyago.", "Muallifi braziliyalik adib Paulo Koelo."]},
    {"display": "1984", "norms": ["1984", "jorj oruell", "oruell"],
     "clues": ["Bu roman totalitar nazorat va 'Katta Birodar' tizimini fosh etadi.", "Asarda 'Haqiqat vazirligi' va 'Fikr politsiyasi' faoliyat yuritadi.", "Bosh qahramon Uinston Smit. Muallifi Jorj Oruell."]},
    {"display": "Hayvonlar fermasi", "norms": ["hayvonlar fermasi", "jorj oruell", "oruell"],
     "clues": ["Bu asar fermadagi inqilob va cho'chqalarning hokimiyatni egallashi haqidagi masal-allegoriya.", "'Barcha hayvonlar teng, ammo ba'zilari tengroq' shiori mashhur.", "Muallifi Jorj Oruell."]},
    {"display": "Don Kixot", "norms": ["don kixot", "servantes", "migel servantes"],
     "clues": ["Bosh qahramon ritsarlik kitoblarini ko'p o'qib, o'zini ritsar deb e'lon qiladi.", "U shamol tegirmonlarini maxluqlar deb o'ylab, ularga hujum qiladi.", "Bosh qahramonning xizmatkori Sancho Pansa. Muallifi Migel de Servantes."]},
    {"display": "Hamlet", "norms": ["hamlet", "shekspir", "uilyam shekspir"],
     "clues": ["Bu tragediya Daniya qirollik saroyidagi qotillik va qasos haqida.", "'Bo'lish yoki bo'lmaslik — mana masala' monologi shu asarda yangraydi.", "Bosh qahramon Daniya shahzodasi. Muallifi Uilyam Shekspir."]},
    {"display": "Otamdan qolgan dalalar", "norms": ["otamdan qolgan dalalar", "togay murod", "tog'ay murod"],
     "clues": ["Bu asar o'zbek dehqonining paxta mashmashalari ostidagi fojiali hayoti haqida.", "Bosh qahramoni Jamoliddin Ketmon va uning otalari taqdiri tasvirlanadi.", "Muallifi Tog'ay Murod, o'zbek nasrining bebaho durdonasi."]},
    {"display": "Yulduzlar mangu yonadi", "norms": ["yulduzlar mangu yonadi", "togay murod", "tog'ay murod"],
     "clues": ["Bu qissada Surxon vohasining polvonlik an'analari tasvirlanadi.", "Bosh qahramon Bo'ri polvon va Nasim qora kurashi aks etgan.", "Muallifi Tog'ay Murod."]},
    {"display": "Ot kishnagan oqshom", "norms": ["ot kishnagan oqshom", "togay murod", "tog'ay murod"],
     "clues": ["Bu qissada chavandozlik va otga bo'lgan cheksiz mehr tasvirlanadi.", "Bosh qahramon — chavandoz Ziyodulla va uning oti Tarlon.", "Muallifi Tog'ay Murod."]},
    {"display": "Sariq devni minib", "norms": ["sariq devni minib", "xudoyberdi to'xtaboyev", "xudoyberdi toxtaboyev"],
     "clues": ["Bu — bolalar uchun yozilgan mashhur fantastik-sarguzasht qissa.", "Bosh qahramon sehrli qalpoqcha yordamida har xil qiyofalarga kiradi.", "Bosh qahramon Hoshimjon. Muallifi Xudoyberdi To'xtaboyev."]},
    {"display": "Chinor", "norms": ["chinor", "asqad muxtor"],
     "clues": ["Bu roman ulkan sulolaning ko'p yillik hayoti va ruhiy ildizlari haqida.", "Asarda Ochil buva, Azizbek va Muzaffar obrazlari bor.", "Muallifi Asqad Muxtor, asar nomi asriy mustahkam daraxt nomidir."]},
    {"display": "Lolazor", "norms": ["lolazor", "murod muhammad do'st", "murod muhammad dost"],
     "clues": ["Bu roman turg'unlik davridagi ma'naviy inqiroz va laganbardorlikni fosh qiladi.", "Asarda Yaxshiboyev, Oshno va boshqa personajlar harakat qiladi.", "Muallifi Murod Muhammad Do'st."]},
    {"display": "Qutlug' qon", "norms": ["qutlug' qon", "qutlug qon", "oybek"],
     "clues": ["Bu roman 1916-yilgi mardikorlikka olishga qarshi xalq qo'zg'oloniga bag'ishlangan.", "Bosh qahramonlari Yo'lchi, Gulnor va Mirzakarimboy.", "Muallifi Oybek."]},
    {"display": "Navoiy", "norms": ["navoiy", "oybek", "muso toshmuhammad"],
     "clues": ["Bu tarixiy roman XV asr Hirot muhiti va buyuk shoir hayotini gavdalantiradi.", "Asarda Husayn Boyqaro, Majididdin va Dildor obrazlari bor.", "Muallifi Oybek."]},
    {"display": "O'g'ri", "norms": ["o'g'ri", "ogri", "abdulla qahhor"],
     "clues": ["Bu hikoyada bir bechora dehqonning yo'qolgan ho'kizi qidiriladi.", "Amin, ellikboshi va pristav dehqonni talab xonavayron qiladi.", "Bosh qahramon Qobil bobo. Muallifi Abdulla Qahhor."]},
    {"display": "Anor", "norms": ["anor", "abdulla qahhor"],
     "clues": ["Bu hikoyada homilador xotinining qon talab qilgan mevasini topolmagan er fojiasi aks etgan.", "Bosh qahramon Turobboy xotiniga meva izlab sarson bo'ladi.", "Muallifi Abdulla Qahhor."]},
    {"display": "Bemor", "norms": ["bemor", "abdulla qahhor"],
     "clues": ["Bu hikoyada qashshoqlik va xurofot tufayli yosh ayolning o'limi tasvirlanadi.", "Bosh qahramon Sotiboldi xotinini qutqarish uchun tabib va folbinga boradi.", "Muallifi Abdulla Qahhor."]},
    {"display": "Dahshat", "norms": ["dahshat", "abdulla qahhor"],
     "clues": ["Bu hikoyada jasur qiz o'z oriyati uchun tunda qabristonga borishga majbur bo'ladi.", "Bosh qahramon Unsin qabr ustiga kovush qo'yish shartini bajaradi.", "Muallifi Abdulla Qahhor."]},
    {"display": "Sinchalak", "norms": ["sinchalak", "abdulla qahhor"],
     "clues": ["Bu qissada faol va shijoatli yosh qizning jamoat ishlaridagi o'rni tasvirlanadi.", "Bosh qahramon Saida kichik qush nomi bilan qiyoslanadi.", "Muallifi Abdulla Qahhor."]},
    {"display": "Ufq", "norms": ["ufq", "said ahmad"],
     "clues": ["Bu mashhur trilogiya urushdan oldingi, urush va urushdan keyingi yillarni qamrab oladi.", "Asarda Ikromjon, Jannat xola, Dildor va Tursunboy obrazlari bor.", "Muallifi Said Ahmad."]},
    {"display": "Ruhlar isyoni", "norms": ["ruhlar isyoni", "erkin vohidov"],
     "clues": ["Bu falsafiy doston ozodlik va erk kuychisi bo'lgan hind shoiri hayotiga bag'ishlangan.", "Asarda Nazrul Islom siymosi orqali mustamlakachilik fosh etiladi.", "Muallifi Erkin Vohidov."]},
    {"display": "Jannatga yo'l", "norms": ["jannatga yo'l", "jannatga yol", "abdulla oripov"],
     "clues": ["Bu dramatik doston inson vijdoni va narigi dunyodagi hisob-kitob haqida.", "Asarda Yigit oxirat sarhadida o'z qilmishlari uchun javob beradi.", "Muallifi Abdulla Oripov."]},
    {"display": "O'zbegim", "norms": ["o'zbegim", "ozbegim", "erkin vohidov"],
     "clues": ["Bu mashhur qasidada o'zbek xalqining ming yillik shonli tarixi tarannum etiladi.", "'Tori sendan, siri sendan...' deb boshlanuvchi otashin misralar bor.", "Muallifi Erkin Vohidov."]},
    {"display": "Padarkush", "norms": ["padarkush", "mahmudxo'ja behbudiy", "behbudiy"],
     "clues": ["Bu — o'zbek milliy teatrining ilk dramatik asari (1911).", "Asarda ilmsizlik tufayli o'z otasini o'ldirgan nodon o'g'il fojiasi ko'rsatiladi.", "Muallifi Mahmudxo'ja Behbudiy."]},
    {"display": "Munozara", "norms": ["munozara", "fitrat", "abdurauf fitrat"],
     "clues": ["Bu asarda yevropalik sayyoh va buxorolik mudarris o'rtasida bahs kechadi.", "Asar Buxorodagi turg'unlik va xurofotni tanqid qiladi.", "Muallifi Abdurauf Fitrat (1909)."]},
    {"display": "Turkiy Guliston yoxud axloq", "norms": ["turkiy guliston", "abdulla avloniy", "avloniy"],
     "clues": ["Bu kitob milliy axloq, tarbiya va insoniy fazilatlarga bag'ishlangan darslikdir.", "'Tarbiya biz uchun yo hayot — yo mamot...' shiori shu asar g'oyasidir.", "Muallifi Abdulla Avloniy."]},
    {"display": "Sherlok Xolms sarguzashtlari", "norms": ["sherlok xolms", "konan doyl", "artur konan doyl"],
     "clues": ["Bu turkumda daho detektiv va uning do'sti doktor tergov olib boradi.", "Bosh qahramon Beyker-strit 221B manzilida istiqomat qiladi.", "Muallifi Artur Konan Doyl."]},
    {"display": "Sharqiy ekspressda qotillik", "norms": ["sharqiy ekspressda qotillik", "agata kristi"],
     "clues": ["Bu mashhur detektiv romanda qor bo'ronida to'xtab qolgan poyezdda qotillik yuz beradi.", "Bosh qahramon belgiya tergovchisi Erkyul Puaro.", "Muallifi Agata Kristi."]},
    {"display": "Parij Bibi Maryam ibodatxonasi", "norms": ["notr dam", "parij bibi maryam ibodatxonasi", "viktor gyugo"],
     "clues": ["Bu tarixiy romanda o'rta asrlar Pariji va buyuk gotika sobori tasvirlanadi.", "Bosh qahramonlari Esmeralda, Kvazimodo va Klod Frollo.", "Muallifi Viktor Gyugo."]},
    {"display": "Faust", "norms": ["faust", "gyote", "iogann volfgang gyote"],
     "clues": ["Bu buyuk tragediyada olim hayot sirlarini bilish uchun iblis bilan shartnoma tuzadi.", "Asarda Mefistofel va Margarita obrazlari bor.", "Muallifi Iogann Volfgang Gyote."]},
    {"display": "Otello", "norms": ["otello", "shekspir", "uilyam shekspir"],
     "clues": ["Bu fojia hasad, tuhmat va rashk tufayli beg'ubor ayolning halokati haqida.", "Bosh qahramonlari Venetsiya sarkardasi va Dezdemona.", "Muallifi Uilyam Shekspir."]},
    {"display": "Anna Karenina", "norms": ["anna karenina", "lev tolstoy", "tolstoy"],
     "clues": ["Bu romanda oliy tabaqa ayolining muhabbat va jamiyat qoliplari orasidagi fojeasi tasvirlanadi.", "Asar 'Hamma baxtli oilalar bir-biriga o'xshaydi...' jumlasi bilan boshlanadi.", "Bosh qahramon ayol temir yo'l relsida halok bo'ladi. Muallifi Lev Tolstoy."]},
    {"display": "Asrga tatigulik kun", "norms": ["asrga tatigulik kun", "chingiz aytmatov", "aytmatov"],
     "clues": ["Bu romanda Sarozek dashtidagi temiryo'lchilar va mankurt afsonasi tasvirlangan.", "Bosh qahramonlari Yedigey, Qozang'ap va Nayman ona.", "Muallifi Chingiz Aytmatov."]},
    {"display": "Qiyomat", "norms": ["qiyomat", "chingiz aytmatov", "aytmatov"],
     "clues": ["Bu romanda insoniyatning tabiatga tajovuzi va bo'rilar fojiasi ochib beriladi.", "Asarda Akbara bo'ri, Avdiy Kallistratov va Bo'stona qismati bor.", "Muallifi Chingiz Aytmatov."]},
    {"display": "451 daraja Farengeyt", "norms": ["451 daraja farengeyt", "rey bredberi", "bredberi"],
     "clues": ["Bu fantastik romanda kitob o'qish taqiqlangan va o't o'chiruvchilar kitoblarni yoqadi.", "Kitob qog'ozi o'z-o'zidan yonib ketadigan harorat asar nomi qilingan.", "Bosh qahramon Gay Monteg. Muallifi Rey Bredberi."]},
    {"display": "Evrilish", "norms": ["evrilish", "frants kafka", "kafka"],
     "clues": ["Bu novellada oddiy xizmatchi bir kuni ertalab bahaybat hasharotga aylanib uyg'onadi.", "Asarda insonning yolg'izligi va oila mehrining soxtaligi ochiladi.", "Bosh qahramon Gregor Zamza. Muallifi Frants Kafka."]},
    {"display": "Begona", "norms": ["begona", "alber kamyu", "kamyu"],
     "clues": ["Bu falsafiy romanda jamiyat qoliplariga bo'ysunmaydigan befarq qahramon tasvirlangan.", "Asar 'Bugun onam vafot etdi. Balki kechadir...' deb boshlanadi.", "Bosh qahramon Merso. Muallifi Alber Kamyu."]},
    {"display": "Yuz yillik yolg'izlik", "norms": ["yuz yillik yolg'izlik", "yuz yillik yolgizlik", "gabriel garsia markes", "markes"],
     "clues": ["Bu sehrli realizm romani Makondo qishlog'idagi Buendialar sulolasi haqida.", "Asarda polkovnik Aurelyano Buendia va Ursula obrazlari markazda turadi.", "Muallifi Nobel mukofoti sohibi Gabriel Garsia Markes."]},
    {"display": "Usta va Margarita", "norms": ["usta va margarita", "mixail bulgakov", "bulgakov"],
     "clues": ["Bu tasavvufiy romanda iblis Voland o'z mulozimlari bilan 1930-yillar Moskvashiga tashrif buyuradi.", "Asarda Iisus Xristos va Pontiy Pilat qissasi ham parallel bayon qilinadi.", "Muallifi Mixail Bulgakov."]},
    {"display": "Dorian Greyning portreti", "norms": ["dorian greyning portreti", "oskar uayld", "uayld"],
     "clues": ["Bu romanda yosh go'zal yigitning o'zi emas, balki portreti qariy boshlaydi.", "Qahramon har qanday gunohni qilsa ham, o'zining tashqi go'zalligini yo'qotmaydi.", "Bosh qahramon Dorian Grey. Muallifi Oskar Uayld."]},
]
