# -*- coding: utf-8 -*-
"""Emoji Kitob — guess the book from emojis.
Over 120+ unique emoji riddle questions with 4 options. Shuffled at runtime.
"""

EMOJI_QUESTIONS = [
    {"emoji": "👴 🌊 🐟 🎣", "options": ["Chol va dengiz", "Robinzon Kruzo", "Oq kema", "Moby Dik"], "correct": 0},
    {"emoji": "🤴 🌹 🦊 🪐", "options": ["Kichkina shahzoda", "Pinokkio", "Piter Pen", "Alisa mo'jizalar mamlakatida"], "correct": 0},
    {"emoji": "🏝️ 👣 ⛵ 🥥", "options": ["Robinzon Kruzo", "Gulliver sayohatlari", "Sindbad", "Kapitan qizi"], "correct": 0},
    {"emoji": "🐺 ❄️ 🐕 🏔️", "options": ["Oq So'yloq", "Bemor", "Momo", "Oq kema"], "correct": 0},
    {"emoji": "🔪 ⚖️ 😰 🪙", "options": ["Jinoyat va jazo", "Anna Karenina", "Telba (Idiot)", "Sarob"], "correct": 0},
    {"emoji": "🚂 💔 👩 ❄️", "options": ["Anna Karenina", "Urush va tinchlik", "Ona", "Sarob"], "correct": 0},
    {"emoji": "⚔️ 🕊️ 🇷🇺 👑", "options": ["Urush va tinchlik", "Tinch Don", "Ona", "Idiot"], "correct": 0},
    {"emoji": "🗡️ 🤺 4️⃣ 🇫🇷", "options": ["Uch mushketyor", "Robin Gud", "Don Kixot", "Ayvengo"], "correct": 0},
    {"emoji": "🏰 💰 🗝️ 🌊", "options": ["Graf Monte-Kristo", "Ali Baba", "Oltin kalit", "Xazina oroli"], "correct": 0},
    {"emoji": "🕌 🦂 📜 💔", "options": ["Mehrobdan chayon", "Shaytanat", "Diyonat", "Kabus"], "correct": 0},
    {"emoji": "👦 😜 🎭 🇺🇿", "options": ["Shum bola", "Tom Soyer", "Chipollino", "Buratino"], "correct": 0},
    {"emoji": "⭐ 🌙 🌃 👑", "options": ["Yulduzli tunlar", "Kecha va kunduz", "Sarob", "Ufq"], "correct": 0},
    {"emoji": "🧪 ⚗️ 🐫 🏜️", "options": ["Alkimyogar", "Sindbad", "Robinzon", "Sahroyi kabir"], "correct": 0},
    {"emoji": "🐷 🐴 🚩 🏛️", "options": ["Hayvonlar fermasi", "Robinzon", "Momo", "Idiot"], "correct": 0},
    {"emoji": "👁️ 🏙️ 1️⃣9️⃣8️⃣4️⃣", "options": ["1984", "Biz", "Farengeyt 451", "O'yin"], "correct": 0},
    {"emoji": "🐛 ➡️ 🧑 😱", "options": ["Metamorfoza", "Jinoyat va jazo", "Telba", "Bemor"], "correct": 0},
    {"emoji": "🎭 💀 🇩🇰 👑", "options": ["Hamlet", "Otello", "Qirol Lir", "Makbet"], "correct": 0},
    {"emoji": "❤️ 🗡️ 👫 ⚰️", "options": ["Romeo va Julyetta", "Layli va Majnun", "Farhod va Shirin", "Tohir va Zuhra"], "correct": 0},
    {"emoji": "🗿 ⛏️ 🏔️ 👑", "options": ["Ulug'bek xazinasi", "Boburnoma", "Navoiy", "Yulduzli tunlar"], "correct": 0},
    {"emoji": "🕵️ 🔍 🚬 🎻", "options": ["Sherlok Xolms", "Erkul Puaro", "Miss Marpl", "Fandorin"], "correct": 0},
    {"emoji": "🐋 ⛵ 🎣 😡", "options": ["Moby Dik", "Chol va dengiz", "Robinzon", "Dengiz ostida 20 ming liga"], "correct": 0},
    {"emoji": "🌊 🚢 🐙 2️⃣0️⃣0️⃣0️⃣0️⃣", "options": ["Dengiz ostida 20 ming liga", "Titanik", "Robinzon", "Sindbad"], "correct": 0},
    {"emoji": "🎈 🌍 8️⃣0️⃣ 📅", "options": ["80 kunda dunyo bo'ylab", "Vaqt mashinasi", "Oy sayohati", "Sindbad"], "correct": 0},
    {"emoji": "🧞 🪔 🏜️ 🏰", "options": ["Alouddin", "Ali Baba", "Sindbad", "Kichkina shahzoda"], "correct": 0},
    {"emoji": "🍎 ❄️ 7️⃣ 👸", "options": ["Qorqiz va yetti gnom", "Zolushka", "Rapunzel", "Qizil shapkacha"], "correct": 0},
    {"emoji": "🐺 👵 🔴 🧺", "options": ["Qizil shapkacha", "Uch cho'chqa", "Qorqiz", "Bo'ri va yetti uloq"], "correct": 0},
    {"emoji": "🎃 👞 🐭 🕛", "options": ["Zolushka", "Qorqiz", "Uxlab qolgan malika", "Rapunzel"], "correct": 0},
    {"emoji": "📖 🌌 ✍️ 🇺🇿", "options": ["O'tkan kunlar", "Kecha va kunduz", "Sarob", "Ufq"], "correct": 0},
    {"emoji": "🧔 👑 📜 🇮🇳", "options": ["Boburnoma", "Navoiy", "Yulduzli tunlar", "Ulug'bek xazinasi"], "correct": 0},
    {"emoji": "🌹 🎶 📚 ✒️", "options": ["Xamsa", "Devon", "Boburnoma", "Qutadg'u bilig"], "correct": 0},
    {"emoji": "🤺 🌪️ 🐴 🛡️", "options": ["Don Kixot", "Uch mushketyor", "Ayvengo", "Robin Gud"], "correct": 0},
    {"emoji": "🧑 📏 👥 🏝️", "options": ["Gulliver sayohatlari", "Robinzon Kruzo", "Sindbad sayohatlari", "Kichkina shahzoda"], "correct": 0},
    {"emoji": "🏰 ❄️ 💂 ❤️", "options": ["Kapitan qizi", "Anna Karenina", "Ruslan va Lyudmila", "Yevgeniy Onegin"], "correct": 0},
    {"emoji": "👩 🚩 ✊ 🏭", "options": ["Ona", "Tinch Don", "Urush va tinchlik", "Ota va bolalar"], "correct": 0},
    {"emoji": "🌊 🐴 ⚔️ 🇷🇺", "options": ["Tinch Don", "Ona", "Urush va tinchlik", "Zamonamiz qahramoni"], "correct": 0},
    {"emoji": "😈 📜 🧪 🧙", "options": ["Faust", "Ilohiy komediya", "Metamorfoza", "Sefillar"], "correct": 0},
    {"emoji": "🔥 😇 📖 3️⃣", "options": ["Ilohiy komediya", "Faust", "Odissey", "Iliada"], "correct": 0},
    {"emoji": "⛪ 🔔 🦴 💃", "options": ["Notr-Dam ibodatxonasi", "Sefillar", "Graf Monte-Kristo", "Uch mushketyor"], "correct": 0},
    {"emoji": "⛓️ 🍞 😢 🥖", "options": ["Sefillar", "Notr-Dam ibodatxonasi", "Graf Monte-Kristo", "Ona"], "correct": 0},
    {"emoji": "🏹 🐎 ⚔️ 🛡️", "options": ["Alpomish", "Xamsa", "Boburnoma", "Qutadg'u bilig"], "correct": 0},
    {"emoji": "❤️ 🏜️ 😢 🥀", "options": ["Layli va Majnun", "Farhod va Shirin", "Tohir va Zuhra", "Romeo va Julyetta"], "correct": 0},
    {"emoji": "⛏️ ⛰️ ❤️ 🌊", "options": ["Farhod va Shirin", "Layli va Majnun", "Tohir va Zuhra", "Alpomish"], "correct": 0},
    {"emoji": "📖 🍀 👑 ⚖️", "options": ["Qutadg'u bilig", "Devonu lug'otit turk", "Xamsa", "Boburnoma"], "correct": 0},
    {"emoji": "👻 📜 🐎 🛒", "options": ["O'lik jonlar", "Jinoyat va jazo", "Telba", "Ona"], "correct": 0},
    {"emoji": "🗡️ 🧙 👸 🐉", "options": ["Ruslan va Lyudmila", "Kapitan qizi", "Yevgeniy Onegin", "Boris Godunov"], "correct": 0},
    {"emoji": "🤴 😵 💭 🚂", "options": ["Telba (Idiot)", "Jinoyat va jazo", "Aka-uka Karamazovlar", "O'lik jonlar"], "correct": 0},
    {"emoji": "👴 👦 ⚡ 🔬", "options": ["Ota va bolalar", "Ona", "Tinch Don", "Zamonamiz qahramoni"], "correct": 0},
    {"emoji": "🏹 🌳 🤲 👑", "options": ["Robin Gud", "Ayvengo", "Uch mushketyor", "Don Kixot"], "correct": 0},
    {"emoji": "🧚 🏴‍☠️ ⏳ 🐊", "options": ["Piter Pen", "Alisa mo'jizalar mamlakatida", "Oz sehrgari", "Kichkina shahzoda"], "correct": 0},
    {"emoji": "🐇 🕳️ 🍄 🃏", "options": ["Alisa mo'jizalar mamlakatida", "Piter Pen", "Oz sehrgari", "Uxlab qolgan malika"], "correct": 0},
    {"emoji": "🐴 🐕 🐈 🐓", "options": ["Bremen shahar musiqachilari", "Uch cho'chqa", "Qizil shapkacha", "Bo'ri va yetti uloq"], "correct": 0},
    {"emoji": "🐷 🐷 🐷 🏠 🐺", "options": ["Uch cho'chqa", "Bo'ri va yetti uloq", "Qizil shapkacha", "Bremen shahar musiqachilari"], "correct": 0},
    {"emoji": "🪵 👃 🤥 🎪", "options": ["Pinokkio", "Buratino", "Chipollino", "Kichkina shahzoda"], "correct": 0},
    {"emoji": "🧅 🍅 🍋 🏰", "options": ["Chipollino", "Pinokkio", "Tom Soyer", "Buratino"], "correct": 0},
    {"emoji": "👦 🎨 🪚 🚢", "options": ["Tom Soyer sarguzashtlari", "Geklberri Fin", "Shum bola", "Robinzon Kruzo"], "correct": 0},
    {"emoji": "🚣 🌊 👦 🏿", "options": ["Geklberri Fin sarguzashtlari", "Tom Soyer", "Oq So'yloq", "Robinzon"], "correct": 0},
    {"emoji": "🍫 🎫 🏭 🎩", "options": ["Charli va shokolad fabrikasi", "Alisa", "Piter Pen", "Sehrli shahar"], "correct": 0},
    {"emoji": "🦁 🧙 🚪 ❄️", "options": ["Narniya solnomalari", "Garri Potter", "Uzuklar hukmdori", "Oz sehrgari"], "correct": 0},
    {"emoji": "💍 🌋 🧙‍♂️ 🧝", "options": ["Uzuklar hukmdori", "Xobbit", "Garri Potter", "Narniya"], "correct": 0},
    {"emoji": "⚡ 👓 🪄 🦉", "options": ["Garri Potter", "Uzuklar hukmdori", "Xobbit", "Piter Pen"], "correct": 0},
    {"emoji": "🐲 🪙 🗡️ 🏔️", "options": ["Xobbit", "Uzuklar hukmdori", "Garri Potter", "Eragon"], "correct": 0},
    {"emoji": "👧 🌪️ 👠 🦁", "options": ["Oz sehrgari", "Alisa", "Piter Pen", "Qor malikasi"], "correct": 0},
    {"emoji": "❄️ 🪞 🦌 🧊", "options": ["Qor malikasi", "Zolushka", "Qorqiz", "Rapunzel"], "correct": 0},
    {"emoji": "🦆 🦢 💧 😢", "options": ["Xunuk o'rdakcha", "Qizil shapkacha", "Dyuymovochka", "Zolushka"], "correct": 0},
    {"emoji": "🌸 🐸 🪲 👧", "options": ["Dyuymovochka", "Xunuk o'rdakcha", "Zolushka", "Qorqiz"], "correct": 0},
    {"emoji": "👑 🪞 🧝 🍎", "options": ["Oppog'oy va yetti gnom", "Zolushka", "Rapunzel", "Uxlab qolgan malika"], "correct": 0},
    {"emoji": "🧗 💇‍♀️ 🏰 🧙‍♀️", "options": ["Rapunzel", "Zolushka", "Oppog'oy", "Qor malikasi"], "correct": 0},
    {"emoji": "🧜‍♀️ 🌊 🐚 💔", "options": ["Suv parisi (Rusalochka)", "Suv osti dunyosi", "Odisseya", "Sindbad"], "correct": 0},
    {"emoji": "👗 🧵 👑 🙈", "options": ["Qirolning yangi kiyimi", "Zolushka", "Shahzoda va gado", "Etik kiygan mushuk"], "correct": 0},
    {"emoji": "🐱 👢 🏰 🌾", "options": ["Etik kiygan mushuk", "Bremen musiqachilari", "Shum bola", "Tom Soyer"], "correct": 0},
    {"emoji": "👦 👑 🔁 👦 🏚️", "options": ["Shahzoda va gado", "Tom Soyer", "Gulliver", "Graf Monte-Kristo"], "correct": 0},
    {"emoji": "🦚 🪞 🖼️ 👴", "options": ["Dorian Grey portreti", "Faust", "Telba", "Metamorfoza"], "correct": 0},
    {"emoji": "🔥 📚 👨‍🚒 🚒", "options": ["Farengeyt 451", "1984", "Biz", "Ajib yangi dunyo"], "correct": 0},
    {"emoji": "🛸 🌍 👽 🤖", "options": ["Dunyolar jangi", "Mars xronikalari", "Vaqt mashinasi", "Solaris"], "correct": 0},
    {"emoji": "⏳ ⚙️ 🏎️ 🦕", "options": ["Vaqt mashinasi", "Dunyolar jangi", "Ko'rinmas odam", "80 kunda"], "correct": 0},
    {"emoji": "🥼 🧪 🫥 👤", "options": ["Ko'rinmas odam", "Doktor Jekil va mister Xayd", "Frankenshteyn", "Metamorfoza"], "correct": 0},
    {"emoji": "⚡ 🧟 🧪 👨‍⚕️", "options": ["Frankenshteyn", "Doktor Jekil", "Drakula", "Ko'rinmas odam"], "correct": 0},
    {"emoji": "🧛 🦇 🩸 🏰", "options": ["Drakula", "Frankenshteyn", "Gofman ertaklari", "Viy"], "correct": 0},
    {"emoji": "💒 👰 🤵 👰 💔", "options": ["O'tkan kunlar", "Mehrobdan chayon", "Kecha va kunduz", "Sarob"], "correct": 0},
    {"emoji": "🌾 🚜 🇺🇿 😢", "options": ["Otamdan qolgan dalalar", "Ikki eshik orasi", "Ufq", "Lolazor"], "correct": 0},
    {"emoji": "🚪 🚪 ⏳ 📜", "options": ["Ikki eshik orasi", "Dunyoning ishlari", "Diyonat", "Jimjitlik"], "correct": 0},
    {"emoji": "🤱 🏡 🍲 👵", "options": ["Dunyoning ishlari", "Ikki eshik orasi", "Bahor qaytmaydi", "Ona"], "correct": 0},
    {"emoji": "🔫 🕶️ 🚗 💰", "options": ["Shaytanat", "Diyonat", "Odam bo'lish qiyin", "Mungli ko'zlar"], "correct": 0},
    {"emoji": "👰 👵 🗣️ 🎭", "options": ["Kelinlar qo'zg'oloni", "Toshkentnoma", "Maysaraning ishi", "Boy ila xizmatchi"], "correct": 0},
    {"emoji": "🌊 ⛵ ⚓ 📜", "options": ["Sindbad sayohatlari", "Robinzon Kruzo", "Odisseya", "Moby Dik"], "correct": 0},
    {"emoji": "🏔️ 🦅 🐎 🏹", "options": ["Alpomish", "Go'ro'g'li", "Kuntug'mish", "Rustamxon"], "correct": 0},
    {"emoji": "👑 🕌 ⚔️ 🏰", "options": ["Temur tuzuklari", "Boburnoma", "Zafarnoma", "Shajarai turk"], "correct": 0},
    {"emoji": "🔭 📐 🌙 ⭐", "options": ["Ziji Ko'ragoniy", "Ulug'bek xazinasi", "Qadimgi yodgorliklar", "At-Tafhim"], "correct": 0},
]
