# -*- coding: utf-8 -*-
"""Ko'pchilik nima dedi? (Feud) question bank.
150+ open crowd-sourced questions about literature, culture, books, and thoughts.
"""

FEUD_QUESTIONS = [
    "Eng mashhur o'zbek yozuvchisini ayting",
    "Eng sevimli kitobingizni ayting",
    "Maktabda o'qigan eng mashhur asarni ayting",
    "Eng buyuk jahon yozuvchisini ayting",
    "Bir o'zbek xalq dostonini ayting",
    "Alisher Navoiyning bir asarini ayting",
    "Eng mashhur o'zbek shoirini ayting",
    "Bolalikda o'qigan bir ertakni ayting",
    "Bir detektiv asar nomini ayting",
    "Eng mashhur jahon kitobini ayting",
    "Bir o'zbek klassik yozuvchisini ayting",
    "Sevimli adabiy qahramoningizni ayting",
    "Bir tarixiy romanni ayting",
    "Bir mashhur rus yozuvchisini ayting",
    "Bir fantastik asarni ayting",
    "Kitob o'qishning bir foydasini ayting",
    "Bir zamonaviy o'zbek yozuvchisini ayting",
    "Bir she'riy to'plam yoki shoir nomini ayting",
    "Bir kutubxona yoki nashriyot nomini ayting",
    "Bir mashhur muallifning taxallusini ayting",
    "Bir jahon klassik asarini ayting",
    "Bolalar uchun bir kitob nomini ayting",
    "Bir urush haqidagi asarni ayting",
    "Eng ko'p o'qiladigan janr qaysi?",
    "Bir mashhur she'rni ayting",
    "Adabiyot darsida yoqtirgan mavzuni ayting",
    "Bir jahon mumtoz shoirini ayting",
    "Eng mashhur ertak qahramonini ayting",
    "Bir o'zbek dramaturgini ayting",
    "Do'stingizga qaysi kitobni sovg'a qilardingiz?",
    "Bir sarguzasht romanini ayting",
    "Bir bolalar jurnali yoki gazetasini ayting",
    "Eng ta'sirli adabiy qahramonni ayting",
    "Bir ilmiy-fantastik yozuvchini ayting",
    "Sevimli o'zbek shoirasini ayting",
    "Bir tarixiy shaxs haqidagi kitobni ayting",
    "Bir maqol ayting",
    "Bir mashhur kutubxonani ayting",
    "Bir zamonaviy bestsellerni ayting",
    "Maktab dasturidagi bir she'rni ayting",
    "Bir jahon xalq ertagini ayting",
    "Bir avtobiografik asarni ayting",
    "Bir rus klassik asarini ayting",
    "Sevimli detektiv qahramonini ayting",
    "Bir falsafiy kitobni ayting",
    "Bir sayohat haqidagi kitobni ayting",
    "Kitob o'qishning bir odatini ayting",
    "Sevimli bolalik kitobingizni ayting",
    "Film qilingan bir kitobni ayting",
    "Bir o'zbek nasr asarini ayting",
    "Bir dunyo shohasarini ayting",
    "Kitob javonida albatta bo'lishi kerak bo'lgan asar?",
    "Bir mumtoz g'azal muallifini ayting",
    "Eng ko'p qayta o'qiydigan kitobingiz?",
    "Bir nashriyot nomini ayting",
    "Adabiy mukofot nomini ayting",
    "Bir she'riy janrni ayting",
    "Sevimli muallifingiz tug'ilgan shaharni ayting",
    "Bir qahramonlik dostonini ayting",
    "Eng qiziqarli kitob muqovasi rangi?",
    "Bir jahon shoirini ayting",
    "Kutubxonada eng ko'p vaqt o'tkazadigan bo'lim?",
    "Bir tarjimon nomini ayting",
    "Bir hadis to'plami nomini ayting",
    "Bir tasavvuf (sufizm) shayxi ismini ayting",
    "Bir islom huquqshunosligi (fiqh) asari nomini ayting",
    "Bir buyuk islom olimi ismini ayting",
    "Bir hikmatli hadis yoki naql ayting",
    "Bir tariqat nomini ayting",
    "Bir qomusiy Sharq olimi ismini ayting",
    "Bir zamonaviy jahon yozuvchisini ayting",
    "Bir ilmiy-fantastika asari nomini ayting",
    "Bir tarjima qilingan sevimli kitobingizni ayting",
    "Bir doston qahramoni ismini ayting",
    "Kitob sotib olganda e'tibor beradigan narsangizni ayting",
    "Bir yozuvchi taxallusini ayting",
    "Ekranlashtirilgan bir romanni ayting",
    "Bir tarixiy shaxs haqidagi eng yaxshi kitobni ayting",
    "O'zbek jadid adabiyotining bir namoyandasini ayting",
    "Bir psixologik yoki motivatsion kitob nomini ayting",
    "Kitob o'qish uchun eng qulay vaqt qaysi?",
    "Elektron kitobmi yoki qog'oz kitobmi?",
    "Bir fransuz adabiyoti durdonasini ayting",
    "Bir ingliz adabiyoti yozuvchisini ayting",
    "Bir sevgi qissasi yoki dostonini ayting",
    "Tarixiy shaxslardan kim haqida kitob o'qishni yoqtirasiz?",
    "Bir afsonaviy shahar yoki maskan nomini ayting",
    "Qaysi janrdagi kitoblarni yoqtirmaysiz?",
    "Qahramoni ijobiy bo'lmagan bir mashhur kitobni ayting",
    "Bir Nobel mukofoti sovrindori yozuvchini ayting",
    "Insonni yig'latadigan bir asar nomini ayting",
    "Insonni kuldiradigan bir asar nomini ayting",
    "Bolalarga o'qib berish kerak bo'lgan eng yaxshi kitob?",
    "Kutubxonangizdagi eng qadimgi kitob nomi?",
    "Bir mashhur satirik asarni ayting",
    "Bir mashhur komediya asarini ayting",
    "Bir mashhur tragediya asarini ayting",
    "Bir o'zbek xalq maqolini ayting",
    "Taqdir haqidagi bir asarni ayting",
    "Do'stlik haqidagi eng yaxshi asarni ayting",
    "Ona haqidagi bir asar yoki she'rni ayting",
    "Vatan haqidagi bir mashhur she'rni ayting",
    "O'qishni boshlab tugatmagan bir kitobingiz?",
    "Bir kunda o'qib tugatgan kitobingiz?",
    "Eng qalin o'qigan kitobingiz?",
    "Bir mashhur ertakdagi sehrli buyumni ayting",
    "Bir yozuvchi uy-muzeyini ayting",
    "Bir adabiy jurnal nomini ayting",
    "Sevimli kitob belgisi (zakladka) turi?",
    "Eng ta'sirli kitob iqtibosini ayting",
    "Bir falsafiy asar muallifini ayting",
    "Kutubxonachi kasbi haqida bir so'z ayting",
    "Yozuvchilar uchun eng kerakli narsa nima?",
    "Kitob o'qish paytida nima ichishni yoqtirasiz?",
    "Bir sarguzashtli dengiz asarini ayting",
    "Bir kosmos haqidagi fantastika asarini ayting",
    "Bir qadimiy qo'lyozma nomini ayting",
    "Bir mashhur g'azalning ilk misrasini ayting",
    "Sevimli kitob do'koningiz nomini ayting",
    "Bir qisqa hikoya muallifini ayting",
    "Kishiga kuch beradigan bir kitob nomini ayting",
    "Bolalikdagi sevimli multfilm asosi bo'lgan ertakni ayting",
    "Bir sharq allomasi yozgan tibbiy asarni ayting",
    "Bir yulduzlar va astronomiyaga oid kitob nomini ayting",
    "Sevgi va sadoqat ramzi bo'lgan bir adabiy juftlikni ayting",
    "Bir o'zbek xalq qo'shig'i yoki lapari nomini ayting",
    "Jahon adabiyotidagi eng mashhur ayg'oqchi yoki detektiv kim?",
    "O'zingiz qahramoni bo'lishni xohlagan kitob nomi?",
    "O'qishni hammaga tavsiya qiladigan birinchi kitobingiz?",
    "Bir mashhur adabiy qahramonning otini ayting",
    "Kutubxonalarning eng katta dushmani nima?",
    "Bir audio kitob tinglaganmisiz, nomi nima?",
    "Kitob muqovasida eng ko'p uchraydigan tasvir nima?",
    "Bir o'zbek hikoyanavisini ayting",
    "Bir mashhur turk yozuvchisini ayting",
    "Bir arab adabiyoti durdonasini ayting",
    "Bir lotin amerika yozuvchisini ayting",
    "Bir yapon yozuvchisini ayting",
    "Bir nemis adabiyoti namoyandasini ayting",
    "Bir she'r yodlaganmisiz, kimning she'ri?",
    "Kitob o'qish paytida sizni eng ko'p chalg'itadigan narsa nima?",
    "Bir adabiy qahramon qurolini ayting",
    "Bir sehrli afsona nomini ayting",
    "Bir ma'rifatparvar jadid allomasini ayting",
    "Eng sevimli qishki mutolaa kitobingiz?",
    "Eng sevimli yozgi sarguzasht kitobingiz?",
    "O'zbek tiliga tarjima qilingan eng yaxshi asar qaysi?",
    "Kitob sovg'a qilish uchun eng yaxshi bayram qaysi?"
]
