# -*- coding: utf-8 -*-
"""Dorboz / Harf Qidiruv (Hangman) — adabiy so'zlar va atamalarni yashirilgan harflar orqali topish."""

HANGMAN_QUESTIONS = [
    {"word": "XAMSA", "hint": "Alisher Navoiyning 5 ta dostondan iborat durdonasi", "distractors": ["DEVON", "QISSA", "G'AZAL", "MASNAVIY"]},
    {"word": "OTABEK", "hint": "«O'tkan kunlar» romanidagi bosh qahramon", "distractors": ["ANVAR", "HOMID", "HOSHIM", "AKROM"]},
    {"word": "KUMUSH", "hint": "O'zbek ayoli vafo va nafosat timsoli bo'lgan qahramon", "distractors": ["ZAYNAB", "RA'NO", "DILBAR", "LAYLI"]},
    {"word": "FARHOD", "hint": "Tog'ni teshib suv chiqargan buyuk xalq qahramoni", "distractors": ["MAJNUN", "SHIRIN", "SHOPUR", "QAYS"]},
    {"word": "SHIRIN", "hint": "Arman eli go'zali, Farhodning vafodor ma'shuqasi", "distractors": ["LAYLI", "DILOROM", "KUMUSH", "RA'NO"]},
    {"word": "MAJNUN", "hint": "Sahrolarda Layli ishqida sargardon bo'lgan Qays", "distractors": ["FARHOD", "BAHROM", "SHOPUR", "NAVFAL"]},
    {"word": "LAYLI", "hint": "Majnun sevgisiga vafodor arab qizi", "distractors": ["SHIRIN", "KUMUSH", "DILOROM", "ZAYNAB"]},
    {"word": "SIMURG'", "hint": "30 qush o'z aksini topgan afsonaviy shoh qush", "distractors": ["HUMO", "BULBUL", "TOVUS", "QARCHIG'AY"]},
    {"word": "ALPOMISH", "hint": "Qo'ng'irot eli bahodiri, Barchinoyning yori", "distractors": ["GORO'G'LI", "RUSTAM", "KUNTUG'MISH", "AVAZXON"]},
    {"word": "BARCHIN", "hint": "Alpomishning o'n to'rt yoshida shart qo'ygan vafodor yori", "distractors": ["XOLBEKA", "GULNOR", "KUMUSH", "QORAKO'Z"]},
    {"word": "BOBUR", "hint": "«Vaqoyi» (Boburnoma) asari muallifi bo'lgan shoh va shoir", "distractors": ["NAVOIY", "TEMUR", "ULUG'BEK", "LUTFIY"]},
    {"word": "NAVOIY", "hint": "G'azal mulkining sultoni, buyuk o'zbek mutafakkiri", "distractors": ["JOMIY", "BOBUR", "LUTFIY", "ATOIY"]},
    {"word": "QODIRIY", "hint": "O'zbek romanchiligining asoschisi", "distractors": ["CHO'LPON", "FITRAT", "OYBEK", "QAHHOR"]},
    {"word": "CHO'LPON", "hint": "«Kecha va kunduz» romani muallifi bo'lgan shoir", "distractors": ["FITRAT", "AVLONIY", "USMON", "BOTU"]},
    {"word": "FITRAT", "hint": "«Munozara» va «Qiyomat» asarlarining jadid adibi", "distractors": ["BEHBUDIY", "QODIRIY", "AVLONIY", "HAMZA"]},
    {"word": "BEHBUDIY", "hint": "«Padarkush» dramasining muallifi bo'lgan alloma", "distractors": ["AVLONIY", "FITRAT", "CHO'LPON", "QODIRIY"]},
    {"word": "AVLONIY", "hint": "«Turkiy Guliston yoxud axloq» kitobi muallifi", "distractors": ["BEHBUDIY", "HAMZA", "OYBEK", "QAHHOR"]},
    {"word": "OYBEK", "hint": "«Navoiy» va «Qutlug' qon» romanlarining lirik adibi", "distractors": ["G'ULOM", "QAHHOR", "HOSHIMOV", "SAID AHMAD"]},
    {"word": "QAHHOR", "hint": "O'zbek hikoyachiligi ustasi, «Sinchalak» qissasi muallifi", "distractors": ["OYBEK", "G'ULOM", "HOSHIMOV", "MALIK"]},
    {"word": "G'ULOM", "hint": "«Shum bola» va «Sen yetim emassan» asarlari muallifi", "distractors": ["OYBEK", "QAHHOR", "ZULFIYA", "HAMID OLIMJON"]},
    {"word": "HOSHIMOV", "hint": "«Dunyoning ishlari» va «Ikki eshik orasi» muallifi", "distractors": ["QAHHOR", "MALIK", "MUROD", "SAID AHMAD"]},
    {"word": "VOHIDOV", "hint": "«O'zbegim» qasidasi va «Ruhlar isyoni» dostoni muallifi", "distractors": ["ORIPOV", "YUSUF", "MATJON", "DAVRON"]},
    {"word": "ORIPOV", "hint": "O'zbekiston madhiyasi matni va «Jannatga yo'l» muallifi", "distractors": ["VOHIDOV", "YUSUF", "XUDOYBERDIYEVA", "CHO'LPON"]},
    {"word": "YUSUF", "hint": "«Biz baxtli bo'lamiz», «Lolaqizg'aldoq» shoiri", "distractors": ["ORIPOV", "VOHIDOV", "MATJON", "DAVRON"]},
    {"word": "MALIK", "hint": "«Shaytanat» va «Odamiylik mulki» asarlari muallifi", "distractors": ["HOSHIMOV", "MUROD", "QAHHOR", "SAID AHMAD"]},
    {"word": "TOG'AY", "hint": "«Otamdan qolgan dalalar» muallifining ismi (Tog'ay Murod)", "distractors": ["SHUKUR", "ERKIN", "MUROD", "ASQAD"]},
    {"word": "ULUG'BEK", "hint": "Samarqandda rasadxona qurdirgan olim hukmdor", "distractors": ["BERUNIY", "XORAZMIY", "FARG'ONIY", "QOZIZODA"]},
    {"word": "BERUNIY", "hint": "«Hindiston» va «Qadimgi xalqlar» asarlari muallifi", "distractors": ["IBN SINO", "FOROBIY", "XORAZMIY", "KOSHIFIY"]},
    {"word": "IBN SINO", "hint": "«Tib qonunlari» muallifi, buyuk alloma tabib", "distractors": ["ROZIY", "BERUNIY", "FARG'ONIY", "TUHSIY"]},
    {"word": "FOROBIY", "hint": "Sharq falsafasida «Muallimi Soniy» deb atalgan daho", "distractors": ["ARASTU", "AFLOTUN", "SOKRAT", "G'AZZOLIY"]},
    {"word": "G'AZZOLIY", "hint": "«Ihyou ulumiddin» va «Mukoshafat ul-qulub» muallifi", "distractors": ["MOTURIDIY", "NASAFIY", "ZAMAXSHARIY", "SAM'ONIY"]},
    {"word": "BUXORIY", "hint": "Eng buyuk muhaddis, «Sahihul Buxoriy» to'plovchisi", "distractors": ["TERMIZIY", "MUSLIM", "NASOIY", "IBN MOJA"]},
    {"word": "TERMIZIY", "hint": "Termizda yashagan mashhur olti hadis to'plamidan birining egasi", "distractors": ["BUXORIY", "DORIMIY", "BAYHAQIY", "TOHIRIY"]},
    {"word": "YASSAVIY", "hint": "«Devoni hikmat» sohibi bo'lgan Turkiston piri", "distractors": ["NAQSHBAND", "G'IJDUVONIY", "KUBRO", "ZANGIOTA"]},
    {"word": "NAQSHBAND", "hint": "Naqshbandiya tariqati asoschisi, Buxoro allomasi", "distractors": ["YASSAVIY", "KUBRO", "SHOSHIY", "SAMARQANDIY"]},
    {"word": "TEMUR", "hint": "Buyuk sarkarda, poytaxti Samarqand bo'lgan sohibqiron", "distractors": ["ULUG'BEK", "BOBUR", "SHOHRUH", "XUDOYOR"]},
    {"word": "MANGUBERDI", "hint": "Jaloliddin — mo'g'ul bosqinchilariga qarshi buyuk qahramon", "distractors": ["TEMUR MALIK", "MUQANNA", "SHIROQ", "SPITAMEN"]},
    {"word": "TO'MARIS", "hint": "Massagetlar jasur malikasi, Eron shohi Kirni yenggan", "distractors": ["ZARINA", "ROXANA", "BARDOH", "PO'LATXON"]},
    {"word": "SHIROQ", "hint": "Doro qo'shinini dashtda adashtirib qirgan fidoyi cho'pon", "distractors": ["TO'MARIS", "SPITAMEN", "MUQANNA", "ALPOMISH"]},
    {"word": "SPITAMEN", "hint": "Makedonskiy qo'shiniga qarshi mardona kurashgan sarkarda", "distractors": ["SHIROQ", "MUQANNA", "MANGUBERDI", "TEMUR MALIK"]},
    {"word": "RUMIY", "hint": "«Masnaviy» muallifi, buyuk mutasavvif shoir (Mavlono)", "distractors": ["HOFIZ", "SA'DIY", "ATTOR", "JOMIY"]},
    {"word": "SA'DIY", "hint": "«Guliston» va «Bo'ston» asarlari muallifi", "distractors": ["RUMIY", "HOFIZ", "JOMIY", "NIZOMIY"]},
    {"word": "HOFIZ", "hint": "Sheroziy — Sharq g'azalchiligining bulbul shoiri", "distractors": ["SA'DIY", "RUMIY", "JOMIY", "ATTOR"]},
    {"word": "JOMIY", "hint": "Abdurahmon — Navoiyning ustozi va do'sti bo'lgan buyuk alloma", "distractors": ["NAVOIY", "BOBUR", "LUTFIY", "RUMIY"]},
    {"word": "SHEKSPIR", "hint": "«Gamlet», «Otello», «Qirol Lir» fojialari muallifi", "distractors": ["GYOTE", "DANTE", "BAYRON", "MOLER"]},
    {"word": "SERVANTES", "hint": "«Don Kixot» romani muallifi bo'lgan ispan adibi", "distractors": ["LORKA", "MARKES", "BORXES", "LOPE DE VEGA"]},
    {"word": "GYOTE", "hint": "«Faust» tragediyasi muallifi bo'lgan nemis adibi", "distractors": ["SHILLER", "GEYNE", "KANT", "GEGEL"]},
    {"word": "TOLSTOY", "hint": "«Urush va tinchlik», «Anna Karenina» asarlari muallifi", "distractors": ["DOSTOYEVSKIY", "CHEXOV", "TURGENEV", "PUSHKIN"]},
    {"word": "DOSTOYEVSKIY", "hint": "«Jinoyat va jazo», «Idiot» romanlari muallifi", "distractors": ["TOLSTOY", "GOGOL", "TURGENEV", "GORKIY"]},
    {"word": "CHEXOV", "hint": "Qisqa psixologik hikoyalar ustasi bo'lgan rus adibi", "distractors": ["GOGOL", "DOSTOYEVSKIY", "TOLSTOY", "BUNIN"]},
    {"word": "PUSHKIN", "hint": "«Yevgeniy Onegin» she'riy romani muallifi", "distractors": ["LERMONTOV", "NEKRASOV", "YESENIN", "BLOK"]},
    {"word": "XEMINGUEY", "hint": "«Chol va dengiz» qissasi uchun Nobel olgan amerikalik adib", "distractors": ["FOLKNER", "FITSJERALD", "STEYNBEK", "LONDON"]},
    {"word": "AYTMATOV", "hint": "«Asrga tatigulik kun», «Oq kema» asarlari muallifi", "distractors": ["RASUL GAMZATOV", "MUSTAY KARIM", "OLJAS SULAYMONOV", "ABAY"]},
    {"word": "MARKES", "hint": "«Yuz yillik yolg'izlik» romani muallifi bo'lgan kolumbiyalik adib", "distractors": ["KORTASAR", "BORXES", "KOELO", "RULFO"]},
    {"word": "ORUELL", "hint": "«1984» va «Molxona» antiutopik asarlari muallifi", "distractors": ["XAKSLI", "BRED BERI", "KAFKA", "KAMYU"]},
    {"word": "KAFKA", "hint": "«Evrilish» va «Jarayon» asarlari muallifi", "distractors": ["KAMYU", "SARTRE", "JONS", "MANNN"]},
    {"word": "KAMYU", "hint": "«Begona» va «Vabo» asarlari muallifi bo'lgan faylasuf", "distractors": ["SARTRE", "KAFKA", "FUKO", "DERRIDA"]},
    {"word": "EKZYUPERI", "hint": "«Kichkina Shahzoda» ertak-qissasi muallifi bo'lgan uchuvchi", "distractors": ["GYUGO", "MOPASSAN", "BALZAK", "FLOBER"]},
    {"word": "GYUGO", "hint": "«Xo'rlanganlar» va «Parij Bibi Maryam ibodatxonasi» muallifi", "distractors": ["DYUMA", "BALZAK", "STENDAL", "ZOLYA"]},
    {"word": "KONAN DOYL", "hint": "Sherlok Xolms va Doktor Vatson personajlari ijodkori", "distractors": ["AGATA KRISTI", "EDGAR PO", "STIVENSON", "CHEZTERTON"]}
]
