# -*- coding: utf-8 -*-
"""Paradokslar Olami: chegarasiz mantiq va falsafiy jumboqlar.

Har savolda 4 ta variant ham TAXMINAN BIR XIL UZUNLIKDA va hammasi
ishonarli falsafiy da'vo -- shuning uchun "eng uzun javobni tanla"
strategiyasi ishlamaydi. Variantlar o'yin vaqtida aralashtiriladi
(quiz_game._prep_question), shuning uchun "correct" indeksining
o'zi hech narsani oshkor qilmaydi.
"""

QUIZ_PARADOX_QUESTIONS = [
    {"q": "«Tezey kemasi» paradoksi qaysi savolni o'rtaga qo'yadi?",
     "options": ["Qismlari butunlay almashgan narsa o'shaligicha qoladimi?",
                 "Butun o'z qismlari yig'indisidan ko'proq narsami?",
                 "Ikki bir xil narsa bir vaqtda bir joyda bo'ladimi?",
                 "Narsaning nomi uning mohiyatini belgilay oladimi?"], "correct": 0},

    {"q": "«Fermi paradoksi» nimaga qaratilgan?",
     "options": ["Koinot ulkan-u, nega o'zga tsivilizatsiyadan darak yo'q?",
                 "Koinot chegarasiz bo'lsa, uning markazi qayerda?",
                 "Yulduz cheksiz bo'lsa, nega osmon qorong'i turadi?",
                 "Hayot paydo bo'lishi uchun qancha vaqt zarur bo'ladi?"], "correct": 0},

    {"q": "«Bobo paradoksi» vaqt sayohatida qanday ziddiyatni ko'rsatadi?",
     "options": ["O'tmishni o'zgartirsang, o'zing mavjud bo'lmay qolasan",
                 "Kelajakni bilsang, uni o'zgartirishga majbur bo'lasan",
                 "Vaqt orqaga oqsa, xotira ham teskari ishlay boshlaydi",
                 "Ikki xil vaqtda bir odam ikki marta yashay oladi"], "correct": 0},

    {"q": "«Yolg'onchi paradoksi» nega yechimsiz qoladi?",
     "options": ["Gap rost bo'lsa yolg'on, yolg'on bo'lsa rost chiqadi",
                 "Gap ma'nosi so'zlovchi niyatiga bog'liq bo'lib qoladi",
                 "Har qanday gap o'zi haqida hukm chiqara olmaydi",
                 "Rost va yolg'on tushunchalari nisbiy hisoblanadi"], "correct": 0},

    {"q": "«Buridan eshagi» qanday holatni tasvirlaydi?",
     "options": ["Ikki teng tanlov orasida qaror qilolmay zarar ko'rish",
                 "Ko'p tanlov ichidan eng yomonini tanlab qo'yish",
                 "Boshqalar tanlaganini o'ylamay takrorlab yurish",
                 "Tanlovdan qochib, mas'uliyatni boshqaga yuklash"], "correct": 0},

    {"q": "«Sorites» (uyum) paradoksi qaysi muammoni ochadi?",
     "options": ["Aniq chegarasi yo'q tushuncha qachon o'zgarib ketadi?",
                 "Sanoqli narsalar cheksizlikka qanday aylanadi?",
                 "Kichik sabab katta oqibatga qanday olib keladi?",
                 "Qism butunning xossalarini o'zida saqlaydimi?"], "correct": 0},

    {"q": "«Shryodinger mushugi» tajribasi nimani ko'rsatadi?",
     "options": ["Kuzatilmagan zarracha bir vaqtda ikki holatda bo'ladi",
                 "Kuzatuvchi tajriba natijasini oldindan bilib turadi",
                 "Zarrachaning o'rni va tezligi bir xil aniqlanadi",
                 "Yopiq tizimda energiya asta-sekin yo'qolib boradi"], "correct": 0},

    {"q": "«Isterlin paradoksi» boylik haqida nimani aytadi?",
     "options": ["Ma'lum darajadan keyin daromad baxtni oshirmay qo'yadi",
                 "Boylik ko'paygani sari ehtiyojlar ham teng kamayadi",
                 "Kambag'al jamiyatda odamlar doim baxtsiz bo'ladi",
                 "Baxt faqat boshqalar bilan solishtirishdan tug'iladi"], "correct": 0},

    {"q": "«Tanlov paradoksi» qanday natijani bashorat qiladi?",
     "options": ["Variant ko'paygani sari qaror qilish qiyinlashadi",
                 "Variant ko'paygani sari odam tezroq qaror qiladi",
                 "Kam variant har doim noto'g'ri tanlovga olib keladi",
                 "Tanlov erkinligi qoniqishni doim oshirib boradi"], "correct": 0},

    {"q": "«Kuzatuvchi effekti» falsafiy jihatdan nimani anglatadi?",
     "options": ["Kuzatishning o'zi kuzatilayotgan narsani o'zgartiradi",
                 "Kuzatuvchi haqiqatni butunlay xolis ko'ra oladi",
                 "Har qanday o'lchov asbobdan mustaqil bo'lib qoladi",
                 "Voqea kuzatuvchisiz umuman sodir bo'lmaydi"], "correct": 0},

    {"q": "Zenonning «Axilles va toshbaqa» aporiyasi nimani da'vo qiladi?",
     "options": ["Tez yuruvchi sekin ketayotganga hech yetib olmaydi",
                 "Harakat faqat to'xtagan nuqtadan boshlanishi mumkin",
                 "Masofa bo'linmas eng kichik qismlardan tashkil topadi",
                 "Tezlik vaqtga emas, faqat masofaga bog'liq bo'ladi"], "correct": 0},

    {"q": "«Uchayotgan o'q» aporiyasi qanday xulosaga keladi?",
     "options": ["Har lahzada o'q qimirlamaydi, demak harakat illyuziya",
                 "O'q havo qarshiligi tufayli aslida tezlashib boradi",
                 "Harakat faqat kuzatuvchiga nisbatan mavjud bo'ladi",
                 "Vaqt bo'linmas lahzalardan iborat emasligi ma'lum"], "correct": 0},

    {"q": "«Ikkilik» (dixotomiya) aporiyasi nimani ta'kidlaydi?",
     "options": ["Yo'l yarmini bosish uchun avval choragi kerak bo'ladi",
                 "Har qanday yo'l oxir-oqibat aylanma bo'lib chiqadi",
                 "Ikki nuqta orasida faqat bitta to'g'ri yo'l bor",
                 "Harakatni boshlash uchun tashqi turtki shart emas"], "correct": 0},

    {"q": "«Rassel paradoksi» to'plamlar nazariyasida nimani ochdi?",
     "options": ["O'zini o'z ichiga olmagan to'plam ziddiyat tug'diradi",
                 "Har qanday to'plam sanoqli elementlardan tuziladi",
                 "Cheksiz to'plamlar bir-biriga doim teng bo'lib chiqadi",
                 "Bo'sh to'plam mantiqan mavjud bo'lolmasligi aniqlandi"], "correct": 0},

    {"q": "«Sartarosh paradoksi» qanday vaziyatni tasvirlaydi?",
     "options": ["O'zini qirmaganni qiradigan sartarosh o'zini qiradimi?",
                 "Sartarosh mijozlarini tanlashda erkin bo'ladimi?",
                 "Kasb egasi o'z xizmatidan foydalana oladimi?",
                 "Qoidani yaratgan odam unga bo'ysunishi shartmi?"], "correct": 0},

    {"q": "«Kuchsiz Quyosh paradoksi» qaysi ziddiyatni bildiradi?",
     "options": ["Quyosh sustroq yongan davrda Yerda suyuq suv bo'lgan",
                 "Quyosh energiyasi Yerga notekis taqsimlanib kelgan",
                 "Yer o'qi og'ishi iqlimni butunlay belgilab bergan",
                 "Qadimda atmosfera bugungidan ancha yupqa bo'lgan"], "correct": 0},

    {"q": "«Olbers paradoksi» qanday savol qo'yadi?",
     "options": ["Yulduz cheksiz bo'lsa, tunda osmon nega qorong'i?",
                 "Yulduzlar nega bir tekis taqsimlanmagan ko'rinadi?",
                 "Yorug'lik nega har doim to'g'ri chiziq bo'ylab yuradi?",
                 "Koinot kengaysa, yulduzlar nega sovib bormaydi?"], "correct": 0},

    {"q": "«Xotira paradoksi» shaxs ayniyati haqida nimani so'raydi?",
     "options": ["Xotirasini butkul yo'qotgan odam o'sha odam bo'lib qoladimi?",
                 "Xotira miyaning qaysi qismida saqlanishi mumkin?",
                 "Yolg'on xotira haqiqiysidan qanday farq qiladi?",
                 "Bolalik xotiralari nega tez unutilib ketadi?"], "correct": 0},

    {"q": "«Kutilmagan imtihon» paradoksi nimadan iborat?",
     "options": ["Kutilmagan deb e'lon qilingan imtihon imkonsiz bo'lib qoladi",
                 "Imtihonga tayyorgarlik natijani doim yaxshilab yuboradi",
                 "Talaba imtihon savolini oldindan taxmin qila oladi",
                 "Har qanday sinov bilimni to'liq o'lchay olmaydi"], "correct": 0},

    {"q": "«Ikki konvert» muammosi qanday xatoga olib keladi?",
     "options": ["Har qaysi konvertni almashtirish foydali ko'rinaveradi",
                 "Konvertdagi pul miqdori doim teng bo'lib chiqadi",
                 "Tanlovdan keyin pul miqdori o'zgarib ketadi",
                 "Ehtimollik hisoblari bu yerda umuman qo'llanmaydi"], "correct": 0},

    {"q": "«Monti Xoll» muammosida to'g'ri strategiya qaysi?",
     "options": ["Tanlovni o'zgartirish yutish ehtimolini oshiradi",
                 "Tanlovni saqlab qolish har doim foydaliroq bo'ladi",
                 "Ikkala variant ham aynan teng ehtimolga ega bo'ladi",
                 "Boshlovchining harakati natijaga ta'sir qilmaydi"], "correct": 0},

    {"q": "«Simpson paradoksi» statistikada nimani ko'rsatadi?",
     "options": ["Guruhlar birlashtirilsa, tendensiya teskari bo'lib chiqadi",
                 "Katta namuna doim aniqroq natija berishi kafolatlanadi",
                 "O'rtacha qiymat medianaga har doim teng kelib qoladi",
                 "Ikki o'zgaruvchi bog'liqligi sababni isbotlab beradi"], "correct": 0},

    {"q": "«Tramvay muammosi» qaysi axloqiy ziddiyatni sinaydi?",
     "options": ["Ko'pchilikni qutqarish uchun birini qurbon qilsa bo'ladimi?",
                 "Begonaga yordam berish burch hisoblanadimi?",
                 "Niyat yaxshi bo'lsa, oqibat ahamiyatsiz bo'ladimi?",
                 "Qonun va vijdon to'qnashsa, qaysi biri ustun turadi?"], "correct": 0},

    {"q": "«Menon paradoksi» bilim haqida nimani so'raydi?",
     "options": ["Bilmagan narsangni qanday qilib izlay olasan?",
                 "Bilim tajribadan oldin tug'ma bo'lishi mumkinmi?",
                 "Haqiqatni bilish uchun ustoz shartmi yoki yo'q?",
                 "Bilim va e'tiqod orasidagi chegara qayerda yotadi?"], "correct": 0},

    {"q": "«Sog'lomlik paradoksi» tibbiyotda nimani anglatadi?",
     "options": ["Tekshiruv ko'paysa, kasallar soni ham ortib ko'rinadi",
                 "Sog'lom turmush tarzi umrni doim uzaytirib boradi",
                 "Dori qancha kuchli bo'lsa, shifo shuncha tez keladi",
                 "Kasallik belgisi bo'lmasa, xavf ham mavjud emas"], "correct": 0},

    {"q": "«Parkinson qonuni» mehnat haqida nimani aytadi?",
     "options": ["Ish ajratilgan vaqtni to'ldirib cho'zilib ketaveradi",
                 "Bo'sh vaqt ijodkorlikni har doim susaytirib qo'yadi",
                 "Ko'p ishlagan odam ko'proq natijaga erishadi",
                 "Dam olish mehnat unumini pasaytirib yuboradi"], "correct": 0},

    {"q": "«Nazorat illyuziyasi» qanday xatoni bildiradi?",
     "options": ["Tasodifiy hodisaga ta'sir o'tkaza olaman deb o'ylash",
                 "O'z qobiliyatini boshqalardan past baholab yurish",
                 "Kelajakni o'tmishga qarab aniq bashorat qilish",
                 "Xatoni tan olmay, sababni tashqaridan izlash"], "correct": 0},

    {"q": "«Omon qolganlar xatosi» nimadan iborat?",
     "options": ["Faqat muvaffaq bo'lganlarga qarab xulosa chiqarish",
                 "Muvaffaqiyatsizlikni omadsizlik deb izohlash",
                 "Ko'pchilik fikrini haqiqat deb qabul qilish",
                 "O'z tajribasini hammaga umumlashtirib yuborish"], "correct": 0},

    {"q": "«Danning-Kruger effekti» nimani tasvirlaydi?",
     "options": ["Bilimi kam odam o'zini haddan tashqari yuqori baholaydi",
                 "Bilimli odam o'z fikrini boshqalarga o'tkaza oladi",
                 "Tajriba ortgani sari ishonch tekis o'sib boraveradi",
                 "Maqtov insonning haqiqiy qobiliyatini oshirib yuboradi"], "correct": 0},

    {"q": "«Tasdiq izlash xatosi» qanday namoyon bo'ladi?",
     "options": ["O'z fikrini quvvatlaydigan dalilnigina izlab yurish",
                 "Har qanday yangi dalilni shubha bilan rad etish",
                 "Boshqalar fikriga qarshi doim isyon ko'tarish",
                 "Xulosani dalil to'planmasdan oldin kechiktirish"], "correct": 0},

    {"q": "«Zerikish paradoksi» zamonaviy hayotda nimani ko'rsatadi?",
     "options": ["Ko'ngilochar vosita ko'paysa, zerikish ham ortib boradi",
                 "Bo'sh vaqt ko'p bo'lsa, odam doim baxtli bo'lib qoladi",
                 "Zerikish ijodkorlikni butunlay so'ndirib yuboradi",
                 "Mashg'ul odam hech qachon zerikishni his qilmaydi"], "correct": 0},

    {"q": "«Bag'rikenglik paradoksi» nimadan ogohlantiradi?",
     "options": ["Cheksiz bag'rikenglik bag'rikenglikni yo'q qilib qo'yadi",
                 "Bag'rikenglik jamiyatni doim mustahkamlab boradi",
                 "Har qanday fikrni taqiqlash tinchlikni saqlab qoladi",
                 "Kelishmovchilik jamiyat uchun har doim zararli bo'ladi"], "correct": 0},

    {"q": "«Qadriyat paradoksi» (olmos va suv) nimani tushuntiradi?",
     "options": ["Hayotiy zarur narsa arzon, keraksizi qimmat bo'lishi mumkin",
                 "Narxni faqat ishlab chiqarish xarajati belgilab beradi",
                 "Noyob narsa har doim foydaliroq bo'lib chiqadi",
                 "Talab va taklif qadriyatga umuman ta'sir qilmaydi"], "correct": 0},

    {"q": "«Jevons paradoksi» resurs sarfida nimani bildiradi?",
     "options": ["Samaradorlik oshsa, resurs sarfi kamaymay ko'payib ketadi",
                 "Tejamkor texnologiya sarfni doim keskin kamaytiradi",
                 "Resurs qimmatlashsa, iste'mol o'zgarmay qolaveradi",
                 "Yangi texnologiya narxni har doim oshirib yuboradi"], "correct": 0},

    {"q": "«Tejash paradoksi» iqtisodda nimani ta'kidlaydi?",
     "options": ["Hamma birdek tejasa, umumiy daromad pasayib ketadi",
                 "Tejamkorlik har doim jamiyatni boyitib boradi",
                 "Sarf-xarajat ko'paysa, inqiroz albatta boshlanadi",
                 "Jamg'arma miqdori inflyatsiyaga bog'liq bo'lmaydi"], "correct": 0},

    {"q": "«Avtomatlashtirish paradoksi» nimani anglatadi?",
     "options": ["Tizim avtomatlashgani sari inson mahorati ko'proq kerak bo'ladi",
                 "Avtomatlashtirish inson xatosini butkul yo'qotib yuboradi",
                 "Mashina nazorati inson ishtirokini keraksiz qilib qo'yadi",
                 "Murakkab tizim doim soddasidan ishonchli bo'lib chiqadi"], "correct": 0},

    {"q": "«Xitoy xonasi» tajribasi nimani shubha ostiga oladi?",
     "options": ["Qoidaga ko'ra javob berish tushunish demakmi?",
                 "Mashina insondan tezroq hisoblay oladimi?",
                 "Til o'rganish uchun muhit shartmi yoki yo'q?",
                 "Ong miyadan tashqarida mavjud bo'la oladimi?"], "correct": 0},

    {"q": "«Zombi argumenti» ong falsafasida nimani so'raydi?",
     "options": ["Tashqi jihatdan bir xil, ammo ongsiz mavjudot bo'ladimi?",
                 "Ong miya faoliyatidan butunlay kelib chiqadimi?",
                 "Hayvonlarda inson kabi ong shakllanadimi?",
                 "Tush ko'rish ongning bir ko'rinishi hisoblanadimi?"], "correct": 0},

    {"q": "«Meri xonasi» tajribasi qanday xulosaga undaydi?",
     "options": ["Barcha ilmiy bilim tajribadagi his-tuyg'uni bermaydi",
                 "Rang ko'rish faqat o'rganish orqali shakllanadi",
                 "Ilmiy bilim tajribadan doim ustun turib qoladi",
                 "Idrok butunlay tildan kelib chiqib shakllanadi"], "correct": 0},

    {"q": "«Teleportatsiya paradoksi» qaysi savolni tug'diradi?",
     "options": ["Nusxang yaratilsa, «sen» qaysi biri bo'lib qolasan?",
                 "Moddani uzoqqa uzatish jismonan mumkinmi?",
                 "Yorug'lik tezligidan tez harakat bo'ladimi?",
                 "Xotira boshqa tanaga ko'chirilishi mumkinmi?"], "correct": 0},

    {"q": "«Bo'lingan miya» tajribasi nimani sinaydi?",
     "options": ["Miya ikkiga bo'linsa, shaxs ham ikkiga bo'linadimi?",
                 "Miyaning qaysi yarmi mantiqqa javob beradi?",
                 "Xotira miyaning bir qismida saqlanadimi?",
                 "Ong uyquda butunlay to'xtab qoladimi?"], "correct": 0},

    {"q": "«Nyukom muammosi» qanday ziddiyatni ochadi?",
     "options": ["Bashorat aniq bo'lsa, erkin tanlov ma'noga egami?",
                 "Ikki quti orasida tanlov doim tengmi?",
                 "Ko'proq pul olish har doim oqilonami?",
                 "Bashoratchi xato qilsa, javobgar kim bo'ladi?"], "correct": 0},

    {"q": "«Mahbus dilemmasi» nimani ko'rsatadi?",
     "options": ["Har kim o'ziga foydalisini tanlasa, ikkalasi yutqazadi",
                 "Hamkorlik har doim eng katta foyda keltirib beradi",
                 "Sotqinlik uzoq muddatda doim afzal bo'lib chiqadi",
                 "Ishonch faqat kuchli tomonga foyda berib qoladi"], "correct": 0},

    {"q": "«Umumiy yaylov fojiasi» qaysi muammoni bildiradi?",
     "options": ["Umumiy resursdan har kim ko'p olsa, resurs tugab qoladi",
                 "Xususiy mulk har doim jamoat mulkidan samarali bo'ladi",
                 "Resurs cheksiz bo'lsa, nizolar ham yo'qolib ketadi",
                 "Jamoa qarori yakka qarordan doim to'g'ri chiqadi"], "correct": 0},

    {"q": "«Sizif mehnati» falsafiy ma'noda nimani anglatadi?",
     "options": ["Natijasiz takrorlanaveradigan mehnat ma'nosi masalasi",
                 "Og'ir mehnat insonni albatta poklab boradi",
                 "Jazo har doim gunohga mos ravishda beriladi",
                 "Mehnatsiz erishilgan natija qadrsiz bo'lib qoladi"], "correct": 0},

    {"q": "Kamyu «Sizif haqida afsona»da qanday xulosaga keladi?",
     "options": ["Ma'nosizlikni tan olib, shunda ham baxtli bo'lish mumkin",
                 "Hayot ma'nosi faqat diniy e'tiqodda topilib qoladi",
                 "Azob chekkan odam oxir-oqibat mukofot olib boradi",
                 "Ma'nosiz mehnatdan voz kechish yagona to'g'ri yo'l"], "correct": 0},

    {"q": "«Absurd» tushunchasi ekzistensializmda nimani bildiradi?",
     "options": ["Inson ma'no izlaydi, olam esa sukut saqlab turadi",
                 "Hayot voqealari mantiqiy izchillikda kechib boradi",
                 "Har bir azobning aniq sababi albatta bo'lib chiqadi",
                 "Ma'no faqat jamiyat tomonidan berilishi mumkin"], "correct": 0},

    {"q": "«Erkinlik yuki» (Sartr) nimani anglatadi?",
     "options": ["Inson erkin bo'lgani uchun tanlovi uchun to'la javobgar",
                 "Erkinlik insonni mas'uliyatdan xalos qilib qo'yadi",
                 "Tanlov imkoni ko'p bo'lsa, yuk ham yengillashadi",
                 "Erkinlik faqat qonun doirasida mavjud bo'lib qoladi"], "correct": 0},

    {"q": "«Yovuzlik muammosi» qanday savolni ko'taradi?",
     "options": ["Qudratli va rahmli Yaratuvchi bo'lsa, azob nega bor?",
                 "Yovuzlik insonning o'zidan kelib chiqadimi?",
                 "Adolat bu dunyoda qaror topishi mumkinmi?",
                 "Yaxshilik va yomonlik nisbiy tushunchami?"], "correct": 0},

    {"q": "«Paskal garovi» qanday mulohazani taklif qiladi?",
     "options": ["E'tiqodning kutilgan foydasi uni tanlashga undab turadi",
                 "Iymon faqat aqliy dalil bilan tasdiqlanishi mumkin",
                 "Shubha e'tiqoddan har doim ustun turib qoladi",
                 "Diniy tajriba hech qanday isbot talab qilmaydi"], "correct": 0},

    {"q": "«Cheksiz mehmonxona» (Hilbert) nimani ko'rsatadi?",
     "options": ["To'la cheksiz mehmonxona yana mehmon qabul qila oladi",
                 "Cheksiz xonalar amalda hech qachon to'lmay qoladi",
                 "Cheksizlik oddiy sonlar kabi qo'shilaveradi",
                 "Har qanday cheksiz to'plam sanoqli bo'lib chiqadi"], "correct": 0},

    {"q": "«Gedel to'liqsizlik teoremasi» nimani isbotladi?",
     "options": ["Har bir izchil tizimda isbotlab bo'lmas haqiqat qoladi",
                 "Matematikaning barcha haqiqatlari isbotlanishi mumkin",
                 "Har qanday tizim o'zini o'zi to'la tekshira oladi",
                 "Mantiq qoidalari tajriba orqali o'zgarib turadi"], "correct": 0},

    {"q": "Borxesning «Bobil kutubxonasi» qanday g'oyani ifodalaydi?",
     "options": ["Barcha kitob mavjud bo'lsa, ma'noni topish imkonsiz bo'ladi",
                 "Kitob ko'p bo'lgan joyda bilim ham ko'p bo'lib qoladi",
                 "Har bir kitobning yagona to'g'ri talqini mavjud bo'ladi",
                 "Yozuv insoniyat xotirasining o'rnini bosa oladi"], "correct": 0},

    {"q": "«Kelajak avlod paradoksi» axloqda nimani so'raydi?",
     "options": ["Hali tug'ilmaganlar oldida burchimiz bormi?",
                 "O'tmish avlod oldida qarzdormizmi yoki yo'q?",
                 "Bugungi manfaat ertangisidan ustun turadimi?",
                 "Tabiat faqat inson uchun yaratilganmi?"], "correct": 0},

    {"q": "«Uyquchi go'zal» muammosi nimani sinaydi?",
     "options": ["Yangi ma'lumotsiz ehtimol qanday yangilanadi?",
                 "Uyqu xotirani qanchalik o'chirib yuboradi?",
                 "Tanga tashlash natijasi oldindan bilinadimi?",
                 "Vaqt oqimi tushda qanday idrok qilinadi?"], "correct": 0},

    {"q": "«Ikki xil men» muammosi shaxs haqida nimani so'raydi?",
     "options": ["Bugungi «men» o'n yil oldingi «men» bilan aynanmi?",
                 "Inson xarakteri butun umr o'zgarmay qoladimi?",
                 "Ism insonning mohiyatini belgilab bera oladimi?",
                 "Tana o'zgarsa, ism ham o'zgarishi kerakmi?"], "correct": 0},

    {"q": "«Bo'sh vaqt paradoksi» zamonaviy inson haqida nimani aytadi?",
     "options": ["Vaqt tejovchi vosita ko'paydi, shoshqinlik ham ortdi",
                 "Texnologiya insonga ko'proq dam berib qo'ydi",
                 "Ish vaqti qisqargani sari stress ham kamaydi",
                 "Bo'sh vaqt boylik bilan to'g'ri proporsional o'sadi"], "correct": 0},

    {"q": "«Kutish paradoksi» psixologiyada nimani bildiradi?",
     "options": ["Ko'p kutilgan quvonch kelganda susayib qolishi mumkin",
                 "Kutish davri quvonchni har doim kuchaytirib boradi",
                 "Kutilmagan hodisa doim salbiy his uyg'otib qoladi",
                 "Sabr natijani albatta yaxshilab berishi kuzatiladi"], "correct": 0},

    {"q": "«Rejalashtirish xatosi» nimadan iborat?",
     "options": ["Ish qancha vaqt olishini doimo kam baholab yuborish",
                 "Rejani haddan tashqari batafsil tuzib chiqish",
                 "Muddatni ataylab uzoqroq qilib belgilab qo'yish",
                 "Reja tuzmasdan ishni to'g'ridan boshlab yuborish"], "correct": 0},

    {"q": "«Yo'qotish qo'rquvi» qarorlarga qanday ta'sir qiladi?",
     "options": ["Yo'qotish og'rig'i teng yutuq quvonchidan kuchli seziladi",
                 "Yutuq va yo'qotish aynan bir xil kuchda his qilinadi",
                 "Yo'qotgan odam keyingi safar tavakkal qilmay qo'yadi",
                 "Qo'rquv qaror sifatini doim oshirib borishi kuzatiladi"], "correct": 0},

    {"q": "«Cho'kib ketgan xarajat» xatosi qanday namoyon bo'ladi?",
     "options": ["Sarflangani achinib, foydasiz ishni davom ettiraverish",
                 "Xarajatni hisoblamay yangi ishga kirishib ketish",
                 "Har qanday sarmoyani darhol qaytarib olishga urinish",
                 "Foyda kelmasa, ishni juda tez tashlab yuborish"], "correct": 0},

    {"q": "«Langar effekti» qaror qabul qilishda nimani anglatadi?",
     "options": ["Birinchi eshitilgan raqam keyingi baholarni bog'lab qo'yadi",
                 "Oxirgi eshitilgan dalil doim ustun kelib chiqaveradi",
                 "Raqamlar hissiyotga umuman ta'sir qilmay qoladi",
                 "Ko'p ma'lumot qarorni doim aniqlashtirib boradi"], "correct": 0},

    {"q": "«Ramka effekti» nimani ko'rsatadi?",
     "options": ["Bir xil ma'lumot boshqacha aytilsa, boshqa qaror chiqadi",
                 "Ma'lumot shakli uning mazmuniga ta'sir qilmay qoladi",
                 "Raqamli dalil doim hissiy dalildan kuchli bo'lib chiqadi",
                 "Qaror faqat mavjud faktlarga asoslanib qabul qilinadi"], "correct": 0},

    {"q": "«Plasebo effekti» nimani ko'rsatadi?",
     "options": ["Ishonchning o'zi ham jismoniy holatni o'zgartira oladi",
                 "Har qanday dori aslida bir xil ta'sir ko'rsatib qoladi",
                 "Kasallik faqat tasavvurdan iborat bo'lib chiqadi",
                 "Shifokorga ishonch davolanishga xalaqit berib turadi"], "correct": 0},

    {"q": "«Nosebo effekti» qanday hodisa hisoblanadi?",
     "options": ["Yomon kutish salbiy jismoniy alomat keltirib chiqaradi",
                 "Ijobiy kutish kasallikni butunlay yo'q qilib yuboradi",
                 "Dori ta'siri faqat uning tarkibiga bog'liq bo'ladi",
                 "Ogohlantirish bemorni har doim tinchlantirib qo'yadi"], "correct": 0},

    {"q": "«Bilim la'nati» muloqotda nimani anglatadi?",
     "options": ["Bilgan odam bilmaganning holatini tasavvur qilolmay qoladi",
                 "Bilimli odam har doim yaxshi tushuntirib bera oladi",
                 "Murakkab mavzuni soddalashtirish oson kechib ketadi",
                 "Tajriba muloqotni doim yengillashtirib yuborishi aniq"], "correct": 0},

    {"q": "«Kassandra sindromi» nimani bildiradi?",
     "options": ["To'g'ri ogohlantirishga hech kim ishonmay qo'yishi",
                 "Yolg'on bashoratning tez tarqalib ketishi",
                 "Kelajakni oldindan ko'rish qobiliyati borligi",
                 "Ogohlantirish falokatni doim to'xtatib qolishi"], "correct": 0},

    {"q": "«O'z-o'zini amalga oshiruvchi bashorat» qanday ishlaydi?",
     "options": ["Bashoratga ishonish uning ro'yobga chiqishiga sabab bo'ladi",
                 "Bashorat qanchalik aniq bo'lsa, shuncha kam ta'sir qiladi",
                 "Kelajak haqidagi fikr voqealarga ta'sir qilmay qoladi",
                 "Har qanday bashorat oxir-oqibat xato bo'lib chiqadi"], "correct": 0},

    {"q": "«Taraqqiyot paradoksi» nimani anglatadi?",
     "options": ["Sharoit yaxshilangani sari norozilik ham kuchayib boradi",
                 "Taraqqiyot barcha muammoni izchil hal qilib boraveradi",
                 "Yaxshi yashash darajasi nizolarni yo'qotib yuboradi",
                 "Texnika rivoji baxtni to'g'ridan-to'g'ri oshirib boradi"], "correct": 0},

    {"q": "«Ikaros paradoksi» muvaffaqiyat haqida nimani aytadi?",
     "options": ["Muvaffaqiyat bergan sifat keyin halokat sababi bo'lib qoladi",
                 "Yuqori maqsad har doim qulashga olib kelishi kuzatiladi",
                 "Muvaffaqiyat faqat omad bilan qo'lga kiritilishi mumkin",
                 "Tajriba orttirgan odam boshqa xato qilmay qo'yadi"], "correct": 0},

    {"q": "«Mutaxassis paradoksi» nimani ko'rsatadi?",
     "options": ["Tor sohaga chuqurlashgan kengroq manzarani ko'rmay qoladi",
                 "Mutaxassis har qanday masalada to'g'ri qaror chiqaradi",
                 "Bilim chuqurlashgani sari xato ehtimoli yo'qolib boradi",
                 "Tajriba bashorat aniqligini doim oshirib borishi aniq"], "correct": 0},

    {"q": "«Buyuk sukunat» tushunchasi nimaga ishora qiladi?",
     "options": ["Koinotdan hech qanday aqlli signal eshitilmayotganiga",
                 "Yulduzlararo masofa signalni butunlay yutib yuborishiga",
                 "Radio to'lqinlar koinotda tarqala olmasligiga",
                 "Aloqa uchun yagona til mavjud emasligiga"], "correct": 0},

    {"q": "«Buyuk filtr» gipotezasi nimani taxmin qiladi?",
     "options": ["Rivojlanishda deyarli hech kim o'tolmas bosqich borligini",
                 "Aqlli hayot koinotda juda tez tarqalib borishini",
                 "Har bir sayyorada hayot muqarrar paydo bo'lishini",
                 "Texnologiya rivoji halokat oldini olishini"], "correct": 0},

    {"q": "«Simulyatsiya argumenti» qanday xulosa taklif qiladi?",
     "options": ["Biz hisoblangan olamda yashayotgan bo'lishimiz mumkinligini",
                 "Kompyuter ongni hech qachon modellay olmasligini",
                 "Haqiqat faqat sezgi orqali tasdiqlanishi mumkinligini",
                 "Olam qonunlari abadiy o'zgarmas bo'lib qolishini"], "correct": 0},

    {"q": "«Bo'ltsman miyasi» g'oyasi nimani ko'taradi?",
     "options": ["Tasodifan paydo bo'lgan ong olamni tasavvur qilayotgan bo'lishi",
                 "Miya faoliyati entropiyaga umuman bo'ysunmasligi",
                 "Xotira tashqi dunyoni aniq aks ettirib turishi",
                 "Ong faqat murakkab tanada shakllana olishi"], "correct": 0},

    {"q": "«Vaqt strelkasi» muammosi nimani so'raydi?",
     "options": ["Qonunlar teskari ishlasa, vaqt nega faqat oldinga oqadi?",
                 "Vaqt tezligi tortishish kuchiga qanday bog'lanadi?",
                 "Soat mexanizmi vaqtni qanchalik aniq o'lchay oladi?",
                 "O'tmish xotirasi nega yildan yilga so'nib boradi?"], "correct": 0},

    {"q": "«Ongning qattiq muammosi» nimadan iborat?",
     "options": ["Fizik jarayon nega ichki kechinma tug'dirishini tushuntirish",
                 "Miya signallarini asboblar bilan aniq o'lchab chiqish",
                 "Uyqu bosqichlarini to'liq tasniflab chiqish masalasi",
                 "Hayvon ongini inson ongi bilan qiyoslab ko'rish"], "correct": 0},

    {"q": "Dekartning «Cogito» xulosasi nimani bildiradi?",
     "options": ["Hamma narsadan shubhalansam ham, shubhalanayotganim aniq",
                 "Sezgilar dunyoni har doim to'g'ri ko'rsatib turadi",
                 "Bilim faqat tajribadan kelib chiqishi mumkin",
                 "Haqiqat ko'pchilik roziligi bilan aniqlanadi"], "correct": 0},

    {"q": "«Ikkilamchi foyda» tushunchasi nimani anglatadi?",
     "options": ["Muammodan yashirin naf ko'rgan undan qutulishni istamaydi",
                 "Har qanday muammo albatta foyda keltirib chiqaradi",
                 "Yordam so'ragan odam ancha tez sog'ayib ketadi",
                 "Qiyinchilik xarakterni doim mustahkamlab boradi"], "correct": 0},

    {"q": "«Yaxshilik paradoksi» axloqda nimani ko'rsatadi?",
     "options": ["Yaxshi niyat bilan qilingan ish zarar keltirib qo'yishi mumkin",
                 "Yaxshilik har doim yaxshilik bo'lib qaytib kelaveradi",
                 "Niyat sof bo'lsa, oqibat tekshirilmasa ham bo'laveradi",
                 "Yordam bergan odam doim minnatdorchilik ko'rib qoladi"], "correct": 0},

    {"q": "«Ozodlik va tartib» ziddiyati nimani bildiradi?",
     "options": ["Cheksiz erkinlik tartibsizlikka, qattiq tartib zulmga eltadi",
                 "Erkinlik va tartib bir-biriga umuman bog'liq bo'lmaydi",
                 "Qattiq qonun jamiyatni doim baxtli qilib qo'yadi",
                 "Tartibsiz jamiyat ancha tez rivojlanib ketadi"], "correct": 0},
]
