# -*- coding: utf-8 -*-
"""Bilim O'yini: Matchbook (Muallif va asar)"""

QUIZ_MATCHBOOK_QUESTIONS = [
    {"q": "Qaysi asar Abdulla Qodiriy qalamiga mansub?", "options": ["O'tkan kunlar", "Sarob", "Kecha va kunduz", "Shum bola"], "correct": 0},
    {"q": "Qaysi asar Cho'lpon qalamiga mansub?", "options": ["Kecha va kunduz", "O'tkan kunlar", "Sarob", "Qutlug' qon"], "correct": 0},
    {"q": "Qaysi asar Abdulla Qahhor qalamiga mansub?", "options": ["Sarob", "O'tkan kunlar", "Navoiy", "Ufq"], "correct": 0},
    {"q": "Qaysi asar Oybek qalamiga mansub?", "options": ["Navoiy", "Sarob", "Yulduzli tunlar", "Jimjitlik"], "correct": 0},
    {"q": "Qaysi asar G'afur G'ulom qalamiga mansub?", "options": ["Shum bola", "O'g'ri", "Anor", "Bemor"], "correct": 0},
    {"q": "Qaysi asar Pirimqul Qodirov qalamiga mansub?", "options": ["Yulduzli tunlar", "Ulug'bek xazinasi", "Diyonat", "Chinor"], "correct": 0},
    {"q": "Qaysi asar Odil Yoqubov qalamiga mansub?", "options": ["Ulug'bek xazinasi", "Yulduzli tunlar", "Ufq", "Jimjitlik"], "correct": 0},
    {"q": "Qaysi asar Said Ahmad qalamiga mansub?", "options": ["Kelinlar qo'zg'oloni", "Dunyoning ishlari", "Shaytanat", "Sariq devni minib"], "correct": 0},
    {"q": "Qaysi asar O'tkir Hoshimov qalamiga mansub?", "options": ["Ikki eshik orasi", "Ufq", "Yulduzli tunlar", "Sarob"], "correct": 0},
    {"q": "Qaysi asar Tohir Malik qalamiga mansub?", "options": ["Shaytanat", "Ikki eshik orasi", "Dunyoning ishlari", "Kelinlar qo'zg'oloni"], "correct": 0},
]

# ── 2026-08 qo'shimcha: muallif-asar moslashtirish ───────────────────────
QUIZ_MATCHBOOK_QUESTIONS += [
  {"q": "Qaysi asar Alisher Navoiy qalamiga mansub?", "options": ["Layli va Majnun", "Boburnoma", "Shum bola", "Sarob"], "correct": 0},
  {"q": "Qaysi asar Zahiriddin Muhammad Bobur qalamiga mansub?", "options": ["Boburnoma", "Xamsa", "Devoni hikmat", "O'tkan kunlar"], "correct": 0},
  {"q": "Qaysi asar Cho'lpon qalamiga mansub?", "options": ["Kecha va kunduz", "Mehrobdan chayon", "Shum bola", "Qutadg'u bilig"], "correct": 0},
  {"q": "Qaysi asar G'afur G'ulom qalamiga mansub?", "options": ["Shum bola", "O'tkan kunlar", "Sarob", "Alpomish"], "correct": 0},
  {"q": "Qaysi asar Abdulla Qahhor qalamiga mansub?", "options": ["Sarob", "Boburnoma", "Xamsa", "Oq kema"], "correct": 0},
  {"q": "Qaysi asar Abu Ali ibn Sino qalamiga mansub?", "options": ["Tib qonunlari", "Devonu lug'otit turk", "Qutadg'u bilig", "Mantiq ut-tayr"], "correct": 0},
  {"q": "Qaysi asar Ahmad Yassaviy qalamiga mansub?", "options": ["Devoni hikmat", "Xamsa", "Shohnoma", "Guliston"], "correct": 0},
  {"q": "Qaysi asar Yusuf Xos Hojib qalamiga mansub?", "options": ["Qutadg'u bilig", "Devonu lug'otit turk", "Boburnoma", "Tib qonunlari"], "correct": 0},
  {"q": "Qaysi asar Mahmud Koshg'ariy qalamiga mansub?", "options": ["Devonu lug'otit turk", "Qutadg'u bilig", "Xamsa", "Masnaviy"], "correct": 0},
  {"q": "Qaysi asar Firdavsiy qalamiga mansub?", "options": ["Shohnoma", "Guliston", "Masnaviy", "Xamsa"], "correct": 0},
  {"q": "Qaysi asar Sa'diy Sheroziy qalamiga mansub?", "options": ["Guliston", "Shohnoma", "Devoni hikmat", "Boburnoma"], "correct": 0},
  {"q": "Qaysi asar Lev Tolstoy qalamiga mansub?", "options": ["Urush va tinchlik", "Jinoyat va jazo", "Evrilish", "Chol va dengiz"], "correct": 0},
  {"q": "Qaysi asar Chingiz Aytmatov qalamiga mansub?", "options": ["Oq kema", "Shum bola", "Sarob", "Kecha va kunduz"], "correct": 0},
  {"q": "Qaysi asar O'tkir Hoshimov qalamiga mansub?", "options": ["Ikki eshik orasi", "Mehrobdan chayon", "Alpomish", "Guliston"], "correct": 0},
  {"q": "Qaysi asar Imom G'azzoliy qalamiga mansub?", "options": ["Ihyou ulumid-din", "Tib qonunlari", "Shohnoma", "Xamsa"], "correct": 0},
  {"q": "Qaysi asar Tog'ay Murod qalamiga mansub?", "options": ["Otamdan qolgan dalalar", "Chinor", "Lolazor", "Shaytanat"], "correct": 0},
  {"q": "Qaysi asar Asqad Muxtor qalamiga mansub?", "options": ["Chinor", "Otamdan qolgan dalalar", "Ikki eshik orasi", "Dunyoning ishlari"], "correct": 0},
  {"q": "Qaysi asar Xudoyberdi To'xtaboyev qalamiga mansub?", "options": ["Sariq devni minib", "Shum bola", "Omonboy va Davronboy", "Kelinlar qo'zg'oloni"], "correct": 0},
  {"q": "Qaysi asar Anvar Obidjon qalamiga mansub?", "options": ["Meshpolvonning janglari", "Sariq devni minib", "Shum bola", "O'g'ri"], "correct": 0},
  {"q": "Qaysi asar Shukur Xolmirzayev qalamiga mansub?", "options": ["O'n sakkizga kirmagan kim bor", "Chinor", "Lolazor", "Shaytanat"], "correct": 0},
  {"q": "Qaysi asar Murod Muhammad Do'st qalamiga mansub?", "options": ["Lolazor", "Otamdan qolgan dalalar", "Yulduzli tunlar", "Jimjitlik"], "correct": 0},
  {"q": "Qaysi asar Erkin Vohidov qalamiga mansub?", "options": ["Ruhlar isyoni", "Jannatga yo'l", "Muqanna", "Surat va siyrat"], "correct": 0},
  {"q": "Qaysi asar Abdulla Oripov qalamiga mansub?", "options": ["Jannatga yo'l", "Ruhlar isyoni", "O'zbegim", "Nido"], "correct": 0},
  {"q": "Qaysi asar Zulfiyaxonim qalamiga mansub?", "options": ["Bahor keldi seni so'roqlab", "O'zbegim", "Jannatga yo'l", "Muqanna"], "correct": 0},
  {"q": "Qaysi asar Hamid Olimjon qalamiga mansub?", "options": ["Muqanna", "Ruhlar isyoni", "Chinor", "Lolazor"], "correct": 0},
  {"q": "Qaysi asar Usmon Nosir qalamiga mansub?", "options": ["Yurak", "Bahor keldi", "O'zbegim", "O'tkan kunlar"], "correct": 0},
  {"q": "Qaysi asar Abdurauf Fitrat qalamiga mansub?", "options": ["Munozara", "Padarkush", "Turkiy Guliston", "Kecha va kunduz"], "correct": 0},
  {"q": "Qaysi asar Mahmudxo'ja Behbudiy qalamiga mansub?", "options": ["Padarkush", "Munozara", "Turkiy Guliston", "O'tkan kunlar"], "correct": 0},
  {"q": "Qaysi asar Abdulla Avloniy qalamiga mansub?", "options": ["Turkiy Guliston yoxud axloq", "Padarkush", "Munozara", "Kecha va kunduz"], "correct": 0},
  {"q": "Qaysi asar Ahmad Yugnakiy qalamiga mansub?", "options": ["Hibat ul-haqoyiq", "Qutadg'u bilig", "Devoni hikmat", "Boburnoma"], "correct": 0},
  {"q": "Qaysi asar Rabg'uziy qalamiga mansub?", "options": ["Qisasi Rabg'uziy", "Muhabbatnoma", "Gulistoni bit-turkiy", "Xamsa"], "correct": 0},
  {"q": "Qaysi asar Xorazmiy qalamiga mansub?", "options": ["Muhabbatnoma", "Qisasi Rabg'uziy", "Hibat ul-haqoyiq", "Qutadg'u bilig"], "correct": 0},
  {"q": "Qaysi asar Sayfi Saroyi qalamiga mansub?", "options": ["Gulistoni bit-turkiy", "Muhabbatnoma", "Qisasi Rabg'uziy", "Xamsa"], "correct": 0},
  {"q": "Qaysi asar Uilyam Shekspir qalamiga mansub?", "options": ["Gamlet", "Faust", "Don Kixot", "Ilohiy komediya"], "correct": 0},
  {"q": "Qaysi asar Migel de Servantes qalamiga mansub?", "options": ["Don Kixot", "Gamlet", "Faust", "Xo'rlanganlar"], "correct": 0},
  {"q": "Qaysi asar Iogann Volfgang Gyote qalamiga mansub?", "options": ["Faust", "Gamlet", "Don Kixot", "Graf Monte-Kristo"], "correct": 0},
  {"q": "Qaysi asar Viktor Gyugo qalamiga mansub?", "options": ["Xo'rlanganlar", "Graf Monte-Kristo", "Uch mushketyor", "Don Kixot"], "correct": 0},
  {"q": "Qaysi asar Aleksandr Dyuma qalamiga mansub?", "options": ["Graf Monte-Kristo", "Xo'rlanganlar", "Parij Bibi Maryam ibodatxonasi", "Gamlet"], "correct": 0},
  {"q": "Qaysi asar Fyodor Dostoyevskiy qalamiga mansub?", "options": ["Jinoyat va jazo", "Urush va tinchlik", "Anna Karenina", "Tirilish"], "correct": 0},
  {"q": "Qaysi asar Ernest Xeminguey qalamiga mansub?", "options": ["Chol va dengiz", "1984", "Evrilish", "Begona"], "correct": 0},
  {"q": "Qaysi asar Gabriel Garsia Markes qalamiga mansub?", "options": ["Yuz yillik yolg'izlik", "Alkimyogar", "1984", "Begona"], "correct": 0},
  {"q": "Qaysi asar Jorj Oruell qalamiga mansub?", "options": ["1984", "451 daraja Farengeyt", "Evrilish", "Begona"], "correct": 0},
  {"q": "Qaysi asar Rey Bredberi qalamiga mansub?", "options": ["451 daraja Farengeyt", "1984", "Molxona", "Evrilish"], "correct": 0},
  {"q": "Qaysi asar Frants Kafka qalamiga mansub?", "options": ["Evrilish", "Begona", "Vabo", "1984"], "correct": 0},
  {"q": "Qaysi asar Alber Kamyu qalamiga mansub?", "options": ["Begona", "Evrilish", "1984", "Alkimyogar"], "correct": 0},
  {"q": "Qaysi asar Paolo Koelo qalamiga mansub?", "options": ["Alkimyogar", "Yuz yillik yolg'izlik", "Begona", "Chol va dengiz"], "correct": 0},
  {"q": "Qaysi asar Antuan de Sent-Ekzyuperi qalamiga mansub?", "options": ["Kichkina Shahzoda", "Xo'rlanganlar", "Parij ibodatxonasi", "Don Kixot"], "correct": 0},
  {"q": "Qaysi asar Artur Konan Doyl qalamiga mansub?", "options": ["Sherlok Xolms sarguzashtlari", "Sharqiy ekspressda qotillik", "O'nta negr bolasi", "Graf Monte-Kristo"], "correct": 0},
  {"q": "Qaysi asar Agata Kristi qalamiga mansub?", "options": ["Sharqiy ekspressda qotillik", "Sherlok Xolms", "Dorian Grey", "Robinzon Kruzo"], "correct": 0},
  {"q": "Qaysi asar Oskar Uayld qalamiga mansub?", "options": ["Dorian Greyning portreti", "Gamlet", "Otello", "Don Kixot"], "correct": 0},
]
