# -*- coding: utf-8 -*-
"""Bilim O'yini: Reverse Quiz (Teskari Viktorina)"""

QUIZ_REVERSE_QUESTIONS = [
    {"q": "Javob: «Otabek va Kumush». Savol qaysi?", "options": ["«O'tkan kunlar» romanining bosh qahramonlari kim?", "«Mehrobdan chayon» bosh qahramonlari kim?", "«Sarob» romani qahramonlari kim?", "«Kecha va kunduz» qahramonlari kim?"], "correct": 0},
    {"q": "Javob: «5 ta». Savol qaysi?", "options": ["Alisher Navoiyning «Xamsa»si nechta dostondan iborat?", "Alisher Navoiy nechta devon tuzgan?", "Boburnoma nechta qismdan iborat?", "O'tkan kunlar nechta jilddan iborat?"], "correct": 0},
    {"q": "Javob: «1984». Savol qaysi?", "options": ["Jorj Oruellning totalitar jamiyat haqidagi distopik romani qaysi?", "Oldos Xakslining mashhur romani qaysi?", "Rey Bredberining romani qaysi?", "Frans Kafkaning romani qaysi?"], "correct": 0},
    {"q": "Javob: «Lev Tolstoy». Savol qaysi?", "options": ["«Urush va tinchlik» va «Anna Karenina» romanlari muallifi kim?", "«Jinoyat va jazo» muallifi kim?", "«O'lik jonlar» muallifi kim?", "«Ota va bolalar» muallifi kim?"], "correct": 0},
    {"q": "Javob: «Verona». Savol qaysi?", "options": ["«Romeo va Julyetta» voqealari qaysi shaharda kechadi?", "«Hamlet» voqealari qayerda bo'ladi?", "«Otello» voqealari qayerda bo'ladi?", "«Faust» qaysi shaharda yashagan?"], "correct": 0},
    {"q": "Javob: «Zahiriddin Muhammad Bobur». Savol qaysi?", "options": ["«Boburnoma» asari muallifi kim?", "«Navoiy» romani qahramoni kim?", "«Ulug'bek xazinasi» qahramoni kim?", "«Xamsa» muallifi kim?"], "correct": 0},
    {"q": "Javob: «Santyago». Savol qaysi?", "options": ["«Alkimyogar» va «Chol va dengiz» asarlaridagi bosh qahramon ismi nima?", "«Graf Monte-Kristo» qahramoni kim?", "«Uch mushketyor» qahramoni kim?", "«Robinzon Kruzo» do'sti kim?"], "correct": 0},
    {"q": "Javob: «Daniya». Savol qaysi?", "options": ["Shekspirning «Hamlet» tragediyasidagi shahzoda qaysi mamlakatga tegishli?", "«Romeo va Julyetta» qaysi davlatda?", "«Faust» qaysi mamlakatda?", "«Don Kixot» qaysi o'lkada?"], "correct": 0},
    {"q": "Javob: «Xudoyberdi To'xtaboyev». Savol qaysi?", "options": ["«Sariq devni minib» sarguzasht qissasi muallifi kim?", "«Shum bola» muallifi kim?", "«Dunyoning ishlari» muallifi kim?", "«Kelinlar qo'zg'oloni» muallifi kim?"], "correct": 0},
    {"q": "Javob: «Pirimqul Qodirov». Savol qaysi?", "options": ["«Yulduzli tunlar» va «Avlodlar dovoni» romanlari muallifi kim?", "«Ulug'bek xazinasi» muallifi kim?", "«Navoiy» romani muallifi kim?", "«O'tkan kunlar» muallifi kim?"], "correct": 0},
]

# ── 2026-08 qo'shimcha: javob berilgan, savolni topish ───────────────────
QUIZ_REVERSE_QUESTIONS += [
  {"q": "Javob: «Alisher Navoiy». Savol qaysi?", "options": ["«Xamsa» asarining muallifi kim?", "«Boburnoma» muallifi kim?", "«Shohnoma» muallifi kim?", "«Shum bola» muallifi kim?"], "correct": 0},
  {"q": "Javob: «Boburnoma». Savol qaysi?", "options": ["Bobur yozgan memuar asar nomi nima?", "Navoiy dostoni nomi nima?", "Qodiriy romani nomi nima?", "Yassaviy she'rlari to'plami nomi nima?"], "correct": 0},
  {"q": "Javob: «Beshta». Savol qaysi?", "options": ["Navoiy «Xamsa»si nechta dostondan iborat?", "Bayt nechta misra?", "Ruboiy nechta misra?", "Muxammas nechta misra?"], "correct": 0},
  {"q": "Javob: «Ikki misra». Savol qaysi?", "options": ["Bayt nechta misradan iborat?", "Ruboiy nechta misra?", "Muxammas nechta misra?", "Doston nechta bob?"], "correct": 0},
  {"q": "Javob: «Imom Buxoriy». Savol qaysi?", "options": ["«Sahih al-Buxoriy» to'plamini kim tuzgan?", "«Tib qonunlari» muallifi kim?", "«Xamsa» muallifi kim?", "Rasadxona qurdirgan kim?"], "correct": 0},
  {"q": "Javob: «Samarqand». Savol qaysi?", "options": ["Ulug'bek rasadxonasi qaysi shaharda?", "Bobur tug'ilgan shahar qaysi?", "Kumush yashagan shahar qaysi?", "Yassaviy maqbarasi qaysi shaharda?"], "correct": 0},
  {"q": "Javob: «Tib qonunlari». Savol qaysi?", "options": ["Ibn Sinoning tibbiyotga oid mashhur asari nomi nima?", "Navoiy dostoni nomi nima?", "Beruniy asari nomi nima?", "Xorazmiy asari nomi nima?"], "correct": 0},
  {"q": "Javob: «Yetti vodiy». Savol qaysi?", "options": ["«Mantiq ut-tayr»da qushlar nechta vodiydan o'tadi?", "«Xamsa» nechta dostondan iborat?", "Ruboiy nechta misra?", "Bayt nechta misra?"], "correct": 0},
  {"q": "Javob: «Cho'lpon». Savol qaysi?", "options": ["«Kecha va kunduz» romani muallifi kim?", "«Shum bola» muallifi kim?", "«Sarob» muallifi kim?", "«Oq kema» muallifi kim?"], "correct": 0},
  {"q": "Javob: «Al-Xorazmiy». Savol qaysi?", "options": ["«Algoritm» atamasi kimning nomidan olingan?", "Rasadxona kim qurdirgan?", "«Xamsa» muallifi kim?", "Hadis to'plovchi kim?"], "correct": 0},
  {"q": "Javob: «Xalq dostoni». Savol qaysi?", "options": ["«Alpomish» qaysi janrga mansub?", "«O'tkan kunlar» qaysi janrda?", "«Boburnoma» qaysi janrda?", "G'azal qaysi janr?"], "correct": 0},
  {"q": "Javob: «Farhod». Savol qaysi?", "options": ["Tog'ni teshib kanal qazigan oshiq kim?", "Cho'lda kezgan oshiq kim?", "Kumushning eri kim?", "Shum bola kim?"], "correct": 0},
  {"q": "Javob: «Memuar». Savol qaysi?", "options": ["«Boburnoma» qaysi janrga mansub?", "«Alpomish» qaysi janr?", "G'azal qaysi janr?", "«Sarob» qaysi janr?"], "correct": 0},
  {"q": "Javob: «Devonu lug'otit turk». Savol qaysi?", "options": ["Mahmud Koshg'ariyning turkiy tillar qomusi nomi nima?", "Yassaviy to'plami nomi nima?", "Navoiy devoni nomi nima?", "Bobur asari nomi nima?"], "correct": 0},
  {"q": "Javob: «To'rt misra». Savol qaysi?", "options": ["Ruboiy nechta misradan iborat?", "Bayt nechta misra?", "Muxammas nechta misra?", "G'azal nechta misra?"], "correct": 0},
  {"q": "Javob: «Abdulla Qodiriy». Savol qaysi?", "options": ["«O'tkan kunlar» va «Mehrobdan chayon» muallifi kim?", "«Shum bola» muallifi kim?", "«Navoiy» muallifi kim?", "«Ufq» muallifi kim?"], "correct": 0},
  {"q": "Javob: «Anvar va Ra'no». Savol qaysi?", "options": ["«Mehrobdan chayon» romanining bosh qahramonlari kim?", "«O'tkan kunlar» qahramonlari kim?", "«Yulduzli tunlar» qahramonlari kim?", "«Farhod va Shirin» qahramonlari kim?"], "correct": 0},
  {"q": "Javob: «Shum bola (Qoravoy)». Savol qaysi?", "options": ["G'afur G'ulomning mashhur sarguzasht qissasi bosh qahramoni kim?", "«Sariq devni minib» qahramoni kim?", "«O'g'ri» qahramoni kim?", "«Bemor» qahramoni kim?"], "correct": 0},
  {"q": "Javob: «Hoshimjon». Savol qaysi?", "options": ["Sehrli qalpoqchani topib olgan qahramon kim?", "Shum bola kim?", "Qobil bobo kim?", "Jamoliddin Ketmon kim?"], "correct": 0},
  {"q": "Javob: «Jamoliddin Ketmon». Savol qaysi?", "options": ["«Otamdan qolgan dalalar» romanidagi bosh qahramon dehqon kim?", "«Yulduzlar mangu yonadi» qahramoni kim?", "«Lolazor» qahramoni kim?", "«Chinor» qahramoni kim?"], "correct": 0},
  {"q": "Javob: «Bo'ri polvon». Savol qaysi?", "options": ["«Yulduzlar mangu yonadi» qissasidagi bosh polvon kim?", "«Ot kishnagan oqshom» chavandozi kim?", "«Alpomish» bahodiri kim?", "«Shaytanat» qahramoni kim?"], "correct": 0},
  {"q": "Javob: «Ziyodulla chavandoz». Savol qaysi?", "options": ["«Ot kishnagan oqshom» qissasidagi bosh chavandoz kim?", "«Yulduzlar mangu yonadi» polvoni kim?", "«Chinor» qahramoni kim?", "«Lolazor» qahramoni kim?"], "correct": 0},
  {"q": "Javob: «Asadbek». Savol qaysi?", "options": ["«Shaytanat» asaridagi bosh qahramon kim?", "«Lolazor» qahramoni kim?", "«Ufq» qahramoni kim?", "«Chinor» qahramoni kim?"], "correct": 0},
  {"q": "Javob: «Erkin Vohidov». Savol qaysi?", "options": ["«O'zbegim» qasidasi va «Ruhlar isyoni» muallifi kim?", "«Jannatga yo'l» muallifi kim?", "«O'zbekiston» muallifi kim?", "«Bahor keldi» muallifi kim?"], "correct": 0},
  {"q": "Javob: «Abdulla Oripov». Savol qaysi?", "options": ["O'zbekiston Respublikasi Davlat madhiyasi matni muallifi kim?", "«O'zbegim» muallifi kim?", "«Biz baxtli bo'lamiz» muallifi kim?", "«Yurak» muallifi kim?"], "correct": 0},
  {"q": "Javob: «Zulfiyaxonim». Savol qaysi?", "options": ["«Bahor keldi seni so'roqlab» she'ri muallifi kim?", "«O'zbegim» muallifi kim?", "«Jannatga yo'l» muallifi kim?", "«Muqanna» muallifi kim?"], "correct": 0},
  {"q": "Javob: «Hamid Olimjon». Savol qaysi?", "options": ["«Muqanna» va «Zaynab va Omon» muallifi kim?", "«Qutlug' qon» muallifi kim?", "«Navoiy» muallifi kim?", "«Shum bola» muallifi kim?"], "correct": 0},
  {"q": "Javob: «Mahmudxo'ja Behbudiy». Savol qaysi?", "options": ["«Padarkush» ilk o'zbek dramasi muallifi kim?", "«Munozara» muallifi kim?", "«Turkiy Guliston» muallifi kim?", "«O'tkan kunlar» muallifi kim?"], "correct": 0},
  {"q": "Javob: «Abdulla Avloniy». Savol qaysi?", "options": ["«Turkiy Guliston yoxud axloq» kitobi muallifi kim?", "«Padarkush» muallifi kim?", "«Munozara» muallifi kim?", "«Kecha va kunduz» muallifi kim?"], "correct": 0},
  {"q": "Javob: «Abdurauf Fitrat». Savol qaysi?", "options": ["«Munozara» va «Hind ixtilolchilari» muallifi kim?", "«Padarkush» muallifi kim?", "«Turkiy Guliston» muallifi kim?", "«O'tkan kunlar» muallifi kim?"], "correct": 0},
  {"q": "Javob: «Sherlok Xolms». Savol qaysi?", "options": ["Beyker-strit 221B da yashovchi mashhur detektiv kim?", "Doktor Vatson kim?", "Puaro kim?", "Monte-Kristo kim?"], "correct": 0},
  {"q": "Javob: «Erkyul Puaro». Savol qaysi?", "options": ["Agata Kristining belgiya-fransuzlik mashhur detektivi kim?", "Sherlok Xolms kim?", "Jan Valjan kim?", "Gamlet kim?"], "correct": 0},
  {"q": "Javob: «Jan Valjan». Savol qaysi?", "options": ["Viktor Gyugoning «Xo'rlanganlar» romanidagi bosh qahramon kim?", "Kozetta kim?", "Javer kim?", "Kvazimodo kim?"], "correct": 0},
  {"q": "Javob: «Kvazimodo». Savol qaysi?", "options": ["Parij Bibi Maryam ibodatxonasining bukri qo'ng'iroqchisi kim?", "Klod Frollo kim?", "Jan Valjan kim?", "D'Artanyan kim?"], "correct": 0},
  {"q": "Javob: «Edmon Dantes». Savol qaysi?", "options": ["«Graf Monte-Kristo» romanining bosh qahramoni kim?", "Uch mushketyor kim?", "Jan Valjan kim?", "Don Kixot kim?"], "correct": 0},
  {"q": "Javob: «Don Kixot». Savol qaysi?", "options": ["Servantesning ritsar xomxayollari bilan yashagan qahramoni kim?", "Sancho Pansa kim?", "Gamlet kim?", "Faust kim?"], "correct": 0},
  {"q": "Javob: «Gamlet». Savol qaysi?", "options": ["«Bo'lmoq yo bo'lmaslik» monologini aytgan Daniya shahzodasi kim?", "Otello kim?", "Klavdiy kim?", "Faust kim?"], "correct": 0},
  {"q": "Javob: «Faust». Savol qaysi?", "options": ["Gyote tragediyasida ruhini Mefistofelga topshirgan olim kim?", "Gamlet kim?", "Don Kixot kim?", "Dorian Grey kim?"], "correct": 0},
  {"q": "Javob: «Raskolnikov». Savol qaysi?", "options": ["«Jinoyat va jazo»da kampirni o'ldirib pushaymon bo'lgan talaba kim?", "Marmeladov kim?", "Razumixin kim?", "Mishkin kim?"], "correct": 0},
  {"q": "Javob: «Santiago». Savol qaysi?", "options": ["«Chol va dengiz» qissasidagi keksa kubalik baliqchi kim?", "Manolin kim?", "Gulliver kim?", "Robinzon kim?"], "correct": 0},
  {"q": "Javob: «Yedigey». Savol qaysi?", "options": ["«Asrga tatigulik kun» romanidagi Sarozek temiryo'lchisi kim?", "Qozang'ap kim?", "Avdiy kim?", "Mankurt kim?"], "correct": 0},
  {"q": "Javob: «Uinston Smit». Savol qaysi?", "options": ["«1984» romanidagi Haqiqat vazirligi xodimi bosh qahramon kim?", "Katta Og'a kim?", "O'Brayen kim?", "Monteg kim?"], "correct": 0},
  {"q": "Javob: «Gay Monteg». Savol qaysi?", "options": ["«451 daraja Farengeyt» romanidagi o't o'chiruvchi qahramon kim?", "Uinston Smit kim?", "Gregor Zamza kim?", "Merso kim?"], "correct": 0},
  {"q": "Javob: «Gregor Zamza». Savol qaysi?", "options": ["Kafkaning «Evrilish»ida hasharotga aylanib qolgan qahramon kim?", "Merso kim?", "Usta kim?", "Dorian kim?"], "correct": 0},
  {"q": "Javob: «Merso». Savol qaysi?", "options": ["Kamyuning «Begona» romanidagi befarq bosh qahramon kim?", "Zamza kim?", "Raskolnikov kim?", "Santyago kim?"], "correct": 0},
  {"q": "Javob: «Robinzon Kruzo». Savol qaysi?", "options": ["Kimsasiz orolda 28 yil yashagan mashhur dengizchi kim?", "Gulliver kim?", "Jim Xokins kim?", "Kapitan Nemo kim?"], "correct": 0},
  {"q": "Javob: «Dorian Grey». Savol qaysi?", "options": ["O'zi emas, balki portreti qariydigan qahramon kim?", "Lord Genri kim?", "Bazil kim?", "Faust kim?"], "correct": 0},
  {"q": "Javob: «Frodo Beggins». Savol qaysi?", "options": ["Yagona Uzukni Mordorga eltgan xobbit kim?", "Gendalf kim?", "Gollum kim?", "Aragorn kim?"], "correct": 0},
  {"q": "Javob: «Garri Potter». Savol qaysi?", "options": ["Peshonasida chaqmoqsimon chandiq bo'lgan yosh sehrgar kim?", "Ron kim?", "Dambldor kim?", "Volan-de-Mort kim?"], "correct": 0},
  {"q": "Javob: «Bazarov». Savol qaysi?", "options": ["«Otalar va bolalar» romanidagi nigilist yosh vrach kim?", "Arkadiy kim?", "Oblomov kim?", "Pechorin kim?"], "correct": 0},
  {"q": "Javob: «Oblomov». Savol qaysi?", "options": ["Goncharovning divandan turishni istamaydigan yalqov qahramoni kim?", "Shtolts kim?", "Bazarov kim?", "Raskolnikov kim?"], "correct": 0},
  {"q": "Javob: «Chichikov». Savol qaysi?", "options": ["Gogolning «O'lik jonlar»ida o'lik dehqonlarni sotib olgan qahramon kim?", "Sobakevich kim?", "Plyushkin kim?", "Nozdryov kim?"], "correct": 0},
]
