# -*- coding: utf-8 -*-
"""Bilim O'yini: Hidden Connection (Yashirin bog'lanish)"""

QUIZ_CONNECTION_QUESTIONS = [
    {"q": "Otabek, Kumush, Ziyo shohichi, Homid — bu qahramonlarni nima bog'lab turadi?", "options": ["«O'tkan kunlar» romani", "«Mehrobdan chayon» romani", "«Kecha va kunduz» romani", "«Sarob» romani"], "correct": 0},
    {"q": "Anvar, Ra'no, Domla Shahobiddin, Solih maxdum — bu qahramonlar qaysi asardan?", "options": ["«Mehrobdan chayon»", "«O'tkan kunlar»", "«Diyonat»", "«Shaytanat»"], "correct": 0},
    {"q": "Farhod, Shirin, Shopur, Xusrav — bu obrazlar qaysi doston qahramonlari?", "options": ["«Farhod va Shirin»", "«Layli va Majnun»", "«Tohir va Zuhra»", "«Alpomish»"], "correct": 0},
    {"q": "Raskolnikov, Sonya Marmeladova, Razumixin, Porfiriy Petrovich — bular qaysi romandan?", "options": ["«Jinoyat va jazo»", "«Telba»", "«Aka-uka Karamazovlar»", "«Ona»"], "correct": 0},
    {"q": "Andrey Bolkonskiy, Pyer Bezuxov, Natasha Rostova — bu qahramonlar qaysi asardan?", "options": ["«Urush va tinchlik»", "«Anna Karenina»", "«Tinch Don»", "«Ota va bolalar»"], "correct": 0},
    {"q": "Atos, Portos, Aramis, D'Artanyan — bu to'rtlikni nima birlashtiradi?", "options": ["«Uch mushketyor»", "«Graf Monte-Kristo»", "«Notr-Dam ibodatxonasi»", "«Ayvengo»"], "correct": 0},
    {"q": "Edmond Dantes, Mersedes, Fernan, Abbe Faria — bular qaysi asardan?", "options": ["«Graf Monte-Kristo»", "«Sefillar»", "«Uch mushketyor»", "«Don Kixot»"], "correct": 0},
    {"q": "Kimsan, Robiya, Shomurod, Mirvali — bu qahramonlar qaysi romanda uchraydi?", "options": ["«Ikki eshik orasi»", "«Dunyoning ishlari»", "«Ufq»", "«Chinor»"], "correct": 0},
    {"q": "Jan Valjan, Jover, Fantina, Kozetta — bu qahramonlar qaysi kitobdan?", "options": ["«Sefillar»", "«Notr-Dam ibodatxonasi»", "«Graf Monte-Kristo»", "«Ona»"], "correct": 0},
    {"q": "Kvazimodo, Esmeralda, Klod Frollo, Feb — bular qaysi asardan?", "options": ["«Notr-Dam ibodatxonasi»", "«Sefillar»", "«Faust»", "«Hamlet»"], "correct": 0},
]

# ── 2026-08 qo'shimcha: yashirin bog'lanishni topish ─────────────────────
QUIZ_CONNECTION_QUESTIONS += [
  {"q": "Anvar, Ra'no, Solih maxdum, Xudoyorxon — bularni nima bog'laydi?", "options": ["«Mehrobdan chayon» romani", "«O'tkan kunlar» romani", "«Kecha va kunduz»", "«Sarob» romani"], "correct": 0},
  {"q": "Hayrat ul-abror, Farhod va Shirin, Layli va Majnun, Sab'ai sayyor — umumiyligi nima?", "options": ["Navoiy «Xamsa»siga kiruvchi dostonlar", "Bobur asarlari", "Xalq dostonlari", "Jahon romanlari"], "correct": 0},
  {"q": "Beruniy, Ibn Sino, Al-Xorazmiy, Farg'oniy — bularni nima birlashtiradi?", "options": ["Sharq Uyg'onish davri allomalari", "Zamonaviy yozuvchilar", "Xalq baxshilari", "Sufiy shoirlar"], "correct": 0},
  {"q": "Alpomish, Go'ro'g'li, Kuntug'mish, Ravshan — umumiy jihati nima?", "options": ["O'zbek xalq dostonlari", "Qodiriy romanlari", "Jahon adabiyoti asarlari", "Tasavvuf risolalari"], "correct": 0},
  {"q": "Cho'lpon, Fitrat, Behbudiy, Avloniy — bularni nima bog'laydi?", "options": ["Jadidchilik harakati namoyandalari", "Astronomiya olimlari", "Xalq baxshilari", "Tabiblar"], "correct": 0},
  {"q": "Buxoriy, Termiziy, Abu Dovud, Nasoiy — umumiyligi nimada?", "options": ["Mashhur hadis to'plovchi muhaddislar", "Astronomlar", "Shoirlar", "Sayyohlar"], "correct": 0},
  {"q": "Tolstoy, Dostoyevskiy, Chexov, Turgenev — bularni nima birlashtiradi?", "options": ["Rus klassik adabiyoti", "Frantsuz romantizmi", "Ingliz dramaturgiyasi", "Ispan adabiyoti"], "correct": 0},
  {"q": "Samarqand, Buxoro, Xiva, Shahrisabz — adabiy jihatdan umumiyligi nima?", "options": ["Sharq ilmi va adabiyoti markazlari bo'lgan qadimiy shaharlar", "Faqat zamonaviy sanoat shaharlari", "Roman qahramonlari ismlari", "Doston nomlari"], "correct": 0},
  {"q": "Rumiy, Attor, Yassaviy, Naqshband — bularni nima bog'laydi?", "options": ["Tasavvuf ta'limoti namoyandalari", "Matematiklar", "Tarixchi solnomachilar", "Zamonaviy shoirlar"], "correct": 0},
  {"q": "Zebi, Kumush, Ra'no, Barchinoy — umumiy jihati nima?", "options": ["O'zbek adabiyotidagi ayol qahramonlar", "Shoira ayollar", "Tarixiy malikalar", "Asar nomlari"], "correct": 0},
  {"q": "Boburnoma, Temur tuzuklari, Boburning kundaliklari — janriy umumiyligi nima?", "options": ["Memuar va tarixiy-hujjatli asarlar", "Sevgi dostonlari", "Hadis to'plamlari", "Sahna asarlari"], "correct": 0},
  {"q": "G'azal, ruboiy, tuyuq, muxammas — bularni nima birlashtiradi?", "options": ["Mumtoz she'riy janrlar", "Nasriy janrlar", "Sahna janrlari", "Ilmiy janrlar"], "correct": 0},
  {"q": "Ulug'bek, Farg'oniy, Beruniy — kasbiy umumiyligi nima?", "options": ["Astronomiya bilan shug'ullanganlar", "Hadis to'plaganlar", "Doston yozganlar", "Tabiblik qilganlar"], "correct": 0},
  {"q": "Qoravoy, Otabek, Anvar, Alpomish — umumiyligi nima?", "options": ["Adabiyotdagi erkak bosh qahramonlar", "Tarixiy hukmdorlar", "Muallif taxalluslari", "Shahar nomlari"], "correct": 0},
  {"q": "Xamsa, Devon, Tazkira, Kulliyot — bular nimani anglatadi?", "options": ["Mumtoz adabiyotdagi to'plam turlari", "Shahar nomlari", "Qahramon ismlari", "She'r vaznlari"], "correct": 0},
  {"q": "Hoshimjon, Donishmand ota, Sehrli qalpoqcha — bu obrazlar qaysi asardan?", "options": ["«Sariq devni minib» (Xudoyberdi To'xtaboyev)", "«Shum bola»", "«Besh bolali yigitcha»", "«Omonboy va Davronboy»"], "correct": 0},
  {"q": "Sariboy bo'lis, Qoravoy, Domla Imom — bular qaysi qissadan?", "options": ["«Shum bola» (G'afur G'ulom)", "«Sariq devni minib»", "«O'g'ri»", "«Yorqinoy»"], "correct": 0},
  {"q": "Jamoliddin Ketmon, Surxondaryo, Paxta yakkahokimligi — bu asar qaysi?", "options": ["«Otamdan qolgan dalalar» (Tog'ay Murod)", "«Yulduzlar mangu yonadi»", "«Ot kishnagan oqshom»", "«Lolazor»"], "correct": 0},
  {"q": "Bo'ri polvon, Nasim qora, Milliy kurash — bu obrazlar qaysi qissadan?", "options": ["«Yulduzlar mangu yonadi» (Tog'ay Murod)", "«Otamdan qolgan dalalar»", "«Ot kishnagan oqshom»", "«Chinor»"], "correct": 0},
  {"q": "Ziyodulla chavandoz, Tarlon, Ko'pkari — bu qahramonlar qaysi asardan?", "options": ["«Ot kishnagan oqshom» (Tog'ay Murod)", "«Yulduzlar mangu yonadi»", "«Lolazor»", "«Chinor»"], "correct": 0},
  {"q": "Muzaffar, Robiyaxonim, O'ratepa chinori — bu qaysi romandan?", "options": ["«Chinor» (Asqad Muxtor)", "«Bo'ronlarda bordek halovat»", "«Tug'ilish»", "«Amu»"], "correct": 0},
  {"q": "Asadbek, Chuvrindi, Sanobar — bu qahramonlar qaysi asardan?", "options": ["«Shaytanat» (Tohir Malik)", "«Murdalar gapirmaydilar»", "«Falak»", "«Kelinlar daftariga»"], "correct": 0},
  {"q": "Yaxshiboyev, Oshno, Lolazor — bu personajlar qaysi kitobdan?", "options": ["«Lolazor» (Murod Muhammad Do'st)", "«Galatepa»", "«Dasht»", "«Mustafo»"], "correct": 0},
  {"q": "Robindranat Tagor, Nazrul Islom, Kalkutta — bu qaysi dostonda uchraydi?", "options": ["«Ruhlar isyoni» (Erkin Vohidov)", "«O'zbegim»", "«Nido»", "«Jannatga yo'l»"], "correct": 0},
  {"q": "Sherlok Xolms, Doktor Vatson, Beyker-strit 221B — bularni nima bog'laydi?", "options": ["Artur Konan Doyl detektivlari", "Agata Kristi asarlari", "Edgar Po asarlari", "Gaston Leru romanlari"], "correct": 0},
  {"q": "Erkyul Puaro, Gastings, Miss Marpl — bu qahramonlarni nima birlashtiradi?", "options": ["Agata Kristi detektiv qahramonlari", "Konan Doyl asarlari", "Jorj Simenon asarlari", "Chesterton asarlari"], "correct": 0},
  {"q": "Don Kixot, Sancho Pansa, Dulsineya — bular qaysi romandan?", "options": ["«Don Kixot» (Migel de Servantes)", "«Gamlet»", "«Dekameron»", "«Faust»"], "correct": 0},
  {"q": "Gamlet, Ofeliya, Klavdiy — bu qahramonlar qaysi fojiadan?", "options": ["«Gamlet» (Uilyam Shekspir)", "«Otello»", "«Makbet»", "«Qirol Lir»"], "correct": 0},
  {"q": "Otello, Dezdemona, Yago — bu personajlar qaysi asardan?", "options": ["«Otello» (Uilyam Shekspir)", "«Gamlet»", "«Romeo va Juletta»", "«Venetsiya savdogari»"], "correct": 0},
  {"q": "Faust, Mefistofel, Gretxen — bular qaysi asarning bosh qahramonlari?", "options": ["«Faust» (Iogann Volfgang Gyote)", "«Verter»", "«Vilgelm Tell»", "«Qaroqchilar»"], "correct": 0},
  {"q": "Santiago, Manolin, Ulkan qilichbaliq — bu obrazlar qaysi kitobdan?", "options": ["«Chol va dengiz» (Ernest Xeminguey)", "«Alvido, qurol!»", "«Qo'ng'iroq kimni chorlaydi»", "«Dengiz bo'risi»"], "correct": 0},
  {"q": "Yedigey, Qozang'ap, Nayman ona — bu obrazlar qaysi romandan?", "options": ["«Asrga tatigulik kun» (Chingiz Aytmatov)", "«Qiyomat»", "«Oq kema»", "«Jamila»"], "correct": 0},
  {"q": "Avdiy Kallistratov, Bo'stona, Akbara bo'ri — bu qahramonlar qaysi asardan?", "options": ["«Qiyomat» (Chingiz Aytmatov)", "«Asrga tatigulik kun»", "«Oq kema»", "«Erta qaytgan turnalar»"], "correct": 0},
  {"q": "Uinston Smit, Juliya, Katta Og'a — bu qahramonlar qaysi kitobdan?", "options": ["«1984» (Jorj Oruell)", "«Molxona»", "«Ajoyib yangi dunyo»", "«Farengeyt»"], "correct": 0},
  {"q": "Napoleon, Snouboll, Bokser ot — bu hayvonlar qaysi qissadan?", "options": ["«Molxona» (Jorj Oruell)", "«1984»", "«Qushlar oroli»", "«Hayvonlar jangi»"], "correct": 0},
  {"q": "Gay Monteg, Klarissa, Mexanik it — bular qaysi romandan?", "options": ["«451 daraja Farengeyt» (Rey Bredberi)", "«Mars xronikalari»", "«Dandelion sharobi»", "«1984»"], "correct": 0},
  {"q": "Gregor Zamza, Greta, Praga — bular qaysi novelladan?", "options": ["«Evrilish» (Frants Kafka)", "«Jarayon»", "«Qasr»", "«Begona»"], "correct": 0},
  {"q": "Merso, Aljir sohillari, Quyosh — bular qaysi romandan?", "options": ["«Begona» (Alber Kamyu)", "«Vabo»", "«Sizif»", "«Yiqilish»"], "correct": 0},
  {"q": "Santyago, Fotima, Alkimyogar — bu obrazlar qaysi kitobdan?", "options": ["«Alkimyogar» (Paolo Koelo)", "«Veronika»", "«Zohir»", "«Maktub»"], "correct": 0},
  {"q": "Aurelyano Buendia, Ursula, Makondo — bular qaysi romandan?", "options": ["«Yuz yillik yolg'izlik» (Gabriel Garsia Markes)", "«Patriarxning kuzi»", "«Vabo davridagi muhabbat»", "«Polkovnik»"], "correct": 0},
  {"q": "Usta, Margarita, Voland — bu qahramonlar qaysi asardan?", "options": ["«Usta va Margarita» (Mixail Bulgakov)", "«It yuragi»", "«Oq gvardiya»", "«Iblisnoma»"], "correct": 0},
  {"q": "Sharik it, Professor Preobrajenskiy, Bormental — bular qaysi kitobdan?", "options": ["«It yuragi» (Mixail Bulgakov)", "«Usta va Margarita»", "«Kvartira»", "«Qizil tuxumlar»"], "correct": 0},
  {"q": "Ostap Bender, Kisa Vorobyaninov, 12 ta stul — bu qahramonlar qaysi asardan?", "options": ["«O'n ikki stul» (Ilf va Petrov)", "«Oltin buzoqcha»", "«Bir qavatli Amerika»", "«Kombinator»"], "correct": 0},
  {"q": "Robinzon Kruzo, Juma, Kimsasiz orol — bular qaysi asardan?", "options": ["«Robinzon Kruzo» (Daniel Defo)", "«Gulliver»", "«Xazinalar oroli»", "«Dengiz bo'risi»"], "correct": 0},
  {"q": "Gulliver, Liliputlar, Brobdigneg devlari — bular qaysi kitobdan?", "options": ["«Gulliverning sayohatlari» (Jonatan Svift)", "«Robinzon Kruzo»", "«Mo''jizalar oroli»", "«Alisa»"], "correct": 0},
  {"q": "Jim Xokins, Jon Silver, Ispaniola kemasi — bular qaysi asardan?", "options": ["«Xazinalar oroli» (Robert Stivenson)", "«Qora o'q»", "«Robinzon Kruzo»", "«Kapitan Grant»"], "correct": 0},
  {"q": "Tom Soyer, Geklberri Finn, Bekki Tetcher — bu bolalar qaysi kitobdan?", "options": ["«Tom Soyerning sarguzashtlari» (Mark Tven)", "«Gek Finn»", "«Shahzoda va gado»", "«Yanki»"], "correct": 0},
  {"q": "Dorian Grey, Lord Genri, Bazil — bu personajlar qaysi romandan?", "options": ["«Dorian Greyning portreti» (Oskar Uayld)", "«Kenterberri sharpasi»", "«Baxtli shahzoda»", "«Salomeya»"], "correct": 0},
  {"q": "Eduard Tyudor, Tom Kenti, London — bular qaysi asardan?", "options": ["«Shahzoda va gado» (Mark Tven)", "«Tom Soyer»", "«Oliver Tvist»", "«Gulliver»"], "correct": 0},
  {"q": "Oliver Tvist, Fegin, Sayks, Roz — bu qahramonlar qaysi kitobdan?", "options": ["«Oliver Tvistning sarguzashtlari» (Charlz Dikkens)", "«Devid Kopperfild»", "«Buyuk umidlar»", "«Robinzon Kruzo»"], "correct": 0},
  {"q": "Frodo, Sem, Gendalf, Aragorn — bu to'rtlik qaysi asardan?", "options": ["«Uzuklar hukmdori» (J.R.R. Tolkien)", "«Xobbit»", "«Narniya»", "«Garri Potter»"], "correct": 0},
  {"q": "Garri Potter, Ron Uizli, Germiona — bu do'stlar qaysi asardan?", "options": ["«Garri Potter» (J.K. Rouling)", "«Narniya»", "«O'rta yer»", "«Alisa»"], "correct": 0},
  {"q": "Bazarov, Arkadiy, Pavel Petrovich — bu qahramonlar qaysi romandan?", "options": ["«Otalar va bolalar» (Ivan Turgenev)", "«Rudin»", "«Asya»", "«Dvoryanlar uyasi»"], "correct": 0},
]
