# -*- coding: utf-8 -*-
"""Bilim O'yini: Timeline (Vaqt mashinasi)"""

QUIZ_TIMELINE_QUESTIONS = [
    {"q": "Alisher Navoiy «Xamsa»si qaysi asrda yozib tugatilgan?", "options": ["XV asr (1483-1485)", "XIV asr", "XVI asr", "XII asr"], "correct": 0},
    {"q": "Yusuf Xos Hojibning «Qutadg'u bilig» asari qaysi asrda yaratilgan?", "options": ["XI asr (1069-1070)", "XV asr", "IX asr", "XIII asr"], "correct": 0},
    {"q": "Abdulla Qodiriyning «O'tkan kunlar» romani qaysi yillarda yozilgan va chop etilgan?", "options": ["1922-1926 yillar", "1935-1938 yillar", "1905-1910 yillar", "1941-1945 yillar"], "correct": 0},
    {"q": "Mirzo Ulug'bek Samarqand rasadxonasini qaysi asrda qurdirgan?", "options": ["XV asr (1424-1428)", "XIV asr", "XVI asr", "XIII asr"], "correct": 0},
    {"q": "Abu Ali ibn Sinoning «Al-Qonun fit-tib» asari qaysi asrda yaratilgan?", "options": ["XI asr boshlari", "XV asr", "VIII asr", "XIV asr"], "correct": 0},
    {"q": "Zahiriddin Muhammad Bobur «Boburnoma» asarini asosan qaysi asrda bitgan?", "options": ["XVI asr", "XIV asr", "XVII asr", "XII asr"], "correct": 0},
    {"q": "Lev Tolstoyning «Urush va tinchlik» romani qaysi asrda chop etilgan?", "options": ["XIX asr (1860-yillar)", "XVIII asr", "XX asr boshlari", "XVII asr"], "correct": 0},
    {"q": "Servantesning «Don Kixot» romani qaysi asr boshlarida chop etilgan?", "options": ["XVII asr (1605-1615)", "XV asr", "XIX asr", "XIV asr"], "correct": 0},
    {"q": "Dante Aligyerining «Ilohiy komediya» dostoni qaysi asrda yozilgan?", "options": ["XIV asr boshlari", "XVI asr", "XVIII asr", "XI asr"], "correct": 0},
    {"q": "Jorj Oruellning «1984» distopik romani qachon yozib tugatilgan?", "options": ["1948-1949 yillar", "1984 yilda", "1914 yilda", "1960 yilda"], "correct": 0},
]

# ── 2026-08 qo'shimcha: davr va sana savollari ───────────────────────────
QUIZ_TIMELINE_QUESTIONS += [
  {"q": "Zahiriddin Muhammad Bobur qaysi asrda yashagan?", "options": ["XV–XVI asr", "XIII asr", "XVIII asr", "XX asr"], "correct": 0},
  {"q": "Abu Ali ibn Sino qaysi asrda yashab ijod qilgan?", "options": ["X–XI asr", "XV asr", "XIX asr", "VII asr"], "correct": 0},
  {"q": "Mirzo Ulug'bek rasadxonasi qaysi asrda qurilgan?", "options": ["XV asr", "XI asr", "XVII asr", "XIX asr"], "correct": 0},
  {"q": "«O'tkan kunlar» romani qaysi asrda yozilgan?", "options": ["XX asr", "XIX asr", "XVI asr", "XVIII asr"], "correct": 0},
  {"q": "Imom Buxoriy qaysi asrda yashagan?", "options": ["IX asr", "XIV asr", "XVI asr", "XX asr"], "correct": 0},
  {"q": "Al-Xorazmiy qaysi asr allomasi?", "options": ["VIII–IX asr", "XV asr", "XVII asr", "XIX asr"], "correct": 0},
  {"q": "Amir Temur davlati qaysi asrda qudratga erishgan?", "options": ["XIV asr", "XI asr", "XVII asr", "XIX asr"], "correct": 0},
  {"q": "Jadidchilik harakati asosan qaysi davrga to'g'ri keladi?", "options": ["XIX asr oxiri – XX asr boshi", "XV asr", "XII asr", "XVII asr"], "correct": 0},
  {"q": "Ahmad Yassaviy qaysi asrda yashagan?", "options": ["XII asr", "XVI asr", "XIX asr", "XX asr"], "correct": 0},
  {"q": "Firdavsiyning «Shohnoma»si qaysi asrda yaratilgan?", "options": ["X–XI asr", "XIV asr", "XVI asr", "XVIII asr"], "correct": 0},
  {"q": "Mahmud Koshg'ariyning «Devonu lug'otit turk» asari qaysi asrda yozilgan?", "options": ["XI asr", "XIV asr", "XVII asr", "XIX asr"], "correct": 0},
  {"q": "Shekspir ijodi qaysi davrga to'g'ri keladi?", "options": ["XVI–XVII asr", "XII asr", "XIX asr", "XX asr"], "correct": 0},
  {"q": "Lev Tolstoyning «Urush va tinchlik» romani qaysi asrda yozilgan?", "options": ["XIX asr", "XVII asr", "XX asr", "XV asr"], "correct": 0},
  {"q": "Abu Rayhon Beruniy qaysi asrda yashagan?", "options": ["X–XI asr", "XIII asr", "XVI asr", "XIX asr"], "correct": 0},
  {"q": "Alisher Navoiy qaysi asrda yashab ijod qilgan?", "options": ["XV asr", "XI asr", "XVIII asr", "XX asr"], "correct": 0},
  {"q": "Ahmad Yugnakiy «Hibat ul-haqoyiq» asarini qaysi asrda yozgan?", "options": ["XII asr oxiri — XIII asr boshi", "XV asr", "IX asr", "XVIII asr"], "correct": 0},
  {"q": "Xorazmiy «Muhabbatnoma» dostonini qaysi asrda yaratgan?", "options": ["XIV asr (1353-yil)", "XII asr", "XVI asr", "X asr"], "correct": 0},
  {"q": "Sayfi Saroyi «Gulistoni bit-turkiy» asarini qaysi asrda yozgan?", "options": ["XIV asr (1391-yil)", "XI asr", "XV asr", "XVII asr"], "correct": 0},
  {"q": "Rabg'uziy «Qisasi Rabg'uziy» asarini qaysi asrda bitgan?", "options": ["XIV asr boshi (1309–1310)", "XI asr", "XVI asr", "IX asr"], "correct": 0},
  {"q": "Husayn Boyqaro Hirot taxtida qaysi yillarda hukmronlik qilgan?", "options": ["1469 – 1506-yillar", "1400 – 1430-yillar", "1530 – 1560-yillar", "1370 – 1400-yillar"], "correct": 0},
  {"q": "Muhammad Solih «Shayboniynoma» dostonini qaysi asrda yaratgan?", "options": ["XVI asr boshi", "XIV asr", "XVIII asr", "XII asr"], "correct": 0},
  {"q": "Turdi Farog'iy Buxoroda qaysi asrda yashab ijod qilgan?", "options": ["XVII asr", "XV asr", "XIX asr", "XIII asr"], "correct": 0},
  {"q": "Boborahim Mashrab qaysi asrlarda yashagan olovnafas shoir?", "options": ["XVII asr oxiri — XVIII asr boshi (1640–1711)", "XV asr", "XII asr", "XX asr"], "correct": 0},
  {"q": "Nodirabegim va Uvaysiy Qo'qon adabiy muhitida qaysi asrda ijod etgan?", "options": ["XIX asr birinchi yarmi", "XVII asr", "XV asr", "XX asr"], "correct": 0},
  {"q": "Munis va Ogahiy Xiva xonligida qaysi asrda yashagan?", "options": ["XIX asr", "XVI asr", "XIV asr", "XI asr"], "correct": 0},
  {"q": "Muqimiy va Furqat Qo'qonda qaysi davrda ijod qilgan?", "options": ["XIX asr oxiri — XX asr boshlari", "XVIII asr", "XVI asr", "XVII asr"], "correct": 0},
  {"q": "Mahmudxo'ja Behbudiy «Padarkush» dramasini nechanchi yilda yozgan?", "options": ["1911-yil", "1875-yil", "1930-yil", "1900-yil"], "correct": 0},
  {"q": "Fitrat «Munozara» asarini nechanchi yilda chop ettirgan?", "options": ["1909-yil", "1895-yil", "1924-yil", "1935-yil"], "correct": 0},
  {"q": "Oybek «Qutlug' qon» romanida qaysi yilgi qo'zg'olonni tasvirlagan?", "options": ["1916-yilgi xalq harakati", "1905-yil", "1930-yil", "1890-yil"], "correct": 0},
  {"q": "G'afur G'ulom «Shum bola» qissasida qaysi davrni tasvirlaydi?", "options": ["XX asr boshi (Birinchi jahon urushi arafasi)", "1945-yil", "XIX asr o'rtalari", "1960-yillar"], "correct": 0},
  {"q": "Said Ahmad «Ufq» trilogiyasida qaysi yillarni qamrab olgan?", "options": ["1938 – 1950-yillar", "1917 – 1920-yillar", "1970 – 1980-yillar", "1900 – 1910-yillar"], "correct": 0},
  {"q": "O'tkir Hoshimov «Ikki eshik orasi»da qaysi 40 yillik davrni tasvirlaydi?", "options": ["1940-yillardan 1980-yillargacha", "1900 – 1940-yillar", "1980 – 2000-yillar", "XIX asr oxiri"], "correct": 0},
  {"q": "Tohir Malik «Shaytanat» asari qaysi davr voqealarini aks ettiradi?", "options": ["XX asrning 80–90-yillari", "1950-yillar", "1920-yillar", "2010-yillar"], "correct": 0},
  {"q": "Gyote «Faust» tragediyasini qaysi davrda yakunlagan?", "options": ["XVIII asr oxiri — XIX asr boshi (1832-yil)", "XVI asr", "XVII asr", "XX asr"], "correct": 0},
  {"q": "Pushkin «Yevgeniy Onegin» asarini qaysi asrda yozgan?", "options": ["XIX asr 20–30-yillari", "XVIII asr", "XVII asr", "XX asr"], "correct": 0},
  {"q": "Gyugo «Parij Bibi Maryam ibodatxonasi»da qaysi asr Parijini tasvirlagan?", "options": ["XV asr (1482-yil)", "XIX asr", "XII asr", "XVIII asr"], "correct": 0},
  {"q": "Dostoyevskiy «Jinoyat va jazo» romanini qaysi yilda chop ettirgan?", "options": ["1866-yil (XIX asr)", "1890-yil", "1840-yil", "1905-yil"], "correct": 0},
  {"q": "Xeminguey «Chol va dengiz» qissasini qaysi yilda yaratgan?", "options": ["1952-yil", "1925-yil", "1970-yil", "1940-yil"], "correct": 0},
  {"q": "Aytmatov «Jamila» qissasini nechanchi yilda yozgan?", "options": ["1958-yil", "1975-yil", "1945-yil", "1990-yil"], "correct": 0},
  {"q": "Markes «Yuz yillik yolg'izlik» asarini nechanchi yilda chop ettirgan?", "options": ["1967-yil", "1950-yil", "1985-yil", "1930-yil"], "correct": 0},
  {"q": "Ekzyuperi «Kichkina Shahzoda» asarini qaysi yillarda yozgan?", "options": ["1942 – 1943-yillar", "1920-yil", "1955-yil", "1935-yil"], "correct": 0},
  {"q": "Xorazm Ma'mun akademiyasi qaysi davrda gullab-yashnagan?", "options": ["X asr oxiri — XI asr boshlari (1004–1017)", "XIV asr", "VIII asr", "XV asr"], "correct": 0},
  {"q": "Jaloliddin Manguberdi qaysi yillarda mo'g'ullarga qarshi kurashgan?", "options": ["1220 – 1231-yillar", "1150 – 1160-yillar", "1300 – 1315-yillar", "1370 – 1385-yillar"], "correct": 0},
  {"q": "O'zbekiston Milliy universiteti dastlab nechanchi yilda tashkil topgan?", "options": ["1918 – 1920-yillar", "1905-yil", "1945-yil", "1935-yil"], "correct": 0},
  {"q": "O'zbekiston Fanlar akademiyasi nechanchi yilda tashkil topgan?", "options": ["1943-yil", "1925-yil", "1960-yil", "1930-yil"], "correct": 0},
  {"q": "Alisher Navoiy tavallud topgan yil qaysi?", "options": ["1441-yil 9-fevral", "1336-yil", "1483-yil", "1501-yil"], "correct": 0},
  {"q": "Zahiriddin Muhammad Bobur tavallud topgan yil qaysi?", "options": ["1483-yil 14-fevral", "1441-yil", "1370-yil", "1530-yil"], "correct": 0},
  {"q": "Amir Temur tavallud topgan yil qaysi?", "options": ["1336-yil 9-aprel", "1405-yil", "1220-yil", "1450-yil"], "correct": 0},
  {"q": "Mirzo Ulug'bek tavallud topgan yil qaysi?", "options": ["1394-yil 22-mart", "1449-yil", "1405-yil", "1336-yil"], "correct": 0},
  {"q": "Abdulla Qodiriy qaysi yilda tavallud topgan?", "options": ["1894-yil (Toshkent)", "1905-yil", "1875-yil", "1920-yil"], "correct": 0},
  {"q": "Abdulhamid Cho'lpon qaysi yilda tavallud topgan?", "options": ["1897-yil (Andijon)", "1880-yil", "1910-yil", "1925-yil"], "correct": 0},
]
