# -*- coding: utf-8 -*-
"""Bilim O'yini: Impostor (Kim yolg'onchi)"""

QUIZ_IMPOSTOR_QUESTIONS = [
    {"q": "Qaysi biri Abdulla Qodiriy asari EMAS?", "options": ["O'tkan kunlar", "Mehrobdan chayon", "Obid ketmon", "Kecha va kunduz"], "correct": 3},
    {"q": "Qaysi biri Alisher Navoiy «Xamsa»siga kirmaydi?", "options": ["Hayrat ul-abror", "Farhod va Shirin", "Layli va Majnun", "Muhabbatnoma"], "correct": 3},
    {"q": "Qaysi biri Oybek qalamiga mansub EMAS?", "options": ["Navoiy", "Qutlug' qon", "Oltin vodiydan shabadalar", "Sarob"], "correct": 3},
    {"q": "Qaysi biri Said Ahmad asari EMAS?", "options": ["Kelinlar qo'zg'oloni", "Ufq", "Jimjitlik", "Dunyoning ishlari"], "correct": 3},
    {"q": "Qaysi biri O'tkir Hoshimov asari EMAS?", "options": ["Dunyoning ishlari", "Ikki eshik orasi", "Bahor qaytmaydi", "Shum bola"], "correct": 3},
    {"q": "Qaysi biri Lev Tolstoy asari EMAS?", "options": ["Urush va tinchlik", "Anna Karenina", "Tirilish", "Jinoyat va jazo"], "correct": 3},
    {"q": "Qaysi biri Fyodor Dostoyevskiy asari EMAS?", "options": ["Jinoyat va jazo", "Telba", "Aka-uka Karamazovlar", "Ota va bolalar"], "correct": 3},
    {"q": "Qaysi biri Chingiz Aytmatov asari EMAS?", "options": ["Oq kema", "Asrga tatigulik kun", "Qiyomat", "Otamdan qolgan dalalar"], "correct": 3},
    {"q": "Qaysi biri Viktor Gyugo asari EMAS?", "options": ["Notr-Dam ibodatxonasi", "Sefillar", "Kulayotgan odam", "Graf Monte-Kristo"], "correct": 3},
    {"q": "Qaysi biri Aleksandr Dyuma asari EMAS?", "options": ["Uch mushketyor", "Graf Monte-Kristo", "Yigirma yildan so'ng", "Qizil va qora"], "correct": 3},
    {"q": "Qaysi biri Shekspir tragediyasi EMAS?", "options": ["Hamlet", "Otello", "Qirol Lir", "Faust"], "correct": 3},
    {"q": "Qaysi biri Jorj Oruell asari EMAS?", "options": ["1984", "Hayvonlar fermasi", "Kataloniyaga ehtirom", "Farengeyt 451"], "correct": 3},
    {"q": "Qaysi biri Tog'ay Murod asari EMAS?", "options": ["Yulduzlar mangu yonadi", "Ot kishnagan oqshom", "Otamdan qolgan dalalar", "Ulug'bek xazinasi"], "correct": 3},
    {"q": "Qaysi biri Odil Yoqubov asari EMAS?", "options": ["Ulug'bek xazinasi", "Diyonat", "Ko'hna dunyo", "Yulduzli tunlar"], "correct": 3},
    {"q": "Qaysi biri Pirimqul Qodirov asari EMAS?", "options": ["Yulduzli tunlar", "Avlodlar dovoni", "Uch ildiz", "Jimjitlik"], "correct": 3},
]

# ── 2026-08 qo'shimcha: soxtasini top ────────────────────────────────────
QUIZ_IMPOSTOR_QUESTIONS += [
  {"q": "Qaysi biri Alisher Navoiy asari EMAS?", "options": ["Xamsa", "Lison ut-tayr", "Mahbub ul-qulub", "Boburnoma"], "correct": 3},
  {"q": "Qaysi biri Cho'lpon qalamiga mansub EMAS?", "options": ["Kecha va kunduz", "Buloqlar", "Uyg'onish", "Shum bola"], "correct": 3},
  {"q": "Qaysi biri Ibn Sino asari EMAS?", "options": ["Tib qonunlari", "Kitob ash-shifo", "Donishnoma", "Devonu lug'otit turk"], "correct": 3},
  {"q": "Qaysi biri xalq dostoni EMAS?", "options": ["Alpomish", "Go'ro'g'li", "Kuntug'mish", "Sarob"], "correct": 3},
  {"q": "Qaysi biri Bobur asari EMAS?", "options": ["Boburnoma", "Mubayyin", "Aruz risolasi", "Xamsa"], "correct": 3},
  {"q": "Qaysi shaxs astronom EMAS?", "options": ["Mirzo Ulug'bek", "Ahmad Farg'oniy", "Abu Rayhon Beruniy", "Imom Buxoriy"], "correct": 3},
  {"q": "Qaysi biri tasavvuf allomasi EMAS?", "options": ["Bahouddin Naqshband", "Ahmad Yassaviy", "Najmiddin Kubro", "Al-Xorazmiy"], "correct": 3},
  {"q": "Qaysi biri rus adabiyoti vakili EMAS?", "options": ["Lev Tolstoy", "Fyodor Dostoyevskiy", "Anton Chexov", "Viktor Gyugo"], "correct": 3},
  {"q": "Qaysi biri «O'tkan kunlar» qahramoni EMAS?", "options": ["Otabek", "Kumushbibi", "Homid", "Ra'no"], "correct": 3},
  {"q": "Qaysi biri she'riy janr EMAS?", "options": ["G'azal", "Ruboiy", "Muxammas", "Roman"], "correct": 3},
  {"q": "Qaysi biri jadid namoyandasi EMAS?", "options": ["Mahmudxo'ja Behbudiy", "Abdurauf Fitrat", "Abdulla Avloniy", "Alisher Navoiy"], "correct": 3},
  {"q": "Qaysi biri hadis to'plami EMAS?", "options": ["Sahih al-Buxoriy", "Sunani Termiziy", "Sunani Abu Dovud", "Qutadg'u bilig"], "correct": 3},
  {"q": "Qaysi biri fors-tojik adabiyoti vakili EMAS?", "options": ["Firdavsiy", "Sa'diy Sheroziy", "Hofiz Sheroziy", "Mahmud Koshg'ariy"], "correct": 3},
  {"q": "Qaysi biri Navoiy «Xamsa»siga kirmaydi?", "options": ["Hayrat ul-abror", "Farhod va Shirin", "Sab'ai sayyor", "Mantiq ut-tayr"], "correct": 3},
  {"q": "Qaysi biri O'tkir Hoshimov asari EMAS?", "options": ["Ikki eshik orasi", "Dunyoning ishlari", "Tushda kechgan umrlar", "Mehrobdan chayon"], "correct": 3},
  {"q": "Qaysi biri Erkin Vohidov asari EMAS?", "options": ["O'zbegim", "Ruhlar isyoni", "Nido", "Jannatga yo'l"], "correct": 3},
  {"q": "Qaysi biri Abdulla Oripov asari EMAS?", "options": ["O'zbekiston", "Jannatga yo'l", "Hakim va ajal", "Ruhlar isyoni"], "correct": 3},
  {"q": "Qaysi biri Tohir Malik asari EMAS?", "options": ["Shaytanat", "Odamiylik mulki", "Murdalar gapirmaydilar", "Chinor"], "correct": 3},
  {"q": "Qaysi biri Asqad Muxtor asari EMAS?", "options": ["Chinor", "Bo'ronlarda bordek halovat", "Tug'ilish", "Otamdan qolgan dalalar"], "correct": 3},
  {"q": "Qaysi biri Xudoyberdi To'xtaboyev asari EMAS?", "options": ["Sariq devni minib", "Sehrli qalpoqcha", "Shirin qovunlar mamlakati", "Kelinlar qo'zg'oloni"], "correct": 3},
  {"q": "Qaysi biri G'afur G'ulom asari EMAS?", "options": ["Shum bola", "Sen yetim emassan", "Yodgor", "O'g'ri"], "correct": 3},
  {"q": "Qaysi biri Abdulla Qahhor hikoyasi EMAS?", "options": ["O'g'ri", "Anor", "Bemor", "Shum bola"], "correct": 3},
  {"q": "Qaysi biri Shukur Xolmirzayev asari EMAS?", "options": ["O'n sakkizga kirmagan kim bor", "Bodom qishda gulladi", "O'zbek xarakteri", "Shaytanat"], "correct": 3},
  {"q": "Qaysi biri Murod Muhammad Do'st asari EMAS?", "options": ["Lolazor", "Galatepaga qaytish", "Dashtu dalalarda", "Ikki eshik orasi"], "correct": 3},
  {"q": "Qaysi biri Anvar Obidjon asari EMAS?", "options": ["Meshpolvonning janglari", "O'g'irlangan pahlavon", "Alamazon va uning piyodalari", "Sariq devni minib"], "correct": 3},
  {"q": "Qaysi biri Zulfiyaxonim asari EMAS?", "options": ["Bahor keldi seni so'roqlab", "Kuylarim sizga", "Hulkar", "O'zbegim"], "correct": 3},
  {"q": "Qaysi biri Hamid Olimjon asari EMAS?", "options": ["Zaynab va Omon", "Semurg'", "Muqanna", "Lolazor"], "correct": 3},
  {"q": "Qaysi biri Usmon Nosir asari EMAS?", "options": ["Yurak", "Nil va Rim", "Monolog", "Qutlug' qon"], "correct": 3},
  {"q": "Qaysi biri Sa'diy Sheroziy asari EMAS?", "options": ["Guliston", "Bo'ston", "Pandnoma", "Masnaviy"], "correct": 3},
  {"q": "Qaysi biri Mavlono Rumiy asari EMAS?", "options": ["Masnaviyi Ma'naviy", "Fihi mo fihi", "Devoni Shams Tabriziy", "Guliston"], "correct": 3},
  {"q": "Qaysi biri Imom G'azzoliy asari EMAS?", "options": ["Ihyou ulumiddin", "Kimyoi saodat", "Mukoshafat ul-qulub", "Tib qonunlari"], "correct": 3},
  {"q": "Qaysi biri Yusuf Xos Hojib asari EMAS?", "options": ["Qutadg'u bilig", "Doston", "Hikmatlar", "Xamsa"], "correct": 3},
  {"q": "Qaysi biri Ahmad Yugnakiy asari EMAS?", "options": ["Hibat ul-haqoyiq", "Hikmatlar", "Axloqiy doston", "Boburnoma"], "correct": 3},
  {"q": "Qaysi biri Mahmud Qoshg'ariy asari EMAS?", "options": ["Devonu lug'otit turk", "Turkiy xaritalar", "Tilshunoslik lug'ati", "Qisasi Rabg'uziy"], "correct": 3},
  {"q": "Qaysi biri Rabg'uziy asari EMAS?", "options": ["Qisasi Rabg'uziy", "Payg'ambarlar qissasi", "Turkiy nasr", "Hayrat ul-abror"], "correct": 3},
  {"q": "Qaysi biri Shekspir komediyasi EMAS?", "options": ["O'n ikkinchi kecha", "Venetsiya savdogari", "Yoqqanicha", "Gamlet"], "correct": 3},
  {"q": "Qaysi biri Artur Konan Doyl asari EMAS?", "options": ["Baskervillar iti", "To'rtlar belgisi", "Qizil tushdagi etyud", "Sharqiy ekspressda qotillik"], "correct": 3},
  {"q": "Qaysi biri Agata Kristi asari EMAS?", "options": ["Sharqiy ekspressda qotillik", "O'nta negr bolasi", "Nildagi qotillik", "Baskervillar iti"], "correct": 3},
  {"q": "Qaysi biri Ernest Xeminguey asari EMAS?", "options": ["Chol va dengiz", "Alvido, qurol!", "Qo'ng'iroq kimni chorlaydi", "Gulliverning sayohatlari"], "correct": 3},
  {"q": "Qaysi biri Gabriel Garsia Markes asari EMAS?", "options": ["Yuz yillik yolg'izlik", "Oshkora qotillik qissasi", "Patriarxning kuzi", "Alkimyogar"], "correct": 3},
  {"q": "Qaysi biri Paolo Koelo asari EMAS?", "options": ["Alkimyogar", "Veronika o'lishga qaror qildi", "Zohir", "Begona"], "correct": 3},
  {"q": "Qaysi biri Alber Kamyu asari EMAS?", "options": ["Begona", "Vabo", "Sizif haqida afsona", "1984"], "correct": 3},
  {"q": "Qaysi biri Frants Kafka asari EMAS?", "options": ["Evrilish", "Jarayon", "Qasr", "Faust"], "correct": 3},
  {"q": "Qaysi biri Daniel Defo asari EMAS?", "options": ["Robinzon Kruzo", "Moll Flenders", "Polkovnik Jek", "Gulliverning sayohatlari"], "correct": 3},
  {"q": "Qaysi biri Jonatan Svift asari EMAS?", "options": ["Gulliverning sayohatlari", "Bochna ertagi", "Kitoblar jangi", "Robinzon Kruzo"], "correct": 3},
  {"q": "Qaysi biri Robert Stivenson asari EMAS?", "options": ["Xazinalar oroli", "Qora o'q", "Doktor Jekil va mister Xayd", "Tom Soyer"], "correct": 3},
  {"q": "Qaysi biri Mark Tven asari EMAS?", "options": ["Tom Soyerning sarguzashtlari", "Geklberri Finn", "Shahzoda va gado", "Oliver Tvist"], "correct": 3},
  {"q": "Qaysi biri Charlz Dikkens asari EMAS?", "options": ["Oliver Tvist", "Devid Kopperfild", "Buyuk umidlar", "Don Kixot"], "correct": 3},
]
