# -*- coding: utf-8 -*-
"""Adabiy Jumboq & Topishmoqlar (Riddle Box) — mumtoz, xalq va jahon adabiyoti jumboqlari."""

RIDDLEBOX_QUESTIONS = [
    {"q": "«Qora tovuq qor ustida don terar» — bu qadimiy adabiy topishmoqda nima nazarda tutilgan?", "options": ["Qalam va oq qog'oz", "Qor yog'ishi", "Qarg'a", "Tugma"], "correct": 0, "hint": "Yozuv quroli va sahifa"},
    {"q": "«Tilsiz, zabonsiz so'zlar, dunyo sirin ochib berar» — bu qaysi xazina?", "options": ["Kitob", "Ko'zgu", "Radio", "Maktub"], "correct": 0, "hint": "Insonning eng yaqin ma'naviy do'sti"},
    {"q": "«O'zi bitta, ko'zi mingta, har ko'zida bir dunyo» — adabiyotda bu nima?", "options": ["Kutubxona / Javon", "Chiroq", "To'r", "Yulduzlar"], "correct": 0, "hint": "Minglab asarlar saqlanadigan maskan"},
    {"q": "Alisher Navoiy «Lison ut-tayr»da 30 qush izlagan sirli shoh kim edi?", "options": ["Simurg' (qushlarning o'z aksi)", "Humoyun", "Sulaymon", "Iskandar"], "correct": 0, "hint": "«Si-murg'» 30 qush demakdir"},
    {"q": "«Kunduzi yashirinadi, kechasi yonadi, donolarga yo'l ko'rsatadi»:", "options": ["Ilm va hikmat nuri", "Oy", "Mash'ala", "Sham"], "correct": 0, "hint": "Zulmatni yorituvchi tafakkur"},
    {"q": "«Boshi tog'da, oyog'i bog'da, asrlar o'tsa ham oqadi daryodek»:", "options": ["Mumtoz she'riyat / G'azal", "Bulut", "Sharshara", "Soyabosh"], "correct": 0, "hint": "Bobolardan qolgan so'z san'ati"},
    {"q": "«Daryo emas — oqadi, daraxt emas — yaprog'i bor, kiyim emas — tikilgan»:", "options": ["Qo'lyozma kitob", "Gilam", "Parda", "Bayroq"], "correct": 0, "hint": "Varaqlari bor, muqovalangan"},
    {"q": "«O'zi qora, qoni oq, yurganda qoldirar iz»:", "options": ["Bo'r (doska va yozuv)", "Siyohdon", "Tosh", "Ko'mir"], "correct": 0, "hint": "Maktabda dars berish vositasi"},
    {"q": "«Qanoti yo'q — uchadi, tili yo'q — chaqadi, pichoqsiz qalbni tiladi»:", "options": ["Zaharli / Achchiq so'z", "Chayon", "O'q", "Shamol"], "correct": 0, "hint": "Inson tilidan chiquvchi narsa"},
    {"q": "«Urib bo'lmas, so'yib bo'lmas, dasturxonga qo'yib bo'lmas, ammo hammaga kerak»:", "options": ["Aql va bilim", "Non", "Tuz", "Suv"], "correct": 0, "hint": "Insonning eng buyuk boyligi"},
    {"q": "«Ichida mingtacha dono yotar jim, kim ochsa so'zlay boshlar birma-bir»:", "options": ["Kutubxona fondi", "Qabr", "Shahar", "Sandıq"], "correct": 0, "hint": "Donishmandlar asarlari to'plami"},
    {"q": "«O'zi yemaydi, elni to'ydiradi, o'zi kiyinmaydi, elni kiyintiradi»:", "options": ["Qalam / Muallif mehnati", "Oshpaz", "Tikuvchi", "Daraxt"], "correct": 0, "hint": "Ma'naviy ozuqa beruvchi ijod"},
    {"q": "«G'or ichida qizil ayg'ir kishnar» — qadimiy topishmoqda nima ifodalangan?", "options": ["Til (og'izdagi so'zlovchi a'zo)", "Olov", "Yurak", "Sham"], "correct": 0, "hint": "So'z so'zlovchi til"},
    {"q": "«Qat-qat qatlama, aqli bo'lsa tashlama»:", "options": ["Kitob sahifalari", "Non", "Qatlama patir", "Kiyim"], "correct": 0, "hint": "Har bir varag'ida hikmat bor"},
    {"q": "«Ko'zga ko'rinmas, qo'lga tushmas, ketsa qaytib kelmas»:", "options": ["O'tgan umr / Vaqt", "Shamol", "Tutun", "Soyabon"], "correct": 0, "hint": "Eng qadrli fursat"},
    {"q": "«Oltin emas — bahosi yo'q, qush emas — qanoti bor, uchsa yetib bo'lmas»:", "options": ["Xayol va tafakkur", "Burgut", "Samolyot", "Shuhrat"], "correct": 0, "hint": "Inson ongidagi uchqur kuch"},
    {"q": "«O'zi kichik, qudrati zo'r, dunyoni ag'dar-to'ntar qilar»:", "options": ["Fikr / G'oya", "Atom", "Chumoli", "Tosh"], "correct": 0, "hint": "Insoniyat tarixini o'zgartiruvchi kuch"},
    {"q": "«Bir ko'rpa bor — butun olamni yopadi, faqat dengizni yopolmaydi»:", "options": ["Qor (yer yuzini qoplovchi)", "Osmon", "Tun", "Bulut"], "correct": 0, "hint": "Qish faslida yog'uvchi qor"},
    {"q": "«Eshigi yo'q, tuynugi yo'q, ichida to'la qizil yoqut»:", "options": ["Anor (adabiyotda qalb ramzi)", "Qovun", "Tarvuz", "Sandıq"], "correct": 0, "hint": "Mumtoz adabiyotdagi donalar ramzi"},
    {"q": "«Kunduzi yig'laydi, kechasi quriydi, shamol tegsa o'ladi»:", "options": ["Sham (ishiq ramzi)", "Muz", "Shudring", "Buloq"], "correct": 0, "hint": "Yonib eruvchi parvona do'sti"},
    {"q": "«Besh og'a-ini bir quduqqa tosh otar» — nima bu?", "options": ["Besh barmoq bilan ovqat yeyish / Yozish", "Yulduzlar", "Toshlar", "O'qlar"], "correct": 0, "hint": "Qo'l harakati"},
    {"q": "«Bir daraxtda o'n ikki shox, har shoxida o'ttiz yaproq»:", "options": ["Yil, 12 oy va 30 kun", "Hafta kunlari", "Kitob jildlari", "Yulduzlar"], "correct": 0, "hint": "Taqvim va vaqt o'lchovi"},
    {"q": "«O'tirsa — o'rni yo'q, yotsa — bo'yi yo'q, quvsa — yetib bo'lmas»:", "options": ["Soya", "Shamol", "Suv", "Tutun"], "correct": 0, "hint": "Quyosh nuri tushganda paydo bo'ladi"},
    {"q": "«Oq dalada qora qo'ylar o'tlaydi, cho'poni — chaqqon qalam»:", "options": ["Qog'ozdagi harflar / Yozuv", "Paxtazor", "Kutubxona", "Maktab"], "correct": 0, "hint": "Yozilgan matn"},
    {"q": "«Yurganda oyog'i yo'q, chaqqanda tishi yo'q, yiqitsa turg'izib bo'lmas»:", "options": ["Suv toshqini / Fitna", "Ilon", "Daryo", "Qor"], "correct": 0, "hint": "Zamon fitnasi"},
    {"q": "«G'ishtsiz qurilgan qal'a, qurolsiz olingan shahar» — bu qaysi g'alaba?", "options": ["Ilm va ma'rifat bilan qalbni zabt etish", "Koshona", "Toshkent", "Buxoro"], "correct": 0, "hint": "So'z va axloq kuchi"},
    {"q": "«Tog'dan tushar dupur-dupur, oyog'i bor — izi yo'q»:", "options": ["Sel / Yomg'ir suvi", "Ot", "Bug'u", "Tosh"], "correct": 0, "hint": "Tabiat hodisasi"},
    {"q": "«Ko'kka boqsam — ko'zim to'yar, yerga boqsam — rizqim to'yar»:", "options": ["Quyosh va Ona Yer", "Yulduz", "Oy", "Dala"], "correct": 0, "hint": "Hayot manbalari"},
    {"q": "«O'zi ko'r, qulog'i kar, lekin hamma sirni saqlar»:", "options": ["Qulf va kalit", "Devor", "Ko'zgu", "Sandıq"], "correct": 0, "hint": "Eshikni mustahkamlovchi vosita"},
    {"q": "«Odam emas — gapiradi, qush emas — sayraydi, tinglagan rohat olar»:", "options": ["Dutor / Tanbur ohangi", "Daftar", "Radio", "Bulbul"], "correct": 0, "hint": "Mumtoz milliy sozimiz"},
    {"q": "«Oq sandig'im ochildi, ichidan dur sochildi»:", "options": ["Tong otishi va quyosh nuri", "Qor", "Paxta", "Bug'doy"], "correct": 0, "hint": "Kun boshlanishi"},
    {"q": "«Bir xumcha shirin asal, unga yetmas hech amal»:", "options": ["Ona suti / Mehr", "Asalari uyasi", "Qand", "Shakar"], "correct": 0, "hint": "Dunyoga kelgandagi ilk ne'mat"},
    {"q": "«Bitta tandirda yuzta kulcha yopilgan»:", "options": ["Kungaboqar urug'lari", "Anor", "Yong'oq", "Bug'doy"], "correct": 0, "hint": "Oftobparast guli"},
    {"q": "«Uzoqdan qarasang — oppoq tog', yaqiniga borsang — paxtazor bog'»:", "options": ["Chigitdan ungan paxta xirmoni", "Qorli tog'", "Bulut", "Muzlik"], "correct": 0, "hint": "O'zbekiston oq oltini"},
    {"q": "«Kechasi ko'kda yurar bir dasta gul, kunduzi yo'qolar birma-bir butkul»:", "options": ["Yulduzlar turkumi", "Kapalaklar", "Gullar", "Chiroqlar"], "correct": 0, "hint": "Tungi osmon ziynati"},
    {"q": "«Bir ko'zani sindirib bo'lmas, ichidagi suvni to'kib bo'lmas»:", "options": ["Inson kallasi va miyasi", "Ko'zgu", "Muz", "Buloq"], "correct": 0, "hint": "Tafakkur manbai"},
    {"q": "«Yozda kiyinar yashil to'n, qishda qolar yalang'och butun»:", "options": ["Barg to'kuvchi daraxt", "Maysa", "Tog'", "Bog'bon"], "correct": 0, "hint": "Fasllar almashuvi"},
    {"q": "«Tilsiz so'rar, jonsiz bilar, har muddaoni ado qilar»:", "options": ["Tarozi / Adolat mezonlari", "Qalam", "Soat", "Kitob"], "correct": 0, "hint": "Haq va adolat o'lchovi"},
    {"q": "«Boshi taroq, dumi o'roq, erta turib qichqirar»:", "options": ["Xo'roz (uyg'onish ramzi)", "Qarg'a", "Bulbul", "Turna"], "correct": 0, "hint": "Tonggi saharda uyg'otuvchi qush"},
    {"q": "«Oyoqsiz yurar, qanotsiz uchar, qorong'i tunda yo'l ochib o'tar»:", "options": ["Oy nuri", "Shamol", "Yulduz", "Chiroq"], "correct": 0, "hint": "Tungi yo'lovchiga yo'ldosh"},
    {"q": "«Yer tagida oltin qoziq, qishin-yozin elga oziq»:", "options": ["Sabzi / Ildizmevalar", "Oltin koni", "Sholg'om", "Kartoshka"], "correct": 0, "hint": "Palovning asosiy masallig'i"},
    {"q": "«O'zi bitta, shoxi to'rtta, doim yuk ko'tarar»:", "options": ["Yag'och xontaxta / Stol", "Bug'u", "Daraxt", "Ot"], "correct": 0, "hint": "Uy jihozi"},
    {"q": "«Soqoli bor — aqli yo'q, shoxi bor — kuchi yo'q»:", "options": ["Echki", "Taka", "Qo'chqor", "Kiyik"], "correct": 0, "hint": "Uy hayvoni"},
    {"q": "«Qanoti bor — patlari yo'q, uchar ammo qush emas»:", "options": ["Ko'rshapalak", "Kapalak", "Ari", "Ninachi"], "correct": 0, "hint": "Tungi uchar jonivor"},
    {"q": "«Olovda kuymas, suvda cho'kmas, yerga ko'msang chirimas»:", "options": ["Haqiqat / Ezgu nom", "Tosh", "Oltin", "Muz"], "correct": 0, "hint": "Mangu yashaydigan ezgulik"},
    {"q": "«Bir uy bor — ming eshikli, har eshigida bir pashsha»:", "options": ["Asalari uyasi (Mavj)", "Chumolixona", "To'r", "G'or"], "correct": 0, "hint": "Asal tayyorlovchi uya"},
    {"q": "«Egasi minmas, minib chiqqan tushmas» — fano dunyosi jumboqi:", "options": ["Tobut / So'nggi yo'l", "Arg'umoq", "Kema", "Aravalar"], "correct": 0, "hint": "Oxirat safari vositasi"},
    {"q": "«Tog'dan kelar toyloq, terisi yo'q maymoq»:", "options": ["Tosh / Muz parchasi", "Ayıq", "Qor", "Sel"], "correct": 0, "hint": "Tog'dan qulagan tosh"},
    {"q": "«Qo'lsiz, oyoqsiz eshik ochar, butun olamni kezib chiqar»:", "options": ["Shamol", "Suv", "Quyosh", "Soya"], "correct": 0, "hint": "Esayotgan shabboda"},
    {"q": "«Bir qop un, ichida bitta ustun»:", "options": ["Jiyda mevasi", "Yong'oq", "Pista", "Bodom"], "correct": 0, "hint": "Daraxtda pishadigan shirin meva"},
    {"q": "«O'zi qizil, kiyimi yashil, ichi to'la qora ko'z»:", "options": ["Tarvuz urug'lari", "Anor", "Olcha", "Qulupnay"], "correct": 0, "hint": "Yozgi poliz ekini"},
    {"q": "«Urib bo'lmas, so'kib bo'lmas, o'zidan boshqa do'sti yo'q»:", "options": ["Vijdon", "Yurak", "Aql", "Sabr"], "correct": 0, "hint": "Inson ichki tarozisi"},
    {"q": "«O'zi shirin, tikanli to'ni bor, terib olsang quvonch solar»:", "options": ["Malina / Maymunjon", "Atirgul", "Bodring", "Do'lana"], "correct": 0, "hint": "O'rmon rezavori"},
    {"q": "«Ko'zga ko'rinsa — quvontirar, qo'lga olsang — eritirar»:", "options": ["Qor parchasi", "Muzqaymoq", "Muz", "Shakar"], "correct": 0, "hint": "Kaftga qo'ngan qor uchquni"},
    {"q": "«Bir onadan yuz bola, hammasi boshiga qalpoq kiygan»:", "options": ["Gugurt cho'plari", "Mixlar", "Qalamlar", "Ignilar"], "correct": 0, "hint": "Olov yoqish qutisi"},
    {"q": "«Yurganda tinmas, uxlaganda to'xtamas, to'xtasa hayot qolmas»:", "options": ["Yurak urishi", "Daryo", "Shamol", "Soat"], "correct": 0, "hint": "Tiriklik belgisi bo'lgan a'zo"},
    {"q": "«O'zi temir, joni yo'q, yurganda qo'rqmas zarracha»:", "options": ["Poyezd / Temir yo'l", "Kema", "Mashina", "Velosiped"], "correct": 0, "hint": "Po'lat izlar ustidagi ulov"},
    {"q": "«O'tga solsang — yonmaydi, suvga solsang — oqmaydi, ko'z bilan ko'rib bo'lmaydi»:", "options": ["Ovoz / Sadolar", "Havo", "Fikr", "Niyat"], "correct": 0, "hint": "Havodagi jarangdor to'lqin"},
    {"q": "«Ichida bog'i bor, bog'ida tog'i bor, bir qarasang dunyo namoyon»:", "options": ["Xarita / Atlas kitobi", "Ko'zgu", "Rasm", "Kino"], "correct": 0, "hint": "Geografik tasvir kitobi"},
    {"q": "«Kechasi charog'on, kunduzi biyobon, har dardi borga malham bo'lgan maskan»:", "options": ["Masjid va xonaqoh", "Bozor", "Saroy", "Qasr"], "correct": 0, "hint": "Zikr va ibodat uyi"},
    {"q": "«O'zi jimjit, siri ko'p, do'st tutsang xiyonat qilmas»:", "options": ["Yaxshi kitob", "Daraxt", "Ko'l", "Qalam"], "correct": 0, "hint": "Eng vafodor ma'naviy sirdosh"}
]
