# -*- coding: utf-8 -*-
"""Tezkor Terish (Speed Type) — mashhur satrlar va aforizmlarni tezkor o'qib muallifini topish."""

SPEEDTYPE_QUESTIONS = [
    {"quote": "Odamiy ersang demagil odami, Onikim yo'q xalq g'amidin g'ami.", "speaker": "Alisher Navoiy", "context": "«Hayrat ul-abror»", "distractors": ["Bobur", "Lutfiy", "Jomiy"]},
    {"quote": "Modomiki biz yangi davrga oyoq qo'ydik, bas, biz har bir yo'sunda yangilikka ergashmog'imiz darkor.", "speaker": "Abdulla Qodiriy", "context": "«O'tkan kunlar»", "distractors": ["Cho'lpon", "Fitrat", "Behbudiy"]},
    {"quote": "Ko'ngil, sen munchalar nega kishanlar bilan do'st bo'lding?", "speaker": "Abdulhamid Cho'lpon", "context": "«Ko'ngil» she'ri", "distractors": ["Usmon Nosir", "Fitrat", "Oybek"]},
    {"quote": "Haq berilmas, haq olinur!", "speaker": "Abdurauf Fitrat", "context": "«Chin sevish»", "distractors": ["Behbudiy", "Qodiriy", "Avloniy"]},
    {"quote": "Tarbiya biz uchun yo hayot — yo mamot, yo najot — yo halokat masalasidur.", "speaker": "Abdulla Avloniy", "context": "«Turkiy Guliston»", "distractors": ["Behbudiy", "Hamza", "Munavvarqori"]},
    {"quote": "Dunyoda turmoq uchun dunyoviy fan va ilm lozimdur.", "speaker": "Mahmudxo'ja Behbudiy", "context": "Jadid matbuoti", "distractors": ["Avloniy", "Fitrat", "Munavvarqori"]},
    {"quote": "Har kimki vafo qilsa vafo topqusidur, Har kimki jafo qilsa jafo topqusidur.", "speaker": "Zahiriddin Muhammad Bobur", "context": "Bobur ruboiysi", "distractors": ["Navoiy", "Lutfiy", "Ogahiy"]},
    {"quote": "Tilga ixtiyorsiz — elga e'tiborsiz.", "speaker": "Oybek (Muso Toshmuhammad o'g'li)", "context": "«Navoiy» romani", "distractors": ["G'afur G'ulom", "Abdulla Qahhor", "Asqad Muxtor"]},
    {"quote": "Sen yetim emassan, tinchlan, jigarim!", "speaker": "G'afur G'ulom", "context": "«Sen yetim emassan»", "distractors": ["Hamid Olimjon", "Zulfiya", "Oybek"]},
    {"quote": "Yaxshi otga bir qamchi, yomonga ming qamchi.", "speaker": "O'zbek xalq maqoli", "context": "Hikmatlar xazinasi", "distractors": ["Yassaviy", "Navoiy", "Sa'diy"]},
    {"quote": "Barcha baxtli oilalar bir-biriga o'xshaydi, har bir baxtsiz oila esa o'zicha baxtsizdir.", "speaker": "Lev Tolstoy", "context": "«Anna Karenina»", "distractors": ["Dostoyevskiy", "Chexov", "Turgenev"]},
    {"quote": "Faqat qalb ko'zi bilangina ko'rish mumkin, eng asosiy narsani ko'z bilan ko'rib bo'lmaydi.", "speaker": "Antuan de Sent-Ekzyuperi", "context": "«Kichkina Shahzoda»", "distractors": ["Kamyu", "Gyugo", "Remark"]},
    {"quote": "Go'zallik dunyoni qutqaradi.", "speaker": "Fyodor Dostoyevskiy", "context": "«Idiot» romani", "distractors": ["Tolstoy", "Pushkin", "Gogol"]},
    {"quote": "Bo'lmoq yo bo'lmaslik, mana masala nimada.", "speaker": "Uilyam Shekspir", "context": "«Gamlet» fojiasi", "distractors": ["Gyote", "Bayron", "Dante"]},
    {"quote": "Insonni yanchib tashlash mumkin, ammo uni mag'lub etib bo'lmaydi.", "speaker": "Ernest Xeminguey", "context": "«Chol va dengiz»", "distractors": ["Folkner", "London", "Remarque"]},
    {"quote": "Inson uchun eng qiyini — har kuni inson bo'lib qolmoqdir.", "speaker": "Chingiz Aytmatov", "context": "«Asrga tatigulik kun»", "distractors": ["Rasul Gamzatov", "Mustay Karim", "Abay"]},
    {"quote": "Biz baxtli bo'lamiz xudo xohlasa, Xudo xohlamasa uchrasharmidik?", "speaker": "Muhammad Yusuf", "context": "Sevgi she'riyati", "distractors": ["Abdulla Oripov", "Erkin Vohidov", "Halima Xudoyberdiyeva"]},
    {"quote": "O'zbegim deb keng jahonga ketsin ovozam!", "speaker": "Erkin Vohidov", "context": "«O'zbegim» qasidasi", "distractors": ["Abdulla Oripov", "Muhammad Yusuf", "Omon Matjon"]},
    {"quote": "Yurtim, seni ko'rganlar qanday baxtiyor...", "speaker": "Abdulla Oripov", "context": "«O'zbekiston» qasidasi", "distractors": ["Erkin Vohidov", "Cho'lpon", "Hamid Olimjon"]},
    {"quote": "Bahor keldi seni so'roqlab...", "speaker": "Zulfiyaxonim", "context": "Xotira she'ri", "distractors": ["Nodirabegim", "Uvaysiy", "Halima Xudoyberdiyeva"]},
    {"quote": "Vatan sajdagoh kabi muqaddasdir.", "speaker": "Hamid Olimjon", "context": "«Muqanna»", "distractors": ["G'afur G'ulom", "Oybek", "Usmon Nosir"]},
    {"quote": "Yurak, sen buncha otashsan, Nega buncha shoshilasan?", "speaker": "Usmon Nosir", "context": "«Yurak» she'ri", "distractors": ["Cho'lpon", "Botu", "Hamid Olimjon"]},
    {"quote": "Kelinlar qo'zg'oloni qishloqqa fayz kiritdi.", "speaker": "Said Ahmad", "context": "Komediya pyesasi", "distractors": ["O'tkir Hoshimov", "Abdulla Qahhor", "Shukur Xolmirzayev"]},
    {"quote": "Ona qalbi dunyodagi eng toza buloqdir.", "speaker": "O'tkir Hoshimov", "context": "«Dunyoning ishlari»", "distractors": ["Said Ahmad", "Tohir Malik", "Shukur Xolmirzayev"]},
    {"quote": "Shaytanat ko'chasiga kirgan odam yorug'likni unutadi.", "speaker": "Tohir Malik", "context": "«Shaytanat»", "distractors": ["O'tkir Hoshimov", "Tog'ay Murod", "Asqad Muxtor"]},
    {"quote": "Bu dunyoda o'lib bo'lmaydi, yashamoq kerak!", "speaker": "Tog'ay Murod", "context": "«Bu dunyoda o'lib bo'lmaydi»", "distractors": ["Shukur Xolmirzayev", "Erkin A'zam", "Murod Muhammad Do'st"]},
    {"quote": "Chinor qancha keksa bo'lsa, ildizi shuncha chuqur ketadi.", "speaker": "Asqad Muxtor", "context": "«Chinor» romani", "distractors": ["Oybek", "Qahhor", "Said Ahmad"]},
    {"quote": "Boshni fido qilmoq oson, el g'amini chekmoq mushkul.", "speaker": "Alisher Navoiy", "context": "«Mahbub ul-qulub»", "distractors": ["Bobur", "Jomiy", "Sa'diy"]},
    {"quote": "Yuraging qayerda yaralangan bo'lsa, nur o'sha yerdan kiradi.", "speaker": "Mavlono Rumiy", "context": "«Masnaviy»", "distractors": ["Hofiz", "Attor", "Sa'diy"]},
    {"quote": "Bani odam a'zoyi yak digarand (Barcha insonlar bir tananing a'zolaridir).", "speaker": "Sa'diy Sheroziy", "context": "«Guliston»", "distractors": ["Rumiy", "Hofiz", "Jomiy"]},
    {"quote": "Dili ba yoru, dasti ba kor (Ko'ngil Allohda, qo'l esa mehnatda bo'lsin).", "speaker": "Bahouddin Naqshband", "context": "Tariqat shiori", "distractors": ["Ahmad Yassaviy", "Najmiddin Kubro", "Abduxoliq G'ijduvoniy"]},
    {"quote": "Diyonatsiz zohidning ibodati havoga ketar.", "speaker": "Xoja Ahmad Yassaviy", "context": "«Devoni hikmat»", "distractors": ["So'fi Ollohyor", "Mashrab", "Yugnakiy"]},
    {"quote": "Ilm o'rganmoq har bir musulmonga farzdir.", "speaker": "Mirzo Ulug'bek peshtoq bitigi", "context": "Samarqand madrasasi", "distractors": ["Al-Buxoriy", "At-Termiziy", "Beruniy"]},
    {"quote": "Haqiqatni bilish uchun barcha taassubdan xoli bo'lish lozim.", "speaker": "Abu Rayhon Beruniy", "context": "«Hindiston» asari", "distractors": ["Ibn Sino", "Forobiy", "Xorazmiy"]},
    {"quote": "G'am-anduh inson tanasini zang temirni yegandek yemirur.", "speaker": "Abu Ali ibn Sino", "context": "«Tib qonunlari»", "distractors": ["Ar-Roziy", "Beruniy", "Forobiy"]},
    {"quote": "Davlat rahbarida adolat bo'lmasa, mamlakat xarob bo'lur.", "speaker": "Yusuf Xos Hojib", "context": "«Qutadg'u bilig»", "distractors": ["Ahmad Yugnakiy", "Navoiy", "Bobur"]},
    {"quote": "Adiblar so'zi durru gavhardir.", "speaker": "Ahmad Yugnakiy", "context": "«Hibat ul-haqoyiq»", "distractors": ["Yusuf Xos Hojib", "Qoshg'ariy", "Yassaviy"]},
    {"quote": "Turk tili arab tili bilan poygalashib borur.", "speaker": "Mahmud Qoshg'ariy", "context": "«Devonu lug'otit turk»", "distractors": ["Alisher Navoiy", "Bobur", "Rabg'uziy"]},
    {"quote": "Navoiy — turkiy tilning quyoshidir.", "speaker": "Abdurahmon Jomiy", "context": "«Bahoriston»", "distractors": ["Husayn Boyqaro", "Bobur", "Lutfiy"]},
    {"quote": "Agar biror narsani chin dildan istasang, butun Koinot senga yordam beradi.", "speaker": "Paolo Koelo", "context": "«Alkimyogar»", "distractors": ["Markes", "Kamyu", "Kafqa"]},
    {"quote": "O'tmishni kim boshqarsa — kelajakni ham o'sha boshqaradi.", "speaker": "Jorj Oruell", "context": "«1984»", "distractors": ["Xaksli", "Bredberi", "Kamyu"]},
    {"quote": "Qahraton qish o'rtasida men o'zimda yengilmas yozni kashf etdim.", "speaker": "Alber Kamyu", "context": "Falsafiy esselar", "distractors": ["Sartr", "Kafka", "Nitsshe"]},
    {"quote": "Yashash uchun «nima uchun»i bor odam har qanday «qanday»ga bardosh beradi.", "speaker": "Fridrix Nitsshe", "context": "Falsafiy aforizmlar", "distractors": ["Frankl", "Kamyu", "Gyote"]},
    {"quote": "Kitob — ichimizdagi muzlagan ummonni sindiruvchi boltadir.", "speaker": "Frants Kafka", "context": "Xatlar", "distractors": ["Dostoyevskiy", "Tolstoy", "Kamyu"]},
    {"quote": "O'tmish — bu xotiralar qabristonidir.", "speaker": "Gabriel Garsia Markes", "context": "«Yuz yillik yolg'izlik»", "distractors": ["Borxes", "Koelo", "Kortasar"]},
    {"quote": "Dunyodagi eng nodir narsa — bu yashashdir, aksariyat odamlar shunchaki mavjuddirlar.", "speaker": "Oskar Uayld", "context": "«Mulohazalar»", "distractors": ["Shou", "Shekspir", "Bayron"]},
    {"quote": "Hayotdagi eng muhim kun: nima uchun dunyoga kelganingizni anglagan kuningizdir.", "speaker": "Mark Tven", "context": "Aforizmlar", "distractors": ["London", "Xeminguey", "Poe"]},
    {"quote": "Hech narsa vaqti kelgan g'oyadek qudratli emas.", "speaker": "Viktor Gyugo", "context": "«Xo'rlanganlar»", "distractors": ["Volter", "Russo", "Balzak"]},
    {"quote": "Qorong'ulikni la'natlagandan ko'ra bitta sham yoqqan afzal.", "speaker": "Konfutsiy", "context": "«Suhbatlar»", "distractors": ["Lao Tszi", "Budda", "Suqrot"]},
    {"quote": "Men faqat bitta narsani bilaman — u ham bo'lsa hech narsa bilmasligimdir.", "speaker": "Suqrot (Socrates)", "context": "Afina suhbatlari", "distractors": ["Aflotun", "Arastu", "Pifagor"]},
    {"quote": "O'zingni angla — shunda butun olamni anglaysan.", "speaker": "Aflotun (Plato)", "context": "Falsafiy dialoglar", "distractors": ["Suqrot", "Arastu", "Seneka"]},
    {"quote": "Aflotun mening do'stim, ammo haqiqat undan ham azizroqdir.", "speaker": "Arastu (Aristotle)", "context": "«Axloqi Kabir»", "distractors": ["Suqrot", "Aflotun", "Pifagor"]},
    {"quote": "Hayotimiz — bu bizning fikrlarimiz mahsulidir.", "speaker": "Mark Avreliy", "context": "«Mulohazalar»", "distractors": ["Seneka", "Epiktet", "Tsitseron"]},
    {"quote": "O'limdan qo'rqma, balki yashay olmagan hayotdan qo'rq.", "speaker": "Seneka", "context": "Lutsiliyga maktublar", "distractors": ["Avreliy", "Epiktet", "Suqrot"]},
    {"quote": "Yaxshilik qil-u daryoga tashla, baliq bilmasa Xoliq bilar.", "speaker": "O'zbek xalq donishmandligi", "context": "Xalq maqollari", "distractors": ["Navoiy", "Sa'diy", "Rumiy"]},
    {"quote": "Aql ko'pga yetkazar, hunar — ko'kka.", "speaker": "Sharq hikmati", "context": "Hikmatlar majmuasi", "distractors": ["Qoshg'ariy", "Yugnakiy", "Yassaviy"]},
    {"quote": "Kitob o'qimagan inson bir marta yashaydi, kitob o'qigan inson esa minglab hayotni boshdan kechiradi.", "speaker": "Jorj Martin", "context": "Adabiy mulohazalar", "distractors": ["Tolkien", "Rouling", "Lyuis"]},
    {"quote": "Maftun bo'lma bu dunyo ziynatiga, barchasi o'tkinchidir.", "speaker": "Boborahim Mashrab", "context": "G'azallar", "distractors": ["So'fi Ollohyor", "Yassaviy", "Huvaido"]},
    {"quote": "Sabr — barcha mushkullarning oltin kalitidir.", "speaker": "Imom G'azzoliy", "context": "«Mukoshafat ul-qulub»", "distractors": ["Moturidiy", "Buxoriy", "Termiziy"]},
    {"quote": "El ardoqlagan inson hech qachon unutilmas.", "speaker": "Shukur Xolmirzayev", "context": "«O'zbek xarakteri»", "distractors": ["Tog'ay Murod", "Asqad Muxtor", "Said Ahmad"]}
]
