# -*- coding: utf-8 -*-
"""Imlo Saralovchi (Spell Check) — adabiy til me'yorlari va to'g'ri yozilgan imlo variantlarini topish."""

SPELLCHECK_QUESTIONS = [
    {"q": "Qaysi so'z TO'G'RI imlo qoidasi asosida yozilgan?", "options": ["Mutafakkir", "Mutaffakir", "Mutafakkur", "Mutafaqqir"], "correct": 0, "hint": "Tafakkur sohibi"},
    {"q": "Qaysi so'zda xatolik YO'Q?", "options": ["Ma'rifatparvar", "Marifatparvar", "Ma'rfatparvar", "Ma'rifatparvr"], "correct": 0, "hint": "Ilm va ma'rifat ulashuvchi"},
    {"q": "Qaysi adabiy atama TO'G'RI yozilgan?", "options": ["Tazod (Zid ma'no)", "Tazot", "Tazzod", "Tozod"], "correct": 0, "hint": "Qarama-qarshilik san'ati"},
    {"q": "Qaysi mumtoz janr nomi TO'G'RI yozilgan?", "options": ["Muhammas (Beshlik)", "Muxammas", "Muhammoz", "Muxammasi"], "correct": 0, "hint": "Besh misrali she'r"},
    {"q": "Qaysi so'z TO'G'RI imloga ega?", "options": ["Tafakkur", "Taffakur", "Tafakur", "Tafaqqur"], "correct": 0, "hint": "Fikr yuritish"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Qutadg'u bilig", "Qutadg'u bilik", "Qutadgu bilig", "Qutatgu bilig"], "correct": 0, "hint": "Yusuf Xos Hojib asari"},
    {"q": "Qaysi so'zda tutuq belgisi (') TO'G'RI qo'yilgan?", "options": ["Ma'naviyat", "Man'aviyat", "Mana'viyat", "Manaviyat'"], "correct": 0, "hint": "Inson ruhiy boyligi"},
    {"q": "Qaysi adabiy san'at nomi TO'G'RI yozilgan?", "options": ["Tashbeh (O'xshatish)", "Tashbeh'", "Tashbi", "Tashbik"], "correct": 0, "hint": "Badiiy o'xshatish"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Istiora (Metafora)", "Isteora", "Istiyora", "Istiora'"], "correct": 0, "hint": "Ko'chma ma'no san'ati"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["Mubolag'a (Giperbola)", "Mubolaga", "Mubolag'ha", "Mubola'ga"], "correct": 0, "hint": "Bo'rttirish san'ati"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Kitobxonlik", "Kitobhonlik", "Kitobxanlik", "Kitobqonlik"], "correct": 0, "hint": "Kitob mutolaasi"},
    {"q": "Qaysi so'zda xato YO'Q?", "options": ["Iste'dod", "Istedod", "Ist'edod", "Iste'dot"], "correct": 0, "hint": "Tug'ma qobiliyat"},
    {"q": "Qaysi mumtoz atama TO'G'RI yozilgan?", "options": ["Munozara", "Munazara", "Munozira", "Munazira"], "correct": 0, "hint": "Bahs-munozara janri"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["Talmeh (Tarixiy ishora)", "Talme'", "Talmex", "Talmih"], "correct": 0, "hint": "Tarixiy voqeaga ishora"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Marsiya (Aza qo'shig'i)", "Marssiya", "Marziya", "Martsia"], "correct": 0, "hint": "Motam she'ri"},
    {"q": "Qaysi janr nomi TO'G'RI yozilgan?", "options": ["Ruboiy (To'rtlik)", "Ruboi", "Ruboyiy", "Ruboy"], "correct": 0, "hint": "To'rt misrali she'r"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Masnaviy (Qo'shaloq qofiya)", "Masnaviy'", "Masnavi", "Masnaffiy"], "correct": 0, "hint": "Ikki misrali qofiyalanish"},
    {"q": "Qaysi alloma nisbasi TO'G'RI yozilgan?", "options": ["Samarqandiy", "Samarqandi", "Samarqandiy'", "Samarkandiy"], "correct": 0, "hint": "Samarqandlik alloma"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Xattotlik", "Hattotlik", "Xatotlik", "Hattatlik"], "correct": 0, "hint": "Husnixat san'ati"},
    {"q": "Qaysi so'zda imlo xatosi YO'Q?", "options": ["Qo'lyozma", "Qo'l yozma", "Qolyozma", "Qul yozma"], "correct": 0, "hint": "Qadimiy yozma meros"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Lug'atshunoslik", "Lugg'atshunoslik", "Lugatshunoslik", "Lug'atshunosliq"], "correct": 0, "hint": "Leksikografiya"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["She'riyat", "Sheriyat", "She'riyad", "Sh'eriyat"], "correct": 0, "hint": "Nazm san'ati"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Maqola", "Maqala", "Maqola'", "Makkola"], "correct": 0, "hint": "Publitsistik janr"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Dostonchilik", "Dastonchilik", "Dostonshunoslik'", "Dostanchilik"], "correct": 0, "hint": "Baxshichilik san'ati"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Aforizm", "Afrizm", "Afarizm", "Afforizm"], "correct": 0, "hint": "Hikmatli qisqa so'z"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Qahramonlik", "Qaxramonlik", "Kahramonlik", "Qahromonlik"], "correct": 0, "hint": "Jasorat ko'rsatish"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Badiiy", "Badiy", "Baddiy", "Badiyiy"], "correct": 0, "hint": "San'atkorona ifoda"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["Allegoriya", "Alegoriya", "Allegareya", "Alligoriya"], "correct": 0, "hint": "Majoz san'ati"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Dramaturgiya", "Dramaturgeya", "Dramaturgya", "Dramaturjiya"], "correct": 0, "hint": "Sahna asarlari san'ati"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Tragediya (Fojia)", "Tragedya", "Trijediya", "Trajedya"], "correct": 0, "hint": "Fojiaviy drama"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Komediya (Hajviyot)", "Komedya", "Kamediya", "Komedea"], "correct": 0, "hint": "Kulgili sahna asari"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Bibliografiya", "Bibliyagrafiya", "Bibliyografiya", "Bebliografiya"], "correct": 0, "hint": "Kitoblar ro'yxati"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Akademiya", "Akademya", "Akademiya'", "Akadimiya"], "correct": 0, "hint": "Oliy ilmiy dargoh"},
    {"q": "Qaysi alloma nomi TO'G'RI yozilgan?", "options": ["Zamaxshariy", "Zamaxshari", "Zamahshariy", "Zamaxshariy'"], "correct": 0, "hint": "Buyuk tilshunos alloma"},
    {"q": "Qaysi shahar nomi TO'G'RI yozilgan?", "options": ["Marg'ilon", "Margilon", "Marg'ilan", "Morg'ilon"], "correct": 0, "hint": "Kumushbibi vatani"},
    {"q": "Qaysi shahar nomi TO'G'RI yozilgan?", "options": ["Shahrisabz", "Shaxrisabz", "Shahrisabs", "Shahrisapz"], "correct": 0, "hint": "Kesh — Amir Temur tug'ilgan joy"},
    {"q": "Qaysi asar nomi TO'G'RI yozilgan?", "options": ["«Lison ut-tayr»", "«Lison ut-tayir»", "«Lisonut tayr»", "«Lison-ul tayr»"], "correct": 0, "hint": "Navoiyning qushlar tili dostoni"},
    {"q": "Qaysi doston nomi TO'G'RI yozilgan?", "options": ["«Hayrat ul-abror»", "«Hayratul abror»", "«Xayrat ul-abror»", "«Hayratul-abror»"], "correct": 0, "hint": "Xamsaning ilk dostoni"},
    {"q": "Qaysi asar nomi TO'G'RI yozilgan?", "options": ["«Mahbub ul-qulub»", "«Mahbubul qulub»", "«Maxbub ul-qulub»", "«Mahbubul-qulub»"], "correct": 0, "hint": "Ko'ngillarning sevgani"},
    {"q": "Qaysi asar nomi TO'G'RI yozilgan?", "options": ["«Muhokamat ul-lug'atayn»", "«Muhokamatul lug'atayn»", "«Muxokamat ul-lugatayn»", "«Muhokamatul-lug'atayn»"], "correct": 0, "hint": "Ikki til bahsi"},
    {"q": "Qaysi asar nomi TO'G'RI yozilgan?", "options": ["«Hibat ul-haqoyiq»", "«Hibatul haqoyiq»", "«Xibat ul-xaqoyiq»", "«Hibatul-haqoyiq»"], "correct": 0, "hint": "Haqiqatlar armug'oni"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Axloq-odob", "Ahloq-odob", "Ahloq odob", "Axloq odob"], "correct": 0, "hint": "Insoniy fazilatlar"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Mehr-oqibat", "Mehru oqibat", "Mehroqibat", "Mehir-oqibat"], "correct": 0, "hint": "Odamgarchilik tuyg'usi"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Oltin boshli", "Oltinboshli", "Oltin-boshli", "Oltin boshliy"], "correct": 0, "hint": "Sifat birikmasi"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Tong saharda", "Tongsaharda", "Tong-saharda", "Tongsahar da"], "correct": 0, "hint": "Vaqt ifodasi"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Kechki payt", "Kechkipayt", "Kechki-payt", "Kechki paytda'"], "correct": 0, "hint": "Oqshom vaqti"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Vatanparvarlik", "Vatan parvarlik", "Vatan-parvarlik", "Vatanparvarliq"], "correct": 0, "hint": "Vatanga bo'lgan muhabbat"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Xalqparvar", "Halqparvar", "Xalq parvar", "Xalq-parvar"], "correct": 0, "hint": "El g'amini yeyuvchi"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Adolatparvar", "Adolat parvar", "Adolat-parvar", "Odolatparvar"], "correct": 0, "hint": "Haqparvar inson"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Donishmandlik", "Danoxonlik", "Donishmandliq", "Danoshmandlik"], "correct": 0, "hint": "Aql-zakovat sohibligi"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["Monolog (Yakkaxon nutq)", "Monalog", "Manolog", "Monolok"], "correct": 0, "hint": "Qahramonning o'z-o'zi bilan so'zlashuvi"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["Dialog (Ikki kishi suhbati)", "Diyalog", "Deyalog", "Dialoq"], "correct": 0, "hint": "O'zaro suhbat"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["Epigraf (Muqaddima shiori)", "Epegraf", "Ipigraf", "Epigrif"], "correct": 0, "hint": "Asar boshidagi iqtibos"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["Prolok emas, Prolog (Muqaddima)", "Proloq", "Prolog'", "Pralog"], "correct": 0, "hint": "Asar muqaddimasi"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["Epilog (Xotima)", "Epiloq", "Epilog'", "Epilok"], "correct": 0, "hint": "Asar yakuniy xulosasi"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Kulminatsiya (Eng yuqori cho'qqi)", "Kulminatseya", "Kulmenatsiya", "Koolminatsiya"], "correct": 0, "hint": "Syujet rivojining eng keskin nuqtasi"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Ekspozitsiya (Boshlang'ich holat)", "Ekspazitsiya", "Ekspozitseya", "Eksspozitsiya"], "correct": 0, "hint": "Voqealar boshlanishidagi tanishtiruv"},
    {"q": "Qaysi so'z TO'G'RI yozilgan?", "options": ["Renessans (Uyg'onish davri)", "Renesans", "Ranessans", "Renessanс"], "correct": 0, "hint": "Sharq va G'arb uyg'onish davri"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["Ensiklopediya (Qomus)", "Ensiklapedya", "Insiklopediya", "Ensiklopedeya"], "correct": 0, "hint": "Barcha ilmlar majmuasi"},
    {"q": "Qaysi atama TO'G'RI yozilgan?", "options": ["Xrestomatiya (Tanlangan namunalar)", "Xrestamateya", "Hrestomatiya", "Xristomatiya"], "correct": 0, "hint": "Adabiy namunalar majmuasi"}
]
