# -*- coding: utf-8 -*-
"""Omon qolish (Survival) question bank.
Over 150+ multiple choice questions with 4 options. Shuffled at runtime.
"""

SURVIVAL_QUESTIONS = [
    {"q": "“O'tkan kunlar” romanining muallifi kim?", "options": ["Abdulla Qodiriy", "Abdulla Qahhor", "Cho'lpon", "G'afur G'ulom"], "correct": 0},
    {"q": "“Boburnoma” qaysi janrga mansub?", "options": ["Memuar", "Doston", "Fantastika", "Detektiv"], "correct": 0},
    {"q": "“Urush va tinchlik” romani muallifi kim?", "options": ["Lev Tolstoy", "Fyodor Dostoyevskiy", "Anton Chexov", "Maksim Gorkiy"], "correct": 0},
    {"q": "“Hamlet” asari qaysi mamlakat qahramoni haqida?", "options": ["Daniya", "Angliya", "Fransiya", "Ispaniya"], "correct": 0},
    {"q": "“Xamsa” nechta dostondan iborat?", "options": ["5 ta", "3 ta", "7 ta", "4 ta"], "correct": 0},
    {"q": "“Al-Qonun fit-tib” asari qaysi sohaga oid?", "options": ["Tibbiyot", "Astronomiya", "Matematika", "Geografiya"], "correct": 0},
    {"q": "Mirzo Ulug'bek qaysi shaharda observatoriya qurdirgan?", "options": ["Samarqand", "Buxoro", "Xiva", "Toshkent"], "correct": 0},
    {"q": "“Jinoyat va jazo” romanida bosh qahramon kimni o'ldiradi?", "options": ["Qari sudxo'r ayolni", "O'z otasini", "Do'stini", "Sevgilisini"], "correct": 0},
    {"q": "“Qutadg'u bilig” asari qaysi asrda yozilgan?", "options": ["XI asr", "XV asr", "XIX asr", "VIII asr"], "correct": 0},
    {"q": "“Don Kixot” bosh qahramoni o'zini kim deb hisoblaydi?", "options": ["Ritsar", "Qirol", "Sarkarda", "Rohib"], "correct": 0},
    {"q": "Algebra atamasini fanga kim kiritgan?", "options": ["Muhammad al-Xorazmiy", "Ibn Sino", "Beruniy", "Farobiy"], "correct": 0},
    {"q": "“Muallimi soniy” laqabi kimga tegishli?", "options": ["Abu Nasr Farobiy", "Ibn Sino", "Beruniy", "Ulug'bek"], "correct": 0},
    {"q": "“Sahih al-Buxoriy” qaysi ilm sohasiga oid?", "options": ["Hadis", "Tib", "Falsafa", "Adabiyot"], "correct": 0},
    {"q": "Ahmad Yassaviy qaysi tariqat ta'limotining asoschisi?", "options": ["Yassaviya", "Naqshbandiya", "Qodiriya", "Kubraviya"], "correct": 0},
    {"q": "“Kichkina shahzoda”da bosh qahramon nima bilan do'stlashadi?", "options": ["Atirgul", "Tulki", "Ilon", "Yulduz"], "correct": 0},
    {"q": "“Shum bola” qissasining muallifi kim?", "options": ["G'afur G'ulom", "Abdulla Qodiriy", "Said Ahmad", "Oybek"], "correct": 0},
    {"q": "Naqshbandiya tariqatining piri qayerda dafn etilgan?", "options": ["Buxoro", "Samarqand", "Yassi (Turkiston)", "Xiva"], "correct": 0},
    {"q": "“Hidoyat” (Al-Hidoya) asari qaysi sohaga oid klassik manba?", "options": ["Fiqh (islom huquqi)", "Tib", "Astronomiya", "Adabiyot"], "correct": 0},
    {"q": "“Sarob” romanining muallifi kim?", "options": ["Abdulla Qahhor", "Abdulla Qodiriy", "Oybek", "Said Ahmad"], "correct": 0},
    {"q": "Imom Termiziy qaysi hadis to'plamining muallifi?", "options": ["Sunan at-Termiziy", "Sahih al-Buxoriy", "Sahih Muslim", "Sunan an-Nasoiy"], "correct": 0},
    {"q": "“Kecha va kunduz” romani muallifining taxallusi nima?", "options": ["Cho'lpon", "Oybek", "Hamid Olimjon", "Usmon Nosir"], "correct": 0},
    {"q": "Marg'ilondan yetishib chiqqan, “Hidoyat” muallifi buyuk faqih kim?", "options": ["Burhoniddin Marg'inoniy", "Imom Buxoriy", "Imom Moturidiy", "Imom A'zam"], "correct": 0},
    {"q": "“Qonun al-Mas'udiy” asarining muallifi kim?", "options": ["Abu Rayhon Beruniy", "Ibn Sino", "Farobiy", "Xorazmiy"], "correct": 0},
    {"q": "Servantesning mashhur romani qaysi?", "options": ["Don Kixot", "Uch mushketyor", "Graf Monte-Kristo", "Robinzon Kruzo"], "correct": 0},
    {"q": "“Qutadg'u bilig” nomi qanday ma'noni anglatadi?", "options": ["Baxt keltiruvchi bilim", "Hikmatlar devoni", "Yaxshi so'zlar kitobi", "Ulug' bilim"], "correct": 0},
    {"q": "“Anna Karenina” romani muallifi kim?", "options": ["Lev Tolstoy", "Dostoyevskiy", "Chexov", "Turgenev"], "correct": 0},
    {"q": "Anton Chexov asosan qaysi janrlarda ijod qilgan?", "options": ["Hikoya va dramaturgiya", "Roman", "Doston", "Ertak"], "correct": 0},
    {"q": "Alisher Navoiy qaysi shaharda tug'ilgan?", "options": ["Hirot", "Samarqand", "Buxoro", "Toshkent"], "correct": 0},
    {"q": "“Farhod va Shirin” dostonini kim yozgan?", "options": ["Alisher Navoiy", "Bobur", "Lutfiy", "Sakkokiy"], "correct": 0},
    {"q": "“Alpomish” qaysi janrga mansub?", "options": ["Doston", "Roman", "Qissa", "Hikoya"], "correct": 0},
    {"q": "“Ona” romani kim asari?", "options": ["Maksim Gorkiy", "Lev Tolstoy", "Chexov", "Sholoxov"], "correct": 0},
    {"q": "“Tinch Don” muallifi kim?", "options": ["Mixail Sholoxov", "Gorkiy", "Fadeyev", "Ostrovskiy"], "correct": 0},
    {"q": "“O'lik jonlar” muallifi kim?", "options": ["Nikolay Gogol", "Pushkin", "Turgenev", "Chexov"], "correct": 0},
    {"q": "“Metamorfoza” asari kimning ijodi?", "options": ["Frans Kafka", "Kamyu", "Sartr", "Jois"], "correct": 0},
    {"q": "“1984” romani kim tomonidan yozilgan?", "options": ["Jorj Oruell", "Oldos Xaksli", "Rey Bredberi", "Zamyatin"], "correct": 0},
    {"q": "“Hayvonlar fermasi” muallifi kim?", "options": ["Jorj Oruell", "Oldos Xaksli", "Rey Bredberi", "Zamyatin"], "correct": 0},
    {"q": "“Robinzon Kruzo” kim asari?", "options": ["Daniel Defo", "Jonatan Svift", "Jyul Vern", "Mark Tven"], "correct": 0},
    {"q": "“Alkimyogar” kitobi muallifi kim?", "options": ["Paulo Koelo", "Gabriel Markes", "Xeminguey", "Kafka"], "correct": 0},
    {"q": "“Graf Monte-Kristo” muallifi kim?", "options": ["Aleksandr Dyuma", "Viktor Gyugo", "Balzak", "Stendal"], "correct": 0},
    {"q": "“Uch mushketyor” muallifi kim?", "options": ["Aleksandr Dyuma", "Viktor Gyugo", "Jyul Vern", "Balzak"], "correct": 0},
    {"q": "“Chol va dengiz” kim asari?", "options": ["Ernest Xeminguey", "Jek London", "Mark Tven", "Folkner"], "correct": 0},
    {"q": "“Gulliverning sayohatlari” muallifi kim?", "options": ["Jonatan Svift", "Daniel Defo", "Mark Tven", "Jyul Vern"], "correct": 0},
    {"q": "“Faust” asari muallifi kim?", "options": ["Gyote", "Shiller", "Bayron", "Gyugo"], "correct": 0},
    {"q": "“Romeo va Julyetta” voqealari qaysi shaharda bo'ladi?", "options": ["Verona", "Rim", "Venetsiya", "Florensiya"], "correct": 0},
    {"q": "Shekspirning “Otello” tragediyasi asosan qaysi mavzuga bag'ishlangan?", "options": ["Rashk", "Sevgi to'g'risidagi komediya", "Tarixiy urush", "Sayohat"], "correct": 0},
    {"q": "“Devonu lug'otit turk” muallifi kim?", "options": ["Mahmud Koshg'ariy", "Yusuf Xos Hojib", "Navoiy", "Bobur"], "correct": 0},
    {"q": "Boburiylar sulolasi qaysi mamlakatda barpo etilgan?", "options": ["Hindiston", "Eron", "Turkiya", "Misr"], "correct": 0},
    {"q": "“Ulug'bek xazinasi” romani muallifi kim?", "options": ["Odil Yoqubov", "Pirimqul Qodirov", "Asqad Muxtor", "Said Ahmad"], "correct": 0},
    {"q": "“Yulduzli tunlar” romani kimning ijodi?", "options": ["Pirimqul Qodirov", "Odil Yoqubov", "Oybek", "Mirmuhsin"], "correct": 0},
    {"q": "“Kelinlar qo'zg'oloni” komediyasining muallifi kim?", "options": ["Said Ahmad", "O'tkir Hoshimov", "Xudoyberdi To'xtaboyev", "G'afur G'ulom"], "correct": 0},
    {"q": "“Dengiz ostida 20 000 liga” asari qahramoni kapitan Nemo boshqargan kema nomi nima?", "options": ["Nautilus", "Ispanola", "Bounty", "Viktoriya"], "correct": 0},
    {"q": "“Xazina oroli” romanida bir oyoqli qaroqchi Jon Silver qanday laqab bilan tanilgan?", "options": ["Oqsoqol (Barbyukyu)", "Qora soqol", "Kaptar", "Flint"], "correct": 0},
    {"q": "“Sherlok Xolms” qaysi ko'chada yashagan?", "options": ["Beyker-strit 221B", "Oksford-strit 10", "Pikadilli 5", "Flit-strit 12"], "correct": 0},
]
