# -*- coding: utf-8 -*-
"""Tarixiy Sayohatchi (Time Traveler) — adabiy asarlar, allomalar va tarixiy davrlarni to'g'ri joylashtirish."""

TIMETRAVELER_QUESTIONS = [
    {"q": "Alisher Navoiy va Zahiriddin Muhammad Bobur qaysi davrda ijod qilgan?", "options": ["XV – XVI asrlar (Temuriylar uyg'onish davri)", "IX – X asrlar (Somoniylar)", "XIX asr oxiri (Jadidchilik)", "XII asr (Xorazmshohlar)"], "correct": 0, "era": "XV – XVI asr"},
    {"q": "Ahmad Yassaviy va Mahmud Qoshg'ariy qaysi asrlarda yashab ijod etgan?", "options": ["XI – XII asrlar (Qoraxoniylar davri)", "XV asr (Temuriylar)", "XIV asr (Amir Temur zamoni)", "XVIII asr (Xonliklar)"], "correct": 0, "era": "XI – XII asr"},
    {"q": "Abdulla Qodiriyning «O'tkan kunlar» romanida tasvirlangan tarixiy davr:", "options": ["XIX asr o'rtalari (Xudoyorxon xonligi zamoni)", "XX asr boshi (Jadidlar zamoni)", "XV asr (Bobur davri)", "XVIII asr (Buxoro amirligi)"], "correct": 0, "era": "XIX asr o'rtalari"},
    {"q": "O'zbek adabiyotida Jadidchilik ma'rifatparvarlik harakati qaysi davrda avj oldi?", "options": ["XIX asr oxiri — XX asr boshlari (1890–1920-yillar)", "XVIII asr o'rtalari", "XVII asr", "XX asrning 50-yillari"], "correct": 0, "era": "1890–1920-yillar"},
    {"q": "Abu Rayhon Beruniy va Ibn Sino qaysi ulug'vor davr allomalaridir?", "options": ["X – XI asrlar (Sharq Renessansi)", "XIII asr (Mo'g'ullar istilosi)", "XVI asr (Shayboniylar)", "VIII asr (Arab xalifaligi)"], "correct": 0, "era": "X – XI asr"},
    {"q": "Pirimqul Qodirovning «Yulduzli tunlar» romani qaysi tarixiy shaxs hayotiga bag'ishlangan?", "options": ["Zahiriddin Muhammad Bobur (1483–1530)", "Amir Temur", "Mirzo Ulug'bek", "Alisher Navoiy"], "correct": 0, "era": "1483–1530"},
    {"q": "Alisher Navoiy «Xamsa» dostonlar majmuasini nechanchi yillarda yaratgan?", "options": ["1483 – 1485-yillar", "1441 – 1450-yillar", "1501 – 1505-yillar", "1470 – 1475-yillar"], "correct": 0, "era": "1483–1485"},
    {"q": "«Alpomish» dostonining shakllanishi qaysi qadimiy davrlarga borib taqaladi?", "options": ["VI – VIII asrlar (Qadimgi Turkiy xoqonlik)", "XV asr", "XVIII asr", "XX asr"], "correct": 0, "era": "VI – VIII asr"},
    {"q": "Yusuf Xos Hojib «Qutadg'u bilig» asarini qaysi asrda yozgan?", "options": ["XI asr (1069–1070-yillar)", "IX asr", "XIV asr", "XVI asr"], "correct": 0, "era": "1069–1070"},
    {"q": "Ahmad Yugnakiy «Hibat ul-haqoyiq» asarini qaysi davrda yaratgan?", "options": ["XII asr oxiri — XIII asr boshi", "XV asr", "X asr", "XVII asr"], "correct": 0, "era": "XII – XIII asr"},
    {"q": "Mirzo Ulug'bek o'zining mashhur «Ziji jadidi Ko'ragoniy» asarini qaysi asrda bitgan?", "options": ["XV asr (1437-yil)", "XIII asr", "XVI asr", "XI asr"], "correct": 0, "era": "XV asr"},
    {"q": "Amir Temur qaysi yillarda hukmronlik qilgan va saltanat qurgan?", "options": ["1370 – 1405-yillar", "1405 – 1449-yillar", "1220 – 1250-yillar", "1500 – 1530-yillar"], "correct": 0, "era": "1370–1405"},
    {"q": "Abdulla Qodiriy «Mehrobdan chayon» asarini qaysi davr voqealariga asoslab yozgan?", "options": ["XIX asr 30–40-yillari (Madalixon davri)", "XV asr Hirot", "XX asr boshlari", "XVIII asr Xiva"], "correct": 0, "era": "XIX asr 30–40-yillar"},
    {"q": "Cho'lponning «Kecha va kunduz» romani qaysi davr ijtimoiy muhitini aks ettiradi?", "options": ["XX asr boshi (Chor Rossiyasi mustamlakasi davri)", "XVIII asr", "Temuriylar davri", "O'rta asrlar"], "correct": 0, "era": "XX asr boshi"},
    {"q": "Muso Xorazmiy algebra faniga asos solgan davr:", "options": ["IX asr (Bag'doddagi Baytul Hikma davri)", "XII asr", "VI asr", "XIV asr"], "correct": 0, "era": "IX asr"},
    {"q": "Abu Nasr Forobiy (Sharq Arastusi) qaysi asrlarda yashagan?", "options": ["IX – X asrlar (873–950-yillar)", "XII asr", "XV asr", "VII asr"], "correct": 0, "era": "873–950"},
    {"q": "Imom Buxoriy «Al-Jome' as-Sahih» hadislar to'plamini qaysi asrda jamlagan?", "options": ["IX asr (810–870-yillar)", "XI asr", "VII asr", "XIII asr"], "correct": 0, "era": "IX asr"},
    {"q": "Imom Termiziy qaysi asrda yashab ijod qilgan buyuk muhaddis?", "options": ["IX asr (824–892-yillar)", "VI asr", "XII asr", "XV asr"], "correct": 0, "era": "IX asr"},
    {"q": "Imom Moturidiy kalom ilmi maktabiga qaysi asrda asos solgan?", "options": ["IX – X asrlar (Samarqand)", "XII asr", "XV asr", "VII asr"], "correct": 0, "era": "IX – X asr"},
    {"q": "Mahmud Qoshg'ariy «Devonu lug'otit turk» asarini qaysi yilda yakunlagan?", "options": ["1074-yil (XI asr)", "1200-yil", "1405-yil", "900-yil"], "correct": 0, "era": "1074-yil"},
    {"q": "Rabg'uziy «Qisasi Rabg'uziy» asarini qaysi asrda yozgan?", "options": ["XIV asr boshi (1309–1310-yillar)", "XI asr", "XVI asr", "IX asr"], "correct": 0, "era": "1309–1310"},
    {"q": "Xorazmiy «Muhabbatnoma» dostonini qaysi asrda yaratgan?", "options": ["XIV asr (1353-yil)", "XII asr", "XVI asr", "X asr"], "correct": 0, "era": "1353-yil"},
    {"q": "Sayfi Saroyi «Gulistoni bit-turkiy» asarini qaysi asrda yozgan?", "options": ["XIV asr (1391-yil)", "XI asr", "XV asr", "XVII asr"], "correct": 0, "era": "1391-yil"},
    {"q": "Atoiy, Sakkokiy va Lutfiy o'zbek mumtoz g'azalchiligini qaysi asrda yuksaltirgan?", "options": ["XV asrning birinchi yarmi", "XII asr", "XVIII asr", "XIX asr"], "correct": 0, "era": "XV asr"},
    {"q": "Husayn Boyqaro Hirot taxtida qaysi yillarda hukmronlik qilgan?", "options": ["1469 – 1506-yillar", "1400 – 1430-yillar", "1530 – 1560-yillar", "1370 – 1400-yillar"], "correct": 0, "era": "1469–1506"},
    {"q": "Bobur Mirzo «Boburnoma» asarini qaysi davrlarda yozib qoldirgan?", "options": ["XVI asr boshlari (Hindiston va Afg'oniston davri)", "XIV asr", "XVIII asr", "XII asr"], "correct": 0, "era": "XVI asr"},
    {"q": "Muhammad Solih «Shayboniynoma» dostonini qaysi asrda yaratgan?", "options": ["XVI asr boshi", "XIV asr", "XVIII asr", "XII asr"], "correct": 0, "era": "XVI asr"},
    {"q": "Majlisiy «Qissai Sayfulmuluk» dostonini qaysi asrda yozgan?", "options": ["XVI asr", "XII asr", "XIX asr", "IX asr"], "correct": 0, "era": "XVI asr"},
    {"q": "Turdi Farog'iy qaysi asrda Buxoro xonligida yashab, fosh etuvchi satirik she'rlar yozgan?", "options": ["XVII asr (Subhonqulixon davri)", "XV asr", "XIX asr", "XIII asr"], "correct": 0, "era": "XVII asr"},
    {"q": "Mashrab (Boborahim Mashrab) qaysi asrda yashagan olovnafas shoir?", "options": ["XVII asr oxiri — XVIII asr boshi (1640–1711)", "XV asr", "XII asr", "XX asr"], "correct": 0, "era": "1640–1711"},
    {"q": "So'fi Ollohyor «Sabot ul-ojizin» asarini qaysi asrda yozgan?", "options": ["XVII asr oxiri — XVIII asr boshi", "XV asr", "XII asr", "XIX asr"], "correct": 0, "era": "XVIII asr"},
    {"q": "Nodirabegim va Uvaysiy Qo'qon adabiy muhitida qaysi asrda ijod qilgan?", "options": ["XIX asrning birinchi yarmi (Amir Umarxon zamoni)", "XVII asr", "XV asr", "XX asr"], "correct": 0, "era": "XIX asr"},
    {"q": "Munis Xorazmiy va Muhammad Rizo Ogahiy Xiva adabiy muhitida qaysi asrda yashagan?", "options": ["XIX asr", "XVI asr", "XIV asr", "XI asr"], "correct": 0, "era": "XIX asr"},
    {"q": "Muqimiy, Furqat va Zavqiy Qo'qon ma'rifatparvarlik muhitida qaysi davrda ijod qilgan?", "options": ["XIX asr oxiri — XX asr boshlari", "XVIII asr", "XVI asr", "XVII asr"], "correct": 0, "era": "XIX – XX asr"},
    {"q": "Mahmudxo'ja Behbudiy «Padarkush» dramasini nechanchi yilda yozgan?", "options": ["1911-yil (XX asr boshi)", "1875-yil", "1930-yil", "1900-yil"], "correct": 0, "era": "1911-yil"},
    {"q": "Munavvarqori Abdurashidxonov Toshkentda ilk jadid maktabini qachon ochgan?", "options": ["1901-yil", "1880-yil", "1925-yil", "1915-yil"], "correct": 0, "era": "1901-yil"},
    {"q": "Fitrat «Munozara» asarini nechanchi yilda Istanbulda nashr ettirgan?", "options": ["1909-yil", "1895-yil", "1924-yil", "1935-yil"], "correct": 0, "era": "1909-yil"},
    {"q": "Oybek «Qutlug' qon» romanida qaysi davr xalq qo'zg'olonini tasvirlagan?", "options": ["1916-yilgi mardikorlikka olishga qarshi xalq harakati", "1905-yil", "1930-yil", "1890-yil"], "correct": 0, "era": "1916-yil"},
    {"q": "G'afur G'ulom «Shum bola» qissasida qaysi yillardagi Toshkent hayotini tasvirlaydi?", "options": ["XX asr boshi (Birinchi jahon urushi arafasi)", "1945-yil", "XIX asr o'rtalari", "1960-yillar"], "correct": 0, "era": "XX asr boshi"},
    {"q": "Said Ahmad «Ufq» trilogiyasida qaysi yillar fojiasini qamrab olgan?", "options": ["1938 – 1950-yillar (Urush va urushdan keyingi davr)", "1917 – 1920-yillar", "1970 – 1980-yillar", "1900 – 1910-yillar"], "correct": 0, "era": "1938–1950"},
    {"q": "O'tkir Hoshimov «Ikki eshik orasi» romanida qaysi 40 yillik davrni tasvirlaydi?", "options": ["1940-yillardan 1980-yillargacha bo'lgan davr", "1900 – 1940-yillar", "1980 – 2000-yillar", "XIX asr oxiri"], "correct": 0, "era": "1940–1980"},
    {"q": "Tohir Malik «Shaytanat» asari qaysi davr jamiyat illatlarini qalamga oladi?", "options": ["XX asrning 80–90-yillari", "1950-yillar", "1920-yillar", "XXI asr 2010-yillari"], "correct": 0, "era": "1980–1990"},
    {"q": "Jahon adabiyotida Servantes «Don Kixot» asarini qaysi asrda yaratgan?", "options": ["XVII asr boshi (1605–1615-yillar)", "XV asr", "XIX asr", "XIV asr"], "correct": 0, "era": "1605–1615"},
    {"q": "Uilyam Shekspir Uyg'onish davrida qaysi asrlarda yashagan?", "options": ["XVI asr oxiri — XVII asr boshi (1564–1616)", "XIV asr", "XVIII asr", "XV asr"], "correct": 0, "era": "1564–1616"},
    {"q": "Iogann Volfgang Gyote «Faust» tragediyasini qaysi davrda yozib tugatgan?", "options": ["XVIII asr oxiri — XIX asr boshi (1832-yil)", "XVI asr", "XVII asr", "XX asr"], "correct": 0, "era": "XVIII – XIX asr"},
    {"q": "Aleksandr Pushkin «Yevgeniy Onegin» she'riy romanini qaysi asrda yozgan?", "options": ["XIX asr 20–30-yillari", "XVIII asr", "XVII asr", "XX asr"], "correct": 0, "era": "XIX asr"},
    {"q": "Viktor Gyugo «Parij Bibi Maryam ibodatxonasi» asarida qaysi asr Frantsiyasini tasvirlagan?", "options": ["XV asr (1482-yil Parij)", "XIX asr", "XII asr", "XVIII asr"], "correct": 0, "era": "XV asr"},
    {"q": "Lev Tolstoy «Urush va tinchlik» romanida qaysi yillar tarixiy voqealarini tasvirlaydi?", "options": ["1805 – 1812-yillardagi Napoleon urushlari", "1853-yil Qrim urushi", "1914-yil", "1700-yil"], "correct": 0, "era": "1805–1812"},
    {"q": "Fyodor Dostoyevskiy «Jinoyat va jazo» romanini nechanchi yilda nashr ettirgan?", "options": ["1866-yil (XIX asr)", "1890-yil", "1840-yil", "1905-yil"], "correct": 0, "era": "1866-yil"},
    {"q": "Ernest Xeminguey «Chol va dengiz» qissasini qaysi yilda yozib, Nobel mukofotiga sazovor bo'lgan?", "options": ["1952-yil (XX asr o'rtalari)", "1925-yil", "1970-yil", "1940-yil"], "correct": 0, "era": "1952-yil"},
    {"q": "Chingiz Aytmatov «Jamila» qissasini nechanchi yilda yozgan?", "options": ["1958-yil", "1975-yil", "1945-yil", "1990-yil"], "correct": 0, "era": "1958-yil"},
    {"q": "Gabriel Garsia Markes «Yuz yillik yolg'izlik» asarini nechanchi yilda chop ettirgan?", "options": ["1967-yil", "1950-yil", "1985-yil", "1930-yil"], "correct": 0, "era": "1967-yil"},
    {"q": "Jorj Oruell «1984» antiutopik romanini nechanchi yilda yozib tugatgan?", "options": ["1948-yil (nashri 1949-yil)", "1930-yil", "1965-yil", "1984-yil"], "correct": 0, "era": "1948-yil"},
    {"q": "Antuan de Sent-Ekzyuperi «Kichkina Shahzoda» ertak-qissasini qaysi yilda yozgan?", "options": ["1942 – 1943-yillar (Ikkinchi jahon urushi davri)", "1920-yil", "1955-yil", "1935-yil"], "correct": 0, "era": "1942–1943"},
    {"q": "Somoniylar davri va Buxoroda ilk kutubxonalar gullab-yashnagan asrlar:", "options": ["IX – X asrlar (Rudakiy va Ibn Sino davri)", "XIV asr", "VII asr", "XII asr"], "correct": 0, "era": "IX – X asr"},
    {"q": "G'aznaviylar davlatida Abu Rayhon Beruniy qaysi hukmdor saroyida faoliyat olib borgan?", "options": ["Sulton Mahmud G'aznaviy (XI asr)", "Alp Arslon", "Sanjar", "Temur Malik"], "correct": 0, "era": "XI asr"},
    {"q": "Xorazm Ma'mun akademiyasi faoliyat ko'rsatgan davr:", "options": ["X asr oxiri — XI asr boshlari (1004–1017-yillar)", "XIV asr", "VIII asr", "XV asr"], "correct": 0, "era": "1004–1017"},
    {"q": "Jaloliddin Manguberdi mo'g'ul bosqinchilariga qarshi qaysi yillarda mardonavor kurashgan?", "options": ["1220 – 1231-yillar (XIII asr)", "1150 – 1160-yillar", "1300 – 1315-yillar", "1370 – 1385-yillar"], "correct": 0, "era": "1220–1231"},
    {"q": "O'zbekiston Milliy universiteti (dastlabki Turkiston davlat universiteti) nechanchi yilda tashkil topgan?", "options": ["1918 – 1920-yillar", "1905-yil", "1945-yil", "1935-yil"], "correct": 0, "era": "1918–1920"},
    {"q": "O'zbekiston Fanlar akademiyasi qaysi yilda tashkil etilgan?", "options": ["1943-yil (Qori Niyoziy birinchi prezident)", "1925-yil", "1960-yil", "1930-yil"], "correct": 0, "era": "1943-yil"}
]
