# -*- coding: utf-8 -*-
"""So'z Qulfi (Word Lock) — adabiy so'zlar va atamalarning qulflangan harflarini topish."""

WORDLOCK_QUESTIONS = [
    {"word": "XAMSA", "hint": "Alisher Navoiyning 5 dostondan iborat shoh asari", "distractors": ["DEVON", "QISSA", "G'AZAL", "MASNAVIY"]},
    {"word": "OTABEK", "hint": "«O'tkan kunlar» romanidagi bosh erkak qahramon", "distractors": ["ANVAR", "HOMID", "HOSHIM", "AKROM"]},
    {"word": "KUMUSH", "hint": "Marg'ilonlik o'zbek iffati va vafo timsoli bo'lgan qahramon", "distractors": ["ZAYNAB", "RA'NO", "DILBAR", "LAYLI"]},
    {"word": "SIMURG'", "hint": "«Lison ut-tayr»dagi 30 qush izlagan afsonaviy shoh qush", "distractors": ["HUMO", "BULBUL", "QARCHIG'AY", "TOVUS"]},
    {"word": "SHUM BOLA", "hint": "G'afur G'ulomning mashhur sarguzasht qissasi bosh qahramoni", "distractors": ["HOSHIMJON", "ORIQ BOLA", "QORAVOY", "DONO BOLA"]},
    {"word": "ALPOMISH", "hint": "Barchinoyning vafodor yori, Qo'ng'irot eli bahodiri", "distractors": ["GORO'G'LI", "RUSTAM", "KUNTUG'MISh", "TO'MARIS"]},
    {"word": "BOBURNOMA", "hint": "Zahiriddin Muhammad Boburning shoh ensiklopedik xotira asari", "distractors": ["SHAJARA", "ZAFARNOMA", "TARIX", "MUXTASAR"]},
    {"word": "MEHROB", "hint": "Abdulla Qodiriyning ikkinchi romani nomidagi muqaddas joy", "distractors": ["MINBAR", "MASJID", "QASR", "SAROY"]},
    {"word": "NAVOIY", "hint": "«G'azal mulkining sultoni» deb e'tirof etilgan buyuk mutafakkir", "distractors": ["BOBUR", "JOMIY", "LUTFIY", "ATOIY"]},
    {"word": "QUTADG'U", "hint": "Yusuf Xos Hojibning «Baxt keltiruvchi bilim» asari nomi", "distractors": ["HIBAT", "LUG'AT", "DEVON", "MAHBUB"]},
    {"word": "CHO'LPON", "hint": "«Kecha va kunduz» romani muallifi bo'lgan otashin shoir", "distractors": ["FITRAT", "USMON", "BOTU", "AVFIY"]},
    {"word": "FITRAT", "hint": "«Chin sevish», «Hind ixtilolchilari» asarlarining jadid muallifi", "distractors": ["BEHBUDIY", "AVLONIY", "QODIRIY", "HAMZA"]},
    {"word": "MASNAVIY", "hint": "Mavlono Jaloliddin Rumiyning ma'naviy durdona asari", "distractors": ["GULISTON", "BOSTON", "RUBОIY", "QASIDA"]},
    {"word": "GULISTON", "hint": "Shayx Sa'diy Sheroziyning axloqiy hikoyatlar to'plami", "distractors": ["BAHORISTON", "SEHRISTON", "NIGORISTON", "SHOHISTON"]},
    {"word": "TEMUR", "hint": "«Kuch — adolatdadir» shioriga amal qilgan buyuk jahongir sohibqiron", "distractors": ["ULUG'BEK", "BOBUR", "SHOHRUH", "XUDOYOR"]},
    {"word": "ULUG'BEK", "hint": "Samarqandda yulduzlar jadvalini tuzgan alloma hukmdor", "distractors": ["BERUNIY", "XORAZMIY", "FARG'ONIY", "QOZIZODA"]},
    {"word": "BERUNIY", "hint": "«Qadimgi xalqlardan qolgan yodgorliklar» asari muallifi", "distractors": ["IBN SINO", "FOROBIY", "XORAZMIY", "KOSHIFIY"]},
    {"word": "IBN SINO", "hint": "G'arbda «Avitsenna» nomi bilan e'zozlangan buyuk tabib", "distractors": ["ROZIY", "BERUNIY", "FARG'ONIY", "TUHSIY"]},
    {"word": "FOROBIY", "hint": "Sharq falsafasida «Muallimi Soniy» (Ikkinchi muallim) deb atalgan zot", "distractors": ["ARASTU", "AFLOTUN", "SOKRAT", "G'AZZOLIY"]},
    {"word": "G'AZZOLIY", "hint": "«Ihyou ulumiddin» va «Kimyoi saodat» asarlari muallifi", "distractors": ["MOTURIDIY", "NASAFIY", "ZAMAXSHARIY", "SAM'ONIY"]},
    {"word": "BUXORIY", "hint": "Eng ishonchli hadislar to'plami «Al-Jome' as-Sahih» sohibi", "distractors": ["TERMIZIY", "MUSLIM", "NASOIY", "IBN MOJA"]},
    {"word": "TERMIZIY", "hint": "«Sunani Termiziy» va «Shamoili Muhammadiyya» muallifi", "distractors": ["BUXORIY", "DORIMIY", "BAYHAQIY", "TOHIRIY"]},
    {"word": "MOTURIDIY", "hint": "Samarqandda ahl as-sunna kalom ta'limotiga asos solgan imom", "distractors": ["ASH'ARIY", "NASAFIY", "PAZDAVIDIY", "KOSONIY"]},
    {"word": "ZAMAXSHARIY", "hint": "«Al-Kashshof» tafsiri muallifi, «Jorulloh» unvoni sohibi", "distractors": ["BAYDOVIY", "TABARIY", "ROZIY", "QURTUBIY"]},
    {"word": "YASSAVIY", "hint": "Turkistonda «Devoni hikmat» yaratgan tasavvuf piri", "distractors": ["NAQSHBAND", "G'IJDUVONIY", "KUBRO", "ZANGIOTA"]},
    {"word": "NAQSHBAND", "hint": "«Dil ba yoru, dast ba kor» shiorini bergan buyuk pir", "distractors": ["YASSAVIY", "KUBRO", "SHOSHIY", "SAMARQANDIY"]},
    {"word": "KUBRO", "hint": "Mo'g'ul bosqinchilariga qarshi qo'lida bayroq bilan shahid bo'lgan pir", "distractors": ["YASSAVIY", "NAQSHBAND", "G'IJDUVONIY", "KULOL"]},
    {"word": "MANGUBERDI", "hint": "Chingizxonga qarshi mardonavor jang qilgan Xorazmshohlar sarkardasi", "distractors": ["TEMUR MALIK", "MUQANNA", "SHIROQ", "SPITAMEN"]},
    {"word": "TO'MARIS", "hint": "Eron shohi Kir II bosqinini tor-mor etgan massagetlar malikasi", "distractors": ["ZARINA", "ROXANA", "BARDOH", "PO'LATXON"]},
    {"word": "SHIROQ", "hint": "Doro qo'shinini dasht ichkarisiga adashtirib boshlagan cho'pon", "distractors": ["TO'MARIS", "SPITAMEN", "MUQANNA", "ALPOMISH"]},
    {"word": "SPITAMEN", "hint": "Iskandar Zulqarnayn (Makedonskiy)ga qarshi So'g'diyona mudofaachisi", "distractors": ["SHIROQ", "MUQANNA", "MANGUBERDI", "TEMUR MALIK"]},
    {"word": "MUQANNA", "hint": "Oq kiyimlilar qo'zg'oloni rahbari bo'lgan tarixiy shaxs", "distractors": ["SPITAMEN", "SHIROQ", "MAHMUD TOROBIY", "PO'LATXON"]},
    {"word": "TOROBIY", "hint": "1238-yilda Buxoroda mo'g'ul zulmiga qarshi xalqni boshlagan hunarmand", "distractors": ["MUQANNA", "MANGUBERDI", "SHIROQ", "TEMUR MALIK"]},
    {"word": "BEHBUDIY", "hint": "Turkiston jadidchilik harakati otasi, «Padarkush» muallifi", "distractors": ["AVLONIY", "FITRAT", "CHO'LPON", "MUNAVVARQORI"]},
    {"word": "AVLONIY", "hint": "«Turkiy Guliston» muallifi, «Ibratxona» teatri asoschisi", "distractors": ["BEHBUDIY", "HAMZA", "QODIRIY", "OYBEK"]},
    {"word": "OYBEK", "hint": "«Qutlug' qon», «Navoiy» romanlarining lirik adibi", "distractors": ["G'AFUR G'ULOM", "HAMID OLIMJON", "ABDULLA QAHHOR", "SAID AHMAD"]},
    {"word": "QAHHOR", "hint": "O'zbek hikoyachiligi ustasi, «O'g'ri», «Anor», «Sinchalak» muallifi", "distractors": ["OYBEK", "G'ULOM", "HOSHIMOV", "MALIK"]},
    {"word": "HOSHIMOV", "hint": "«Ikki eshik orasi», «Dunyoning ishlari» romanlarining ardoqli adibi", "distractors": ["QAHHOR", "MALIK", "MUROD", "SAID AHMAD"]},
    {"word": "VOHIDOV", "hint": "«O'zbegim» qasidasi va «Ruhlar isyoni» dostoni muallifi", "distractors": ["ORIPOV", "YUSUF", "MATJON", "DAVRON"]},
    {"word": "ORIPOV", "hint": "O'zbekiston Respublikasi Davlat madhiyasi matni muallifi", "distractors": ["VOHIDOV", "YUSUF", "XUDOYBERDIYEVA", "CHO'LPON"]},
    {"word": "YUSUF", "hint": "«Biz baxtli bo'lamiz», «Lolaqizg'aldoq» she'rlari bilan tanilgan xalq shoiri", "distractors": ["ORIPOV", "VOHIDOV", "MATJON", "DAVRON"]},
    {"word": "MALIK", "hint": "«Shaytanat», «Falak», «Murdalar gapirmaydilar» asarlari muallifi", "distractors": ["HOSHIMOV", "MUROD", "QAHHOR", "SAID AHMAD"]},
    {"word": "TOG'AY MUROD", "hint": "«Otamdan qolgan dalalar», «Bu dunyoda o'lib bo'lmaydi» muallifi", "distractors": ["SHUKUR XOLMIRZAYEV", "O'TKIR HOSHIMOV", "MUROD MUHAMMAD DO'ST", "ERKIN A'ZAM"]},
    {"word": "SHEKSPIR", "hint": "«Gamlet», «Otello», «Qirol Lir» fojialarining ingliz dahosi", "distractors": ["GYOTE", "DANTE", "BAYRON", "MOLER"]},
    {"word": "SERVANTES", "hint": "«Don Kixot» asarini yaratgan buyuk ispan adibi", "distractors": ["LORKA", "MARKES", "BORXES", "LOPE DE VEGA"]},
    {"word": "DANTE", "hint": "«Ilohiy komediya» dostoni muallifi bo'lgan italyan adibi", "distractors": ["BOKKACHCHO", "PETRARKA", "MAKYAVELLI", "TORQUATO"]},
    {"word": "GYOTE", "hint": "«Faust» tragediyasi muallifi bo'lgan nemis mutafakkiri", "distractors": ["SHILLER", "GEYNE", "KANT", "GEGEL"]},
    {"word": "TOLSTOY", "hint": "«Urush va tinchlik», «Anna Karenina», «Tirilish» muallifi", "distractors": ["DOSTOYEVSKIY", "CHEXOV", "TURGENEV", "PUSHKIN"]},
    {"word": "DOSTOYEVSKIY", "hint": "«Jinoyat va jazo», «Aka-uka Karamazovlar», «Idiot» muallifi", "distractors": ["TOLSTOY", "GOGOL", "TURGENEV", "GORKIY"]},
    {"word": "CHEXOV", "hint": "Qisqa hikoyalar va «Giloszor» pyesasining rus ustasi", "distractors": ["GOGOL", "DOSTOYEVSKIY", "TOLSTOY", "BUNIN"]},
    {"word": "PUSHKIN", "hint": "«Yevgeniy Onegin», «Kapitan qizi» asarlari muallifi bo'lgan shoir", "distractors": ["LERMONTOV", "NEKRASOV", "YESENIN", "BLOK"]},
    {"word": "XEMINGUEY", "hint": "«Chol va dengiz», «Alvido, qurol!» asarlari uchun Nobel olgan adib", "distractors": ["FOLKNER", "FITSJERALD", "STEYNBEK", "LONDON"]},
    {"word": "AYTMATOV", "hint": "«Asrga tatigulik kun», «Qiyomat», «Oq kema» asarlari muallifi", "distractors": ["RASUL GAMZATOV", "MUSTAY KARIM", "OLJAS SULAYMONOV", "ABAY"]},
    {"word": "MARKES", "hint": "«Yuz yillik yolg'izlik», «Oshkora qotillik qissasi» muallifi", "distractors": ["KORTASAR", "BORXES", "KOELO", "RULFO"]},
    {"word": "ORUELL", "hint": "«1984» va «Molxona» antiutopik romanlari muallifi", "distractors": ["XAKSLI", "BRED BERI", "KAFKA", "KAMYU"]},
    {"word": "KAFKA", "hint": "«Evrilish», «Jarayon», «Qasr» asarlari muallifi bo'lgan pragalik adib", "distractors": ["KAMYU", "SARTRE", "JONS", "MANNN"]},
    {"word": "KAMYU", "hint": "«Begona», «Vabo», «Sizif haqida afsona» muallifi bo'lgan faylasuf", "distractors": ["SARTRE", "KAFKA", "FUKO", "DERRIDA"]},
    {"word": "EKZYUPERI", "hint": "«Kichkina Shahzoda», «Insonlar zamini» muallifi bo'lgan uchuvchi", "distractors": ["GYUGO", "MOPASSAN", "BALZAK", "FLOBER"]},
    {"word": "GYUGO", "hint": "«Xo'rlanganlar», «Parij Bibi Maryam ibodatxonasi» muallifi", "distractors": ["DYUMA", "BALZAK", "STENDAL", "ZOLYA"]},
    {"word": "KONAN DOYL", "hint": "Sherlok Xolms va Doktor Vatson sarguzashtlari ijodkori", "distractors": ["AGATA KRISTI", "EDGAR PO", "STIVENSON", "CHEZTERTON"]}
]
