# Generated by Django 4.2.16 on 2024-12-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0009_alter_confirmationreport_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="gender",
            field=models.BooleanField(
                default=False, help_text="False for females, True for males"
            ),
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=6,
                null=True,
            ),
        ),
    ]
