# Generated by Django 4.2.16 on 2025-01-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0010_group_gender_telegramprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Group is deleted ?"),
        ),
    ]
