# Generated by Django 5.0.12 on 2025-02-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0012_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="days_completed",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Days of performing this habit"
            ),
        ),
    ]
