# Generated by Django 5.0.12 on 2025-02-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0013_habit_days_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="days_completed",
        ),
        migrations.AddField(
            model_name="habit",
            name="completed_days",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Completed days"
            ),
        ),
    ]
