# Generated by Django 5.0.12 on 2025-02-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0014_remove_habit_days_completed_habit_completed_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField(verbose_name="Time")),
            ],
            options={
                "verbose_name": "Hour",
                "verbose_name_plural": "Hours",
            },
        ),
        migrations.AddField(
            model_name="habit",
            name="hours",
            field=models.ManyToManyField(
                related_name="habits", to="tgbot.hour", verbose_name="Reminder hours"
            ),
        ),
    ]
