# Generated by Django 5.0.12 on 2025-02-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0015_hour_habit_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reminders_per_day",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Number of daily reminders"
            ),
        ),
    ]
