# Generated by Django 4.2.19 on 2025-02-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0016_alter_habit_reminders_per_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Region Name")),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "db_table": "regions",
            },
        ),
        migrations.RemoveField(
            model_name="blockeduser",
            name="user",
        ),
        migrations.DeleteModel(
            name="Media",
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
        migrations.AddField(
            model_name="confirmationreport",
            name="spent_time",
            field=models.IntegerField(
                null=True, verbose_name="Spent time (in minutes)"
            ),
        ),
        migrations.DeleteModel(
            name="BlockedUser",
        ),
        migrations.AddField(
            model_name="telegramprofile",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="tgbot.region",
                verbose_name="Region",
            ),
        ),
    ]
