# Generated by Django 5.0.12 on 2025-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0017_region_remove_blockeduser_user_delete_media_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="notification_must_be_sent",
            field=models.BooleanField(
                default=True, verbose_name="Notification must be sent"
            ),
        ),
    ]
