# Generated by Django 5.0.12 on 2025-03-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0018_habit_notification_must_be_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="ball",
            field=models.IntegerField(default=0, verbose_name="Ball"),
        ),
    ]
