# Generated by Django 5.0.12 on 2025-03-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0020_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramprofile",
            name="ball",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Ball"
            ),
        ),
    ]
