# Generated by Django 5.0.14 on 2026-01-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0022_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmationreport',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Xulosa'),
        ),
    ]
