# Generated by Django 5.0.14 on 2026-01-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0023_confirmationreport_conclusion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="chat_id",
            field=models.CharField(
                db_index=True,
                default="-1002237773868",
                max_length=255,
                verbose_name="Chat ID",
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="telegram_id",
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
