# Generated by Django 5.0.14 on 2026-01-18 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0024_alter_group_chat_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BooksToRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255)),
                ("total_pages", models.PositiveIntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tgbot.telegramprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book to read",
                "verbose_name_plural": "Books to read",
                "db_table": "books_to_read",
            },
        ),
        migrations.AddField(
            model_name="confirmationreport",
            name="books",
            field=models.ManyToManyField(
                blank=True, to="tgbot.bookstoread", verbose_name="Books"
            ),
        ),
    ]
