# Generated by Django 5.0.14 on 2026-01-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0025_bookstoread_confirmationreport_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramprofile",
            name="referral_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Referral Code",
            ),
        ),
        migrations.CreateModel(
            name="UserReferal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "referred_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_by",
                        to="tgbot.telegramprofile",
                        verbose_name="Referred User",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="tgbot.telegramprofile",
                        verbose_name="Referrer",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Referral",
                "verbose_name_plural": "User Referrals",
                "db_table": "user_referrals",
            },
        ),
    ]
