# Generated by Django 5.0.14 on 2026-01-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0027_contest_quiz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="name",
        ),
    ]
