# Generated by Django 5.0.14 on 2026-01-22 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0028_remove_quiz_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("options", models.JSONField(verbose_name="Options")),
                (
                    "correct_option",
                    models.PositiveSmallIntegerField(
                        help_text="Index of the correct option in the options list (starts from 0)",
                        verbose_name="Correct Option Index",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, null=True, verbose_name="Explanation"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Order")),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="tgbot.contest",
                        verbose_name="Contest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "db_table": "questions",
                "ordering": ["order"],
            },
        ),
    ]
