# Generated by Django 5.0.14 on 2026-01-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0029_question"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramprofile",
            name="bot",
        ),
    ]
