# Generated by Django 5.0.14 on 2026-01-22 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0030_remove_telegramprofile_bot"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="is_finished",
            field=models.BooleanField(default=False, verbose_name="Is Finished"),
        ),
        migrations.AddField(
            model_name="contest",
            name="req_referrals",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Required Referrals"
            ),
        ),
        migrations.CreateModel(
            name="ContestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("total_score", models.IntegerField(default=0)),
                (
                    "total_time",
                    models.FloatField(default=0.0, help_text="Total time in seconds"),
                ),
                ("is_finished", models.BooleanField(default=False)),
                ("current_question_index", models.IntegerField(default=0)),
                ("last_question_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="tgbot.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_participations",
                        to="tgbot.telegramprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContestSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("selected_option", models.IntegerField()),
                ("is_correct", models.BooleanField(default=False)),
                ("time_taken", models.FloatField(help_text="Time taken in seconds")),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="tgbot.contestparticipant",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tgbot.question"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Quiz",
        ),
        migrations.AddIndex(
            model_name="contestparticipant",
            index=models.Index(
                fields=["contest", "total_score", "total_time"],
                name="tgbot_conte_contest_444e9b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contestparticipant",
            unique_together={("contest", "user")},
        ),
        migrations.AddIndex(
            model_name="contestsubmission",
            index=models.Index(
                fields=["participant", "question"],
                name="tgbot_conte_partici_92e6ce_idx",
            ),
        ),
    ]
