# Generated by Django 5.0.14 on 2026-01-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0031_contest_is_finished_contest_req_referrals_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="is_notified",
            field=models.BooleanField(default=False, verbose_name="Is Notified"),
        ),
    ]
