# Generated by Django 5.0.14 on 2026-01-24 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0032_contest_is_notified"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "poll_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tgbot.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_states",
                        to="tgbot.telegramprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll State",
                "verbose_name_plural": "Poll States",
                "db_table": "poll_states",
            },
        ),
    ]
