# Generated by Django 5.0.14 on 2026-01-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0033_pollstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="is_started",
            field=models.BooleanField(default=False, verbose_name="Is Started"),
        ),
    ]
