# Generated by Django 5.0.14 on 2026-01-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0034_contest_is_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="notification_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Notification Date"
            ),
        ),
        migrations.AddField(
            model_name="contest",
            name="notification_task_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Notification Task ID",
            ),
        ),
    ]
