# Generated by Django 5.0.14 on 2026-01-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0035_contest_notification_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contest",
            name="start_task_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Start Task ID"
            ),
        ),
    ]
