# Generated by Django 5.0.14 on 2026-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbot", "0036_contest_start_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookstoread",
            name="current_page",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
