# Generated by Django 5.2.9 on 2026-06-01 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0060_shop_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(default='3 Kunlik Referal BOOM', max_length=200)),
                ('start_at', models.DateTimeField(verbose_name='Start')),
                ('end_at', models.DateTimeField(verbose_name='End')),
                ('tier1_reward', models.PositiveIntegerField(default=150, help_text='Kitobcha per referral for the first tier1_cap referrals.')),
                ('tier1_cap', models.PositiveIntegerField(default=10, help_text='Referrals up to and including this count earn tier1_reward.')),
                ('tier2_reward', models.PositiveIntegerField(default=300, help_text='Kitobcha per referral once tier1_cap is exceeded.')),
                ('total_reminders', models.PositiveIntegerField(default=21, help_text='How many playful reminders each participant receives across the window.')),
                ('is_active', models.BooleanField(default=False)),
                ('announced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Referral BOOM',
                'verbose_name_plural': 'Referral BOOMlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReferralBoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('rules_sent', models.BooleanField(default=False, help_text='True once the welcome+rules DM has been sent (sent exactly once).')),
                ('referrals_count', models.PositiveIntegerField(default=0, help_text='Referrals brought in DURING this boom window.')),
                ('kitobcha_earned', models.PositiveIntegerField(default=0, help_text='Total boom-bonus Kitobcha earned by this participant.')),
                ('reminder_schedule', models.JSONField(default=list, help_text='Ascending list of ISO datetimes when reminders fire.')),
                ('reminders_sent', models.PositiveIntegerField(default=0, help_text='Pointer into reminder_schedule — index of the next reminder to send.')),
                ('used_reminder_keys', models.JSONField(default=list, help_text='Template keys already used, to avoid repeating copy.')),
                ('boom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tgbot.referralboom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boom_participations', to='tgbot.telegramprofile')),
            ],
            options={
                'verbose_name': 'Referral BOOM Qatnashchisi',
                'verbose_name_plural': 'Referral BOOM Qatnashchilari',
                'unique_together': {('boom', 'user')},
            },
        ),
    ]
