# Generated by Django 5.2.9 on 2026-06-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0061_referral_boom'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralboom',
            name='is_queued',
            field=models.BooleanField(default=False, help_text='If set, the next regular 3-day challenge rotation launches this boom instead of a normal challenge (then resumes the pool).'),
        ),
    ]
