# Generated by Django 5.2.9 on 2026-06-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0062_referralboom_is_queued'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderTitleAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('winners', models.JSONField(default=list, help_text='List of {"k": category_key, "t": winner_telegram_id}.')),
                ('congratulators', models.JSONField(default=list, help_text='Telegram ids who already congratulated (dedupe).')),
            ],
            options={
                'verbose_name': 'Reader Title Announcement',
                'verbose_name_plural': 'Reader Title Announcements',
                'ordering': ('-created_at',),
            },
        ),
    ]
