# Generated by Django 5.2.9 on 2026-07-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0072_emoji_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaingame',
            name='pending',
            field=models.JSONField(blank=True, default=None, help_text='Candidate awaiting a crowd vote: {"norm","display","user_id","name","letter","last_letter","started_at","yes":[ids],"no":[ids]}.', null=True),
        ),
        migrations.AddField(
            model_name='chaingame',
            name='rejected_norms',
            field=models.JSONField(default=list, help_text='Norms voted down for the CURRENT letter — blocked from resubmission until the letter advances.'),
        ),
        migrations.CreateModel(
            name='GameSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slot', models.CharField(choices=[('morning', '10:00'), ('evening', '22:00')], max_length=10)),
                ('date', models.DateField()),
                ('game_types', models.JSONField(default=list, help_text='3 randomly chosen, non-repeating game types for this slot.')),
                ('current_index', models.PositiveSmallIntegerField(default=0)),
                ('current_game_type', models.CharField(blank=True, default='', max_length=10)),
                ('current_game_id', models.PositiveIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Kunlik O'yin Ketma-ketligi",
                'verbose_name_plural': "Kunlik O'yin Ketma-ketliklari",
                'db_table': 'game_sequences',
                'ordering': ('-date', 'slot'),
                'unique_together': {('slot', 'date')},
            },
        ),
    ]
