# Generated by Django 5.2.9 on 2026-07-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0073_chaingame_pending_chaingame_rejected_norms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='trial_premium_until',
            field=models.DateTimeField(blank=True, help_text='If set and in the future, the user has temporary trial Premium (e.g. from the daily random giveaway) — see has_active_premium() and tasks.grant_daily_trial_premium.', null=True),
        ),
    ]
