# Generated by Django 5.2.9 on 2026-07-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0075_detectivegame_quizgame_survivalgame_wisdomgame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='flavor',
            field=models.CharField(choices=[('twofacts', "Ikki haqiqat, bir yolg'on"), ('impostor', "Kim yolg'onchi?"), ('connection', "Yashirin bog'lanish"), ('teams', 'Jamoa Jangi'), ('timeline', 'Vaqt Mashinasi'), ('matchbook', 'Muallif-Asar Moslashtirish'), ('reverse', 'Teskari Viktorina')], max_length=12),
        ),
    ]
