# Generated by Django 5.2.9 on 2026-07-23 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0076_alter_castlegame_id_alter_castlehit_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('years_reading', models.CharField(blank=True, max_length=20, null=True)),
                ('wishes_text', models.TextField(blank=True, null=True)),
                ('books_per_year', models.CharField(blank=True, max_length=20, null=True)),
                ('suggestions_text', models.TextField(blank=True, null=True)),
                ('suggestions_content_type', models.CharField(blank=True, max_length=20, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('rewarded', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey_response', to='tgbot.telegramprofile')),
            ],
            options={
                'db_table': 'project_survey_responses',
                'ordering': ('-created_at',),
            },
        ),
    ]
