# Generated by Django 5.2.9 on 2026-07-26 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0083_bookcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='bonus_survival_lives',
            field=models.PositiveSmallIntegerField(default=0, help_text="Extra starting lives for the next Omon qolish (Survival) game, from a Market 'Sirli quti' win. Consumed on join."),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='streak_freeze_count',
            field=models.PositiveIntegerField(default=0, help_text="Banked 'streak muzlatish' tokens from the Market. Auto-consumed by tasks.apply_streak_freezes on the first day the user misses a report while holding a token — see StreakFreezeCoverage."),
        ),
        migrations.CreateModel(
            name='LeaderboardSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_sponsorships', to='tgbot.telegramprofile')),
            ],
            options={
                'verbose_name': 'Leaderboard Sponsor',
                'verbose_name_plural': 'Leaderboard Sponsors',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='StreakFreezeCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_freeze_coverages', to='tgbot.telegramprofile')),
            ],
            options={
                'verbose_name': 'Streak Freeze Coverage',
                'verbose_name_plural': 'Streak Freeze Coverages',
                'ordering': ('-date',),
                'unique_together': {('user', 'date')},
            },
        ),
    ]
