# Generated by Django 5.2.9 on 2026-07-28 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0084_telegramprofile_bonus_survival_lives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('item_key', models.CharField(help_text="market_service.ITEMS key, e.g. 'mystery_box'.", max_length=30)),
                ('price', models.PositiveIntegerField(help_text='Kitobcha charged for this purchase.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_purchases', to='tgbot.telegramprofile')),
            ],
            options={
                'verbose_name': 'Market Purchase',
                'verbose_name_plural': 'Market Purchases',
                'ordering': ('-created_at',),
            },
        ),
    ]
