# Generated by Django 5.2.9 on 2026-07-28 23:02
# Hand-trimmed: makemigrations also proposed AlterField ops on ~30 unrelated
# tables (stray id AutoField->BigAutoField drift, plus help_text-only diffs
# on chaingame/chainscore) that are pre-existing environment noise, not part
# of this change — see feedback_makemigrations_stray_id_alters. Only the new
# model is kept here, with a plain AutoField id to match the existing
# convention rather than picking up BigAutoField from the stale
# DEFAULT_AUTO_FIELD setting.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0085_alter_bookcomment_id_alter_castlegame_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitobchaLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('delta', models.IntegerField(help_text='Positive = earned, negative = spent.')),
                ('reason', models.CharField(blank=True, default='', max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitobcha_ledger_entries', to='tgbot.telegramprofile')),
            ],
            options={
                'verbose_name': 'Kitobcha Ledger Entry',
                'verbose_name_plural': 'Kitobcha Ledger Entries',
                'ordering': ('-created_at',),
            },
        ),
    ]
