# Generated by Django 5.2.9 on 2026-07-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0086_kitobchaledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='trial_ai_quiz_until',
            field=models.DateTimeField(blank=True, help_text="If set and in the future, this non-Premium user may create AI quizzes for a 1-hour window — see tasks.grant_daily_ai_quiz_trial and quiz_admin.py's 'ai' action gate.", null=True),
        ),
    ]
