# Generated by Django 5.2.9 on 2026-07-29 00:08
# Hand-trimmed: makemigrations also proposed an unrelated AddField
# (telegramprofile.free_ai_quiz_used, from other in-progress work not part
# of this change) plus the usual stray id AutoField->BigAutoField /
# help_text-only AlterField noise across ~30 unrelated tables — see
# feedback_makemigrations_stray_id_alters. Only the new model is kept here,
# with a plain AutoField id to match the existing convention.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0087_telegramprofile_trial_ai_quiz_until_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('chat_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='False once the bot loses admin rights or is removed — stops broadcasts without deleting history.')),
            ],
            options={
                'verbose_name': 'Broadcast Group',
                'verbose_name_plural': 'Broadcast Groups',
                'db_table': 'broadcast_groups',
            },
        ),
    ]
