# Generated by Django 5.2.9 on 2026-07-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0088_broadcastgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='free_ai_quiz_used',
            field=models.BooleanField(default=False, help_text="Every non-Premium user gets exactly ONE free lifetime AI quiz generation (separate from the daily trial-window giveaway) — set True the moment they use it. See quiz_admin.py's 'ai' action gate."),
        ),
    ]
