# Generated by Django 5.2.9 on 2026-07-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0089_telegramprofile_free_ai_quiz_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstoread',
            name='active_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookstoread',
            name='credited_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookstoread',
            name='fee_charged',
            field=models.BooleanField(default=False, help_text='Whether the one-time start fee was already deducted.'),
        ),
        migrations.AddField(
            model_name='bookstoread',
            name='max_page_reached',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookstoread',
            name='page_reward_total_granted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookstoread',
            name='topped_up',
            field=models.BooleanField(default=False),
        ),
    ]
