# Generated by Django 5.2.9 on 2026-07-29 19:26
# Hand-trimmed: makemigrations also proposed the usual stray id
# AutoField->BigAutoField / help_text-only AlterField noise across ~30
# unrelated tables (see feedback_makemigrations_stray_id_alters) -- only
# the ReferralBoom changes are kept here.

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0091_siteevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralboom',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional banner sent with the welcome DM when someone joins (sendPhoto + caption instead of a plain text message).', null=True, upload_to='referral_boom/'),
        ),
        migrations.AddField(
            model_name='referralboom',
            name='planned_days',
            field=models.PositiveIntegerField(default=3, help_text="Duration once launched via the '🚀 Hozir e'lon qilish' admin action on this row (start_at/end_at below are placeholders until then)."),
        ),
        migrations.AlterField(
            model_name='referralboom',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='referralboom',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start'),
        ),
    ]
