# Generated by Django 5.2.9 on 2026-07-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0091_referralboom_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('event_type', models.CharField(choices=[('pageview', "Sahifa ko'rish"), ('click', 'Tugma bosish')], db_index=True, max_length=10)),
                ('section', models.CharField(db_index=True, help_text="e.g. 'site', 'library', 'quiz-impostor'.", max_length=32)),
                ('label', models.CharField(blank=True, default='', help_text='Button text/id — empty for pageviews.', max_length=120)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_events', to='tgbot.telegramprofile')),
            ],
            options={
                'verbose_name': 'Sayt Statistikasi — Hodisa',
                'verbose_name_plural': 'Sayt Statistikasi — Hodisalar',
                'db_table': 'site_events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_type', 'section', 'created_at'], name='site_events_event_t_368d81_idx')],
            },
        ),
    ]
