# Generated by Django 5.2.9 on 2026-07-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0092_siteevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralboom',
            name='announce_text',
            field=models.TextField(blank=True, default='', help_text='Custom launch-announcement copy (HTML allowed). If blank, an auto-generated announcement is used instead.'),
        ),
        migrations.AlterField(
            model_name='referralboom',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional banner sent with the welcome DM when someone joins, and with the initial launch announcement (sendPhoto + caption instead of a plain text message).', null=True, upload_to='referral_boom/'),
        ),
    ]
