# Generated by Django 5.2.9 on 2026-07-31 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0093_referralboom_announce_text_alter_bookcomment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralboom',
            name='planned_days',
            field=models.PositiveIntegerField(default=7, help_text="Duration once launched via the '🚀 Hozir e'lon qilish' admin action on this row (start_at/end_at below are placeholders until then)."),
        ),
        migrations.AlterField(
            model_name='referralboom',
            name='title',
            field=models.CharField(default='Yaxshilik ulashuvchi', max_length=200),
        ),
        migrations.CreateModel(
            name='AdminInboxThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('copies', models.JSONField(default=list, help_text='[{"admin_id": <telegram_id>, "header_message_id": <int>, "content_message_id": <int>}, ...] — one entry per admin the message was forwarded to.')),
                ('answered', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_inbox_threads', to='tgbot.telegramprofile')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_inbox_threads', to='tgbot.telegramprofile')),
            ],
            options={
                'verbose_name': 'Admin Inbox — Xabar',
                'verbose_name_plural': 'Admin Inbox — Xabarlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
