# Generated by Django 5.2.9 on 2026-07-31 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0094_alter_bookcomment_id_alter_broadcastgroup_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralboom',
            options={'ordering': ('-created_at',), 'verbose_name': 'Yaxshilik ulashuvchi', 'verbose_name_plural': 'Yaxshilik ulashuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='referralboomparticipant',
            options={'verbose_name': 'Yaxshilik ulashuvchi Qatnashchisi', 'verbose_name_plural': 'Yaxshilik ulashuvchi Qatnashchilari'},
        ),
        migrations.CreateModel(
            name='BookCoverRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('options', models.JSONField(default=list, help_text='The 4 shuffled book titles shown as answers.')),
                ('correct_index', models.PositiveSmallIntegerField(default=0)),
                ('reward', models.PositiveIntegerField(default=100, help_text='Kitobcha granted to each correct guesser.')),
                ('consolation', models.PositiveIntegerField(default=5, help_text='Kitobcha granted to wrong guessers as motivation.')),
                ('group_messages', models.JSONField(default=list, help_text='Posted group copies as [{"chat_id":…, "message_id":…}], edited live to show the right/wrong board.')),
                ('is_active', models.BooleanField(default=True, help_text='Only the latest round accepts answers; older ones are closed.')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_game_rounds', to='tgbot.globalbook')),
            ],
            options={
                'verbose_name': 'Kitob Muqovasi — Tur',
                'verbose_name_plural': 'Kitob Muqovasi — Turlar',
                'db_table': 'book_cover_rounds',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BookCoverAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('chosen_index', models.PositiveSmallIntegerField()),
                ('is_correct', models.BooleanField(default=False)),
                ('rewarded', models.BooleanField(default=False, help_text='True once the Kitobcha reward was paid out.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_cover_answers', to='tgbot.telegramprofile')),
                ('cover_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tgbot.bookcoverround')),
            ],
            options={
                'verbose_name': 'Kitob Muqovasi — Javob',
                'verbose_name_plural': 'Kitob Muqovasi — Javoblar',
                'db_table': 'book_cover_answers',
                'ordering': ('-created_at',),
                'unique_together': {('cover_round', 'user')},
            },
        ),
    ]
