# Generated by Django 5.2.9 on 2026-07-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0095_alter_referralboom_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcoverround',
            name='book',
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='flavor',
            field=models.CharField(choices=[('twofacts', "Ikki haqiqat, bir yolg'on"), ('impostor', "Kim yolg'onchi?"), ('connection', "Yashirin bog'lanish"), ('teams', 'Jamoa Jangi'), ('timeline', 'Vaqt Mashinasi'), ('matchbook', 'Muallif-Asar Moslashtirish'), ('reverse', 'Teskari Viktorina'), ('cover', 'Kitob Muqovasi')], max_length=12),
        ),
        migrations.DeleteModel(
            name='BookCoverAnswer',
        ),
        migrations.DeleteModel(
            name='BookCoverRound',
        ),
    ]
