# Generated by Django 5.2.9 on 2026-08-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0096_remove_bookcoverround_book_alter_bookcomment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file_id', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
