# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0097_welcomevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='bonus_free_game_entries',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Free live-game entries banked from a 'Sirli quti' win -- consumed one at a time by chain_game.charge_entry_fee instead of the normal Kitobcha entry fee, shared by every live game.",
            ),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='next_market_discount_pct',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Percent off the next Market purchase, from a 'Sirli quti' win. Consumed (reset to 0) on the next successful market.charge() call.",
            ),
        ),
    ]
