# Generated by Django 5.2.9

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0098_telegramprofile_bonus_free_game_entries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='ai_quiz_bonus_sent_at',
            field=models.DateTimeField(
                null=True,
                blank=True,
                db_index=True,
                help_text="When this user received the one-off site-wide AI-quiz make-good bonus (the qz:ai gate bug denied Sirli quti winners their prize). NULL = not yet reached by the drip. Set by services.ai_quiz_bonus.drip_ai_quiz_bonus, which paces the rollout at a fixed number of users per hour during waking hours.",
            ),
        ),
    ]
