# Generated by Django 5.2.9 on 2026-08-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0099_telegramprofile_ai_quiz_bonus_sent_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chainscore',
            options={'ordering': ('-points', 'total_time', 'created_at'), 'verbose_name': 'Kitob Zanjiri — Ball', 'verbose_name_plural': 'Kitob Zanjiri — Ballar'},
        ),
        migrations.AlterModelOptions(
            name='detectivescore',
            options={'ordering': ('-points', 'total_time', 'created_at'), 'verbose_name': 'Kitob Detektivi — Ball', 'verbose_name_plural': 'Kitob Detektivi — Ballar'},
        ),
        migrations.AlterModelOptions(
            name='emojiscore',
            options={'ordering': ('-points', 'total_time', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='feudscore',
            options={'ordering': ('-points', 'total_time', 'created_at')},
        ),
        migrations.AlterModelOptions(
            name='quizscore',
            options={'ordering': ('-points', 'total_time', 'created_at'), 'verbose_name': "Bilim O'yini — Ball", 'verbose_name_plural': "Bilim O'yini — Ballar"},
        ),
        migrations.AlterModelOptions(
            name='survivalplayer',
            options={'ordering': ('eliminated', '-correct_count', 'total_time', 'created_at'), 'verbose_name': "Omon qolish — O'yinchi", 'verbose_name_plural': "Omon qolish — O'yinchilar"},
        ),
        migrations.AlterModelOptions(
            name='wisdomscore',
            options={'ordering': ('-points', 'total_time', 'created_at'), 'verbose_name': 'Hikmat Xazinasi — Ball', 'verbose_name_plural': 'Hikmat Xazinasi — Ballar'},
        ),
        migrations.AddField(
            model_name='castlehit',
            name='time_taken',
            field=models.FloatField(default=0.0, help_text='Seconds taken to hit.'),
        ),
        migrations.AddField(
            model_name='chainscore',
            name='total_time',
            field=models.FloatField(default=0.0, help_text='Total solve time in seconds.'),
        ),
        migrations.AddField(
            model_name='detectivescore',
            name='total_time',
            field=models.FloatField(default=0.0, help_text='Total guess time in seconds.'),
        ),
        migrations.AddField(
            model_name='emojianswer',
            name='time_taken',
            field=models.FloatField(default=0.0, help_text='Seconds taken to submit answer.'),
        ),
        migrations.AddField(
            model_name='emojiscore',
            name='total_time',
            field=models.FloatField(default=0.0, help_text='Total response time in seconds.'),
        ),
        migrations.AddField(
            model_name='feudanswer',
            name='time_taken',
            field=models.FloatField(default=0.0, help_text='Seconds taken to submit answer.'),
        ),
        migrations.AddField(
            model_name='feudscore',
            name='total_time',
            field=models.FloatField(default=0.0, help_text='Total response time in seconds.'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='time_taken',
            field=models.FloatField(default=0.0, help_text='Seconds taken to submit answer.'),
        ),
        migrations.AddField(
            model_name='quizparticipant',
            name='total_time',
            field=models.FloatField(default=0.0, help_text='Total response time in seconds.'),
        ),
        migrations.AddField(
            model_name='quizscore',
            name='total_time',
            field=models.FloatField(default=0.0, help_text='Total response time in seconds.'),
        ),
        migrations.AddField(
            model_name='quizuseranswer',
            name='time_taken',
            field=models.FloatField(default=0.0, help_text='Response time for this question in seconds.'),
        ),
        migrations.AddField(
            model_name='survivalanswer',
            name='time_taken',
            field=models.FloatField(default=0.0, help_text='Seconds taken to submit answer.'),
        ),
        migrations.AddField(
            model_name='survivalplayer',
            name='total_time',
            field=models.FloatField(default=0.0, help_text='Total response time in seconds.'),
        ),
        migrations.AddField(
            model_name='wisdomanswer',
            name='time_taken',
            field=models.FloatField(default=0.0, help_text='Seconds taken to submit answer.'),
        ),
        migrations.AddField(
            model_name='wisdomscore',
            name='total_time',
            field=models.FloatField(default=0.0, help_text='Total response time in seconds.'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='broadcastgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='castlegame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='castlehit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chaingame',
            name='chain',
            field=models.JSONField(default=list, help_text='Solved rounds: [{"idx","title","masked","user_id","name","at"}].'),
        ),
        migrations.AlterField(
            model_name='chaingame',
            name='current_letter',
            field=models.CharField(default='', help_text='Unused since the missing-letter mechanic replaced the free-text chain — kept only to avoid a destructive migration.', max_length=1),
        ),
        migrations.AlterField(
            model_name='chaingame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chaingame',
            name='pending',
            field=models.JSONField(blank=True, default=None, help_text='Current in-progress round: {"book_id","title","masked","blanks":[{"pos","letter"}],"started_at"}.', null=True),
        ),
        migrations.AlterField(
            model_name='chaingame',
            name='rejected_norms',
            field=models.JSONField(default=list, help_text='Unused since the missing-letter mechanic replaced the free-text chain — kept only to avoid a destructive migration.'),
        ),
        migrations.AlterField(
            model_name='chaingame',
            name='used_norms',
            field=models.JSONField(default=list, help_text='GlobalBook ids already used this game (no repeats).'),
        ),
        migrations.AlterField(
            model_name='chainscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chainscore',
            name='kicked',
            field=models.BooleanField(default=False, help_text='Unused since the missing-letter mechanic replaced the free-text chain — kept only to avoid a destructive migration.'),
        ),
        migrations.AlterField(
            model_name='chainscore',
            name='links',
            field=models.PositiveIntegerField(default=0, help_text='Rounds this user solved.'),
        ),
        migrations.AlterField(
            model_name='chainscore',
            name='strikes',
            field=models.PositiveIntegerField(default=0, help_text='Unused since the missing-letter mechanic replaced the free-text chain — kept only to avoid a destructive migration.'),
        ),
        migrations.AlterField(
            model_name='chainword',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detectivegame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detectivescore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emojianswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emojigame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emojiscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feudanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feudgame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feudscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gamesequence',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kitobchaledger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizgame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shoppurchase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='siteevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='survivalanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='survivalgame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='survivalplayer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='welcomevideo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wisdomanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wisdomgame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wisdomscore',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
