# Generated by Django 5.2.9 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0100_alter_chainscore_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='flavor',
            field=models.CharField(
                choices=[
                    ('twofacts', "Ikki haqiqat, bir yolg'on"),
                    ('impostor', "Kim yolg'onchi?"),
                    ('connection', 'Yashirin bog\'lanish'),
                    ('teams', 'Jamoa Jangi'),
                    ('timeline', 'Vaqt Mashinasi'),
                    ('matchbook', 'Muallif-Asar Moslashtirish'),
                    ('reverse', 'Teskari Viktorina'),
                    ('cover', 'Kitob Muqovasi'),
                    ('anagram', '🔠 Anagramma Kitob'),
                    ('blitz', '⚡️ Blitz 60'),
                    ('crossword', '🧩 Mini Krossvord'),
                    ('wordle', '🔤 Harfma-Harf'),
                    ('cipher', '🔐 Sherlok Kodi'),
                    ('acronym', '🎯 Bosh Harflar'),
                    ('character', '👤 Qahramonni Top'),
                    ('dialogue', '🗣 Kimning gapi?'),
                    ('plotmap', '🗺 Syujet Xaritasi'),
                    ('sequence', '⏳ Ketma-ketlik'),
                    ('oddone', '🔍 Ortiqchasini Top'),
                    ('ending', '✍️ Asar Yakuni'),
                    ('pixel', '🖼 Piksel Muqova'),
                    ('aiart', '🎨 AI Rasmlar'),
                    ('scenes', '🎭 Sahna Ko\'rinishi'),
                    ('audioquote', '🎧 Ovozli Iqtibos'),
                    ('mosaic', '🧩 Kitob Mozaikasi'),
                    ('hiddendetail', '🔎 Yashirin Detal'),
                    ('duel', '🤺 1v1 Jonli Duel'),
                    ('buzzer', '🔔 Tezkor Qo\'ng\'iroq'),
                    ('bracket', '🏆 Haftalik Turnir'),
                    ('auction', '💰 Kitob Auksioni'),
                    ('regions', '👥 Viloyatlar Jangi'),
                    ('king', '👑 Qirol Taxti'),
                    ('rhyme', '📜 Bahri-Bayt'),
                    ('scholars', '🕌 Sharq Allomalari'),
                    ('genres', '📚 Janrlar Ustasi'),
                    ('numbers', '🔢 Adabiy Raqamlar'),
                    ('worldlit', '🌍 Jahon Adabiyoti'),
                    ('mysterybox', '🎁 Sirli Sandiq'),
                ],
                max_length=32
            ),
        ),
        migrations.AddField(
            model_name='quizgame',
            name='is_vip',
            field=models.BooleanField(default=False, help_text='True if this game is exclusive to VIP Premium users.'),
        ),
        migrations.AlterField(
            model_name='gamesequence',
            name='slot',
            field=models.CharField(
                choices=[('morning', '10:00'), ('evening', '22:00'), ('vip_2230', '22:30 VIP Premium')],
                max_length=16
            ),
        ),
        migrations.AlterField(
            model_name='gamesequence',
            name='current_game_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='gamesequence',
            name='game_types',
            field=models.JSONField(default=list, help_text='Randomly chosen, non-repeating game types for this slot.'),
        ),
    ]
