# Generated by Django 5.2.9 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0102_add_philosophy_logic_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizgame',
            name='flavor',
            field=models.CharField(
                choices=[
                    ('twofacts', "Ikki haqiqat, bir yolg'on"),
                    ('impostor', "Kim yolg'onchi?"),
                    ('connection', 'Yashirin bog\'lanish'),
                    ('teams', 'Jamoa Jangi'),
                    ('timeline', 'Vaqt Mashinasi'),
                    ('matchbook', 'Muallif-Asar Moslashtirish'),
                    ('reverse', 'Teskari Viktorina'),
                    ('cover', 'Kitob Muqovasi'),
                    ('anagram', '🔠 Anagramma Kitob'),
                    ('blitz', '⚡️ Blitz 60'),
                    ('crossword', '🧩 Mini Krossvord'),
                    ('wordle', '🔤 Harfma-Harf'),
                    ('cipher', '🔐 Sherlok Kodi'),
                    ('acronym', '🎯 Bosh Harflar'),
                    ('character', '👤 Qahramonni Top'),
                    ('dialogue', '🗣 Kimning gapi?'),
                    ('plotmap', '🗺 Syujet Xaritasi'),
                    ('sequence', '⏳ Ketma-ketlik'),
                    ('oddone', '🔍 Ortiqchasini Top'),
                    ('ending', '✍️ Asar Yakuni'),
                    ('pixel', '🖼 Piksel Muqova'),
                    ('aiart', '🎨 AI Rasmlar'),
                    ('scenes', '🎭 Sahna Ko\'rinishi'),
                    ('audioquote', '🎧 Ovozli Iqtibos'),
                    ('mosaic', '🧩 Kitob Mozaikasi'),
                    ('hiddendetail', '🔎 Yashirin Detal'),
                    ('duel', '🤺 1v1 Jonli Duel'),
                    ('buzzer', '🔔 Tezkor Qo\'ng\'iroq'),
                    ('bracket', '🏆 Haftalik Turnir'),
                    ('auction', '💰 Kitob Auksioni'),
                    ('regions', '👥 Viloyatlar Jangi'),
                    ('king', '👑 Qirol Taxti'),
                    ('rhyme', '📜 Bahri-Bayt'),
                    ('scholars', '🕌 Sharq Allomalari'),
                    ('genres', '📚 Janrlar Ustasi'),
                    ('numbers', '🔢 Adabiy Raqamlar'),
                    ('worldlit', '🌍 Jahon Adabiyoti'),
                    ('mysterybox', '🎁 Sirli Sandiq'),
                    ('mindtrap', '🧠 Fikr Tuzog\'i'),
                    ('stoic', '🧘‍♂️ Ongli Hayot'),
                    ('antiherd', '🐑 Podadan Ajral'),
                    ('dilemma', '⚖️ Axloqiy Dilemma'),
                    ('causeeffect', '🔮 Sabab va Oqibat'),
                    ('masks', '🎭 Niqoblar Foshi'),
                    ('socrates', '🏛 Sokrat Suhbatlari'),
                    ('memento', '⌛️ Vaqt Paradoksi'),
                    ('strategy', '♟ Strategik Tafakkur'),
                    ('paradox', '💡 Paradokslar Olami'),
                    ('simurgh', '🕊 Simurg\' Parvozi'),
                    ('ishq', '🕯 Parvona va Sham'),
                    ('nafs', '⚔️ Buyuk Jihod'),
                    ('qalb', '🪞 Qalb Sayqali'),
                    ('naqshband', '🌾 Xalvat dar Anjuman'),
                    ('yassaviy', '📜 Hikmatlar Daryosi'),
                    ('masnaviy', '🪈 Nay Nidosi'),
                    ('gazzoliy', '🗝 Kimyoi Saodat'),
                    ('fano', '🌊 Fanofilloh'),
                    ('marifat', '☀️ Haqiqat Quyoshi'),
                ],
                max_length=32
            ),
        ),
    ]
