# Generated by Django 5.2.9 on 2026-08-17 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0103_add_sufism_nafs_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='premium_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='Free Premium days actually granted for this placing (VIP arena top-3). Doubles as the idempotency marker so a re-finalize/settle never grants twice.'),
        ),
        migrations.CreateModel(
            name='MysteryBoxWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('prize_key', models.CharField(help_text="market.MYSTERY_PRIZES key, e.g. 'grand_jackpot'.", max_length=40)),
                ('label', models.CharField(help_text='Human-readable prize text shown to the winner.', max_length=255)),
                ('reward_type', models.CharField(blank=True, default='', help_text='market.CREATIVE_TANGIBLE_REWARDS type: ball_direct/premium_days/ticket/...', max_length=24)),
                ('reward_value', models.CharField(blank=True, default='', help_text="That type's value (hours, days, count, badge name) as text.", max_length=64)),
                ('kitobcha', models.PositiveIntegerField(default=0, help_text='Kitobcha this prize credited, if any.')),
                ('premium_days', models.PositiveSmallIntegerField(default=0, help_text='Whole Premium days granted, if any.')),
                ('premium_hours', models.PositiveSmallIntegerField(default=0, help_text='Premium hours granted, if any.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mystery_box_wins', to='tgbot.telegramprofile')),
            ],
            options={
                'verbose_name': "Sirli quti yutug'i",
                'verbose_name_plural': 'Sirli quti yutuqlari',
                'ordering': ('-created_at',),
            },
        ),
    ]
