# Generated by Django 5.2.9 on 2026-08-18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def set_active_product_to_auction(apps, schema_editor):
    ShopProduct = apps.get_model('tgbot', 'ShopProduct')
    # Find active products and convert the first one to a 10-day auction with 100 min bid
    active_prod = ShopProduct.objects.filter(is_active=True).first()
    if active_prod:
        active_prod.is_auction = True
        active_prod.min_start_bid = 100
        active_prod.auction_end_at = timezone.now() + datetime.timedelta(days=10)
        active_prod.save(update_fields=['is_auction', 'min_start_bid', 'auction_end_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0104_add_mystery_box_win_and_quiz_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='is_auction',
            field=models.BooleanField(default=False, help_text='When True, users place bids instead of instant purchase.'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='min_start_bid',
            field=models.PositiveIntegerField(default=100, help_text='Minimum starting bid amount in Kitobcha (default: 100).'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='auction_end_at',
            field=models.DateTimeField(blank=True, help_text='When the auction finishes and winner is decided.', null=True),
        ),
        migrations.CreateModel(
            name='ShopAuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('amount', models.PositiveIntegerField(help_text='Total active Kitobcha bid placed by this user for this auction.')),
                ('is_refunded', models.BooleanField(default=False, help_text='Set to True when auction concludes and this user was not the #1 winner.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to='tgbot.shopproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_auction_bids', to='tgbot.telegramprofile')),
            ],
            options={
                'verbose_name': 'Shop Auction Bid',
                'verbose_name_plural': 'Shop Auction Bids',
                'ordering': ('-amount', 'created_at'),
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.RunPython(set_active_product_to_auction, migrations.RunPython.noop),
    ]
