# Generated by Django 5.2.9 on 2026-08-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0105_shop_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='active_theme',
            field=models.CharField(blank=True, help_text="Faol mini-app mavzusi (masalan: 'dark', 'matrix')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='telegramprofile',
            name='unlocked_themes',
            field=models.JSONField(blank=True, default=list, help_text="Foydalanuvchi sotib olgan mavzular ro'yxati"),
        ),
    ]
