# Generated by Django 5.2.9 on 2026-09-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0107_game_jokers'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='ad_slot_hours',
            field=models.PositiveIntegerField(blank=True, help_text='Set to 24 or 48 to make this an ADVERTISING slot instead of an ordinary prize. The auction winner is asked for a link and ad text, an admin approves it, and it is then broadcast to every group and every bot user for this many hours. Leave blank for normal products.', null=True),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='premium_only',
            field=models.BooleanField(default=False, help_text='Only Premium members may bid on / buy this. Used by the advertising slots.'),
        ),
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('duration_hours', models.PositiveIntegerField(help_text='How long the ad runs once approved (24 or 48).')),
                ('bid_amount', models.PositiveIntegerField(default=0, help_text='Winning bid in Kitobcha, kept for the record.')),
                ('link', models.URLField(blank=True, default='', max_length=500)),
                ('ad_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('awaiting', 'Havola kutilmoqda'), ('review', 'Moderatsiyada'), ('rejected', 'Rad etilgan'), ('live', 'Efirda'), ('finished', 'Tugagan')], default='awaiting', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('broadcast_groups', models.PositiveIntegerField(default=0)),
                ('broadcast_users', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns', to='tgbot.shopproduct')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_campaigns_reviewed', to='tgbot.telegramprofile')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_campaigns', to='tgbot.telegramprofile')),
            ],
            options={
                'verbose_name': 'Ad Campaign',
                'verbose_name_plural': 'Ad Campaigns',
                'ordering': ('-created_at',),
            },
        ),
    ]
