"""Starter dictionary for Kitob Zanjiri — recognizable book titles and author
names (Uzbek + world classics), spelled in Uzbek Latin so letter-chaining works.

This is a seed only; grow it from the Django admin (ChainWord) over time.
Each entry is (display, kind) where kind is "book" or "author".
"""

CHAIN_WORDS = [
    # ── Uzbek authors ──────────────────────────────────────────────────────
    ("Alisher Navoiy", "author"),
    ("Zahiriddin Muhammad Bobur", "author"),
    ("Abdulla Qodiriy", "author"),
    ("Abdulla Qahhor", "author"),
    ("Cho'lpon", "author"),
    ("Oybek", "author"),
    ("G'afur G'ulom", "author"),
    ("Hamid Olimjon", "author"),
    ("Zulfiya", "author"),
    ("Erkin Vohidov", "author"),
    ("Abdulla Oripov", "author"),
    ("Said Ahmad", "author"),
    ("O'tkir Hoshimov", "author"),
    ("Tohir Malik", "author"),
    ("Pirimqul Qodirov", "author"),
    ("Odil Yoqubov", "author"),
    ("Asqad Muxtor", "author"),
    ("Shukur Xolmirzayev", "author"),
    ("Xudoyberdi To'xtaboyev", "author"),
    ("Nazar Eshonqul", "author"),
    ("Isajon Sulton", "author"),
    ("Muhammad Yusuf", "author"),
    ("Usmon Azim", "author"),
    ("Halima Xudoyberdiyeva", "author"),
    ("Mirtemir", "author"),
    ("Uyg'un", "author"),
    ("Maqsud Shayxzoda", "author"),

    # ── World authors (Uzbek Latin) ───────────────────────────────────────
    ("Lev Tolstoy", "author"),
    ("Fyodor Dostoyevskiy", "author"),
    ("Anton Chexov", "author"),
    ("Aleksandr Pushkin", "author"),
    ("Maksim Gorkiy", "author"),
    ("Ivan Turgenev", "author"),
    ("Nikolay Gogol", "author"),
    ("Sergey Yesenin", "author"),
    ("Chingiz Aytmatov", "author"),
    ("Ernest Xeminguey", "author"),
    ("Jek London", "author"),
    ("Mark Tven", "author"),
    ("Antuan de Sent-Ekzyuperi", "author"),
    ("Paulo Koelo", "author"),
    ("Gabriel Garsia Markes", "author"),
    ("Vilyam Shekspir", "author"),
    ("Aleksandr Dyuma", "author"),
    ("Jyul Vern", "author"),
    ("Daniel Defo", "author"),
    ("Migel de Servantes", "author"),
    ("Franz Kafka", "author"),
    ("Viktor Hugo", "author"),
    ("Onore de Balzak", "author"),
    ("Xorxe Luis Borxes", "author"),
    ("Agata Kristi", "author"),
    ("Artur Konan Doyl", "author"),
    ("Charlz Dikkens", "author"),
    ("Jorj Oruell", "author"),
    ("Rey Bredberi", "author"),
    ("Stiven King", "author"),

    # ── Uzbek books / dostons ─────────────────────────────────────────────
    ("O'tkan kunlar", "book"),
    ("Mehrobdan chayon", "book"),
    ("Kecha va kunduz", "book"),
    ("Sarob", "book"),
    ("Shum bola", "book"),
    ("Ikki eshik orasi", "book"),
    ("Ufq", "book"),
    ("Dunyoning ishlari", "book"),
    ("Yulduzli tunlar", "book"),
    ("Ulug'bek xazinasi", "book"),
    ("Qutlug' qon", "book"),
    ("Navoiy", "book"),
    ("Diyonat", "book"),
    ("Sha'ytanat", "book"),
    ("Kabus", "book"),
    ("Chayon yili", "book"),
    ("Jimjitlik", "book"),
    ("Muqaddas", "book"),
    ("Otamdan qolgan dalalar", "book"),
    ("Bahor qaytmaydi", "book"),
    ("Yozning yolg'iz yodgori", "book"),
    ("Qo'shchinor chiroqlari", "book"),
    ("Sinchalak", "book"),
    ("Anor", "book"),
    ("Bemor", "book"),
    ("Boy ila xizmatchi", "book"),
    ("Alpomish", "book"),
    ("Kuntug'mish", "book"),
    ("Yusuf va Zulayho", "book"),
    ("Farhod va Shirin", "book"),
    ("Layli va Majnun", "book"),
    ("Xamsa", "book"),
    ("Boburnoma", "book"),
    ("Qutadg'u bilig", "book"),
    ("Devonu lug'otit turk", "book"),
    ("Sariq devni minib", "book"),
    ("Sehrli qalpoqcha", "book"),
    ("Besh bolali yigitcha", "book"),
    ("So'nggi o'q", "book"),
    ("Tunda chaqmoq chaqadi", "book"),
    ("Bir kishlik umr", "book"),
    ("Lolazor", "book"),
    ("Ozod", "book"),

    # ── World books (Uzbek Latin) ─────────────────────────────────────────
    ("Urush va tinchlik", "book"),
    ("Jinoyat va jazo", "book"),
    ("Anna Karenina", "book"),
    ("Aka-uka Karamazovlar", "book"),
    ("Kapitan qizi", "book"),
    ("Hoji Murod", "book"),
    ("Oq kema", "book"),
    ("Jamila", "book"),
    ("Asrni qaritgan kun", "book"),
    ("Kichkina shahzoda", "book"),
    ("Alkimyogar", "book"),
    ("Chol va dengiz", "book"),
    ("Robinzon Kruzo", "book"),
    ("Gulliver sayohatlari", "book"),
    ("Graf Monte-Kristo", "book"),
    ("Uch mushketyor", "book"),
    ("Sherlok Xolms", "book"),
    ("Gamlet", "book"),
    ("Otello", "book"),
    ("Romeo va Julyetta", "book"),
    ("Qirol Lir", "book"),
    ("Faust", "book"),
    ("Don Kixot", "book"),
    ("Tom Soyer sarguzashtlari", "book"),
    ("Oq so'yloq", "book"),
    ("Martin Iden", "book"),
    ("Ozodlik", "book"),
    ("Kambag'allar", "book"),
    ("Idiot", "book"),
    ("Telba", "book"),
    ("Bosqinchi", "book"),
    ("Robinzon", "book"),
    ("Notr-Dam ibodatxonasi", "book"),
    ("Yer osti dunyosi", "book"),
    ("Shamollar shahri", "book"),
    ("Vaqt mashinasi", "book"),
    ("Ko'rinmas odam", "book"),
    ("Buyuk Getsbi", "book"),
    ("Momo Havo", "book"),
    ("Insoniyat tarixi", "book"),
    ("Metamorfoza", "book"),
]
