"""Question banks for the live games.

FEUD_QUESTIONS  — open questions for "Ko'pchilik nima dedi?" (crowd answers).
CASTLE_QUESTIONS — multiple-choice literary trivia for "Bilim Qal'asi".
                   Options are shuffled per game at runtime, so the stored
                   `correct` index is only the seed position.
"""

FEUD_QUESTIONS = [
    "Eng mashhur o'zbek yozuvchisini ayting",
    "Eng sevimli kitobingizni ayting",
    "Maktabda o'qigan eng mashhur asarni ayting",
    "Eng buyuk jahon yozuvchisini ayting",
    "Bir o'zbek xalq dostonini ayting",
    "Alisher Navoiyning bir asarini ayting",
    "Eng mashhur o'zbek shoirini ayting",
    "Bolalikda o'qigan bir ertakni ayting",
    "Bir detektiv asar nomini ayting",
    "Eng mashhur jahon kitobini ayting",
    "Bir o'zbek klassik yozuvchisini ayting",
    "Sevimli adabiy qahramoningizni ayting",
    "Bir tarixiy romanni ayting",
    "Bir mashhur rus yozuvchisini ayting",
    "Bir fantastik asarni ayting",
    "Kitob o'qishning bir foydasini ayting",
    "Bir zamonaviy o'zbek yozuvchisini ayting",
    "Bir she'riy to'plam yoki shoir nomini ayting",
    "Bir kutubxona yoki nashriyot nomini ayting",
    "Bir mashhur muallifning taxallusini ayting",
    "Bir jahon klassik asarini ayting",
    "Bolalar uchun bir kitob nomini ayting",
    "Bir urush haqidagi asarni ayting",
    "Eng ko'p o'qiladigan janr qaysi?",
    "Bir mashhur she'rni ayting",
    "Adabiyot darsida yoqtirgan mavzuni ayting",
    "Bir jahon mumtoz shoirini ayting",
    "Eng mashhur ertak qahramonini ayting",
    "Bir o'zbek dramaturgini ayting",
    "Do'stingizga qaysi kitobni sovg'a qilardingiz?",
    "Bir sarguzasht romanini ayting",
    "Bir bolalar jurnali yoki gazetasini ayting",
    "Eng ta'sirli adabiy qahramonni ayting",
    "Bir ilmiy-fantastik yozuvchini ayting",
    "Sevimli o'zbek shoirasini ayting",
    "Bir tarixiy shaxs haqidagi kitobni ayting",
    "Bir maqol ayting",
    "Bir mashhur kutubxonani ayting",
    "Bir zamonaviy bestsellerni ayting",
    "Maktab dasturidagi bir she'rni ayting",
    "Bir jahon xalq ertagini ayting",
    "Bir avtobiografik asarni ayting",
    "Bir rus klassik asarini ayting",
    "Sevimli detektiv qahramonini ayting",
    "Bir falsafiy kitobni ayting",
    "Bir sayohat haqidagi kitobni ayting",
    "Kitob o'qishning bir odatini ayting",
    "Sevimli bolalik kitobingizni ayting",
    "Film qilingan bir kitobni ayting",
    "Bir o'zbek nasr asarini ayting",
    "Bir dunyo shohasarini ayting",
    "Kitob javonida albatta bo'lishi kerak bo'lgan asar?",
    "Bir mumtoz g'azal muallifini ayting",
    "Eng ko'p qayta o'qiydigan kitobingiz?",
    "Bir nashriyot nomini ayting",
    "Adabiy mukofot nomini ayting",
    "Bir she'riy janrni ayting",
    "Sevimli muallifingiz tug'ilgan shaharni ayting",
    "Bir qahramonlik dostonini ayting",
    "Eng qiziqarli kitob muqovasi rangi?",
    "Bir jahon shoirini ayting",
    "Kutubxonada eng ko'p vaqt o'tkazadigan bo'lim?",
    "Bir tarjimon nomini ayting",
]

CASTLE_QUESTIONS = [
    {"q": "«O'tkan kunlar» romani muallifi kim?",
     "options": ["Abdulla Qodiriy", "Cho'lpon", "Oybek", "G'afur G'ulom"], "correct": 0},
    {"q": "«Mehrobdan chayon» kim qalamiga mansub?",
     "options": ["Oybek", "Abdulla Qodiriy", "Said Ahmad", "Tohir Malik"], "correct": 1},
    {"q": "Alisher Navoiy «Xamsa»si nechta dostondan iborat?",
     "options": ["3", "4", "5", "6"], "correct": 2},
    {"q": "«Urush va tinchlik» muallifi kim?",
     "options": ["Dostoyevskiy", "Chexov", "Lev Tolstoy", "Pushkin"], "correct": 2},
    {"q": "«Jinoyat va jazo» kim asari?",
     "options": ["Tolstoy", "Dostoyevskiy", "Gogol", "Turgenev"], "correct": 1},
    {"q": "«Kichkina shahzoda» muallifi kim?",
     "options": ["Jyul Vern", "Antuan de Sent-Ekzyuperi", "Defo", "Dyuma"], "correct": 1},
    {"q": "«Boburnoma» asari kim qalamiga mansub?",
     "options": ["Bobur", "Ulug'bek", "Navoiy", "Husayn Boyqaro"], "correct": 0},
    {"q": "«Yulduzli tunlar» romani kim ijodi?",
     "options": ["Pirimqul Qodirov", "Odil Yoqubov", "Oybek", "Mirmuhsin"], "correct": 0},
    {"q": "«Ulug'bek xazinasi» muallifi kim?",
     "options": ["Odil Yoqubov", "Pirimqul Qodirov", "Asqad Muxtor", "Said Ahmad"], "correct": 0},
    {"q": "«Alkimyogar» kitobi muallifi kim?",
     "options": ["Gabriel Markes", "Paulo Koelo", "Xeminguey", "Kafka"], "correct": 1},
    {"q": "«Chol va dengiz» kim asari?",
     "options": ["Jek London", "Ernest Xeminguey", "Mark Tven", "Folkner"], "correct": 1},
    {"q": "«Shum bola» qissasi muallifi kim?",
     "options": ["G'afur G'ulom", "Abdulla Qahhor", "Oybek", "Cho'lpon"], "correct": 0},
    {"q": "«Kecha va kunduz» romani kim qalamiga mansub?",
     "options": ["Cho'lpon", "Oybek", "Qodiriy", "Fitrat"], "correct": 0},
    {"q": "«O'tkan kunlar»da bosh qahramon kim?",
     "options": ["Otabek", "Anvar", "Yodgor", "Kumush"], "correct": 0},
    {"q": "«Sarob» romani muallifi kim?",
     "options": ["Abdulla Qahhor", "Oybek", "Said Ahmad", "G'afur G'ulom"], "correct": 0},
    {"q": "Zahiriddin Muhammad Bobur qaysi sulola asoschisi?",
     "options": ["Boburiylar", "Shayboniylar", "Temuriylar", "Ashtarxoniylar"], "correct": 0},
    {"q": "«Ikki eshik orasi» muallifi kim?",
     "options": ["O'tkir Hoshimov", "Tohir Malik", "Said Ahmad", "Shukur Xolmirzayev"], "correct": 0},
    {"q": "«Robinzon Kruzo» kim asari?",
     "options": ["Daniel Defo", "Jonatan Svift", "Jyul Vern", "Mark Tven"], "correct": 0},
    {"q": "«Hamlet» tragediyasi muallifi kim?",
     "options": ["Shekspir", "Molyer", "Dante", "Gyote"], "correct": 0},
    {"q": "«Anna Karenina» kim ijodi?",
     "options": ["Lev Tolstoy", "Dostoyevskiy", "Turgenev", "Gogol"], "correct": 0},
    {"q": "«Layli va Majnun» dostoni (o'zbek adabiyoti) kimniki?",
     "options": ["Alisher Navoiy", "Bobur", "Lutfiy", "Sakkokiy"], "correct": 0},
    {"q": "«Sariq devni minib» asari muallifi kim?",
     "options": ["Xudoyberdi To'xtaboyev", "Anvar Obidjon", "G'afur G'ulom", "Quddus Muhammadiy"], "correct": 0},
    {"q": "«Faust» asari muallifi kim?",
     "options": ["Gyote", "Shiller", "Bayron", "Gyugo"], "correct": 0},
    {"q": "«Don Kixot» kim qalamiga mansub?",
     "options": ["Migel de Servantes", "Lope de Vega", "Kalderon", "Dante"], "correct": 0},
    {"q": "«Graf Monte-Kristo» muallifi kim?",
     "options": ["Aleksandr Dyuma", "Viktor Gyugo", "Balzak", "Stendal"], "correct": 0},
    {"q": "«Diyonat» romani muallifi kim?",
     "options": ["Odil Yoqubov", "Said Ahmad", "Oybek", "Asqad Muxtor"], "correct": 0},
    {"q": "Alisher Navoiy qaysi shaharda tug'ilgan?",
     "options": ["Hirot", "Samarqand", "Buxoro", "Toshkent"], "correct": 0},
    {"q": "«Qutadg'u bilig» muallifi kim?",
     "options": ["Yusuf Xos Hojib", "Mahmud Koshg'ariy", "Navoiy", "Rabg'uziy"], "correct": 0},
    {"q": "«Devonu lug'otit turk» muallifi kim?",
     "options": ["Mahmud Koshg'ariy", "Yusuf Xos Hojib", "Navoiy", "Bobur"], "correct": 0},
    {"q": "Cho'lponning asl ismi nima?",
     "options": ["Abdulhamid Sulaymon o'g'li", "Muso Toshmuhammad", "Abdulla Nabiyev", "Sanjar Siddiq"], "correct": 0},
    {"q": "«Alpomish» qaysi janrga mansub?",
     "options": ["Doston", "Roman", "Qissa", "Hikoya"], "correct": 0},
    {"q": "Zulfiya kim bo'lgan?",
     "options": ["Shoira", "Rassom", "Bastakor", "Aktrisa"], "correct": 0},
    {"q": "«Ona» romani kim asari?",
     "options": ["Maksim Gorkiy", "Lev Tolstoy", "Chexov", "Sholoxov"], "correct": 0},
    {"q": "«Tinch Don» muallifi kim?",
     "options": ["Mixail Sholoxov", "Gorkiy", "Fadeyev", "Ostrovskiy"], "correct": 0},
    {"q": "«O'lik jonlar» muallifi kim?",
     "options": ["Nikolay Gogol", "Pushkin", "Turgenev", "Chexov"], "correct": 0},
    {"q": "«Kapitan qizi» kim asari?",
     "options": ["Aleksandr Pushkin", "Gogol", "Lermontov", "Tolstoy"], "correct": 0},
    {"q": "«Ota va bolalar» romani muallifi kim?",
     "options": ["Ivan Turgenev", "Dostoyevskiy", "Tolstoy", "Gogol"], "correct": 0},
    {"q": "«Zamonamiz qahramoni» kim asari?",
     "options": ["Lermontov", "Pushkin", "Gogol", "Turgenev"], "correct": 0},
    {"q": "«Ruslan va Lyudmila» muallifi kim?",
     "options": ["Pushkin", "Lermontov", "Gogol", "Tolstoy"], "correct": 0},
    {"q": "«Telba» (Idiot) romanida bosh qahramon kim?",
     "options": ["Knyaz Mishkin", "Raskolnikov", "Stavrogin", "Bazarov"], "correct": 0},
    {"q": "«Jinoyat va jazo»da bosh qahramon kim?",
     "options": ["Raskolnikov", "Bazarov", "Onegin", "Bezuxov"], "correct": 0},
    {"q": "Anton Chexov asosan qaysi janrlarda ijod qilgan?",
     "options": ["Hikoya va dramaturgiya", "Roman", "Doston", "Ertak"], "correct": 0},
    {"q": "Lev Tolstoy qaysi davlat yozuvchisi?",
     "options": ["Rossiya", "Fransiya", "Angliya", "Germaniya"], "correct": 0},
    {"q": "«Gulliverning sayohatlari» muallifi kim?",
     "options": ["Jonatan Svift", "Daniel Defo", "Mark Tven", "Jyul Vern"], "correct": 0},
    {"q": "Sherlok Xolmsning sodiq yordamchisi kim?",
     "options": ["Doktor Vatson", "Lestrad", "Maykroft", "Moriarti"], "correct": 0},
    {"q": "Agata Kristi qaysi janr yozuvchisi?",
     "options": ["Detektiv", "Fantastika", "Tarixiy", "She'riyat"], "correct": 0},
    {"q": "«Uch mushketyor» muallifi kim?",
     "options": ["Aleksandr Dyuma", "Viktor Gyugo", "Jyul Vern", "Balzak"], "correct": 0},
    {"q": "Jyul Vern qaysi janr asoschilaridan biri?",
     "options": ["Ilmiy-fantastika", "Detektiv", "Drama", "Memuar"], "correct": 0},
    {"q": "«Notr-Dam ibodatxonasi» muallifi kim?",
     "options": ["Viktor Gyugo", "Dyuma", "Balzak", "Stendal"], "correct": 0},
    {"q": "«Sefillar» (Les Misérables) muallifi kim?",
     "options": ["Viktor Gyugo", "Dyuma", "Balzak", "Zolya"], "correct": 0},
    {"q": "«Graf Monte-Kristo» qahramoni ismi nima?",
     "options": ["Edmond Dantes", "Jan Valjan", "D'Artanyan", "Kvazimodo"], "correct": 0},
    {"q": "Mark Tven qaysi davlat yozuvchisi?",
     "options": ["AQSh", "Angliya", "Kanada", "Avstraliya"], "correct": 0},
    {"q": "«Tom Soyer sarguzashtlari» muallifi kim?",
     "options": ["Mark Tven", "Jek London", "Xeminguey", "Dikkens"], "correct": 0},
    {"q": "Jek Londonning «Oq So'yloq» asari nima haqida?",
     "options": ["It va bo'ri", "Dengiz", "Urush", "Kosmos"], "correct": 0},
    {"q": "Paulo Koelo qaysi davlat yozuvchisi?",
     "options": ["Braziliya", "Portugaliya", "Ispaniya", "Meksika"], "correct": 0},
    {"q": "«Alkimyogar»da bosh qahramon kim?",
     "options": ["Cho'pon Santyago", "Paulo", "Melkisedek", "Fotima"], "correct": 0},
    {"q": "Gabriel Garsia Markes qaysi davlat yozuvchisi?",
     "options": ["Kolumbiya", "Argentina", "Meksika", "Chili"], "correct": 0},
    {"q": "«Yolg'izlikning yuz yili» muallifi kim?",
     "options": ["Markes", "Borxes", "Koelo", "Neruda"], "correct": 0},
    {"q": "«Metamorfoza» asari muallifi kim?",
     "options": ["Franz Kafka", "Kamyu", "Sartr", "Jois"], "correct": 0},
    {"q": "«Ilohiy komediya» muallifi kim?",
     "options": ["Dante Aligyeri", "Petrarka", "Bokkachcho", "Servantes"], "correct": 0},
    {"q": "«Romeo va Julyetta» voqealari qaysi shaharda bo'ladi?",
     "options": ["Verona", "Rim", "Venetsiya", "Florensiya"], "correct": 0},
    {"q": "Uilyam Shekspir qaysi davlat dramaturgi?",
     "options": ["Angliya", "Fransiya", "Ispaniya", "Germaniya"], "correct": 0},
    {"q": "«Faust» qaysi mamlakat adabiyotiga mansub?",
     "options": ["Germaniya", "Fransiya", "Angliya", "Italiya"], "correct": 0},
    {"q": "Bobur asos solgan saltanat qayerda edi?",
     "options": ["Hindiston", "Eron", "Turkiya", "Misr"], "correct": 0},
    {"q": "«O'tkan kunlar» qaysi davrni tasvirlaydi?",
     "options": ["XIX asr Turkiston", "Sovet davri", "XV asr", "Hozirgi zamon"], "correct": 0},
    {"q": "Navoiy she'riyatida keng qo'llangan asosiy janr?",
     "options": ["G'azal", "Sonet", "Ballada", "Verlibr"], "correct": 0},
    {"q": "«Xamsa»ning birinchi dostoni qaysi?",
     "options": ["Hayrat ul-abror", "Farhod va Shirin", "Layli va Majnun", "Saddi Iskandariy"], "correct": 0},
    {"q": "Erkin Vohidov qaysi soha ustasi?",
     "options": ["She'riyat", "Rassomlik", "Musiqa", "Kino"], "correct": 0},
    {"q": "Abdulla Qahhorning asari qaysi?",
     "options": ["O'tmishdan ertaklar", "Yulduzli tunlar", "Ikki eshik orasi", "Diyonat"], "correct": 0},
    {"q": "«Boburnoma» asosan qaysi tilda yozilgan?",
     "options": ["Eski o'zbek (chig'atoy)", "Fors", "Arab", "Rus"], "correct": 0},
    {"q": "Ernest Xeminguey qaysi davlat yozuvchisi?",
     "options": ["AQSh", "Angliya", "Fransiya", "Italiya"], "correct": 0},
    {"q": "«Robinzon Kruzo» qahramoni orolda taxminan qancha yashaydi?",
     "options": ["28 yil", "5 yil", "10 yil", "40 yil"], "correct": 0},
    {"q": "«Kichkina shahzoda» qaysi tildan tarjima qilingan?",
     "options": ["Fransuz", "Ingliz", "Nemis", "Ispan"], "correct": 0},
    {"q": "Hamid Olimjon kim bo'lgan?",
     "options": ["Shoir", "Rassom", "Bastakor", "Me'mor"], "correct": 0},
    {"q": "Said Ahmadning mashhur komediyasi qaysi?",
     "options": ["Kelinlar qo'zg'oloni", "Toshkentnoma", "Sarob", "Ufq"], "correct": 0},
]


# Emoji Kitob — guess the book from emojis (multiple choice; options shuffled at
# runtime, `correct` is the seed position).
EMOJI_QUESTIONS = [
    {"emoji": "👴 🌊 🐟", "options": ["Chol va dengiz", "Robinzon Kruzo", "Oq kema", "Moby Dik"], "correct": 0},
    {"emoji": "🤴 🌹 🦊 🪐", "options": ["Kichkina shahzoda", "Pinokkio", "Piter Pen", "Alisa"], "correct": 0},
    {"emoji": "🏝️ 👣 ⛵", "options": ["Robinzon Kruzo", "Gulliver sayohatlari", "Sindbad", "Kapitan qizi"], "correct": 0},
    {"emoji": "🐺 ❄️ 🐕", "options": ["Oq So'yloq", "Bemor", "Momo", "Oq kema"], "correct": 0},
    {"emoji": "🔪 ⚖️ 😰", "options": ["Jinoyat va jazo", "Anna Karenina", "Idiot", "Telba"], "correct": 0},
    {"emoji": "🚂 💔 👩", "options": ["Anna Karenina", "Urush va tinchlik", "Ona", "Sarob"], "correct": 0},
    {"emoji": "⚔️ 🕊️ 🇷🇺", "options": ["Urush va tinchlik", "Tinch Don", "Ona", "Idiot"], "correct": 0},
    {"emoji": "🗡️ 🤺 4️⃣", "options": ["Uch mushketyor", "Robin Gud", "Don Kixot", "Ayvengo"], "correct": 0},
    {"emoji": "🏰 💰 🗝️ 🌊", "options": ["Graf Monte-Kristo", "Ali Baba", "Oltin kalit", "Xazina oroli"], "correct": 0},
    {"emoji": "🕌 🦂", "options": ["Mehrobdan chayon", "Sha'ytanat", "Diyonat", "Kabus"], "correct": 0},
    {"emoji": "👦 😜 🎭", "options": ["Shum bola", "Tom Soyer", "Chipollino", "Buratino"], "correct": 0},
    {"emoji": "⭐ 🌙 🌃", "options": ["Yulduzli tunlar", "Kecha va kunduz", "Sarob", "Ufq"], "correct": 0},
    {"emoji": "🧪 ⚗️ 🐫 🏜️", "options": ["Alkimyogar", "Sindbad", "Robinzon", "Sahroyi kabir"], "correct": 0},
    {"emoji": "🐷 🐴 🚩 🏛️", "options": ["Hayvonlar fermasi", "Robinzon", "Momo", "Idiot"], "correct": 0},
    {"emoji": "👁️ 🏙️ 1️⃣9️⃣8️⃣4️⃣", "options": ["1984", "Biz", "451 daraja", "O'yin"], "correct": 0},
    {"emoji": "🐛 ➡️ 🧑 😱", "options": ["Metamorfoza", "Jinoyat va jazo", "Telba", "Bemor"], "correct": 0},
    {"emoji": "🎭 💀 🇩🇰", "options": ["Hamlet", "Otello", "Qirol Lir", "Makbet"], "correct": 0},
    {"emoji": "❤️ 🗡️ 👫 ⚰️", "options": ["Romeo va Julyetta", "Layli va Majnun", "Farhod va Shirin", "Tohir va Zuhra"], "correct": 0},
    {"emoji": "🗿 ⛏️ 🏔️ 👑", "options": ["Ulug'bek xazinasi", "Boburnoma", "Navoiy", "Yulduzli tunlar"], "correct": 0},
    {"emoji": "🕵️ 🔍 🚬 🎻", "options": ["Sherlok Xolms", "Erkul Puaro", "Miss Marpl", "Fandorin"], "correct": 0},
    {"emoji": "🐋 ⛵ 🎣 😡", "options": ["Moby Dik", "Chol va dengiz", "Robinzon", "20 ming liga"], "correct": 0},
    {"emoji": "🌊 🚢 🐙 2️⃣0️⃣0️⃣0️⃣0️⃣", "options": ["Dengiz ostida 20 ming liga", "Titanik", "Robinzon", "Sindbad"], "correct": 0},
    {"emoji": "🎈 🌍 8️⃣0️⃣ 📅", "options": ["80 kunda dunyo bo'ylab", "Vaqt mashinasi", "Oy sayohati", "Sindbad"], "correct": 0},
    {"emoji": "🧞 🪔 🏜️", "options": ["Alouddin", "Ali Baba", "Sindbad", "Kichkina shahzoda"], "correct": 0},
    {"emoji": "🍎 ❄️ 7️⃣ 👸", "options": ["Qorqiz va yetti gnom", "Zolushka", "Rapunzel", "Qizil shapkacha"], "correct": 0},
    {"emoji": "🐺 👵 🔴 🧺", "options": ["Qizil shapkacha", "Uch cho'chqa", "Qorqiz", "Bo'ri va yetti uloq"], "correct": 0},
    {"emoji": "🎃 👞 🐭 🕛", "options": ["Zolushka", "Qorqiz", "Uxlab qolgan malika", "Rapunzel"], "correct": 0},
    {"emoji": "📖 🌌 ✍️ 🇺🇿", "options": ["O'tkan kunlar", "Kecha va kunduz", "Sarob", "Ufq"], "correct": 0},
    {"emoji": "🧔 👑 📜 🇮🇳", "options": ["Boburnoma", "Navoiy", "Yulduzli tunlar", "Ulug'bek xazinasi"], "correct": 0},
    {"emoji": "🌹 🎶 📚 ✒️", "options": ["Xamsa", "Devon", "Boburnoma", "Qutadg'u bilig"], "correct": 0},
]


# ─────────────────────────────────────────────────────────────────────────────
# Hikmat Xazinasi — a widely-known hikmat (wisdom saying) is shown; guess which
# thinker/scholar/ulamo it's commonly attributed to (multiple choice; options
# shuffled at runtime, `correct` is the seed position). Sayings here are the
# commonly-repeated paraphrased forms used in Uzbek educational contexts, not
# claimed as precise verbatim primary-source quotations. Figures are all
# broadly and uncontroversially respected across the Sunni/Central Asian
# tradition, with an emphasis on Uzbekistan's own religious heritage.
# ─────────────────────────────────────────────────────────────────────────────
WISDOM_QUESTIONS = [
    {"quote": "“Ilm — Xitoyda bo'lsa ham boring, uni izlang” hadisini rivoyat qilgan buyuk muhaddis kim?",
     "options": ["Imom Buxoriy", "Imom Termiziy", "Imom Muslim", "Imom A'zam"], "correct": 0},
    {"quote": "“Sahih al-Buxoriy” hadis to'plamining muallifi kim?",
     "options": ["Imom Buxoriy", "Imom Naqshband", "Ahmad Yassaviy", "Imom G'azzoliy"], "correct": 0},
    {"quote": "“Sunan at-Termiziy” asari kimga tegishli?",
     "options": ["Imom Termiziy", "Imom Muslim", "Imom Moturidiy", "Farobiy"], "correct": 0},
    {"quote": "Hanafiy mazhabining asoschisi — “Imom A'zam” nomi bilan mashhur bo'lgan olim kim?",
     "options": ["Abu Hanifa", "Imom Shofi'iy", "Imom Buxoriy", "Beruniy"], "correct": 0},
    {"quote": "“Ihyo ulum ad-din” (Din ilmlarini tiriltirish) asarining muallifi kim?",
     "options": ["Imom G'azzoliy", "Imom Termiziy", "Ahmad Yassaviy", "Ibn Sino"], "correct": 0},
    {"quote": "“Hikmatlar devoni” asari va sufizmdagi “hikmat” yo'nalishi kimga bog'liq?",
     "options": ["Ahmad Yassaviy", "Bahouddin Naqshband", "Najmiddin Kubro", "Alisher Navoiy"], "correct": 0},
    {"quote": "“Dil ba yoru, dast ba kor” (Qalb Haq bilan, qo'l ish bilan) hikmatli qoidasi kimga nisbat beriladi?",
     "options": ["Bahouddin Naqshband", "Ahmad Yassaviy", "Najmiddin Kubro", "Imom Moturidiy"], "correct": 0},
    {"quote": "Naqshbandiya tariqatining piri, Buxoroda dafn etilgan buyuk shayx kim?",
     "options": ["Bahouddin Naqshband", "Ahmad Yassaviy", "Xoja Ahror Vali", "Abdulxoliq G'ijduvoniy"], "correct": 0},
    {"quote": "“Kubraviya” tariqatiga asos solgan, Xorazmda yetishib chiqqan mutasavvif olim kim?",
     "options": ["Najmiddin Kubro", "Bahouddin Naqshband", "Ahmad Yassaviy", "Imom G'azzoliy"], "correct": 0},
    {"quote": "“Kitob at-Tavhid” asari va “Moturidiya” aqidaviy maktabining asoschisi kim?",
     "options": ["Imom Moturidiy", "Imom Buxoriy", "Imom A'zam", "Imom Shofi'iy"], "correct": 0},
    {"quote": "“At-Tafhim” va “Qonun al-Mas'udiy” kabi ilmiy asarlar muallifi, buyuk qomusiy olim kim?",
     "options": ["Abu Rayhon Beruniy", "Ibn Sino", "Farobiy", "Ulug'bek"], "correct": 0},
    {"quote": "“Tib qonunlari” (Al-Qonun fit-tib) asari bilan jahonga mashhur bo'lgan tabib-faylasuf kim?",
     "options": ["Ibn Sino", "Beruniy", "Farobiy", "Xorazmiy"], "correct": 0},
    {"quote": "“Muallimi soniy” (Ikkinchi muallim — Arastudan keyingi) laqabi bilan tanilgan faylasuf kim?",
     "options": ["Abu Nasr Farobiy", "Ibn Sino", "Beruniy", "Imom G'azzoliy"], "correct": 0},
    {"quote": "Algebra faniga asos solgan, “al-jabr” atamasini ilmga kiritgan olim kim?",
     "options": ["Muhammad al-Xorazmiy", "Ibn Sino", "Beruniy", "Ulug'bek"], "correct": 0},
    {"quote": "Samarqandda observatoriya qurdirgan, buyuk astronom va hukmdor kim edi?",
     "options": ["Mirzo Ulug'bek", "Amir Temur", "Zahiriddin Bobur", "Shohruh Mirzo"], "correct": 0},
    {"quote": "“Sahih Muslim” hadis to'plamining muallifi kim?",
     "options": ["Imom Muslim", "Imom Buxoriy", "Imom Termiziy", "Imom Nasoiy"], "correct": 0},
    {"quote": "“Ilmni beshikdan qabrgacha izlang” degan mashhur hikmatli da'vat kimning ta'limotiga xos?",
     "options": ["Payg'ambarimiz (s.a.v.) hadisi", "Imom G'azzoliy", "Ibn Sino", "Farobiy"], "correct": 0},
    {"quote": "“Kimki bir yo'lni ilm izlab bossa, Alloh unga jannat yo'lini osonlashtiradi” hadisini kim rivoyat qilgan?",
     "options": ["Imom Muslim", "Imom Termiziy", "Imom Buxoriy", "Imom A'zam"], "correct": 0},
    {"quote": "Toshkentda “Hazrati Imom” majmuasida qadimiy Qur'on (Usmon mushafi) saqlanadigan bo'lib, u qaysi imom nomi bilan bog'liq?",
     "options": ["Imom Buxoriy", "Imom Termiziy", "Imom Moturidiy", "Imom A'zam"], "correct": 0},
    {"quote": "“Qutadg'u bilig” (Baxt keltiruvchi bilim) hikmatnomasining muallifi kim?",
     "options": ["Yusuf Xos Hojib", "Ahmad Yassaviy", "Alisher Navoiy", "Mahmud Qoshg'ariy"], "correct": 0},
]


# ─────────────────────────────────────────────────────────────────────────────
# Kitob Detektivi — a mystery book revealed through 3 progressively less vague
# clues (vague → medium → specific). `norms` lists every accepted normalized
# answer form (title and/or author, matched via chain_text.normalize).
# ─────────────────────────────────────────────────────────────────────────────
DETECTIVE_BOOKS = [
    {"display": "O'tkan kunlar", "norms": ["otkan kunlar", "abdulla qodiriy"],
     "clues": ["Bu — birinchi o'zbek romani.", "Bosh qahramoni Otabek va Kumush.",
               "Muallifi Abdulla Qodiriy, XIX asr oxiri voqealari haqida."]},
    {"display": "Mehrobdan chayon", "norms": ["mehrobdan chayon", "abdulla qodiriy"],
     "clues": ["Bu ham Abdulla Qodiriy qalamiga mansub.", "Bosh qahramon — munofiq domla Anvar.",
               "Nomida diniy joy va zaharli jonivor bor: mehrob va chayon."]},
    {"display": "Sarob", "norms": ["sarob", "abdulla qahhor"],
     "clues": ["Bu roman ikkiyuzlamachilik mavzusiga bag'ishlangan.", "Muallifi Abdulla Qahhor.",
               "Nomi — cho'lda ko'rinadigan yolg'on suv tasviri (illyuziya)ni bildiradi."]},
    {"display": "Kecha va kunduz", "norms": ["kecha va kunduz", "cholpon", "abdulhamid sulaymon"],
     "clues": ["Muallifi taxallusi — tabiat hodisasi nomi bilan bog'liq.", "Roman ikki qismdan iborat rejalashtirilgan edi.",
               "Muallifi Cho'lpon, asar nomi sutkaning ikki qarama-qarshi qismini ifodalaydi."]},
    {"display": "Shum bola", "norms": ["shum bola", "g'afur g'ulom"],
     "clues": ["Bu — hazil-mutoyibaga boy qissa.", "Bosh qahramon yetim, ammo hazilkash bola.",
               "Muallifi G'afur G'ulom."]},
    {"display": "Boburnoma", "norms": ["boburnoma", "zahiriddin muhammad bobur", "bobur"],
     "clues": ["Bu — memuar (xotira) janridagi asar.", "Muallifi Hindistonda Boburiylar sulolasiga asos solgan.",
               "Asar Zahiriddin Muhammad Boburning o'z hayoti haqidagi yozuvlari."]},
    {"display": "Xamsa", "norms": ["xamsa", "alisher navoiy"],
     "clues": ["Bu — besh dostondan iborat to'plam.", "Muallifi o'zbek adabiyotining buyuk mutafakkiri.",
               "Alisher Navoiy qalamiga mansub, “beshlik” ma'nosini beradi."]},
    {"display": "Qutadg'u bilig", "norms": ["qutadgu bilig", "yusuf xos hojib"],
     "clues": ["Bu — turkiy tildagi eng qadimgi hikmatnomalardan biri.", "Nomi “baxt keltiruvchi bilim” degan ma'noni beradi.",
               "Muallifi Yusuf Xos Hojib, XI asrda yozilgan."]},
    {"display": "Hidoyat", "norms": ["hidoyat", "burhoniddin marg'inoniy"],
     "clues": ["Bu — islom huquqshunosligi (fiqh)ga oid klassik asar.", "Muallifi Marg'ilondan yetishib chiqqan buyuk faqih.",
               "“Al-Hidoya” nomi bilan butun dunyoda tanilgan, Burhoniddin Marg'inoniy qalamiga mansub."]},
    {"display": "Al-Qonun fit-tib", "norms": ["al qonun fit tib", "tib qonunlari", "ibn sino"],
     "clues": ["Bu — tibbiyotga oid qomusiy asar.", "Asrlar davomida Yevropa universitetlarida darslik bo'lgan.",
               "Muallifi Ibn Sino, nomi “Tib qonunlari” deb tarjima qilinadi."]},
    {"display": "Urush va tinchlik", "norms": ["urush va tinchlik", "lev tolstoy"],
     "clues": ["Bu — rus mumtoz adabiyotining eng yirik romanlaridan biri.", "Voqealar Napoleon urushlari davrida kechadi.",
               "Muallifi Lev Tolstoy."]},
    {"display": "Jinoyat va jazo", "norms": ["jinoyat va jazo", "fyodor dostoyevskiy"],
     "clues": ["Bosh qahramon qari sudxo'r ayolni o'ldiradi.", "Roman vijdon azobi mavzusiga bag'ishlangan.",
               "Muallifi Fyodor Dostoyevskiy."]},
    {"display": "Hamlet", "norms": ["hamlet", "shekspir", "uilyam shekspir"],
     "clues": ["Bu — Daniya shahzodasi haqidagi tragediya.", "Mashhur “Bo'lish yoki bo'lmaslik” monologi shu asarda.",
               "Muallifi Uilyam Shekspir."]},
    {"display": "Don Kixot", "norms": ["don kixot", "servantes", "migel servantes"],
     "clues": ["Bosh qahramon o'zini ritsar deb hisoblaydi.", "U shamol tegirmonlariga hujum qiladi.",
               "Muallifi ispan yozuvchisi Migel de Servantes."]},
    {"display": "Kichkina shahzoda", "norms": ["kichkina shahzoda", "sent ekzyuperi", "antuan sent ekzyuperi"],
     "clues": ["Bosh qahramon boshqa sayyoradan kelgan.", "U bitta atirgul bilan do'stlashadi.",
               "Muallifi frantsuz yozuvchisi va uchuvchi Antuan de Sent-Ekzyuperi."]},
]


# ─────────────────────────────────────────────────────────────────────────────
# Omon qolish (Survival) — general book/literature trivia, wrong or missed
# answer costs a life. Same {"q","options","correct"} shape as CASTLE_QUESTIONS
# (options shuffled at runtime); shared by the "teams" QuizGame flavor too.
# ─────────────────────────────────────────────────────────────────────────────
SURVIVAL_QUESTIONS = [
    {"q": "“O'tkan kunlar” romanining muallifi kim?",
     "options": ["Abdulla Qodiriy", "Abdulla Qahhor", "Cho'lpon", "G'afur G'ulom"], "correct": 0},
    {"q": "“Boburnoma” qaysi janrga mansub?", "options": ["Memuar", "Doston", "Fantastika", "Detektiv"], "correct": 0},
    {"q": "“Urush va tinchlik” romani muallifi kim?",
     "options": ["Lev Tolstoy", "Fyodor Dostoyevskiy", "Anton Chexov", "Maksim Gorkiy"], "correct": 0},
    {"q": "“Hamlet” asari qaysi mamlakat qahramoni haqida?",
     "options": ["Daniya", "Angliya", "Fransiya", "Ispaniya"], "correct": 0},
    {"q": "“Xamsa” nechta dostondan iborat?", "options": ["5 ta", "3 ta", "7 ta", "4 ta"], "correct": 0},
    {"q": "“Al-Qonun fit-tib” asari qaysi sohaga oid?",
     "options": ["Tibbiyot", "Astronomiya", "Matematika", "Geografiya"], "correct": 0},
    {"q": "Mirzo Ulug'bek qaysi shaharda observatoriya qurdirgan?",
     "options": ["Samarqand", "Buxoro", "Xiva", "Toshkent"], "correct": 0},
    {"q": "“Jinoyat va jazo” romanida bosh qahramon kimni o'ldiradi?",
     "options": ["Qari sudxo'r ayolni", "O'z otasini", "Do'stini", "Sevgilisini"], "correct": 0},
    {"q": "“Qutadg'u bilig” asari qaysi asrda yozilgan?",
     "options": ["XI asr", "XV asr", "XIX asr", "VIII asr"], "correct": 0},
    {"q": "“Don Kixot” bosh qahramoni o'zini kim deb hisoblaydi?",
     "options": ["Ritsar", "Qirol", "Sarkarda", "Rohib"], "correct": 0},
    {"q": "Algebra atamasini fanga kim kiritgan?",
     "options": ["Muhammad al-Xorazmiy", "Ibn Sino", "Beruniy", "Farobiy"], "correct": 0},
    {"q": "“Muallimi soniy” laqabi kimga tegishli?",
     "options": ["Abu Nasr Farobiy", "Ibn Sino", "Beruniy", "Ulug'bek"], "correct": 0},
    {"q": "“Sahih al-Buxoriy” qaysi ilm sohasiga oid?",
     "options": ["Hadis", "Tib", "Falsafa", "Adabiyot"], "correct": 0},
    {"q": "Ahmad Yassaviy qaysi tariqat ta'limotining asoschisi?",
     "options": ["Yassaviya", "Naqshbandiya", "Qodiriya", "Kubraviya"], "correct": 0},
    {"q": "“Kichkina shahzoda”da bosh qahramon nima bilan do'stlashadi?",
     "options": ["Atirgul", "Tulki", "Ilon", "Yulduz"], "correct": 0},
    {"q": "“Shum bola” qissasining muallifi kim?",
     "options": ["G'afur G'ulom", "Abdulla Qodiriy", "Said Ahmad", "Oybek"], "correct": 0},
    {"q": "Naqshbandiya tariqatining piri qayerda dafn etilgan?",
     "options": ["Buxoro", "Samarqand", "Yassi (Turkiston)", "Xiva"], "correct": 0},
    {"q": "“Hidoyat” (Al-Hidoya) asari qaysi sohaga oid klassik manba?",
     "options": ["Fiqh (islom huquqi)", "Tib", "Astronomiya", "Adabiyot"], "correct": 0},
    {"q": "“Sarob” romanining muallifi kim?",
     "options": ["Abdulla Qahhor", "Abdulla Qodiriy", "Oybek", "Said Ahmad"], "correct": 0},
    {"q": "Imom Termiziy qaysi hadis to'plamining muallifi?",
     "options": ["Sunan at-Termiziy", "Sahih al-Buxoriy", "Sahih Muslim", "Sunan an-Nasoiy"], "correct": 0},
    {"q": "“Kecha va kunduz” romani muallifining taxallusi nima?",
     "options": ["Cho'lpon", "Oybek", "Hamid Olimjon", "Usmon Nosir"], "correct": 0},
    {"q": "Marg'ilondan yetishib chiqqan, “Hidoyat” muallifi buyuk faqih kim?",
     "options": ["Burhoniddin Marg'inoniy", "Imom Buxoriy", "Imom Moturidiy", "Imom A'zam"], "correct": 0},
    {"q": "“Qonun al-Mas'udiy” asarining muallifi kim?",
     "options": ["Abu Rayhon Beruniy", "Ibn Sino", "Farobiy", "Xorazmiy"], "correct": 0},
    {"q": "Servantesning mashhur romani qaysi?",
     "options": ["Don Kixot", "Uch mushketyor", "Graf Monte-Kristo", "Robinzon Kruzo"], "correct": 0},
    {"q": "“Qutadg'u bilig” nomi qanday ma'noni anglatadi?",
     "options": ["Baxt keltiruvchi bilim", "Hikmatlar devoni", "Yaxshi so'zlar kitobi", "Ulug' bilim"], "correct": 0},
]


# ─────────────────────────────────────────────────────────────────────────────
# Bilim O'yini (QuizGame) content — 4 flavors sharing the {"q","options","correct"}
# MC shape, so the same engine/template runs all of them.
# ─────────────────────────────────────────────────────────────────────────────

# twofacts — "Ikki haqiqat, bir yolg'on": 3 statements about a book/author,
# find the FAKE one. `correct` = index of the fake statement.
QUIZ_TWOFACTS_QUESTIONS = [
    {"q": "“O'tkan kunlar” haqida qaysi gap YOLG'ON?",
     "options": [
         "Bu birinchi o'zbek romani hisoblanadi",
         "Bosh qahramonlari Otabek va Kumush",
         "Muallifi Abdulla Qodiriy uni frantsuz tilida yozgan",
     ], "correct": 2},
    {"q": "“Boburnoma” haqida qaysi gap YOLG'ON?",
     "options": [
         "Uni Zahiriddin Muhammad Bobur yozgan",
         "Bu — memuar (xotira) janridagi asar",
         "Asar to'liq she'riy vaznda yozilgan",
     ], "correct": 2},
    {"q": "Ibn Sino haqida qaysi gap YOLG'ON?",
     "options": [
         "U “Al-Qonun fit-tib” asarining muallifi",
         "Uning asari asrlar davomida Yevropada darslik bo'lgan",
         "U faqat shoir bo'lgan, tibbiyot bilan shug'ullanmagan",
     ], "correct": 2},
    {"q": "Mirzo Ulug'bek haqida qaysi gap YOLG'ON?",
     "options": [
         "U Samarqandda observatoriya qurdirgan",
         "U buyuk astronom bo'lgan",
         "U hech qachon yulduzlar jadvalini tuzmagan",
     ], "correct": 2},
    {"q": "“Xamsa” haqida qaysi gap YOLG'ON?",
     "options": [
         "Muallifi Alisher Navoiy",
         "U besh dostondan iborat",
         "U roman janrida yozilgan, dostonlardan iborat emas",
     ], "correct": 2},
    {"q": "Imom Buxoriy haqida qaysi gap YOLG'ON?",
     "options": [
         "U “Sahih al-Buxoriy” hadis to'plamining muallifi",
         "U buyuk muhaddis (hadis olimi) bo'lgan",
         "U faqat shifokor bo'lib, hadis bilan shug'ullanmagan",
     ], "correct": 2},
    {"q": "“Urush va tinchlik” haqida qaysi gap YOLG'ON?",
     "options": [
         "Muallifi Lev Tolstoy",
         "Voqealar Napoleon urushlari davrida kechadi",
         "Roman atigi 50 betdan iborat qisqa qissa",
     ], "correct": 2},
    {"q": "Ahmad Yassaviy haqida qaysi gap YOLG'ON?",
     "options": [
         "U “Hikmatlar devoni” muallifi",
         "U Yassaviya tariqatiga asos solgan",
         "U hech qachon hikmatli she'r yozmagan",
     ], "correct": 2},
    {"q": "“Hamlet” haqida qaysi gap YOLG'ON?",
     "options": [
         "Muallifi Uilyam Shekspir",
         "Bosh qahramon Daniya shahzodasi",
         "Asar baxtli sevgi haqidagi komediya",
     ], "correct": 2},
    {"q": "Abu Rayhon Beruniy haqida qaysi gap YOLG'ON?",
     "options": [
         "U qomusiy olim bo'lgan",
         "U “Qonun al-Mas'udiy” asarini yozgan",
         "U faqat musiqachi bo'lib, ilm bilan shug'ullanmagan",
     ], "correct": 2},
    {"q": "“Don Kixot” haqida qaysi gap YOLG'ON?",
     "options": [
         "Muallifi Migel de Servantes",
         "Bosh qahramon o'zini ritsar deb biladi",
         "Asar haqiqiy voqealar - tarixiy hujjat sifatida yozilgan",
     ], "correct": 2},
    {"q": "“Hidoyat” (Al-Hidoya) haqida qaysi gap YOLG'ON?",
     "options": [
         "Muallifi Burhoniddin Marg'inoniy",
         "Bu fiqh (islom huquqi)ga oid klassik manba",
         "Bu asar zamonaviy fantastik roman",
     ], "correct": 2},
]

# impostor — "Kim yolg'onchi?": 3 real, correctly-matched book/author snippets
# and 1 fabricated (fake pairing). `options` = the 3 real ones, `fake` = the
# fake one; options+fake are shuffled together at runtime by the service.
QUIZ_IMPOSTOR_QUESTIONS = [
    {"real": ["Abdulla Qodiriy — “O'tkan kunlar”", "Abdulla Qahhor — “Sarob”", "Cho'lpon — “Kecha va kunduz”"],
     "fake": "G'afur G'ulom — “Jinoyat va jazo”"},
    {"real": ["Lev Tolstoy — “Urush va tinchlik”", "Fyodor Dostoyevskiy — “Jinoyat va jazo”", "Uilyam Shekspir — “Hamlet”"],
     "fake": "Migel de Servantes — “Robinzon Kruzo”"},
    {"real": ["Ibn Sino — “Al-Qonun fit-tib”", "Abu Rayhon Beruniy — “Qonun al-Mas'udiy”", "Farobiy — falsafiy risolalar"],
     "fake": "Ahmad Yassaviy — “Al-Qonun fit-tib”"},
    {"real": ["Imom Buxoriy — “Sahih al-Buxoriy”", "Imom Muslim — “Sahih Muslim”", "Imom Termiziy — “Sunan at-Termiziy”"],
     "fake": "Imom G'azzoliy — “Sahih al-Buxoriy”"},
    {"real": ["Alisher Navoiy — “Xamsa”", "Yusuf Xos Hojib — “Qutadg'u bilig”", "Zahiriddin Bobur — “Boburnoma”"],
     "fake": "Ahmad Yassaviy — “Xamsa”"},
    {"real": ["Burhoniddin Marg'inoniy — “Hidoyat”", "Imom Moturidiy — “Kitob at-Tavhid”", "Imom A'zam — hanafiy mazhabi asoschisi"],
     "fake": "Beruniy — “Hidoyat”"},
    {"real": ["Migel de Servantes — “Don Kixot”", "Antuan de Sent-Ekzyuperi — “Kichkina shahzoda”", "Uilyam Shekspir — “Hamlet”"],
     "fake": "Lev Tolstoy — “Don Kixot”"},
    {"real": ["Bahouddin Naqshband — Naqshbandiya piri", "Najmiddin Kubro — Kubraviya asoschisi", "Ahmad Yassaviy — Yassaviya asoschisi"],
     "fake": "Imom Buxoriy — bir tariqat piri"},
]

# connection — "Yashirin bog'lanish": 4 items share a hidden theme; pick it.
QUIZ_CONNECTION_QUESTIONS = [
    {"items": ["O'tkan kunlar", "Mehrobdan chayon", "Sarob", "Kecha va kunduz"],
     "q": "Bu 4 asarni nima bog'laydi?",
     "options": ["Barchasi o'zbek mumtoz nasri", "Barchasi she'riy to'plam", "Barchasi tarjima asar", "Barchasi bolalar kitobi"],
     "correct": 0},
    {"items": ["Imom Buxoriy", "Imom Muslim", "Imom Termiziy", "Imom Nasoiy"],
     "q": "Bu 4 olimni nima bog'laydi?",
     "options": ["Barchasi mashhur hadis to'plamlari muallifi", "Barchasi shifokor", "Barchasi shoir", "Barchasi hukmdor"],
     "correct": 0},
    {"items": ["Ibn Sino", "Beruniy", "Farobiy", "Xorazmiy"],
     "q": "Bu 4 mutafakkirni nima bog'laydi?",
     "options": ["Barchasi Islom oltin davri olimlari", "Barchasi zamonaviy yozuvchi", "Barchasi rassom", "Barchasi harbiy sarkarda"],
     "correct": 0},
    {"items": ["Ahmad Yassaviy", "Bahouddin Naqshband", "Najmiddin Kubro", "Xoja Ahror Vali"],
     "q": "Bu 4 shaxsni nima bog'laydi?",
     "options": ["Barchasi tasavvuf (sufizm) yo'nalishi piri", "Barchasi tarixchi", "Barchasi tabib", "Barchasi me'mor"],
     "correct": 0},
    {"items": ["Hamlet", "Otello", "Qirol Lir", "Makbet"],
     "q": "Bu 4 asarni nima bog'laydi?",
     "options": ["Barchasi Shekspir tragediyasi", "Barchasi komediya", "Barchasi bitta muallif she'ri", "Barchasi bolalar ertagi"],
     "correct": 0},
    {"items": ["O'tkan kunlar", "Boburnoma", "Xamsa", "Qutadg'u bilig"],
     "q": "Bu 4 asarni nima bog'laydi?",
     "options": ["Barchasi turkiy/o'zbek adabiyoti durdonasi", "Barchasi rus adabiyoti", "Barchasi zamonaviy detektiv", "Barchasi ilmiy fantastika"],
     "correct": 0},
    {"items": ["Urush va tinchlik", "Jinoyat va jazo", "Anna Karenina", "Idiot"],
     "q": "Bu 4 asarni nima bog'laydi?",
     "options": ["Barchasi rus mumtoz nasri", "Barchasi frantsuz romani", "Barchasi bolalar kitobi", "Barchasi she'riy doston"],
     "correct": 0},
]


# ─────────────────────────────────────────────────────────────────────────────
# Vaqt Mashinasi (QuizGame flavor "timeline") — guess which era/century a
# book or thinker belongs to. Same {"q","options","correct"} shape.
# ─────────────────────────────────────────────────────────────────────────────
QUIZ_TIMELINE_QUESTIONS = [
    {"q": "“O'tkan kunlar” qaysi asrda yozilgan?",
     "options": ["XX asr boshi", "XIX asr", "XVIII asr", "XXI asr"], "correct": 0},
    {"q": "Imom Buxoriy qaysi asrda yashagan?",
     "options": ["IX asr", "XV asr", "XX asr", "VI asr"], "correct": 0},
    {"q": "Ibn Sino qaysi asrda yashagan?",
     "options": ["X-XI asr", "XVIII asr", "XX asr", "VII asr"], "correct": 0},
    {"q": "Alisher Navoiy qaysi asrda ijod qilgan?",
     "options": ["XV asr", "XX asr", "X asr", "XVIII asr"], "correct": 0},
    {"q": "Mirzo Ulug'bek observatoriyasi qaysi asrda qurilgan?",
     "options": ["XV asr", "XIX asr", "XX asr", "XI asr"], "correct": 0},
    {"q": "“Qutadg'u bilig” qaysi asrda yozilgan?",
     "options": ["XI asr", "XIX asr", "XVI asr", "XX asr"], "correct": 0},
    {"q": "“Urush va tinchlik” qaysi asrda yozilgan?",
     "options": ["XIX asr", "XVII asr", "XX asr", "XV asr"], "correct": 0},
    {"q": "“Hamlet” qaysi asrda yozilgan?",
     "options": ["XVI-XVII asr", "XIX asr", "XX asr", "XII asr"], "correct": 0},
    {"q": "Abu Rayhon Beruniy qaysi asrda yashagan?",
     "options": ["X-XI asr", "XVIII asr", "XX asr", "VII asr"], "correct": 0},
    {"q": "Boburiylar sulolasi (Boburnoma muallifi) qaysi asrda hukmronlik boshlagan?",
     "options": ["XVI asr", "XIX asr", "XX asr", "XII asr"], "correct": 0},
]


# ─────────────────────────────────────────────────────────────────────────────
# Muallif-Asar Moslashtirish (QuizGame flavor "matchbook") — given an author,
# pick their real book from 4 options (bibliography-matching speed round).
# ─────────────────────────────────────────────────────────────────────────────
QUIZ_MATCHBOOK_QUESTIONS = [
    {"q": "Abdulla Qodiriyga qaysi asar tegishli?",
     "options": ["O'tkan kunlar", "Sarob", "Kecha va kunduz", "Shum bola"], "correct": 0},
    {"q": "Abdulla Qahhorga qaysi asar tegishli?",
     "options": ["Sarob", "O'tkan kunlar", "Boburnoma", "Xamsa"], "correct": 0},
    {"q": "Cho'lponga qaysi asar tegishli?",
     "options": ["Kecha va kunduz", "Shum bola", "Sarob", "Mehrobdan chayon"], "correct": 0},
    {"q": "G'afur G'ulomga qaysi asar tegishli?",
     "options": ["Shum bola", "O'tkan kunlar", "Kecha va kunduz", "Boburnoma"], "correct": 0},
    {"q": "Alisher Navoiyga qaysi asar tegishli?",
     "options": ["Xamsa", "Qutadg'u bilig", "Boburnoma", "Devon"], "correct": 0},
    {"q": "Zahiriddin Muhammad Boburga qaysi asar tegishli?",
     "options": ["Boburnoma", "Xamsa", "O'tkan kunlar", "Qutadg'u bilig"], "correct": 0},
    {"q": "Yusuf Xos Hojibga qaysi asar tegishli?",
     "options": ["Qutadg'u bilig", "Xamsa", "Boburnoma", "Hidoyat"], "correct": 0},
    {"q": "Ibn Sinoga qaysi asar tegishli?",
     "options": ["Al-Qonun fit-tib", "Qonun al-Mas'udiy", "Hidoyat", "At-Tafhim"], "correct": 0},
    {"q": "Abu Rayhon Beruniyga qaysi asar tegishli?",
     "options": ["Qonun al-Mas'udiy", "Al-Qonun fit-tib", "Xamsa", "Sahih al-Buxoriy"], "correct": 0},
    {"q": "Lev Tolstoyga qaysi asar tegishli?",
     "options": ["Urush va tinchlik", "Jinoyat va jazo", "Hamlet", "Don Kixot"], "correct": 0},
    {"q": "Fyodor Dostoyevskiyga qaysi asar tegishli?",
     "options": ["Jinoyat va jazo", "Urush va tinchlik", "Anna Karenina", "Hamlet"], "correct": 0},
    {"q": "Uilyam Shekspirga qaysi asar tegishli?",
     "options": ["Hamlet", "Don Kixot", "Kichkina shahzoda", "Robinzon Kruzo"], "correct": 0},
]


# ─────────────────────────────────────────────────────────────────────────────
# Teskari Viktorina (QuizGame flavor "reverse") — the ANSWER is shown first;
# pick which of the 4 questions/clues it actually matches (Jeopardy-style).
# ─────────────────────────────────────────────────────────────────────────────
QUIZ_REVERSE_QUESTIONS = [
    {"q": "Javob: «O'tkan kunlar». Bu qaysi savolga to'g'ri javob?",
     "options": ["Birinchi o'zbek romani qaysi?", "Eng qadimgi turkiy hikmatnoma qaysi?",
                 "Ikki barobar Kitobcha kim beradi?", "Qaysi asar 20 ta dostondan iborat?"], "correct": 0},
    {"q": "Javob: «Ibn Sino». Bu qaysi savolga to'g'ri javob?",
     "options": ["“Al-Qonun fit-tib” kim tomonidan yozilgan?", "“Sahih al-Buxoriy” muallifi kim?",
                 "Samarqandda observatoriya kim qurdirgan?", "“Xamsa” muallifi kim?"], "correct": 0},
    {"q": "Javob: «Imom Buxoriy». Bu qaysi savolga to'g'ri javob?",
     "options": ["“Sahih al-Buxoriy” muallifi kim?", "“Al-Qonun fit-tib” muallifi kim?",
                 "“Boburnoma” muallifi kim?", "Naqshbandiya piri kim?"], "correct": 0},
    {"q": "Javob: «Mirzo Ulug'bek». Bu qaysi savolga to'g'ri javob?",
     "options": ["Samarqandda observatoriya kim qurdirgan?", "“Hidoyat” muallifi kim?",
                 "“Xamsa” muallifi kim?", "Naqshbandiya piri kim?"], "correct": 0},
    {"q": "Javob: «Alisher Navoiy». Bu qaysi savolga to'g'ri javob?",
     "options": ["“Xamsa” muallifi kim?", "“Boburnoma” muallifi kim?",
                 "“Al-Qonun fit-tib” muallifi kim?", "“Qutadg'u bilig” muallifi kim?"], "correct": 0},
    {"q": "Javob: «Lev Tolstoy». Bu qaysi savolga to'g'ri javob?",
     "options": ["“Urush va tinchlik” muallifi kim?", "“Jinoyat va jazo” muallifi kim?",
                 "“Hamlet” muallifi kim?", "“Don Kixot” muallifi kim?"], "correct": 0},
    {"q": "Javob: «Abu Rayhon Beruniy». Bu qaysi savolga to'g'ri javob?",
     "options": ["“Qonun al-Mas'udiy” muallifi kim?", "“Al-Qonun fit-tib” muallifi kim?",
                 "“Sahih Muslim” muallifi kim?", "“Xamsa” muallifi kim?"], "correct": 0},
    {"q": "Javob: «Bahouddin Naqshband». Bu qaysi savolga to'g'ri javob?",
     "options": ["Naqshbandiya tariqatining piri kim?", "Yassaviya tariqatining piri kim?",
                 "Kubraviya tariqatining piri kim?", "“Hidoyat” muallifi kim?"], "correct": 0},
    {"q": "Javob: «Yusuf Xos Hojib». Bu qaysi savolga to'g'ri javob?",
     "options": ["“Qutadg'u bilig” muallifi kim?", "“Xamsa” muallifi kim?",
                 "“Boburnoma” muallifi kim?", "“Devon” muallifi kim?"], "correct": 0},
]
