# -*- coding: utf-8 -*-
"""Question banks for the live games.

Backward-compatible facade importing from tgbot.services.questions.
"""

from tgbot.services.questions import (
    FEUD_QUESTIONS,
    CASTLE_QUESTIONS,
    EMOJI_QUESTIONS,
    WISDOM_QUESTIONS,
    DETECTIVE_BOOKS,
    SURVIVAL_QUESTIONS,
    QUIZ_TWOFACTS_QUESTIONS,
    QUIZ_IMPOSTOR_QUESTIONS,
    QUIZ_CONNECTION_QUESTIONS,
    QUIZ_TIMELINE_QUESTIONS,
    QUIZ_MATCHBOOK_QUESTIONS,
    QUIZ_REVERSE_QUESTIONS,
)

__all__ = [
    "FEUD_QUESTIONS",
    "CASTLE_QUESTIONS",
    "EMOJI_QUESTIONS",
    "WISDOM_QUESTIONS",
    "DETECTIVE_BOOKS",
    "SURVIVAL_QUESTIONS",
    "QUIZ_TWOFACTS_QUESTIONS",
    "QUIZ_IMPOSTOR_QUESTIONS",
    "QUIZ_CONNECTION_QUESTIONS",
    "QUIZ_TIMELINE_QUESTIONS",
    "QUIZ_MATCHBOOK_QUESTIONS",
    "QUIZ_REVERSE_QUESTIONS",
]
