"""Question banks for the live games.

FEUD_QUESTIONS  — open questions for "Ko'pchilik nima dedi?" (crowd answers).
CASTLE_QUESTIONS — multiple-choice literary trivia for "Bilim Qal'asi".
                   Options are shuffled per game at runtime, so the stored
                   `correct` index is only the seed position.
"""

FEUD_QUESTIONS = [
    "Eng mashhur o'zbek yozuvchisini ayting",
    "Eng sevimli kitobingizni ayting",
    "Maktabda o'qigan eng mashhur asarni ayting",
    "Eng buyuk jahon yozuvchisini ayting",
    "Bir o'zbek xalq dostonini ayting",
    "Alisher Navoiyning bir asarini ayting",
    "Eng mashhur o'zbek shoirini ayting",
    "Bolalikda o'qigan bir ertakni ayting",
    "Bir detektiv asar nomini ayting",
    "Eng mashhur jahon kitobini ayting",
    "Bir o'zbek klassik yozuvchisini ayting",
    "Sevimli adabiy qahramoningizni ayting",
    "Bir tarixiy romanni ayting",
    "Bir mashhur rus yozuvchisini ayting",
    "Bir fantastik asarni ayting",
    "Kitob o'qishning bir foydasini ayting",
    "Bir zamonaviy o'zbek yozuvchisini ayting",
    "Bir she'riy to'plam yoki shoir nomini ayting",
    "Bir kutubxona yoki nashriyot nomini ayting",
    "Bir mashhur muallifning taxallusini ayting",
    "Bir jahon klassik asarini ayting",
    "Bolalar uchun bir kitob nomini ayting",
    "Bir urush haqidagi asarni ayting",
    "Eng ko'p o'qiladigan janr qaysi?",
]

CASTLE_QUESTIONS = [
    {"q": "«O'tkan kunlar» romani muallifi kim?",
     "options": ["Abdulla Qodiriy", "Cho'lpon", "Oybek", "G'afur G'ulom"], "correct": 0},
    {"q": "«Mehrobdan chayon» kim qalamiga mansub?",
     "options": ["Oybek", "Abdulla Qodiriy", "Said Ahmad", "Tohir Malik"], "correct": 1},
    {"q": "Alisher Navoiy «Xamsa»si nechta dostondan iborat?",
     "options": ["3", "4", "5", "6"], "correct": 2},
    {"q": "«Urush va tinchlik» muallifi kim?",
     "options": ["Dostoyevskiy", "Chexov", "Lev Tolstoy", "Pushkin"], "correct": 2},
    {"q": "«Jinoyat va jazo» kim asari?",
     "options": ["Tolstoy", "Dostoyevskiy", "Gogol", "Turgenev"], "correct": 1},
    {"q": "«Kichkina shahzoda» muallifi kim?",
     "options": ["Jyul Vern", "Antuan de Sent-Ekzyuperi", "Defo", "Dyuma"], "correct": 1},
    {"q": "«Boburnoma» asari kim qalamiga mansub?",
     "options": ["Bobur", "Ulug'bek", "Navoiy", "Husayn Boyqaro"], "correct": 0},
    {"q": "«Yulduzli tunlar» romani kim ijodi?",
     "options": ["Pirimqul Qodirov", "Odil Yoqubov", "Oybek", "Mirmuhsin"], "correct": 0},
    {"q": "«Ulug'bek xazinasi» muallifi kim?",
     "options": ["Odil Yoqubov", "Pirimqul Qodirov", "Asqad Muxtor", "Said Ahmad"], "correct": 0},
    {"q": "«Alkimyogar» kitobi muallifi kim?",
     "options": ["Gabriel Markes", "Paulo Koelo", "Xeminguey", "Kafka"], "correct": 1},
    {"q": "«Chol va dengiz» kim asari?",
     "options": ["Jek London", "Ernest Xeminguey", "Mark Tven", "Folkner"], "correct": 1},
    {"q": "«Shum bola» qissasi muallifi kim?",
     "options": ["G'afur G'ulom", "Abdulla Qahhor", "Oybek", "Cho'lpon"], "correct": 0},
    {"q": "«Kecha va kunduz» romani kim qalamiga mansub?",
     "options": ["Cho'lpon", "Oybek", "Qodiriy", "Fitrat"], "correct": 0},
    {"q": "«O'tkan kunlar»da bosh qahramon kim?",
     "options": ["Otabek", "Anvar", "Yodgor", "Kumush"], "correct": 0},
    {"q": "«Sarob» romani muallifi kim?",
     "options": ["Abdulla Qahhor", "Oybek", "Said Ahmad", "G'afur G'ulom"], "correct": 0},
    {"q": "Zahiriddin Muhammad Bobur qaysi sulola asoschisi?",
     "options": ["Boburiylar", "Shayboniylar", "Temuriylar", "Ashtarxoniylar"], "correct": 0},
    {"q": "«Ikki eshik orasi» muallifi kim?",
     "options": ["O'tkir Hoshimov", "Tohir Malik", "Said Ahmad", "Shukur Xolmirzayev"], "correct": 0},
    {"q": "«Robinzon Kruzo» kim asari?",
     "options": ["Daniel Defo", "Jonatan Svift", "Jyul Vern", "Mark Tven"], "correct": 0},
    {"q": "«Hamlet» tragediyasi muallifi kim?",
     "options": ["Shekspir", "Molyer", "Dante", "Gyote"], "correct": 0},
    {"q": "«Anna Karenina» kim ijodi?",
     "options": ["Lev Tolstoy", "Dostoyevskiy", "Turgenev", "Gogol"], "correct": 0},
    {"q": "«Layli va Majnun» dostoni (o'zbek adabiyoti) kimniki?",
     "options": ["Alisher Navoiy", "Bobur", "Lutfiy", "Sakkokiy"], "correct": 0},
    {"q": "«Sariq devni minib» asari muallifi kim?",
     "options": ["Xudoyberdi To'xtaboyev", "Anvar Obidjon", "G'afur G'ulom", "Quddus Muhammadiy"], "correct": 0},
    {"q": "«Faust» asari muallifi kim?",
     "options": ["Gyote", "Shiller", "Bayron", "Gyugo"], "correct": 0},
    {"q": "«Don Kixot» kim qalamiga mansub?",
     "options": ["Migel de Servantes", "Lope de Vega", "Kalderon", "Dante"], "correct": 0},
    {"q": "«Graf Monte-Kristo» muallifi kim?",
     "options": ["Aleksandr Dyuma", "Viktor Gyugo", "Balzak", "Stendal"], "correct": 0},
    {"q": "«Diyonat» romani muallifi kim?",
     "options": ["Odil Yoqubov", "Said Ahmad", "Oybek", "Asqad Muxtor"], "correct": 0},
]
