from environs import Env

env = Env()
env.read_env()

ADMIN_GROUP_ID = env.str("ADMIN_GROUP_ID")
TECHNICAL_SUPPORT_THREAD_ID = env.int("TECHNICAL_SUPPORT_THREAD_ID", 103)
MESSAGE_THREAD_ID = env.int("MESSAGE_THREAD_ID", 101)
PAYMENT_THREAD_ID = env.int("PAYMENT_THREAD_ID", 99)

CHALLENGE_CHANNEL_ID = env.str("CHALLENGE_CHANNEL_ID")
GAMES_THREAD_ID = env.int("GAMES_THREAD_ID", 34402)

BOYS_GROUP_ID = env.str("BOYS_GROUP_ID")
GIRLS_GROUP_ID = env.str("GIRLS_GROUP_ID")

B_BOYS_THREAD_ID = env.int("B_BOYS_THREAD_ID")
B_GIRLS_THREAD_ID = env.int("B_GIRLS_THREAD_ID")

D_BOYS_THREAD_ID = env.int("D_BOYS_THREAD_ID", 101)
D_GIRLS_THREAD_ID = env.int("D_GIRLS_THREAD_ID", 102)

C_BOYS_THREAD_ID = env.int("C_BOYS_THREAD_ID", 101)
C_GIRLS_THREAD_ID = env.int("C_GIRLS_THREAD_ID", 102)

E_BOYS_THREAD_ID = env.int("E_BOYS_THREAD_ID", 101)
E_GIRLS_THREAD_ID = env.int("E_GIRLS_THREAD_ID", 102)

REFERRAL_THRESHOLD = 1
REFERRAL_CODE_LENGTH = 8
